-- Degree Programs - Lot 1 foundation. Run after 009_certification_notifications.sql.
do $$ begin create type public.academic_role as enum ('STUDENT','INSTRUCTOR','COURSE_COORDINATOR','UNIT_COORDINATOR','PROGRAM_COORDINATOR','ACADEMIC_SECRETARY','ACADEMIC_ADMIN','INTERNSHIP_SUPERVISOR','THESIS_SUPERVISOR','JURY_MEMBER','JURY_CHAIR','FINANCE_OFFICER','SUPER_ADMIN'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_scope_type as enum ('ORGANIZATION','DEPARTMENT','CAMPUS','PROGRAM'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_record_status as enum ('DRAFT','ACTIVE','INACTIVE','ARCHIVED'); exception when duplicate_object then null; end $$;

create table if not exists public.academic_departments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code citext not null,name_fr text not null,name_en text not null,description_fr text,description_en text,head_user_id uuid references public.profiles(id) on delete set null,status public.academic_record_status not null default 'ACTIVE',created_by uuid references public.profiles(id) on delete set null,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table if not exists public.academic_campuses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code citext not null,name_fr text not null,name_en text not null,country_code char(2),city text,address text,timezone text not null default 'Africa/Douala',status public.academic_record_status not null default 'ACTIVE',created_by uuid references public.profiles(id) on delete set null,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table if not exists public.academic_role_assignments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,user_id uuid not null references public.profiles(id) on delete restrict,role public.academic_role not null,scope_type public.academic_scope_type not null default 'ORGANIZATION',scope_id uuid,active boolean not null default true,valid_from date not null default current_date,valid_to date,assigned_by uuid references public.profiles(id) on delete set null,assignment_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(valid_to is null or valid_to>=valid_from),unique nulls not distinct(organization_id,user_id,role,scope_type,scope_id));
create table if not exists public.academic_role_permissions(id uuid primary key default gen_random_uuid(),role public.academic_role not null,permission_code citext not null,description_fr text not null,description_en text not null,created_at timestamptz not null default now(),unique(role,permission_code));
create table if not exists public.academic_module_settings(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete restrict,enabled boolean not null default false,default_locale text not null default 'fr' check(default_locale in ('fr','en')),institution_name_fr text,institution_name_en text,registry_page_size integer not null default 25 check(registry_page_size between 10 and 200),created_by uuid references public.profiles(id) on delete set null,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.academic_audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,actor_user_id uuid references public.profiles(id) on delete set null,entity_type text not null,entity_id uuid,action text not null,old_value jsonb,new_value jsonb,reason text,request_id uuid,ip_address inet,created_at timestamptz not null default now());
create table if not exists public.academic_registry_exports(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,requested_by uuid not null references public.profiles(id) on delete restrict,registry_code text not null,format text not null check(format in ('CSV','XLSX','PDF')),filters jsonb not null default '{}'::jsonb,row_count integer check(row_count is null or row_count>=0),file_path text,status text not null default 'REQUESTED' check(status in ('REQUESTED','PROCESSING','READY','FAILED','EXPIRED')),expires_at timestamptz,created_at timestamptz not null default now(),completed_at timestamptz);

create index if not exists academic_departments_org_status_idx on public.academic_departments(organization_id,status);
create index if not exists academic_campuses_org_status_idx on public.academic_campuses(organization_id,status);
create index if not exists academic_role_assignments_user_idx on public.academic_role_assignments(user_id,active);
create index if not exists academic_role_assignments_scope_idx on public.academic_role_assignments(organization_id,scope_type,scope_id,role);
create index if not exists academic_audit_entity_idx on public.academic_audit_logs(organization_id,entity_type,entity_id,created_at desc);
create index if not exists academic_audit_actor_idx on public.academic_audit_logs(actor_user_id,created_at desc);
create index if not exists academic_exports_requester_idx on public.academic_registry_exports(requested_by,created_at desc);

create or replace function public.academic_is_super_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='super_admin') or exists(select 1 from public.academic_role_assignments a where a.user_id=auth.uid() and a.role='SUPER_ADMIN' and a.active and a.valid_from<=current_date and(a.valid_to is null or a.valid_to>=current_date)) $$;
create or replace function public.academic_has_access(p_organization_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.academic_is_super_admin() or exists(select 1 from public.academic_role_assignments a where a.organization_id=p_organization_id and a.user_id=auth.uid() and a.active and a.valid_from<=current_date and(a.valid_to is null or a.valid_to>=current_date)) $$;
create or replace function public.academic_has_permission(p_organization_id uuid,p_permission text) returns boolean language sql stable security definer set search_path=public as $$ select public.academic_is_super_admin() or exists(select 1 from public.academic_role_assignments a join public.academic_role_permissions rp on rp.role=a.role where a.organization_id=p_organization_id and a.user_id=auth.uid() and a.active and a.valid_from<=current_date and(a.valid_to is null or a.valid_to>=current_date) and rp.permission_code=p_permission) $$;
grant execute on function public.academic_is_super_admin() to authenticated;
grant execute on function public.academic_has_access(uuid) to authenticated;
grant execute on function public.academic_has_permission(uuid,text) to authenticated;

insert into public.academic_role_permissions(role,permission_code,description_fr,description_en) values
('STUDENT','student.self.read','Consulter son dossier','Read own academic record'),('INSTRUCTOR','teaching.assigned.manage','Gerer les enseignements affectes','Manage assigned teaching'),('COURSE_COORDINATOR','course.manage','Gerer les cours coordonnes','Manage coordinated courses'),('UNIT_COORDINATOR','unit.manage','Gerer les UE coordonnees','Manage coordinated units'),('PROGRAM_COORDINATOR','program.manage','Gerer le programme','Manage program'),('PROGRAM_COORDINATOR','registry.export','Exporter les registres autorises','Export authorized registries'),('ACADEMIC_SECRETARY','admission.manage','Gerer admissions et inscriptions','Manage admissions and registrations'),('ACADEMIC_SECRETARY','registry.export','Exporter les registres autorises','Export authorized registries'),('ACADEMIC_ADMIN','academic.manage','Administrer le moteur academique','Administer academic engine'),('ACADEMIC_ADMIN','reference.manage','Gerer les referentiels','Manage reference data'),('ACADEMIC_ADMIN','roles.manage','Gerer les roles academiques','Manage academic roles'),('ACADEMIC_ADMIN','audit.read','Consulter audit academique','Read academic audit'),('ACADEMIC_ADMIN','registry.export','Exporter les registres','Export registries'),('INTERNSHIP_SUPERVISOR','internship.assigned.manage','Gerer les stages affectes','Manage assigned internships'),('THESIS_SUPERVISOR','thesis.assigned.manage','Gerer les memoires affectes','Manage assigned theses'),('JURY_MEMBER','jury.assigned.read','Consulter les jurys affectes','Read assigned juries'),('JURY_CHAIR','jury.assigned.decide','Valider les decisions du jury','Approve jury decisions'),('FINANCE_OFFICER','finance.manage','Gerer les finances etudiantes','Manage student finance'),('FINANCE_OFFICER','registry.export','Exporter les registres financiers','Export finance registries'),('SUPER_ADMIN','academic.manage','Administration academique complete','Full academic administration'),('SUPER_ADMIN','reference.manage','Gerer les referentiels','Manage reference data'),('SUPER_ADMIN','roles.manage','Gerer les roles academiques','Manage academic roles'),('SUPER_ADMIN','audit.read','Consulter audit academique','Read academic audit'),('SUPER_ADMIN','registry.export','Exporter tous les registres','Export every registry') on conflict(role,permission_code) do update set description_fr=excluded.description_fr,description_en=excluded.description_en;

alter table public.academic_departments enable row level security; alter table public.academic_campuses enable row level security; alter table public.academic_role_assignments enable row level security; alter table public.academic_role_permissions enable row level security; alter table public.academic_module_settings enable row level security; alter table public.academic_audit_logs enable row level security; alter table public.academic_registry_exports enable row level security;
drop policy if exists "academic departments read" on public.academic_departments; create policy "academic departments read" on public.academic_departments for select to authenticated using(public.academic_has_access(organization_id));
drop policy if exists "academic departments manage" on public.academic_departments; create policy "academic departments manage" on public.academic_departments for all to authenticated using(public.academic_has_permission(organization_id,'reference.manage')) with check(public.academic_has_permission(organization_id,'reference.manage'));
drop policy if exists "academic campuses read" on public.academic_campuses; create policy "academic campuses read" on public.academic_campuses for select to authenticated using(public.academic_has_access(organization_id));
drop policy if exists "academic campuses manage" on public.academic_campuses; create policy "academic campuses manage" on public.academic_campuses for all to authenticated using(public.academic_has_permission(organization_id,'reference.manage')) with check(public.academic_has_permission(organization_id,'reference.manage'));
drop policy if exists "academic assignments read" on public.academic_role_assignments; create policy "academic assignments read" on public.academic_role_assignments for select to authenticated using(user_id=auth.uid() or public.academic_has_permission(organization_id,'roles.manage'));
drop policy if exists "academic assignments manage" on public.academic_role_assignments; create policy "academic assignments manage" on public.academic_role_assignments for all to authenticated using(public.academic_has_permission(organization_id,'roles.manage')) with check(public.academic_has_permission(organization_id,'roles.manage'));
drop policy if exists "academic permissions read" on public.academic_role_permissions; create policy "academic permissions read" on public.academic_role_permissions for select to authenticated using(true);
drop policy if exists "academic settings read" on public.academic_module_settings; create policy "academic settings read" on public.academic_module_settings for select to authenticated using(public.academic_has_access(organization_id));
drop policy if exists "academic settings manage" on public.academic_module_settings; create policy "academic settings manage" on public.academic_module_settings for all to authenticated using(public.academic_has_permission(organization_id,'academic.manage')) with check(public.academic_has_permission(organization_id,'academic.manage'));
drop policy if exists "academic audit read" on public.academic_audit_logs; create policy "academic audit read" on public.academic_audit_logs for select to authenticated using(public.academic_has_permission(organization_id,'audit.read'));
drop policy if exists "academic audit append" on public.academic_audit_logs; create policy "academic audit append" on public.academic_audit_logs for insert to authenticated with check(actor_user_id=auth.uid() and public.academic_has_access(organization_id));
drop policy if exists "academic exports read own" on public.academic_registry_exports; create policy "academic exports read own" on public.academic_registry_exports for select to authenticated using(requested_by=auth.uid() or public.academic_has_permission(organization_id,'audit.read'));
drop policy if exists "academic exports request" on public.academic_registry_exports; create policy "academic exports request" on public.academic_registry_exports for insert to authenticated with check(requested_by=auth.uid() and public.academic_has_permission(organization_id,'registry.export'));
comment on table public.academic_audit_logs is 'Immutable degree-program audit trail. JSON is limited to before/after snapshots.';