-- Degree Programs - Lot 8: internships, theses and defense preparation. Run after migration 016.
do $$ begin create type public.academic_internship_status as enum ('DRAFT','SUBMITTED','APPROVED','IN_PROGRESS','COMPLETED','UNDER_REVIEW','VALIDATED','REJECTED','CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_supervision_progress as enum ('NOT_STARTED','ON_TRACK','AT_RISK','DELAYED','COMPLETED','BLOCKED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_thesis_status as enum ('PROPOSED','SUBMITTED','APPROVED','IN_PROGRESS','SUBMITTED_FOR_REVIEW','UNDER_REVIEW','READY_FOR_DEFENSE','DEFENDED','CORRECTIONS_REQUIRED','VALIDATED','REJECTED','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_milestone_status as enum ('PLANNED','IN_PROGRESS','SUBMITTED','ACCEPTED','REVISION_REQUIRED','COMPLETED','CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_defense_status as enum ('DRAFT','SCHEDULED','CONFIRMED','COMPLETED','POSTPONED','CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_defense_decision as enum ('PENDING','PASSED','FAILED','CORRECTIONS_REQUIRED','ADJOURNED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.academic_practicum_document_type as enum ('AGREEMENT','INSURANCE','MISSION_ORDER','TIMESHEET','SUPERVISION_REPORT','INTERNSHIP_REPORT','EVALUATION','THESIS_PROPOSAL','THESIS_DRAFT','THESIS_FINAL','PLAGIARISM_REPORT','DEFENSE_MINUTES','PRESENTATION','CORRECTION_PROOF','OTHER'); exception when duplicate_object then null; end $$;
create sequence if not exists public.academic_internship_code_seq;create sequence if not exists public.academic_thesis_code_seq;create sequence if not exists public.academic_milestone_code_seq;create sequence if not exists public.academic_defense_code_seq;

create table if not exists public.academic_internships(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,internship_number text not null unique,student_id uuid not null references public.academic_students(id) on delete restrict,program_id uuid not null references public.academic_programs(id) on delete restrict,academic_year_id uuid not null references public.academic_years(id) on delete restrict,semester_id uuid references public.academic_semesters(id) on delete restrict,course_id uuid references public.academic_courses(id) on delete restrict,
 organization_name text not null,organization_address text,organization_country text,department_or_unit text,position_title_fr text not null,position_title_en text not null,objectives_fr text not null,objectives_en text not null,workplace_supervisor_name text not null,workplace_supervisor_email citext,workplace_supervisor_phone text,academic_supervisor_id uuid references public.profiles(id) on delete set null,start_date date not null,end_date date not null,expected_hours numeric(8,2) not null check(expected_hours>0),completed_hours numeric(8,2) not null default 0 check(completed_hours>=0),status public.academic_internship_status not null default 'DRAFT',report_storage_path text,evaluation_score numeric(7,2) check(evaluation_score between 0 and 100),evaluation_comment text,submitted_by uuid references public.profiles(id),submitted_at timestamptz,validated_by uuid references public.profiles(id),validated_at timestamptz,rejection_reason text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date),check(completed_hours<=expected_hours));
create table if not exists public.academic_internship_supervisions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,internship_id uuid not null references public.academic_internships(id) on delete restrict,supervision_date date not null,supervisor_id uuid not null references public.profiles(id) on delete restrict,progress_status public.academic_supervision_progress not null,completed_hours numeric(8,2) check(completed_hours>=0),objectives_review_fr text not null,objectives_review_en text not null,comments_fr text not null,comments_en text not null,next_action_fr text,next_action_en text,next_action_due_date date,student_acknowledged_at timestamptz,created_at timestamptz not null default now(),unique(internship_id,supervision_date,supervisor_id));

create table if not exists public.academic_theses(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,thesis_number text not null unique,student_id uuid not null references public.academic_students(id) on delete restrict,program_id uuid not null references public.academic_programs(id) on delete restrict,academic_year_id uuid not null references public.academic_years(id) on delete restrict,title_fr text not null,title_en text not null,topic_fr text not null,topic_en text not null,research_question_fr text,research_question_en text,methodology_fr text,methodology_en text,supervisor_id uuid references public.profiles(id) on delete set null,co_supervisor_id uuid references public.profiles(id) on delete set null,proposal_date date,approval_date date,submission_date date,status public.academic_thesis_status not null default 'PROPOSED',document_storage_path text,plagiarism_status text check(plagiarism_status is null or plagiarism_status in('NOT_CHECKED','PENDING','CLEAR','REVIEW_REQUIRED','BLOCKED')),plagiarism_score numeric(5,2) check(plagiarism_score between 0 and 100),submitted_by uuid references public.profiles(id),submitted_at timestamptz,validated_by uuid references public.profiles(id),validated_at timestamptz,rejection_reason text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(supervisor_id is null or supervisor_id<>co_supervisor_id));
create table if not exists public.academic_thesis_milestones(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,milestone_number text not null unique,thesis_id uuid not null references public.academic_theses(id) on delete restrict,title_fr text not null,title_en text not null,description_fr text not null,description_en text not null,due_date date not null,submitted_at timestamptz,reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,status public.academic_milestone_status not null default 'PLANNED',review_comment_fr text,review_comment_en text,storage_path text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.academic_defenses(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,defense_number text not null unique,thesis_id uuid not null references public.academic_theses(id) on delete restrict,student_id uuid not null references public.academic_students(id) on delete restrict,program_id uuid not null references public.academic_programs(id) on delete restrict,defense_date date not null,start_time time not null,end_time time,location_or_link text not null,jury_id uuid,presentation_score numeric(7,2) check(presentation_score between 0 and 100),document_score numeric(7,2) check(document_score between 0 and 100),final_score numeric(7,2) check(final_score between 0 and 100),decision public.academic_defense_decision not null default 'PENDING',comments_fr text,comments_en text,status public.academic_defense_status not null default 'DRAFT',scheduled_by uuid references public.profiles(id),completed_by uuid references public.profiles(id),completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(thesis_id),check(end_time is null or end_time>start_time));
create table if not exists public.academic_practicum_documents(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,student_id uuid not null references public.academic_students(id) on delete restrict,entity_type text not null check(entity_type in('INTERNSHIP','SUPERVISION','THESIS','MILESTONE','DEFENSE')),entity_id uuid not null,document_type public.academic_practicum_document_type not null,title_fr text not null,title_en text not null,storage_bucket text not null default 'academic-practicum-documents',storage_path text not null,original_file_name text not null,mime_type text,file_size_bytes bigint check(file_size_bytes is null or file_size_bytes>=0),version integer not null default 1 check(version>0),status public.academic_record_status not null default 'ACTIVE',uploaded_by uuid not null references public.profiles(id),uploaded_at timestamptz not null default now(),verified_by uuid references public.profiles(id),verified_at timestamptz,verification_comment text,unique(entity_type,entity_id,document_type,version));
create table if not exists public.academic_practicum_history(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,entity_type text not null check(entity_type in('INTERNSHIP','SUPERVISION','THESIS','MILESTONE','DEFENSE','DOCUMENT')),entity_id uuid not null,student_id uuid not null references public.academic_students(id) on delete restrict,old_status text,new_status text,action text not null,reason text not null,changed_by uuid references public.profiles(id),changed_at timestamptz not null default now());

create index if not exists academic_internships_student_idx on public.academic_internships(student_id,academic_year_id,status);
create index if not exists academic_internships_supervisor_idx on public.academic_internships(academic_supervisor_id,status);
create index if not exists academic_supervisions_internship_idx on public.academic_internship_supervisions(internship_id,supervision_date desc);
create index if not exists academic_theses_student_idx on public.academic_theses(student_id,program_id,status);
create index if not exists academic_theses_supervisor_idx on public.academic_theses(supervisor_id,status);
create index if not exists academic_milestones_thesis_idx on public.academic_thesis_milestones(thesis_id,due_date,status);
create index if not exists academic_defenses_program_idx on public.academic_defenses(program_id,defense_date,status);
create index if not exists academic_practicum_documents_entity_idx on public.academic_practicum_documents(entity_type,entity_id,version desc);
create index if not exists academic_practicum_history_entity_idx on public.academic_practicum_history(entity_type,entity_id,changed_at desc);

create or replace function public.academic_set_practicum_number() returns trigger language plpgsql as $$ begin
 if tg_table_name='academic_internships' and coalesce(new.internship_number,'')='' then new.internship_number:='INT-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.academic_internship_code_seq')::text,5,'0');
 elsif tg_table_name='academic_theses' and coalesce(new.thesis_number,'')='' then new.thesis_number:='THS-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.academic_thesis_code_seq')::text,5,'0');
 elsif tg_table_name='academic_thesis_milestones' and coalesce(new.milestone_number,'')='' then new.milestone_number:='MS-'||lpad(nextval('public.academic_milestone_code_seq')::text,6,'0');
 elsif tg_table_name='academic_defenses' and coalesce(new.defense_number,'')='' then new.defense_number:='DEF-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.academic_defense_code_seq')::text,5,'0');end if;return new;end $$;
do $$ declare t text;begin foreach t in array array['academic_internships','academic_theses','academic_thesis_milestones','academic_defenses'] loop execute format('drop trigger if exists %I_number on public.%I',t,t);execute format('create trigger %I_number before insert on public.%I for each row execute function public.academic_set_practicum_number()',t,t);end loop;end $$;

create or replace function public.academic_transition_internship(p_id uuid,p_status public.academic_internship_status,p_reason text) returns public.academic_internships language plpgsql security definer set search_path=public as $$
declare r public.academic_internships;old public.academic_internship_status;allowed boolean;begin select * into r from public.academic_internships where id=p_id for update;if r.id is null then raise exception 'Internship not found';end if;old:=r.status;
allowed:=case when old='DRAFT' then p_status in('SUBMITTED','CANCELLED') when old='SUBMITTED' then p_status in('APPROVED','REJECTED') when old='REJECTED' then p_status='DRAFT' when old='APPROVED' then p_status='IN_PROGRESS' when old='IN_PROGRESS' then p_status in('COMPLETED','CANCELLED') when old='COMPLETED' then p_status='UNDER_REVIEW' when old='UNDER_REVIEW' then p_status in('VALIDATED','REJECTED') else false end;if not allowed then raise exception 'Invalid internship transition: % -> %',old,p_status;end if;
if not(exists(select 1 from public.academic_students s where s.id=r.student_id and s.user_id=auth.uid() and p_status in('SUBMITTED','CANCELLED','DRAFT'))or r.academic_supervisor_id=auth.uid()or public.academic_has_program_scope(r.organization_id,r.program_id,case when p_status in('APPROVED','VALIDATED','REJECTED') then 'internship.validate' else 'internship.manage' end))then raise exception 'Internship workflow permission required';end if;
if p_status='COMPLETED' and(r.completed_hours<r.expected_hours or r.report_storage_path is null)then raise exception 'Expected hours and internship report are required before completion';end if;
update public.academic_internships set status=p_status,submitted_by=case when p_status='SUBMITTED' then auth.uid() else submitted_by end,submitted_at=case when p_status='SUBMITTED' then now() else submitted_at end,validated_by=case when p_status='VALIDATED' then auth.uid() else validated_by end,validated_at=case when p_status='VALIDATED' then now() else validated_at end,rejection_reason=case when p_status='REJECTED' then p_reason else null end,updated_at=now() where id=p_id returning * into r;
insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,old_status,new_status,action,reason,changed_by)values(r.organization_id,'INTERNSHIP',r.id,r.student_id,old::text,p_status::text,'STATUS_CHANGED',coalesce(nullif(trim(p_reason),''),'Workflow transition'),auth.uid());return r;end $$;
create or replace function public.academic_transition_thesis(p_id uuid,p_status public.academic_thesis_status,p_reason text) returns public.academic_theses language plpgsql security definer set search_path=public as $$
declare r public.academic_theses;old public.academic_thesis_status;allowed boolean;begin select * into r from public.academic_theses where id=p_id for update;if r.id is null then raise exception 'Thesis not found';end if;old:=r.status;
allowed:=case when old='PROPOSED' then p_status='SUBMITTED' when old='SUBMITTED' then p_status in('APPROVED','REJECTED') when old='REJECTED' then p_status='PROPOSED' when old='APPROVED' then p_status='IN_PROGRESS' when old='IN_PROGRESS' then p_status='SUBMITTED_FOR_REVIEW' when old='SUBMITTED_FOR_REVIEW' then p_status in('UNDER_REVIEW','CORRECTIONS_REQUIRED') when old='UNDER_REVIEW' then p_status in('READY_FOR_DEFENSE','CORRECTIONS_REQUIRED') when old='CORRECTIONS_REQUIRED' then p_status='SUBMITTED_FOR_REVIEW' when old='READY_FOR_DEFENSE' then p_status='DEFENDED' when old='DEFENDED' then p_status in('VALIDATED','CORRECTIONS_REQUIRED') else false end;if not allowed then raise exception 'Invalid thesis transition: % -> %',old,p_status;end if;
if not(exists(select 1 from public.academic_students s where s.id=r.student_id and s.user_id=auth.uid() and p_status in('SUBMITTED','SUBMITTED_FOR_REVIEW'))or r.supervisor_id=auth.uid()or r.co_supervisor_id=auth.uid()or public.academic_has_program_scope(r.organization_id,r.program_id,case when p_status in('APPROVED','READY_FOR_DEFENSE','VALIDATED','REJECTED') then 'thesis.validate' else 'thesis.manage' end))then raise exception 'Thesis workflow permission required';end if;
if p_status='READY_FOR_DEFENSE' and(r.document_storage_path is null or r.plagiarism_status<>'CLEAR')then raise exception 'Final document and clear plagiarism check are required';end if;
update public.academic_theses set status=p_status,approval_date=case when p_status='APPROVED' then current_date else approval_date end,submission_date=case when p_status='SUBMITTED_FOR_REVIEW' then current_date else submission_date end,submitted_by=case when p_status in('SUBMITTED','SUBMITTED_FOR_REVIEW') then auth.uid() else submitted_by end,submitted_at=case when p_status in('SUBMITTED','SUBMITTED_FOR_REVIEW') then now() else submitted_at end,validated_by=case when p_status='VALIDATED' then auth.uid() else validated_by end,validated_at=case when p_status='VALIDATED' then now() else validated_at end,rejection_reason=case when p_status='REJECTED' then p_reason else null end,updated_at=now() where id=p_id returning * into r;
insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,old_status,new_status,action,reason,changed_by)values(r.organization_id,'THESIS',r.id,r.student_id,old::text,p_status::text,'STATUS_CHANGED',coalesce(nullif(trim(p_reason),''),'Workflow transition'),auth.uid());return r;end $$;

insert into public.academic_role_permissions(role,permission_code,description_fr,description_en)values
('STUDENT','practicum.self.read','Consulter ses stages et memoires','Read own internships and theses'),
('INTERNSHIP_SUPERVISOR','internship.read','Consulter les stages affectes','Read assigned internships'),('INTERNSHIP_SUPERVISOR','internship.manage','Suivre les stages affectes','Manage assigned internships'),
('THESIS_SUPERVISOR','thesis.read','Consulter les memoires affectes','Read assigned theses'),('THESIS_SUPERVISOR','thesis.manage','Suivre les memoires affectes','Manage assigned theses'),
('PROGRAM_COORDINATOR','internship.read','Consulter les stages du programme','Read program internships'),('PROGRAM_COORDINATOR','internship.manage','Gerer les stages du programme','Manage program internships'),('PROGRAM_COORDINATOR','internship.validate','Valider les stages','Validate internships'),('PROGRAM_COORDINATOR','thesis.read','Consulter les memoires du programme','Read program theses'),('PROGRAM_COORDINATOR','thesis.manage','Gerer les memoires du programme','Manage program theses'),('PROGRAM_COORDINATOR','thesis.validate','Valider les memoires','Validate theses'),
('ACADEMIC_SECRETARY','internship.read','Consulter les stages','Read internships'),('ACADEMIC_SECRETARY','thesis.read','Consulter les memoires','Read theses'),
('ACADEMIC_ADMIN','internship.read','Consulter tous les stages','Read all internships'),('ACADEMIC_ADMIN','internship.manage','Gerer tous les stages','Manage all internships'),('ACADEMIC_ADMIN','internship.validate','Valider les stages','Validate internships'),('ACADEMIC_ADMIN','thesis.read','Consulter tous les memoires','Read all theses'),('ACADEMIC_ADMIN','thesis.manage','Gerer tous les memoires','Manage all theses'),('ACADEMIC_ADMIN','thesis.validate','Valider les memoires','Validate theses'),
('SUPER_ADMIN','internship.read','Consulter tous les stages','Read all internships'),('SUPER_ADMIN','internship.manage','Gerer tous les stages','Manage all internships'),('SUPER_ADMIN','internship.validate','Valider les stages','Validate internships'),('SUPER_ADMIN','thesis.read','Consulter tous les memoires','Read all theses'),('SUPER_ADMIN','thesis.manage','Gerer tous les memoires','Manage all theses'),('SUPER_ADMIN','thesis.validate','Valider les memoires','Validate theses')
on conflict(role,permission_code)do update set description_fr=excluded.description_fr,description_en=excluded.description_en;

do $$ declare t text;begin foreach t in array array['academic_internships','academic_internship_supervisions','academic_theses','academic_thesis_milestones','academic_defenses','academic_practicum_documents','academic_practicum_history']loop execute format('alter table public.%I enable row level security',t);end loop;end $$;
create or replace function public.academic_can_read_practicum(p_student_id uuid,p_program_id uuid,p_supervisor_id uuid,p_permission text)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.academic_students s where s.id=p_student_id and s.user_id=auth.uid())or p_supervisor_id=auth.uid()or public.academic_has_program_scope((select organization_id from public.academic_students where id=p_student_id),p_program_id,p_permission)$$;
grant execute on function public.academic_can_read_practicum(uuid,uuid,uuid,text)to authenticated;
drop policy if exists "internships read" on public.academic_internships;create policy "internships read" on public.academic_internships for select to authenticated using(public.academic_can_read_practicum(student_id,program_id,academic_supervisor_id,'internship.read'));
drop policy if exists "internships create" on public.academic_internships;create policy "internships create" on public.academic_internships for insert to authenticated with check(created_by=auth.uid()and(exists(select 1 from public.academic_students s where s.id=student_id and s.user_id=auth.uid())or public.academic_has_program_scope(organization_id,program_id,'internship.manage')));
drop policy if exists "supervisions read" on public.academic_internship_supervisions;create policy "supervisions read" on public.academic_internship_supervisions for select to authenticated using(exists(select 1 from public.academic_internships i where i.id=internship_id and public.academic_can_read_practicum(i.student_id,i.program_id,i.academic_supervisor_id,'internship.read')));
drop policy if exists "supervisions create" on public.academic_internship_supervisions;create policy "supervisions create" on public.academic_internship_supervisions for insert to authenticated with check(supervisor_id=auth.uid()and exists(select 1 from public.academic_internships i where i.id=internship_id and(i.academic_supervisor_id=auth.uid()or public.academic_has_program_scope(i.organization_id,i.program_id,'internship.manage'))));
drop policy if exists "theses read" on public.academic_theses;create policy "theses read" on public.academic_theses for select to authenticated using(public.academic_can_read_practicum(student_id,program_id,supervisor_id,'thesis.read')or co_supervisor_id=auth.uid());
drop policy if exists "theses create" on public.academic_theses;create policy "theses create" on public.academic_theses for insert to authenticated with check(created_by=auth.uid()and(exists(select 1 from public.academic_students s where s.id=student_id and s.user_id=auth.uid())or public.academic_has_program_scope(organization_id,program_id,'thesis.manage')));
drop policy if exists "milestones read" on public.academic_thesis_milestones;create policy "milestones read" on public.academic_thesis_milestones for select to authenticated using(exists(select 1 from public.academic_theses t where t.id=thesis_id and(public.academic_can_read_practicum(t.student_id,t.program_id,t.supervisor_id,'thesis.read')or t.co_supervisor_id=auth.uid())));
drop policy if exists "milestones create" on public.academic_thesis_milestones;create policy "milestones create" on public.academic_thesis_milestones for insert to authenticated with check(created_by=auth.uid()and exists(select 1 from public.academic_theses t where t.id=thesis_id and(public.academic_can_read_practicum(t.student_id,t.program_id,t.supervisor_id,'thesis.manage')or t.co_supervisor_id=auth.uid())));
drop policy if exists "defenses read" on public.academic_defenses;create policy "defenses read" on public.academic_defenses for select to authenticated using(public.academic_can_read_practicum(student_id,program_id,null,'thesis.read'));
drop policy if exists "practicum documents read" on public.academic_practicum_documents;create policy "practicum documents read" on public.academic_practicum_documents for select to authenticated using(exists(select 1 from public.academic_students s where s.id=student_id and(s.user_id=auth.uid()or public.academic_has_program_scope(organization_id,s.current_program_id,'internship.read')or public.academic_has_program_scope(organization_id,s.current_program_id,'thesis.read'))));
drop policy if exists "practicum documents create" on public.academic_practicum_documents;create policy "practicum documents create" on public.academic_practicum_documents for insert to authenticated with check(uploaded_by=auth.uid()and exists(select 1 from public.academic_students s where s.id=student_id and(s.user_id=auth.uid()or public.academic_has_program_scope(organization_id,s.current_program_id,'internship.manage')or public.academic_has_program_scope(organization_id,s.current_program_id,'thesis.manage'))));
drop policy if exists "practicum history read" on public.academic_practicum_history;create policy "practicum history read" on public.academic_practicum_history for select to authenticated using(exists(select 1 from public.academic_students s where s.id=student_id and(s.user_id=auth.uid()or public.academic_has_program_scope(organization_id,s.current_program_id,'internship.read')or public.academic_has_program_scope(organization_id,s.current_program_id,'thesis.read'))));

revoke all on function public.academic_transition_internship(uuid,public.academic_internship_status,text)from public;revoke all on function public.academic_transition_thesis(uuid,public.academic_thesis_status,text)from public;
grant execute on function public.academic_transition_internship(uuid,public.academic_internship_status,text)to authenticated;grant execute on function public.academic_transition_thesis(uuid,public.academic_thesis_status,text)to authenticated;
insert into storage.buckets(id,name,public)values('academic-practicum-documents','academic-practicum-documents',false)on conflict(id)do nothing;
drop policy if exists "academic practicum files read" on storage.objects;create policy "academic practicum files read" on storage.objects for select to authenticated using(bucket_id='academic-practicum-documents'and(storage.foldername(name))[1]~'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'and exists(select 1 from public.academic_students s where s.id=(storage.foldername(name))[1]::uuid and(s.user_id=auth.uid()or public.academic_has_program_scope(s.organization_id,s.current_program_id,'internship.read')or public.academic_has_program_scope(s.organization_id,s.current_program_id,'thesis.read'))));
drop policy if exists "academic practicum files upload" on storage.objects;create policy "academic practicum files upload" on storage.objects for insert to authenticated with check(bucket_id='academic-practicum-documents'and(storage.foldername(name))[1]~'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'and exists(select 1 from public.academic_students s where s.id=(storage.foldername(name))[1]::uuid and(s.user_id=auth.uid()or public.academic_has_program_scope(s.organization_id,s.current_program_id,'internship.manage')or public.academic_has_program_scope(s.organization_id,s.current_program_id,'thesis.manage'))));insert into public.academic_role_permissions(role,permission_code,description_fr,description_en)values
('INTERNSHIP_SUPERVISOR','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area'),('THESIS_SUPERVISOR','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area'),('PROGRAM_COORDINATOR','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area'),('ACADEMIC_SECRETARY','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area'),('ACADEMIC_ADMIN','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area'),('SUPER_ADMIN','practicum.read','Acceder a l espace stages et memoires','Access internships and theses area')
on conflict(role,permission_code)do update set description_fr=excluded.description_fr,description_en=excluded.description_en;
create or replace function public.academic_register_practicum_document(p_student_id uuid,p_entity_type text,p_entity_id uuid,p_document_type public.academic_practicum_document_type,p_title_fr text,p_title_en text,p_storage_path text,p_original_file_name text,p_mime_type text,p_file_size_bytes bigint)
returns public.academic_practicum_documents language plpgsql security definer set search_path=public as $$
declare s public.academic_students;allowed boolean:=false;v integer;r public.academic_practicum_documents;begin
 select * into s from public.academic_students where id=p_student_id;if s.id is null then raise exception 'Student not found';end if;
 allowed:=s.user_id=auth.uid()or public.academic_has_program_scope(s.organization_id,s.current_program_id,case when p_entity_type in('INTERNSHIP','SUPERVISION')then 'internship.manage' else 'thesis.manage' end);if not allowed then raise exception 'Document upload permission required';end if;
 if p_storage_path not like p_student_id::text||'/%' then raise exception 'Storage path must begin with the student ID';end if;
 if p_entity_type='INTERNSHIP' then allowed:=exists(select 1 from public.academic_internships where id=p_entity_id and student_id=p_student_id);
 elsif p_entity_type='SUPERVISION' then allowed:=exists(select 1 from public.academic_internship_supervisions x join public.academic_internships i on i.id=x.internship_id where x.id=p_entity_id and i.student_id=p_student_id);
 elsif p_entity_type='THESIS' then allowed:=exists(select 1 from public.academic_theses where id=p_entity_id and student_id=p_student_id);
 elsif p_entity_type='MILESTONE' then allowed:=exists(select 1 from public.academic_thesis_milestones x join public.academic_theses t on t.id=x.thesis_id where x.id=p_entity_id and t.student_id=p_student_id);
 elsif p_entity_type='DEFENSE' then allowed:=exists(select 1 from public.academic_defenses where id=p_entity_id and student_id=p_student_id);else allowed:=false;end if;if not allowed then raise exception 'Document entity does not belong to student';end if;
 select coalesce(max(version),0)+1 into v from public.academic_practicum_documents where entity_type=p_entity_type and entity_id=p_entity_id and document_type=p_document_type;
 insert into public.academic_practicum_documents(organization_id,student_id,entity_type,entity_id,document_type,title_fr,title_en,storage_path,original_file_name,mime_type,file_size_bytes,version,uploaded_by)values(s.organization_id,p_student_id,p_entity_type,p_entity_id,p_document_type,p_title_fr,p_title_en,p_storage_path,p_original_file_name,p_mime_type,p_file_size_bytes,v,auth.uid())returning * into r;
 if p_entity_type='INTERNSHIP' and p_document_type='INTERNSHIP_REPORT' then update public.academic_internships set report_storage_path=p_storage_path,updated_at=now()where id=p_entity_id;
 elsif p_entity_type='THESIS' and p_document_type='THESIS_FINAL' then update public.academic_theses set document_storage_path=p_storage_path,updated_at=now()where id=p_entity_id;elsif p_entity_type='MILESTONE' then update public.academic_thesis_milestones set storage_path=p_storage_path,updated_at=now()where id=p_entity_id;end if;
 insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,action,reason,changed_by)values(s.organization_id,'DOCUMENT',r.id,p_student_id,'DOCUMENT_VERSION_ADDED','Version '||v||' - '||p_document_type::text,auth.uid());return r;end $$;

create or replace function public.academic_update_internship_progress(p_id uuid,p_completed_hours numeric,p_evaluation_score numeric,p_evaluation_comment text,p_reason text)returns public.academic_internships language plpgsql security definer set search_path=public as $$
declare r public.academic_internships;begin select * into r from public.academic_internships where id=p_id for update;if r.id is null then raise exception 'Internship not found';end if;if not(r.academic_supervisor_id=auth.uid()or public.academic_has_program_scope(r.organization_id,r.program_id,'internship.manage'))then raise exception 'Internship management permission required';end if;if p_completed_hours<0 or p_completed_hours>r.expected_hours then raise exception 'Completed hours must be between zero and expected hours';end if;
 update public.academic_internships set completed_hours=p_completed_hours,evaluation_score=p_evaluation_score,evaluation_comment=p_evaluation_comment,updated_at=now()where id=p_id returning * into r;insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,action,reason,changed_by)values(r.organization_id,'INTERNSHIP',r.id,r.student_id,'PROGRESS_UPDATED',p_reason,auth.uid());return r;end $$;

create or replace function public.academic_update_thesis_review(p_id uuid,p_plagiarism_status text,p_plagiarism_score numeric,p_reason text)returns public.academic_theses language plpgsql security definer set search_path=public as $$
declare r public.academic_theses;begin select * into r from public.academic_theses where id=p_id for update;if r.id is null then raise exception 'Thesis not found';end if;if not(r.supervisor_id=auth.uid()or r.co_supervisor_id=auth.uid()or public.academic_has_program_scope(r.organization_id,r.program_id,'thesis.manage'))then raise exception 'Thesis management permission required';end if;if p_plagiarism_status not in('NOT_CHECKED','PENDING','CLEAR','REVIEW_REQUIRED','BLOCKED')or p_plagiarism_score<0 or p_plagiarism_score>100 then raise exception 'Invalid plagiarism review';end if;
 update public.academic_theses set plagiarism_status=p_plagiarism_status,plagiarism_score=p_plagiarism_score,updated_at=now()where id=p_id returning * into r;insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,action,reason,changed_by)values(r.organization_id,'THESIS',r.id,r.student_id,'PLAGIARISM_REVIEWED',p_reason,auth.uid());return r;end $$;
revoke all on function public.academic_register_practicum_document(uuid,text,uuid,public.academic_practicum_document_type,text,text,text,text,text,bigint)from public;
revoke all on function public.academic_update_internship_progress(uuid,numeric,numeric,text,text)from public;
revoke all on function public.academic_update_thesis_review(uuid,text,numeric,text)from public;
grant execute on function public.academic_register_practicum_document(uuid,text,uuid,public.academic_practicum_document_type,text,text,text,text,text,bigint)to authenticated;
grant execute on function public.academic_update_internship_progress(uuid,numeric,numeric,text,text)to authenticated;
grant execute on function public.academic_update_thesis_review(uuid,text,numeric,text)to authenticated;
create or replace function public.academic_transition_thesis_milestone(p_id uuid,p_status public.academic_milestone_status,p_storage_path text,p_comment_fr text,p_comment_en text,p_reason text)returns public.academic_thesis_milestones language plpgsql security definer set search_path=public as $$
declare r public.academic_thesis_milestones;t public.academic_theses;old public.academic_milestone_status;allowed boolean;begin select * into r from public.academic_thesis_milestones where id=p_id for update;select * into t from public.academic_theses where id=r.thesis_id;if r.id is null then raise exception 'Milestone not found';end if;old:=r.status;allowed:=case when old='PLANNED' then p_status='IN_PROGRESS' when old='IN_PROGRESS' then p_status='SUBMITTED' when old='SUBMITTED' then p_status in('ACCEPTED','REVISION_REQUIRED') when old='REVISION_REQUIRED' then p_status='SUBMITTED' when old='ACCEPTED' then p_status='COMPLETED' else false end;if not allowed then raise exception 'Invalid milestone transition: % -> %',old,p_status;end if;
if p_status='SUBMITTED' then if not exists(select 1 from public.academic_students s where s.id=t.student_id and s.user_id=auth.uid())and not(t.supervisor_id=auth.uid()or t.co_supervisor_id=auth.uid())then raise exception 'Student or supervisor permission required';end if;if coalesce(p_storage_path,r.storage_path) is null then raise exception 'A milestone file is required';end if;elsif not(t.supervisor_id=auth.uid()or t.co_supervisor_id=auth.uid()or public.academic_has_program_scope(t.organization_id,t.program_id,'thesis.manage'))then raise exception 'Milestone review permission required';end if;
update public.academic_thesis_milestones set status=p_status,storage_path=coalesce(p_storage_path,storage_path),submitted_at=case when p_status='SUBMITTED' then now()else submitted_at end,reviewed_by=case when p_status in('ACCEPTED','REVISION_REQUIRED','COMPLETED')then auth.uid()else reviewed_by end,reviewed_at=case when p_status in('ACCEPTED','REVISION_REQUIRED','COMPLETED')then now()else reviewed_at end,review_comment_fr=coalesce(p_comment_fr,review_comment_fr),review_comment_en=coalesce(p_comment_en,review_comment_en),updated_at=now()where id=p_id returning * into r;
insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,old_status,new_status,action,reason,changed_by)values(r.organization_id,'MILESTONE',r.id,t.student_id,old::text,p_status::text,'STATUS_CHANGED',p_reason,auth.uid());return r;end $$;

create or replace function public.academic_schedule_defense(p_thesis_id uuid,p_date date,p_start_time time,p_end_time time,p_location_or_link text,p_reason text)returns public.academic_defenses language plpgsql security definer set search_path=public as $$
declare t public.academic_theses;r public.academic_defenses;begin select * into t from public.academic_theses where id=p_thesis_id for update;if t.id is null then raise exception 'Thesis not found';end if;if t.status<>'READY_FOR_DEFENSE' then raise exception 'Thesis must be ready for defense';end if;if not public.academic_has_program_scope(t.organization_id,t.program_id,'thesis.validate')then raise exception 'Defense scheduling permission required';end if;if p_date<current_date or(p_end_time is not null and p_end_time<=p_start_time)then raise exception 'Invalid defense schedule';end if;
insert into public.academic_defenses(organization_id,thesis_id,student_id,program_id,defense_date,start_time,end_time,location_or_link,status,scheduled_by)values(t.organization_id,t.id,t.student_id,t.program_id,p_date,p_start_time,p_end_time,p_location_or_link,'SCHEDULED',auth.uid())returning * into r;insert into public.academic_practicum_history(organization_id,entity_type,entity_id,student_id,new_status,action,reason,changed_by)values(t.organization_id,'DEFENSE',r.id,t.student_id,'SCHEDULED','DEFENSE_SCHEDULED',p_reason,auth.uid());return r;end $$;
revoke all on function public.academic_transition_thesis_milestone(uuid,public.academic_milestone_status,text,text,text,text)from public;
revoke all on function public.academic_schedule_defense(uuid,date,time,time,text,text)from public;
grant execute on function public.academic_transition_thesis_milestone(uuid,public.academic_milestone_status,text,text,text,text)to authenticated;
grant execute on function public.academic_schedule_defense(uuid,date,time,time,text,text)to authenticated;