-- Degree Programs - Lot 10: reporting and dashboards. Run after 018.
do $$ begin
 if to_regclass('public.academic_internships') is null or to_regclass('public.academic_theses') is null then
  raise exception 'Prerequisite missing: run 017_degree_programs_internships_theses.sql before migration 019';
 end if;
end $$;
do $$ begin create type public.academic_report_status as enum ('REQUESTED','RUNNING','COMPLETED','FAILED','EXPIRED'); exception when duplicate_object then null; end $$;
create table if not exists public.academic_report_definitions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),code citext not null,name_fr text not null,name_en text not null,description_fr text,description_en text,report_category text not null,active boolean not null default true,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table if not exists public.academic_report_runs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),definition_id uuid references public.academic_report_definitions(id),program_id uuid references public.academic_programs(id),academic_year_id uuid references public.academic_years(id),semester_id uuid references public.academic_semesters(id),requested_format text not null default 'DASHBOARD' check(requested_format in('DASHBOARD','CSV','XLSX','PDF')),status public.academic_report_status not null default 'REQUESTED',requested_by uuid not null references public.profiles(id),requested_at timestamptz not null default now(),completed_at timestamptz,file_path text,error_message text);
create table if not exists public.academic_report_metric_rows(
 id uuid primary key default gen_random_uuid(),report_run_id uuid not null references public.academic_report_runs(id) on delete cascade,metric_code text not null,label_fr text not null,label_en text not null,dimension_code text not null default 'TOTAL',dimension_value text not null default 'ALL',numeric_value numeric(18,4),text_value text,display_order integer not null default 0,created_at timestamptz not null default now(),unique(report_run_id,metric_code,dimension_code,dimension_value),check(numeric_value is not null or text_value is not null));
create index if not exists academic_report_runs_scope_idx on public.academic_report_runs(organization_id,program_id,academic_year_id,semester_id,requested_at desc);
create index if not exists academic_report_metrics_run_idx on public.academic_report_metric_rows(report_run_id,display_order);
create or replace view public.academic_program_reporting_v with(security_invoker=true)as
select p.organization_id,p.id program_id,p.code::text program_code,p.name_fr,p.name_en,
 (select count(*)from public.academic_students s where s.current_program_id=p.id)students_total,
 (select count(*)from public.academic_students s where s.current_program_id=p.id and s.academic_status='ENROLLED')students_active,
 (select count(*)from public.academic_students s where s.current_program_id=p.id and s.academic_status='GRADUATED')graduates,
 (select count(*)from public.academic_administrative_registrations ar where ar.program_id=p.id and ar.status='VALIDATED')registrations_validated,
 (select count(*)from public.academic_course_results cr join public.academic_students s on s.id=cr.student_id where s.current_program_id=p.id and cr.workflow_status='VALIDATED')course_results_validated,
 coalesce((select round(avg(cr.final_score),2)from public.academic_course_results cr join public.academic_students s on s.id=cr.student_id where s.current_program_id=p.id and cr.workflow_status='VALIDATED'),0)average_score,
 coalesce((select round(100.0*count(*)filter(where cr.result_status in('PASSED','EXEMPTED'))/nullif(count(*),0),2)from public.academic_course_results cr join public.academic_students s on s.id=cr.student_id where s.current_program_id=p.id and cr.workflow_status='VALIDATED'),0)success_rate,
 (select count(*)from public.academic_resit_eligibility re join public.academic_students s on s.id=re.student_id where s.current_program_id=p.id and re.status in('ELIGIBLE','REGISTERED'))resits,
 (select count(*)from public.academic_internships i where i.program_id=p.id)internships,
 (select count(*)from public.academic_theses t where t.program_id=p.id)theses,
 (select count(*)from public.academic_defenses d where d.program_id=p.id and d.status in('SCHEDULED','CONFIRMED'))upcoming_defenses
from public.academic_programs p offset 0;
create or replace view public.academic_student_dashboard_v with(security_invoker=true)as
select s.organization_id,s.id student_id,s.user_id,s.student_number,s.current_program_id,s.current_level,s.current_semester,s.academic_status,
 coalesce((select sum(cl.credits_earned)from public.academic_credit_ledger cl where cl.student_id=s.id and cl.level='COURSE'),0)credits_earned,p.total_credits greatest_credits,
 greatest(p.total_credits-coalesce((select sum(cl.credits_earned)from public.academic_credit_ledger cl where cl.student_id=s.id and cl.level='COURSE'),0),0)credits_remaining,
 coalesce((select round(avg(cr.final_score),2)from public.academic_course_results cr where cr.student_id=s.id and cr.workflow_status='VALIDATED'),0)published_average,
 (select count(*)from public.academic_course_enrollments ce where ce.student_id=s.id and ce.status='ACTIVE')active_courses,
 (select count(*)from public.academic_assessments a join public.academic_course_enrollments ce on ce.course_id=a.course_id and ce.semester_id=a.semester_id where ce.student_id=s.id and ce.status='ACTIVE'and a.status='OPEN'and a.assessment_date>=current_date)upcoming_assessments,
 (select count(*)from public.academic_attendance_records ar where ar.student_id=s.id and ar.status='ABSENT')absences
from public.academic_students s join public.academic_programs p on p.id=s.current_program_id offset 0;create or replace function public.academic_create_report_snapshot(p_code text,p_program uuid,p_year uuid,p_semester uuid,p_format text)returns public.academic_report_runs language plpgsql security definer set search_path=public as $$
declare org uuid;def uuid;r public.academic_report_runs;begin select organization_id into org from public.academic_programs where id=p_program;if org is null then select organization_id into org from public.academic_role_assignments where user_id=auth.uid()and active limit 1;end if;if not public.academic_has_permission(org,'reporting.export')then raise exception 'Reporting export permission required';end if;select id into def from public.academic_report_definitions where organization_id=org and code=p_code and active;
insert into public.academic_report_runs(organization_id,definition_id,program_id,academic_year_id,semester_id,requested_format,status,requested_by)values(org,def,p_program,p_year,p_semester,coalesce(p_format,'DASHBOARD'),'RUNNING',auth.uid())returning * into r;
if p_code='PROGRAM_OVERVIEW'then insert into public.academic_report_metric_rows(report_run_id,metric_code,label_fr,label_en,numeric_value,display_order)select r.id,'STUDENTS','Effectif','Students',students_total,1 from public.academic_program_reporting_v where program_id=p_program union all select r.id,'SUCCESS_RATE','Taux de reussite','Success rate',success_rate,2 from public.academic_program_reporting_v where program_id=p_program union all select r.id,'GRADUATES','Diplomes','Graduates',graduates,3 from public.academic_program_reporting_v where program_id=p_program;end if;
update public.academic_report_runs set status='COMPLETED',completed_at=now()where id=r.id returning * into r;insert into public.academic_audit_logs(organization_id,actor_user_id,entity_type,entity_id,action,new_value,reason)values(org,auth.uid(),'academic_report_runs',r.id,'REPORT_GENERATED',to_jsonb(r),'Structured academic report snapshot');return r;exception when others then if r.id is not null then update public.academic_report_runs set status='FAILED',error_message=sqlerrm,completed_at=now()where id=r.id;end if;raise;end$$;
insert into public.academic_role_permissions(role,permission_code,description_fr,description_en)values
('STUDENT','dashboard.self.read','Consulter son tableau de bord','Read own dashboard'),('INSTRUCTOR','dashboard.instructor.read','Consulter son tableau enseignant','Read instructor dashboard'),('PROGRAM_COORDINATOR','reporting.read','Consulter les rapports du programme','Read program reports'),('PROGRAM_COORDINATOR','reporting.export','Exporter les rapports du programme','Export program reports'),('ACADEMIC_SECRETARY','reporting.read','Consulter les rapports academiques','Read academic reports'),('ACADEMIC_ADMIN','reporting.read','Consulter tous les rapports','Read all reports'),('ACADEMIC_ADMIN','reporting.export','Exporter tous les rapports','Export all reports'),('SUPER_ADMIN','reporting.read','Consulter tous les rapports','Read all reports'),('SUPER_ADMIN','reporting.export','Exporter tous les rapports','Export all reports')on conflict(role,permission_code)do update set description_fr=excluded.description_fr,description_en=excluded.description_en;
alter table public.academic_report_definitions enable row level security;alter table public.academic_report_runs enable row level security;alter table public.academic_report_metric_rows enable row level security;
drop policy if exists "report definitions read" on public.academic_report_definitions;create policy "report definitions read" on public.academic_report_definitions for select to authenticated using(public.academic_has_permission(organization_id,'reporting.read'));
drop policy if exists "report definitions manage" on public.academic_report_definitions;create policy "report definitions manage" on public.academic_report_definitions for all to authenticated using(public.academic_has_permission(organization_id,'academic.manage'))with check(public.academic_has_permission(organization_id,'academic.manage'));
drop policy if exists "report runs read" on public.academic_report_runs;create policy "report runs read" on public.academic_report_runs for select to authenticated using(requested_by=auth.uid()or public.academic_has_permission(organization_id,'reporting.read'));
drop policy if exists "report metrics read" on public.academic_report_metric_rows;create policy "report metrics read" on public.academic_report_metric_rows for select to authenticated using(exists(select 1 from public.academic_report_runs r where r.id=report_run_id and(r.requested_by=auth.uid()or public.academic_has_permission(r.organization_id,'reporting.read'))));
revoke all on function public.academic_create_report_snapshot(text,uuid,uuid,uuid,text)from public;grant execute on function public.academic_create_report_snapshot(text,uuid,uuid,uuid,text)to authenticated;
