create table if not exists public.child_growth_page_settings(
 id integer primary key default 1 check(id=1),page_title text not null,page_title_en text not null,page_intro text not null,page_intro_en text not null,
 chart_title text not null,chart_title_en text not null,normal_message text not null,normal_message_en text not null,
 advice_title text not null,advice_title_en text not null,advice jsonb not null default '[]'::jsonb,
 help_title text not null,help_title_en text not null,help_text text not null,help_text_en text not null,updated_at timestamptz not null default now());
alter table public.child_growth_page_settings enable row level security;
drop policy if exists "Public reads child growth page settings" on public.child_growth_page_settings;
drop policy if exists "Admins manage child growth page settings" on public.child_growth_page_settings;
create policy "Public reads child growth page settings" on public.child_growth_page_settings for select using(true);
create policy "Admins manage child growth page settings" on public.child_growth_page_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
insert into public.child_growth_page_settings(id,page_title,page_title_en,page_intro,page_intro_en,chart_title,chart_title_en,normal_message,normal_message_en,advice_title,advice_title_en,advice,help_title,help_title_en,help_text,help_text_en) values(1,'Suivi Promotion Croissance Enfant','Child Growth Promotion Monitoring','Suivez la croissance et le développement de votre enfant en toute simplicité.','Monitor your child’s growth and development with ease.','Courbes de croissance OMS','WHO growth charts','La position de votre enfant est interprétée selon les normes OMS et son historique personnel.','Your child’s position is interpreted using WHO standards and their personal history.','Conseils personnalisés','Personalized advice','[{"icon":"food","title":"Alimentation","title_en":"Nutrition","text":"Assurez une alimentation équilibrée, variée et adaptée à l’âge de l’enfant.","text_en":"Provide a balanced, varied diet suited to your child’s age."},{"icon":"activity","title":"Activité physique","title_en":"Physical activity","text":"Encouragez au moins 60 minutes de jeu actif par jour.","text_en":"Encourage at least 60 minutes of active play each day."},{"icon":"sleep","title":"Sommeil","title_en":"Sleep","text":"Maintenez des horaires de sommeil réguliers adaptés à son âge.","text_en":"Maintain regular, age-appropriate sleep times."},{"icon":"water","title":"Hydratation","title_en":"Hydration","text":"Proposez régulièrement de l’eau tout au long de la journée.","text_en":"Offer water regularly throughout the day."}]'::jsonb,'Besoin d’aide ?','Need help?','Notre équipe est là pour vous accompagner.','Our team is here to support you.') on conflict(id) do nothing;
