-- Operations Management (Wave 6): distribution activity reports (+ product lines + beneficiary
-- breakdown) and invoices (both SF/HGSF and non-SF paths).
-- Run after ppm-ops-mise-en-oeuvre-sf.sql.

create table if not exists public.ppm_ops_activity_reports (
  id text unique not null,
  id_pk uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.ppm_ops_sites(id),
  delivery_note_id uuid references public.ppm_ops_delivery_notes(id_pk),
  period_start date not null,
  period_end date not null,
  effective_distribution_start date,
  effective_distribution_end date,
  ration_days_provided int,
  comment text,
  amount_distributed_figures numeric(16,2),
  amount_distributed_currency text,
  amount_distributed_words text,
  status text not null default 'draft' check(status in ('draft','submitted','verified','approved','returned','rejected')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.ppm_ops_activity_report_products (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.ppm_ops_activity_reports(id_pk) on delete cascade,
  product_id uuid not null references public.ppm_ops_products(id),
  start_qty numeric(14,4),
  received_qty numeric(14,4),
  received_date date,
  distributed_qty numeric(14,4),
  damaged_qty numeric(14,4),
  damaged_reason text,
  returned_qty numeric(14,4),
  returned_reason text,
  remaining_qty numeric(14,4)
);

create table if not exists public.ppm_ops_activity_beneficiaries (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.ppm_ops_activity_reports(id_pk) on delete cascade,
  sex text not null check(sex in ('male','female')),
  age_group_id uuid not null references public.ppm_ops_age_groups(id),
  count int not null default 0
);

-- Invoices — SF/HGSF path is generated by the cooperative against a delivery; non-SF path is
-- generated by the distribution manager using a flat cost-per-tonne x tonnage. Both paths share
-- the same table/workflow; cooperative_id/cost_per_tonne are simply null on whichever side
-- doesn't apply.
create table if not exists public.ppm_ops_invoices (
  id text primary key,
  delivery_note_id uuid not null references public.ppm_ops_delivery_notes(id_pk),
  site_id uuid not null references public.ppm_ops_sites(id),
  cooperative_id uuid references public.ppm_ops_cooperatives(id),
  is_sf_hgsf boolean not null,
  cost_per_tonne numeric(14,2),
  total_tonnage numeric(14,4),
  amount_figures numeric(16,2) not null,
  amount_words text not null,
  currency text not null,
  payment_account_type text check(payment_account_type in ('mobile_money','bank','other')),
  payment_account_number text,
  payment_account_name text,
  status text not null default 'draft' check(status in (
    'draft','submitted','distribution_manager_endorsed','school_endorsed','in_synthesis','paid_to_school','paid_to_cooperative','rejected'
  )),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ppm_ops_activity_reports_site on public.ppm_ops_activity_reports(site_id);
create index if not exists ppm_ops_activity_reports_delivery on public.ppm_ops_activity_reports(delivery_note_id);
create index if not exists ppm_ops_activity_report_products_report on public.ppm_ops_activity_report_products(report_id);
create index if not exists ppm_ops_activity_beneficiaries_report on public.ppm_ops_activity_beneficiaries(report_id);
create index if not exists ppm_ops_invoices_delivery on public.ppm_ops_invoices(delivery_note_id);
create index if not exists ppm_ops_invoices_site on public.ppm_ops_invoices(site_id);

alter table public.ppm_ops_activity_reports enable row level security;
alter table public.ppm_ops_activity_report_products enable row level security;
alter table public.ppm_ops_activity_beneficiaries enable row level security;
alter table public.ppm_ops_invoices enable row level security;

drop policy if exists "PPM users read ops activity reports" on public.ppm_ops_activity_reports;
create policy "PPM users read ops activity reports" on public.ppm_ops_activity_reports
  for select to authenticated using(public.platform_has_access('project_management'));
drop policy if exists "PPM managers manage ops activity reports" on public.ppm_ops_activity_reports;
create policy "PPM managers manage ops activity reports" on public.ppm_ops_activity_reports for all to authenticated
  using(exists(select 1 from public.ppm_ops_sites s where s.id = site_id and public.ppm_ops_access(s.operation_id)))
  with check(exists(select 1 from public.ppm_ops_sites s where s.id = site_id and public.ppm_ops_access(s.operation_id)));

drop policy if exists "PPM users read ops activity report products" on public.ppm_ops_activity_report_products;
create policy "PPM users read ops activity report products" on public.ppm_ops_activity_report_products
  for select to authenticated using(public.platform_has_access('project_management'));
drop policy if exists "PPM managers manage ops activity report products" on public.ppm_ops_activity_report_products;
create policy "PPM managers manage ops activity report products" on public.ppm_ops_activity_report_products for all to authenticated
  using(exists(select 1 from public.ppm_ops_activity_reports r join public.ppm_ops_sites s on s.id = r.site_id where r.id_pk = report_id and public.ppm_ops_access(s.operation_id)))
  with check(exists(select 1 from public.ppm_ops_activity_reports r join public.ppm_ops_sites s on s.id = r.site_id where r.id_pk = report_id and public.ppm_ops_access(s.operation_id)));

drop policy if exists "PPM users read ops activity beneficiaries" on public.ppm_ops_activity_beneficiaries;
create policy "PPM users read ops activity beneficiaries" on public.ppm_ops_activity_beneficiaries
  for select to authenticated using(public.platform_has_access('project_management'));
drop policy if exists "PPM managers manage ops activity beneficiaries" on public.ppm_ops_activity_beneficiaries;
create policy "PPM managers manage ops activity beneficiaries" on public.ppm_ops_activity_beneficiaries for all to authenticated
  using(exists(select 1 from public.ppm_ops_activity_reports r join public.ppm_ops_sites s on s.id = r.site_id where r.id_pk = report_id and public.ppm_ops_access(s.operation_id)))
  with check(exists(select 1 from public.ppm_ops_activity_reports r join public.ppm_ops_sites s on s.id = r.site_id where r.id_pk = report_id and public.ppm_ops_access(s.operation_id)));

drop policy if exists "PPM users read ops invoices" on public.ppm_ops_invoices;
create policy "PPM users read ops invoices" on public.ppm_ops_invoices
  for select to authenticated using(public.platform_has_access('project_management'));
drop policy if exists "PPM managers manage ops invoices" on public.ppm_ops_invoices;
create policy "PPM managers manage ops invoices" on public.ppm_ops_invoices for all to authenticated
  using(exists(select 1 from public.ppm_ops_sites s where s.id = site_id and public.ppm_ops_access(s.operation_id)))
  with check(exists(select 1 from public.ppm_ops_sites s where s.id = site_id and public.ppm_ops_access(s.operation_id)));
