-- Bilingual and administrable scientific research, innovation and strategic consulting page.
insert into public.site_pages(page_key,title,eyebrow,description,sections,cta_label,cta_url,title_en,eyebrow_en,description_en,sections_en,cta_label_en)
values(
 'recherche-innovation','Transformer les données en décisions, les idées en impact','Recherche · Innovation · Conseil','Nous accompagnons partout dans le monde les institutions, organisations, entreprises et chercheurs, de la conception à la mesure de l impact.',
 '[{"title":"Recherche scientifique","text":"Des protocoles rigoureux et des résultats exploitables.","items":["Études quantitatives, qualitatives et mixtes","Enquêtes et recherche opérationnelle"]},{"title":"Innovation","text":"Solutions numériques et méthodologiques adaptées.","items":["Santé numérique","Analyse de données, SIG et intelligence artificielle"]},{"title":"Conseil stratégique","text":"Accompagnement de bout en bout aligné sur les standards internationaux.","items":["Conception de projets","Suivi-évaluation et capitalisation","Renforcement des capacités"]}]'::jsonb,
 'Parler de votre projet','/contact','Turn data into decisions and ideas into impact','Research · Innovation · Consulting','We support institutions, organizations, companies and researchers worldwide, from design through impact measurement.',
 '[{"title":"Scientific research","text":"Rigorous protocols and actionable findings.","items":["Quantitative, qualitative and mixed-method studies","Surveys and operational research"]},{"title":"Innovation","text":"Digital and methodological solutions tailored to each context.","items":["Digital health","Data analysis, GIS and artificial intelligence"]},{"title":"Strategic consulting","text":"End-to-end support aligned with international standards.","items":["Project design","Monitoring, evaluation and learning","Capacity strengthening"]}]'::jsonb,
 'Discuss your project'
)
on conflict(page_key) do update set title=excluded.title,eyebrow=excluded.eyebrow,description=excluded.description,sections=excluded.sections,cta_label=excluded.cta_label,cta_url=excluded.cta_url,title_en=excluded.title_en,eyebrow_en=excluded.eyebrow_en,description_en=excluded.description_en,sections_en=excluded.sections_en,cta_label_en=excluded.cta_label_en;
