import Link from "next/link";
import { AcademicCapIcon, ArrowRightIcon, BeakerIcon, BuildingOffice2Icon, ChartBarSquareIcon, ClipboardDocumentListIcon, HeartIcon, PresentationChartLineIcon, ShoppingBagIcon, UserGroupIcon, VideoCameraIcon } from "@heroicons/react/24/outline";
import { getCurrentLocale } from "@/lib/i18n-server";
import { localizedPath } from "@/lib/i18n";
import { serviceEntryUrl } from "@/lib/service-entry";
const categories=[
 {titleFr:"Consultations diététiques et nutritionnelles",titleEn:"Dietetic and nutrition consultations",descriptionFr:"Des consultations en présentiel ou en ligne, avec bilan, orientation et suivi professionnel adaptés à votre situation.",descriptionEn:"In-person or online consultations with assessment, guidance and professional follow-up tailored to your situation.",icon:VideoCameraIcon,items:[{fr:"Découvrir les consultations",en:"Discover consultations",href:"/teleconseils",icon:VideoCameraIcon}]},
 {titleFr:"Suivi Santé Autonome",titleEn:"Autonomous Health Monitoring",descriptionFr:"Suivez vos indicateurs de santé et la croissance de vos enfants dans des espaces privés, avec tendances, analyses et rapports.",descriptionEn:"Monitor your health indicators and your children's growth in private spaces with trends, analyses and reports.",icon:ChartBarSquareIcon,items:[{fr:"Suivi santé autonome",en:"Autonomous health monitoring",href:serviceEntryUrl("health","client"),icon:HeartIcon},{fr:"Suivi de la croissance de l'enfant",en:"Child growth monitoring",href:serviceEntryUrl("child_growth","client"),icon:UserGroupIcon}]},
 {titleFr:"Applications de support",titleEn:"Support applications",descriptionFr:"Des outils métiers pour les programmes, institutions et équipes opérationnelles.",descriptionEn:"Professional tools for programmes, institutions and operational teams.",icon:BuildingOffice2Icon,items:[{fr:"Prise en charge de la malnutrition aiguë (NutriTrack)",en:"Acute malnutrition care (NutriTrack)",href:serviceEntryUrl("nutritrack"),icon:HeartIcon},{fr:"Gestion des projets, programmes et portefeuilles",en:"Project, programme and portfolio management",href:serviceEntryUrl("project_management"),icon:PresentationChartLineIcon},{fr:"Enquêtes de sécurité alimentaire et nutrition",en:"Food security and nutrition surveys",href:serviceEntryUrl("survey"),icon:ClipboardDocumentListIcon}]},
 {titleFr:"Formations certifiantes",titleEn:"Certified training",descriptionFr:"Des parcours pratiques, évalués et certifiants conçus par des experts.",descriptionEn:"Practical, assessed certification pathways designed by experts.",icon:AcademicCapIcon,items:[{fr:"Découvrir NutVitaGlobalis Academy",en:"Discover NutVitaGlobalis Academy",href:"/formations",icon:AcademicCapIcon}]},
 {titleFr:"Service de restauration",titleEn:"Catering service",descriptionFr:"Menus du jour, commande par ville, livraison et réseau de restauration NutVitaGlobalis.",descriptionEn:"Daily menus, city-based ordering, delivery and the NutVitaGlobalis catering network.",icon:ShoppingBagIcon,items:[{fr:"Voir les menus et commander",en:"Browse menus and order",href:"/restauration",icon:ShoppingBagIcon}]},
 {titleFr:"Recherche scientifique, innovation et conseil stratégique",titleEn:"Scientific Research, Innovation & Strategic Consulting",descriptionFr:"Une expertise mondiale couvrant recherche, données, intelligence artificielle, conseil et mise en œuvre.",descriptionEn:"Global expertise spanning research, data, artificial intelligence, consulting and implementation.",icon:BeakerIcon,items:[{fr:"Découvrir la solution",en:"Discover the solution",href:"/recherche-innovation",icon:BeakerIcon}]},
] as const;
export const metadata={title:"Nos services"};
export default async function ServicesPage(){const locale=await getCurrentLocale(),en=locale==="en";return <main><section className="bg-forest py-16 text-white"><div className="container-site"><p className="text-sm font-black uppercase tracking-widest text-orange">NutVitaGlobalis</p><h1 className="mt-4 text-5xl font-black text-white">{en?"Six complementary service areas":"Six catégories de services complémentaires"}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{en?"Consultations, autonomous monitoring, operational applications, certified learning, healthy catering and strategic expertise in one ecosystem.":"Consultations, suivi autonome, applications métiers, formations certifiantes, restauration saine et expertise stratégique réunis dans un même écosystème."}</p></div></section><section className="section"><div className="container-site grid gap-7 lg:grid-cols-2">{categories.map(category=>{const CategoryIcon=category.icon;return <article key={category.titleFr} className="card p-7 md:p-9"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-mint text-leaf"><CategoryIcon className="h-7"/></span><h2 className="mt-5 text-3xl font-black">{en?category.titleEn:category.titleFr}</h2><p className="mt-3 leading-7 text-slate-600">{en?category.descriptionEn:category.descriptionFr}</p><div className="mt-6 grid gap-3">{category.items.map(item=>{const Icon=item.icon;return <Link key={item.fr} href={localizedPath(locale,item.href)} className="group flex items-center gap-4 rounded-2xl border p-4 font-black text-forest transition hover:border-leaf hover:bg-mint"><Icon className="h-6 shrink-0 text-leaf"/><span className="flex-1">{en?item.en:item.fr}</span><ArrowRightIcon className="h-5 transition group-hover:translate-x-1"/></Link>})}</div></article>})}</div></section></main>}
