import Link from "next/link";
import { AcademicCapIcon, ArrowRightIcon, BeakerIcon, BuildingOffice2Icon, ChartBarSquareIcon, ClipboardDocumentListIcon, HeartIcon, PresentationChartLineIcon, ShoppingBagIcon, UserGroupIcon, VideoCameraIcon } from "@heroicons/react/24/outline";
import { getCurrentLocale } from "@/lib/i18n-server";
import { localizedPath } from "@/lib/i18n";
import { serviceEntryUrl } from "@/lib/service-entry";

const categories = [
  {titleFr:"Suivi santé",titleEn:"Health services",descriptionFr:"Un parcours coordonné qui réunit consultations, suivi autonome et croissance de l’enfant.",descriptionEn:"A coordinated pathway combining consultations, autonomous monitoring and child growth.",icon:HeartIcon,items:[
    {fr:"Consultations diététiques/nutritionnelles, en présentiel ou en ligne",en:"Dietetic/nutrition consultations, in person or online",href:serviceEntryUrl("teleconsultation","client"),icon:VideoCameraIcon},
    {fr:"Suivi santé autonome",en:"Autonomous health monitoring",href:serviceEntryUrl("health","client"),icon:ChartBarSquareIcon},
    {fr:"Suivi de la croissance de l’enfant",en:"Child growth monitoring",href:serviceEntryUrl("child_growth","client"),icon:UserGroupIcon},
  ]},
  {titleFr:"Applications de support",titleEn:"Support applications",descriptionFr:"Des outils métiers pour les programmes, institutions et équipes opérationnelles.",descriptionEn:"Professional tools for programmes, institutions and operational teams.",icon:BuildingOffice2Icon,items:[
    {fr:"Prise en charge de la malnutrition aiguë (NutriTrack)",en:"Acute malnutrition care (NutriTrack)",href:serviceEntryUrl("nutritrack"),icon:HeartIcon},
    {fr:"Gestion des projets, programmes et portefeuilles",en:"Project, programme and portfolio management",href:serviceEntryUrl("project_management"),icon:PresentationChartLineIcon},
    {fr:"Enquêtes de sécurité alimentaire et nutrition",en:"Food security and nutrition surveys",href:serviceEntryUrl("survey"),icon:ClipboardDocumentListIcon},
  ]},
  {titleFr:"Formations certifiantes",titleEn:"Certified training",descriptionFr:"Des parcours pratiques, évalués et certifiants conçus par des experts.",descriptionEn:"Practical, assessed certification pathways designed by experts.",icon:AcademicCapIcon,items:[{fr:"Découvrir NutVitaGlobalis Academy",en:"Discover NutVitaGlobalis Academy",href:serviceEntryUrl("academy","student"),icon:AcademicCapIcon}]},
  {titleFr:"Service de restauration",titleEn:"Catering service",descriptionFr:"Menus du jour, commande par ville, livraison et réseau de restauration NutVitaGlobalis.",descriptionEn:"Daily menus, city-based ordering, delivery and the NutVitaGlobalis catering network.",icon:ShoppingBagIcon,items:[{fr:"Voir les menus et commander",en:"Browse menus and order",href:"/restauration",icon:ShoppingBagIcon}]},
  {titleFr:"Recherche scientifique, innovation et expertise technique",titleEn:"Scientific Research, Innovation & Technical Expertise",descriptionFr:"Nous accompagnons les institutions, ONG, entreprises et particuliers dans la recherche scientifique, la conception, la mise en \u0153uvre et le suivi-\u00e9valuation de projets en sant\u00e9 publique, nutrition et s\u00e9curit\u00e9 alimentaire.",descriptionEn:"We support institutions, NGOs, businesses and individuals in scientific research and in the design, implementation, monitoring and evaluation of public health, nutrition and food security projects.",icon:BeakerIcon,items:[{fr:"Nous contacter",en:"Contact us",href:"/contact",icon:BeakerIcon}]},
] as const;

export const metadata={title:"Nos services"};
export default async function ServicesPage(){const locale=await getCurrentLocale(),en=locale==="en";return <main><section className="bg-forest py-16 text-white"><div className="container-site"><p className="text-sm font-black uppercase tracking-widest text-orange">NutVitaGlobalis</p><h1 className="mt-4 text-5xl font-black text-white">{en?"Five areas of expertise":"Cinq cat\u00e9gories de services"}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{en?"Health, operational applications, certified learning, healthy catering and scientific expertise in one ecosystem.":"Le suivi sant\u00e9, les applications m\u00e9tiers, les formations certifiantes, la restauration saine et l\u2019expertise scientifique r\u00e9unis dans un m\u00eame \u00e9cosyst\u00e8me."}</p></div></section><section className="section"><div className="container-site grid gap-7 lg:grid-cols-2">{categories.map(category=>{const CategoryIcon=category.icon;return <article key={category.titleFr} className="card p-7 md:p-9"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-mint text-leaf"><CategoryIcon className="h-7"/></span><h2 className="mt-5 text-3xl font-black">{en?category.titleEn:category.titleFr}</h2><p className="mt-3 leading-7 text-slate-600">{en?category.descriptionEn:category.descriptionFr}</p><div className="mt-6 grid gap-3">{category.items.map(item=>{const Icon=item.icon;return <Link key={item.fr} href={localizedPath(locale,item.href)} className="group flex items-center gap-4 rounded-2xl border p-4 font-black text-forest transition hover:border-leaf hover:bg-mint"><Icon className="h-6 shrink-0 text-leaf"/><span className="flex-1">{en?item.en:item.fr}</span><ArrowRightIcon className="h-5 transition group-hover:translate-x-1"/></Link>})}</div></article>})}</div></section></main>}
