import Link from "next/link";
import {
  AcademicCapIcon, ArrowRightIcon, BuildingOffice2Icon, ChartBarSquareIcon,
  ClipboardDocumentListIcon, HeartIcon, PresentationChartLineIcon, VideoCameraIcon,
} from "@heroicons/react/24/outline";
import { getCurrentLocale } from "@/lib/i18n-server";
import { localizedPath } from "@/lib/i18n";

const services = [
  {
    titleFr: "Application de Suivi sante personnalise Pour enfants (suivi de la croissance) et adultes.", titleEn: "Personalized health monitoring application for children (growth monitoring) and adults.", href: "/suivi-sante", icon: HeartIcon, tone: "bg-emerald-50 text-emerald-700",
    fr: "Prenez une part active dans la gestion de votre santÃ© nutritionnelle grÃ¢ce Ã  un espace personnel conÃ§u pour suivre vos paramÃ¨tres dans le temps. Enregistrez vos mesures anthropomÃ©triques, biologiques, alimentaires et liÃ©es au mode de vie, visualisez leurs tendances et obtenez des analyses structurÃ©es. Les rapports PDF rÃ©unissent les indicateurs, graphiques et points de vigilance pour faciliter les Ã©changes avec votre professionnel de santÃ©. La formule Premium permet, avec votre consentement, de partager le dossier avec le nutritionniste qui vous accompagne afin de construire un suivi continu, documentÃ© et vÃ©ritablement personnalisÃ©.",
    en: "Take an active role in managing your nutritional health through a personal space designed to monitor your indicators over time. Record anthropometric, biological, dietary and lifestyle measurements, review trends and receive structured analyses. PDF reports bring together indicators, charts and points requiring attention, making discussions with your health professional easier. With your consent, the Premium plan allows your complete record to be shared with the nutrition professional supporting you, creating continuous, documented and genuinely personalized care while keeping you in control of how your information is used.",
  },
  {
    titleFr: "Suivi de la croissance de lâ€™enfant", titleEn: "Child Growth Monitoring", href: "/connexion?redirect=/espace-client/croissance-enfant", icon: ChartBarSquareIcon, tone: "bg-sky-50 text-sky-700",
    fr: "Suivez la croissance et le bien-Ãªtre nutritionnel de chaque enfant dans un dossier clair, Ã©volutif et sÃ©curisÃ©. Le service calcule les indicateurs selon les normes de croissance de lâ€™OMS, prÃ©sente les courbes avec leurs Ã©carts-types et met en Ã©vidence les situations nÃ©cessitant une attention particuliÃ¨re. Il intÃ¨gre les mesures anthropomÃ©triques, lâ€™Ã©valuation de lâ€™alimentation, la diversitÃ© alimentaire minimale, le rÃ©gime minimum acceptable et le statut vaccinal selon lâ€™Ã¢ge. Les parents peuvent conserver lâ€™historique, consulter le profil de lâ€™enfant et produire des rapports illustrÃ©s afin de mieux prÃ©parer les consultations et agir plus tÃ´t.",
    en: "Monitor each childâ€™s growth and nutritional well-being in a clear, evolving and secure record. The service calculates indicators according to WHO Child Growth Standards, displays growth curves with standard-deviation lines and highlights situations requiring attention. It combines anthropometric measurements, feeding assessment, minimum dietary diversity, minimum acceptable diet and age-appropriate vaccination review. Parents can maintain a complete history, access the childâ€™s profile and generate illustrated reports to prepare consultations more effectively. By turning measurements into understandable trends, the platform helps families and professionals identify concerns earlier and support healthier development.",
  },
  {
    titleFr: "Formations certifiantes", titleEn: "Certified Training", href: "/formations", icon: AcademicCapIcon, tone: "bg-violet-50 text-violet-700",
    fr: "DÃ©veloppez des compÃ©tences immÃ©diatement mobilisables en nutrition, diÃ©tÃ©tique, santÃ© publique et gestion des programmes grÃ¢ce Ã  des parcours structurÃ©s par des experts. Les formations associent connaissances scientifiques, situations pratiques, outils professionnels et Ã©valuations progressives pour rÃ©pondre aux rÃ©alitÃ©s du terrain. Elles sâ€™adressent aux professionnels, Ã©tudiants, organisations et personnes souhaitant renforcer leurs capacitÃ©s. Chaque parcours met lâ€™accent sur la qualitÃ© des pratiques, lâ€™interprÃ©tation des donnÃ©es et la prise de dÃ©cision responsable. Les attestations et certificats valorisent les acquis tout en encourageant une amÃ©lioration continue au service des populations et des institutions.",
    en: "Build immediately applicable skills in nutrition, dietetics, public health and programme management through learning paths structured by experts. Courses combine scientific knowledge, practical situations, professional tools and progressive assessments that reflect real operational challenges. They are designed for professionals, students, organizations and anyone seeking to strengthen their capabilities. Each pathway emphasizes quality practice, sound data interpretation and responsible decision-making. Certificates recognize achievement while encouraging continuous improvement. NutVitaGlobalis training helps learners move beyond theory and develop the confidence, methods and practical resources required to create meaningful impact within communities and institutions.",
  },
  {
    titleFr: "TÃ©lÃ©conseils et packs", titleEn: "Nutrition Consultations and Care Packs", href: "/teleconseils", icon: VideoCameraIcon, tone: "bg-orange/10 text-orange",
    fr: "BÃ©nÃ©ficiez dâ€™un accompagnement nutritionnel Ã  distance organisÃ© autour de vos besoins rÃ©els. Les packs diabÃ¨te, perte de poids, grossesse et nutrition infantile combinent consultations, objectifs personnalisÃ©s, plan de prise en charge, suivi des paramÃ¨tres et rendez-vous programmÃ©s. Le nutritionniste documente les plaintes, les habitudes alimentaires, lâ€™activitÃ© physique, le mode de vie et les rÃ©sultats disponibles avant de proposer des actions mesurables. Les ordonnances et comptes rendus sont gÃ©nÃ©rÃ©s en PDF et restent accessibles aux parties autorisÃ©es. Cette continuitÃ© transforme une consultation isolÃ©e en parcours professionnel, coordonnÃ© et adaptÃ© Ã  votre quotidien.",
    en: "Receive remote nutrition support organized around your real needs. Diabetes, weight management, pregnancy and infant nutrition packs combine consultations, personalized objectives, a care plan, indicator monitoring and scheduled follow-up appointments. The nutrition professional documents concerns, dietary habits, physical activity, lifestyle and available results before recommending measurable actions. Prescriptions and consultation records are generated as PDFs and remain accessible to authorized participants. This continuity turns an isolated consultation into a professional, coordinated journey adapted to daily life, helping clients understand priorities, track progress and remain actively involved in decisions concerning their health.",
  },
  {
    titleFr: "Application de support a la prise en charge de la malnutrition aigue (Nutritrack)", titleEn: "Acute malnutrition care support application (Nutritrack)", href: "/acces-nutritrack", icon: BuildingOffice2Icon, tone: "bg-cyan-50 text-cyan-700",
    fr: "NutriTrack soutient les formations sanitaires et les programmes communautaires dans la prise en charge intÃ©grÃ©e de la malnutrition aiguÃ«. Lâ€™application centralise les admissions, diagnostics, visites, rÃ©fÃ©rences, stocks nutritionnels, activitÃ©s communautaires, supervisions et rapports. Les Ã©quipes disposent dâ€™une vision partagÃ©e des enfants suivis, des cas nÃ©cessitant une attention particuliÃ¨re et de la disponibilitÃ© des intrants. Les donnÃ©es sont organisÃ©es par structure et par rÃ´le afin de renforcer la coordination, la traÃ§abilitÃ© et la redevabilitÃ©. NutriTrack aide ainsi les responsables Ã  sÃ©curiser les parcours de soins et Ã  piloter les interventions avec des informations actualisÃ©es.",
    en: "NutriTrack supports health facilities and community programmes in the integrated management of acute malnutrition. The application centralizes admissions, diagnoses, visits, referrals, nutrition supplies, community activities, supervision and reporting. Teams gain a shared view of children receiving care, cases requiring special attention and the availability of essential commodities. Data is organized by organization and user role to strengthen coordination, traceability and accountability. NutriTrack helps programme managers protect continuity of care, identify operational gaps and guide interventions using up-to-date information, while giving frontline teams practical tools for their daily work.",
  },
  {
    titleFr: "Application de Support aux enquetes de securite alimentaire et nutrition.", titleEn: "Food security and nutrition survey support application.", href: "/surveys", icon: ClipboardDocumentListIcon, tone: "bg-lime-50 text-lime-800",
    fr: "Concevez et conduisez vos enquÃªtes de sÃ©curitÃ© alimentaire et nutrition dans un environnement professionnel unifiÃ©. Le service couvre la planification, lâ€™Ã©chantillonnage, la conception de questionnaires, le dÃ©ploiement ODK, la collecte, le contrÃ´le qualitÃ©, lâ€™analyse anthropomÃ©trique et les modules avancÃ©s. Les outils calculent les indicateurs dÃ©rivÃ©s, documentent les anomalies et expliquent clairement les causes lorsquâ€™un test statistique ne peut pas aboutir. Les rapports de plausibilitÃ© et rapports finaux intÃ¨grent tableaux, graphiques, filtres et Ã©lÃ©ments mÃ©thodologiques. Vous conservez ainsi une chaÃ®ne cohÃ©rente, depuis le questionnaire jusquâ€™Ã  la restitution dÃ©cisionnelle.",
    en: "Design and conduct food security and nutrition surveys in one professional environment. The service covers planning, sampling, questionnaire design, ODK deployment, data collection, quality control, anthropometric analysis and advanced analytical modules. Tools calculate derived indicators, document anomalies and clearly explain why a statistical test cannot be completed. Plausibility and final reports combine tables, charts, filters and methodological information to support transparent interpretation. This creates a coherent workflow from questionnaire development to decision-ready reporting, reducing fragmented tools and helping survey teams preserve data quality, analytical consistency and a clear audit trail.",
  },
  {
    titleFr: "Application de support a la gestion des projets, programmes et portefeuilles", titleEn: "Project, programme and portfolio management support application", href: "/op-management", icon: PresentationChartLineIcon, tone: "bg-blue-50 text-blue-700",
    fr: "Pilotez portefeuilles, programmes, projets et financements depuis un espace concu pour les initiatives complexes et multi-acteurs. Le service structure l'organisation, les bureaux, sites, staffs, partenaires, documents strategiques, portefeuilles, programmes, projets, parties prenantes, plans integres, risques, procurement, qualite, ressources, budgets et indicateurs. Les equipes peuvent relier chaque activite aux objectifs, suivre les plans mensuels, documenter les realisations, depenses, recommandations et preuves, puis produire des rapports de progression par periode. L'objectif est de transformer les informations dispersees en une vision exploitable de l'execution, des ecarts, des arbitrages et des decisions.",
    en: "Manage portfolios, programmes, projects and funding from a workspace designed for complex, multi-stakeholder initiatives. The service structures organization records, offices, sites, staff, partners, strategic documents, portfolios, programmes, projects, stakeholders, integrated plans, risks, procurement, quality, resources, budgets and indicators. Teams can link each activity to objectives, track monthly plans, document achievements, expenditure, recommendations and evidence, then produce period-based progress reports. Its purpose is to turn fragmented operational information into an actionable view of implementation, variances, trade-offs and decisions while preserving the relationships between strategy, plans, resources and field delivery.",
  },
] as const;

export const metadata = { title: "Nos services" };

export default async function ServicesPage() {
  const locale = await getCurrentLocale();
  const english = locale === "en";
  return <main>
    <section className="bg-forest py-16 text-white"><div className="container-site"><p className="text-sm font-black uppercase tracking-widest text-orange">NutVitaGlobalis</p><h1 className="mt-4 text-5xl font-black text-white">{english ? "Our Services" : "Nos services"}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{english ? "Health, learning, data and operational solutions designed for individuals, professionals and organizations." : "Des solutions de santÃ©, de formation, de donnÃ©es et de gestion opÃ©rationnelle conÃ§ues pour les individus, les professionnels et les organisations."}</p></div></section>
    <section className="section"><div className="container-site"><div className="grid gap-6 lg:grid-cols-2">{services.map((service) => { const Icon = service.icon; return <article key={service.titleFr} className="card flex flex-col p-7 md:p-9"><span className={`grid h-12 w-12 place-items-center rounded-lg ${service.tone}`}><Icon className="h-6" /></span><h2 className="mt-5 text-2xl font-black">{english ? service.titleEn : service.titleFr}</h2><p className="mt-4 flex-1 leading-7 text-slate-600">{english ? service.en : service.fr}</p><Link href={localizedPath(locale, service.href)} className="btn-secondary mt-7 justify-between">{english ? "Open service" : "AccÃ©der au service"}<ArrowRightIcon className="ml-3 h-5" /></Link></article>; })}</div></div></section>
  </main>;
}
