"use client";
import { useMemo, useState } from "react";
import Image from "next/image";

type Menu={id:string;name_fr:string;name_en?:string;description_fr:string;description_en?:string;image_url?:string;city:string;available_date:string;base_price?:number;currency:string};
type Order={id:string;order_number:string;status:string;city:string;delivery_address:string;preferred_delivery_at?:string;total_amount?:number;currency:string;quote_note?:string;catering_order_items?:Array<{id:string;menu_name:string;quantity:number}>};
const statusLabel:Record<string,[string,string]>={
  awaiting_review:["En attente de validation","Awaiting review"],quoted:["Devis à confirmer","Quote to confirm"],customer_confirmed:["Commande confirmée","Order confirmed"],awaiting_delivery:["En attente de livraison","Awaiting delivery"],out_for_delivery:["En cours de livraison","Out for delivery"],delivered:["Livrée","Delivered"],cancelled:["Annulée","Cancelled"],rejected:["Refusée","Rejected"],
};

export default function CateringOrderCenter({locale,menus,orders:initial,profile}:{locale:"fr"|"en";menus:Menu[];orders:Order[];profile:{name:string;phone:string;city:string}}){
  const en=locale==="en",[orders,setOrders]=useState(initial),[city,setCity]=useState(profile.city||""),[quantities,setQuantities]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const cities=[...new Set(menus.map(m=>m.city))].sort(),visible=useMemo(()=>menus.filter(m=>!city||m.city===city),[menus,city]);
  async function submit(form:FormData){setBusy(true);setMessage("");const items=Object.entries(quantities).filter(([,quantity])=>quantity>0).map(([menu_id,quantity])=>({menu_id,quantity}));const payload={city,items,contact_name:String(form.get("contact_name")||""),contact_phone:String(form.get("contact_phone")||""),delivery_address:String(form.get("delivery_address")||""),delivery_details:String(form.get("delivery_details")||""),preferred_delivery_at:String(form.get("preferred_delivery_at")||"")};const response=await fetch("/api/restauration/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await response.json();setBusy(false);if(!response.ok)return setMessage(json.message||"Erreur");setOrders(current=>[json.order,...current]);setQuantities({});setMessage(en?"Order submitted for review.":"Commande transmise pour validation.");}
  async function confirm(id:string){setBusy(true);const response=await fetch("/api/restauration/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"confirm"})});const json=await response.json();setBusy(false);if(!response.ok)return setMessage(json.message||"Erreur");setOrders(current=>current.map(order=>order.id===id?json.order:order));}
  return <div className="grid gap-8"><section><p className="text-xs font-black uppercase tracking-widest text-orange">{en?"Catering":"Restauration"}</p><h1 className="mt-2 text-4xl font-black">{en?"Order a meal":"Commander un repas"}</h1><p className="mt-3 text-slate-600">{en?"Select your city first. Only menus deliverable there will appear.":"Sélectionnez d’abord votre ville. Seuls les menus qui peuvent y être livrés apparaîtront."}</p></section>
    <section className="rounded-3xl border bg-white p-6"><label className="grid gap-2 font-black">{en?"Delivery city":"Ville de livraison"}<select className="input" value={city} onChange={event=>setCity(event.target.value)}><option value="">{en?"Select a city":"Choisir une ville"}</option>{cities.map(value=><option key={value}>{value}</option>)}</select></label>
      {city&&<div className="mt-6 grid gap-5 md:grid-cols-2">{visible.map(menu=><article key={menu.id} className="overflow-hidden rounded-2xl border"><div className="relative h-44 bg-mint">{menu.image_url?<Image src={menu.image_url} alt={en?menu.name_en||menu.name_fr:menu.name_fr} fill className="object-cover"/>:<div className="grid h-full place-items-center text-5xl">🍽️</div>}</div><div className="p-5"><h3 className="text-xl font-black">{en?menu.name_en||menu.name_fr:menu.name_fr}</h3><p className="mt-2 text-sm text-slate-500">{en?menu.description_en||menu.description_fr:menu.description_fr}</p><label className="mt-4 flex items-center justify-between font-bold">{en?"Quantity":"Quantité"}<input className="input w-24" type="number" min="0" value={quantities[menu.id]||0} onChange={event=>setQuantities(current=>({...current,[menu.id]:Math.max(0,Number(event.target.value))}))}/></label></div></article>)}</div>}
    </section>
    {city&&<form action={submit} className="grid gap-5 rounded-3xl border bg-white p-6 md:grid-cols-2"><h2 className="text-2xl font-black md:col-span-2">{en?"Delivery details":"Informations de livraison"}</h2><label className="grid gap-2 font-bold">{en?"Name":"Nom"}<input name="contact_name" defaultValue={profile.name} required className="input"/></label><label className="grid gap-2 font-bold">{en?"Phone":"Téléphone"}<input name="contact_phone" defaultValue={profile.phone} required className="input"/></label><label className="grid gap-2 font-bold md:col-span-2">{en?"Precise delivery address":"Adresse précise de livraison"}<input name="delivery_address" required className="input"/></label><label className="grid gap-2 font-bold">{en?"Preferred delivery time":"Heure souhaitée"}<input name="preferred_delivery_at" type="datetime-local" className="input"/></label><label className="grid gap-2 font-bold">{en?"Additional directions":"Précisions supplémentaires"}<input name="delivery_details" className="input"/></label><button disabled={busy||!Object.values(quantities).some(q=>q>0)} className="btn-primary md:col-span-2">{busy?"…":en?"Submit for quotation":"Soumettre pour devis"}</button></form>}
    {message&&<p className="rounded-2xl bg-mint p-4 font-bold text-forest">{message}</p>}
    <section><h2 className="text-2xl font-black">{en?"My orders":"Mes commandes"}</h2><div className="mt-5 grid gap-4">{orders.map(order=><article key={order.id} className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black text-orange">{order.order_number}</p><h3 className="mt-1 text-xl font-black">{(statusLabel[order.status]||[order.status,order.status])[en?1:0]}</h3></div>{order.total_amount!=null&&<p className="text-2xl font-black text-forest">{Number(order.total_amount).toLocaleString(en?"en-US":"fr-FR")} {order.currency}</p>}</div><p className="mt-3 text-sm text-slate-600">{order.catering_order_items?.map(item=>`${item.quantity} × ${item.menu_name}`).join(" · ")}</p>{order.quote_note&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{order.quote_note}</p>}{order.status==="quoted"&&<button disabled={busy} onClick={()=>confirm(order.id)} className="btn-primary mt-5">{en?"Confirm this order":"Confirmer cette commande"}</button>}</article>)}</div></section>
  </div>;
}
