"use client";
import type {ReactNode} from "react";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {ArrowRightStartOnRectangleIcon,BeakerIcon,BellAlertIcon,ChartBarIcon,ChatBubbleLeftRightIcon,ClipboardDocumentCheckIcon,ClipboardDocumentListIcon,CreditCardIcon,DocumentCheckIcon,HomeIcon,KeyIcon,LockClosedIcon,QrCodeIcon,ShieldCheckIcon,SparklesIcon,UserCircleIcon,UserGroupIcon,VideoCameraIcon} from "@heroicons/react/24/outline";
import MedicalDisclaimer from "@/components/MedicalDisclaimer";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import HelpBox from "@/components/shared/HelpBox";
import type {ClientEntitlements} from "@/lib/client";
import {createClient} from "@/lib/supabase/client";
type LinkItem=readonly[string,string,typeof HomeIcon,boolean];
export default function ClientShellClient({children,email,access,activeService,english=false}:{children:ReactNode;email:string;access:ClientEntitlements;activeService:string;english?:boolean}){
  const router=useRouter(),path=usePathname(),t=(fr:string,en:string)=>english?en:fr;
  const common:LinkItem[]=[["/espace-client",t("Tableau de bord","Dashboard"),HomeIcon,true],["/espace-client/abonnement",t("Mes abonnements","My subscriptions"),CreditCardIcon,true],["/espace-client/profil",t("Mon profil","My profile"),UserCircleIcon,true],["/espace-client/carte",t("Ma carte d’accès","My access card"),QrCodeIcon,true],["/espace-client/securite",t("Mot de passe","Password"),KeyIcon,true],["/espace-client/confidentialite",t("Confidentialité","Privacy"),ShieldCheckIcon,true],["/espace-client/ressources-premium",t("Ressources Premium","Premium resources"),LockClosedIcon,access.premiumResources]];
  const premiumTools:LinkItem[]=[["/espace-client/nutvita-ia","NutVita IA",SparklesIcon,access.health],["/espace-client/dossier",t("Mes paramètres de santé","My health measurements"),ClipboardDocumentListIcon,access.health],["/espace-client/tendances",t("Tendances","Trends"),ChartBarIcon,access.health],["/espace-client/analyse",t("Analyses et rapports","Analyses and reports"),SparklesIcon,access.health],["/espace-client/objectifs",t("Mes objectifs","My goals"),ClipboardDocumentCheckIcon,access.health],["/espace-client/consentements-sante",t("Consentements","Consents"),ShieldCheckIcon,access.health],["/espace-client/ordonnances",t("Ordonnances","Prescriptions"),DocumentCheckIcon,access.health],["/espace-client/resultats-laboratoire",t("Résultats de laboratoire","Laboratory results"),BeakerIcon,access.health]];
  const health:LinkItem[]=[["/espace-client",t("Tableau de bord","Dashboard"),HomeIcon,true],...premiumTools];
  const childGrowth:LinkItem[]=[["/espace-client/croissance-enfant",t("Croissance enfant","Child growth"),UserGroupIcon,access.childGrowth],["/espace-client/nutvita-ia","NutVita IA",SparklesIcon,true]];
  const careBase:LinkItem[]=[["/espace-client/messages",t("Messages","Messages"),ChatBubbleLeftRightIcon,true],["/espace-client/appels",t("Appels vidéo","Video calls"),VideoCameraIcon,true],["/espace-client/documents",t("Mes documents","My documents"),DocumentCheckIcon,true],["/espace-client/journal-alimentaire",t("Journal alimentaire","Food journal"),ClipboardDocumentListIcon,true],["/espace-client/symptomes",t("Suivi des symptômes","Symptom tracking"),ClipboardDocumentCheckIcon,true],["/espace-client/rappels",t("Rappels","Reminders"),BellAlertIcon,true],["/espace-client/historique",t("Historique complet","Complete history"),ClipboardDocumentListIcon,true]];
  const nutrition:LinkItem[]=[["/espace-client/consultations",t("Tableau de bord consultation","Consultation dashboard"),HomeIcon,access.teleconsultation],["/rendez-vous",t("Rendez-vous","Appointments"),ClipboardDocumentCheckIcon,access.teleconsultation],["/espace-client/menus",t("Plans alimentaires","Meal plans"),ClipboardDocumentListIcon,access.teleconsultation],...careBase,...premiumTools,["/espace-client/abonnement",t("Paiements et factures","Payments and invoices"),CreditCardIcon,true],["/espace-client/profil",t("Paramètres","Settings"),UserCircleIcon,true]];
  const medical:LinkItem[]=[["/espace-client/consultations-medicales",t("Tableau de bord médical","Medical dashboard"),HomeIcon,access.medicalConsultation],["/consultations-medicales/specialistes",t("Spécialistes et rendez-vous","Specialists and appointments"),UserGroupIcon,access.medicalConsultation],...careBase,...premiumTools,["/espace-client/abonnement",t("Paiements et factures","Payments and invoices"),CreditCardIcon,true],["/espace-client/profil",t("Paramètres","Settings"),UserCircleIcon,true]];
  const catering:LinkItem[]=[["/restauration/commander",t("Commander un repas","Order a meal"),CreditCardIcon,true]];
  const commonPaths=["/espace-client","/espace-client/abonnement","/espace-client/profil","/espace-client/carte","/espace-client/securite","/espace-client/confidentialite","/espace-client/ressources-premium"];
  const serviceLinks=commonPaths.includes(path)?common:activeService==="health"?health:activeService==="child_growth"?childGrowth:activeService==="teleconsultation"?nutrition:activeService==="medical_consultation"?medical:activeService==="catering"?catering:common;
  const healthMode=["health","child_growth","teleconsultation","medical_consultation"].includes(activeService);
  async function logout(){await createClient().auth.signOut();router.push("/connexion");router.refresh()}
  const brand=activeService==="health"?"Santé":activeService==="child_growth"?"Croissance":activeService==="teleconsultation"?"Consultations":activeService==="medical_consultation"?"Médical":activeService==="catering"?"Restauration":"Client";
  return <div className="min-h-screen bg-slate-100"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/espace-client" className="text-xl font-black text-forest">NutVita<span className="text-orange">{brand}</span></Link><div className="flex items-center gap-3"><Link href="/" className="rounded-xl border px-3 py-2 text-sm font-black text-forest hover:bg-mint">{t("Page principale","Main website")}</Link><LanguageSwitcher compact/><span className="hidden text-sm text-slate-500 sm:block">{email}</span><button onClick={logout} className="flex gap-2 text-sm font-bold"><ArrowRightStartOnRectangleIcon className="h-5"/>{t("Déconnexion","Sign out")}</button></div></div></header>{healthMode&&<MedicalDisclaimer/>}<div className="mx-auto grid max-w-7xl gap-7 px-5 py-8 lg:grid-cols-[290px_1fr]"><nav className="flex flex-col self-stretch rounded-3xl bg-forest p-4 text-white"><Link href="/espace-client" className="mb-3 flex gap-3 rounded-xl bg-white/10 px-4 py-3 font-bold hover:bg-white/15"><SparklesIcon className="h-5"/>{t("Changer de service","Change service")}</Link>{serviceLinks.filter(([, , ,visible])=>visible).filter((item,index,array)=>array.findIndex(x=>x[0]===item[0])===index).map(([href,label,Icon])=><Link key={href} href={href} className={`flex gap-3 rounded-xl px-4 py-3 font-bold ${path===href?"bg-white/15":"hover:bg-white/10"}`}><Icon className="h-5 shrink-0"/><span>{label}</span></Link>)}<div className="mt-auto pt-4"><HelpBox text={t("Notre équipe est là pour vous accompagner.","Our team is here to support you.")} label={t("Contactez-nous","Contact us")}/></div></nav><main className="min-w-0">{children}</main></div></div>
}
