"use client";
import Link from "next/link";
import {AcademicCapIcon,ArrowRightIcon,BuildingOfficeIcon,ChartBarSquareIcon,ChatBubbleLeftRightIcon,ClipboardDocumentListIcon,CreditCardIcon,HeartIcon,KeyIcon,MagnifyingGlassIcon,ShieldCheckIcon,ShoppingBagIcon,UserCircleIcon,UsersIcon} from "@heroicons/react/24/outline";
type Choice={service:string;role:string;roleLabel:string;href:string};
type Service={key:string;title:string;description:string;activation:"offer"|"authorization";icon:typeof HeartIcon};
const SERVICES:Service[]=[
  {key:"academy",title:"NutVitaGlobalis Academy",description:"Formations, évaluations, progression et certificats.",activation:"offer",icon:AcademicCapIcon},
  {key:"health",title:"Suivi santé personnalisé",description:"Paramètres, questionnaires, tendances, analyses et rapports.",activation:"offer",icon:HeartIcon},
  {key:"child_growth",title:"Suivi de la croissance des enfants",description:"Un dossier strictement séparé pour chaque enfant : mesures, courbes et analyses.",activation:"offer",icon:ChartBarSquareIcon},
  {key:"teleconsultation",title:"Consultations diététiques/nutritionnelles, en présentiel ou en ligne",description:"Consultations, messagerie et appels vidéo.",activation:"offer",icon:ChatBubbleLeftRightIcon},
  {key:"catering",title:"Service de restauration",description:"Menus du jour, commande par ville et livraison.",activation:"offer",icon:ShoppingBagIcon},
  {key:"nutritrack",title:"Prise en charge de la malnutrition aiguë (NutriTrack)",description:"Application destinée aux équipes et structures autorisées.",activation:"authorization",icon:HeartIcon},
  {key:"survey",title:"Enquêtes de sécurité alimentaire et nutrition",description:"Questionnaires, collecte, analyse et rapports d’enquête.",activation:"authorization",icon:MagnifyingGlassIcon},
  {key:"project_management",title:"Gestion de projets, programmes et portefeuilles",description:"Planification, suivi des activités, ressources et résultats.",activation:"authorization",icon:ClipboardDocumentListIcon},
  {key:"recruitment",title:"Candidatures",description:"Soumission et suivi d’un dossier de candidature.",activation:"authorization",icon:UsersIcon},
  {key:"maximus",title:"Maximus",description:"Gestion interne du cabinet réservée au personnel autorisé.",activation:"authorization",icon:BuildingOfficeIcon},
  {key:"administration",title:"Administration NutVitaGlobalis",description:"Configuration et contrôle transversal réservés aux administrateurs.",activation:"authorization",icon:ShieldCheckIcon},
];
export default function ClientServiceLanding({name,choices}:{name:string;choices:Choice[]}){
  function open(service:Service,access:Choice[]){if(service.key==="child_growth"&&!access.length){location.assign("/api/access/open?service=client&role=client&return=/espace-client/croissance-enfant");return}const params=new URLSearchParams({service:service.key});if(access.length===1)params.set("role",access[0].role);location.assign(`/api/access/open?${params.toString()}`)}
  return <div className="grid gap-8">
    <section className="overflow-hidden rounded-[2rem] bg-forest text-white shadow-soft"><div className="grid gap-8 p-7 md:grid-cols-[1.3fr_.7fr] md:p-10"><div><p className="text-xs font-black uppercase tracking-[.22em] text-orange">Mon espace NutVitaGlobalis</p><h1 className="mt-4 text-4xl font-black text-white">Bonjour {name}</h1><p className="mt-3 max-w-2xl leading-7 text-white/75">Voici toutes les applications NutVitaGlobalis. Votre niveau d’accès est indiqué sur chaque carte.</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-sm text-white/70">Vous souhaitez activer un service ?</p><Link href="/espace-client/services" className="mt-3 inline-flex items-center gap-2 font-black text-white">Découvrir les solutions <ArrowRightIcon className="h-4"/></Link></div></div></section>
    <section><h2 className="text-2xl font-black">Applications et niveaux d’accès</h2><p className="mt-1 text-sm text-slate-500">Les applications non accessibles restent visibles et indiquent comment obtenir un accès.</p><div className="mt-5 grid gap-5 md:grid-cols-2">{SERVICES.filter(service=>service.key!=="maximus"||choices.some(choice=>choice.service==="maximus")).map(service=>{const access=choices.filter(c=>c.service===service.key);return <button key={service.key} type="button" onClick={()=>open(service,access)} className="group rounded-3xl border bg-white p-6 text-left shadow-soft transition hover:-translate-y-1 hover:border-leaf"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-forest"><service.icon className="h-6"/></span><span className={`rounded-full px-3 py-1 text-xs font-black ${access.length?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{access.length?"Accessible":"Non accessible"}</span></div><h3 className="mt-5 text-xl font-black text-forest">{service.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{service.description}</p><div className="mt-4 flex flex-wrap gap-2">{access.length?access.map(c=><span key={c.role} className="rounded-full bg-mint px-3 py-1 text-xs font-black text-forest">Accès : {c.roleLabel}</span>):<span className="rounded-full bg-orange/10 px-3 py-1 text-xs font-black text-orange">{service.activation==="offer"?"À activer":"Sur autorisation"}</span>}</div><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-leaf">{access.length?"Ouvrir cet espace":service.activation==="offer"?"Voir les offres":"Demander l’accès"} <ArrowRightIcon className="h-4 transition group-hover:translate-x-1"/></span></button>})}</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Utility href="/espace-client/services" label="Acheter un service" icon={ShoppingBagIcon}/><Utility href="/espace-client/abonnement" label="Mes abonnements" icon={CreditCardIcon}/><Utility href="/espace-client/profil" label="Mon profil" icon={UserCircleIcon}/><Utility href="/espace-client/securite" label="Mot de passe" icon={KeyIcon}/></section>
  </div>
}
function Utility({href,label,icon:Icon}:{href:string;label:string;icon:typeof HeartIcon}){return <Link href={href} className="flex items-center gap-3 rounded-2xl border bg-white p-5 font-black text-forest transition hover:border-leaf hover:bg-mint"><Icon className="h-6"/>{label}</Link>}
