"use client";
import Link from "next/link";
import {AcademicCapIcon,ArrowRightIcon,BuildingOfficeIcon,ChartBarSquareIcon,ChatBubbleLeftRightIcon,ClipboardDocumentListIcon,CreditCardIcon,HeartIcon,KeyIcon,MagnifyingGlassIcon,ShieldCheckIcon,ShoppingBagIcon,UserCircleIcon,UsersIcon} from "@heroicons/react/24/outline";
type Choice={service:string;role:string;roleLabel:string;href:string};
type Service={key:string;title:string;titleEn:string;description:string;descriptionEn:string;activation:"offer"|"authorization";icon:typeof HeartIcon};
const SERVICES:Service[]=[
  {key:"academy",title:"NutVitaGlobalis Academy",titleEn:"NutVitaGlobalis Academy",description:"Formations, évaluations, progression et certificats.",descriptionEn:"Training, assessments, progress and certificates.",activation:"offer",icon:AcademicCapIcon},
  {key:"health",title:"Suivi santé autonome",titleEn:"Autonomous health monitoring",description:"Paramètres, questionnaires, tendances, analyses et rapports.",descriptionEn:"Measurements, questionnaires, trends, analyses and reports.",activation:"offer",icon:HeartIcon},
  {key:"child_growth",title:"Suivi de la croissance des enfants",titleEn:"Child growth monitoring",description:"Un dossier strictement séparé pour chaque enfant : mesures, courbes et analyses.",descriptionEn:"A strictly separated record for each child: measurements, charts and analyses.",activation:"offer",icon:ChartBarSquareIcon},
  {key:"teleconsultation",title:"Consultations diététiques et nutritionnelles",titleEn:"Dietetic and nutrition consultations",description:"Consultations, messagerie, appels vidéo et tous les outils du suivi santé Premium.",descriptionEn:"Consultations, messaging, video calls and every Premium health-monitoring tool.",activation:"offer",icon:ChatBubbleLeftRightIcon},
  {key:"medical_consultation",title:"Consultations médicales spécialisées",titleEn:"Specialist medical consultations",description:"Prise en charge médicale sécurisée avec tous les outils du suivi santé Premium.",descriptionEn:"Secure specialist medical care with every Premium health-monitoring tool.",activation:"offer",icon:HeartIcon},
  {key:"catering",title:"Service de restauration",titleEn:"Catering service",description:"Menus du jour, commande par ville et livraison.",descriptionEn:"Daily menus, city-based ordering and delivery.",activation:"offer",icon:ShoppingBagIcon},
  {key:"nutritrack",title:"Prise en charge de la malnutrition aiguë (NutriTrack)",titleEn:"Acute malnutrition care (NutriTrack)",description:"Application destinée aux équipes et structures autorisées.",descriptionEn:"Application for authorized teams and facilities.",activation:"authorization",icon:HeartIcon},
  {key:"survey",title:"Enquêtes de sécurité alimentaire et nutrition",titleEn:"Food security and nutrition surveys",description:"Questionnaires, collecte, analyse et rapports d’enquête.",descriptionEn:"Questionnaires, data collection, analysis and survey reports.",activation:"authorization",icon:MagnifyingGlassIcon},
  {key:"project_management",title:"Gestion de projets, programmes et portefeuilles",titleEn:"Project, programme and portfolio management",description:"Planification, suivi des activités, ressources et résultats.",descriptionEn:"Planning and monitoring of activities, resources and results.",activation:"authorization",icon:ClipboardDocumentListIcon},
  {key:"recruitment",title:"Candidatures",titleEn:"Applications",description:"Soumission et suivi d’un dossier de candidature.",descriptionEn:"Submit and track an application.",activation:"authorization",icon:UsersIcon},
  {key:"maximus",title:"Maximus",titleEn:"Maximus",description:"Gestion interne du cabinet réservée au personnel autorisé.",descriptionEn:"Internal management reserved for authorized staff.",activation:"authorization",icon:BuildingOfficeIcon},
  {key:"administration",title:"Administration NutVitaGlobalis",titleEn:"NutVitaGlobalis administration",description:"Configuration et contrôle transversal réservés aux administrateurs.",descriptionEn:"Cross-platform configuration and control reserved for administrators.",activation:"authorization",icon:ShieldCheckIcon},
];
export default function ClientServiceLanding({name,choices,english=false}:{name:string;email:string;choices:Choice[];english?:boolean}){
  const t=(fr:string,en:string)=>english?en:fr;
  const hasConsultation=choices.some(choice=>choice.role==="client"&&["teleconsultation","medical_consultation"].includes(choice.service));
  function open(service:Service,access:Choice[]){if(service.key==="child_growth"&&!access.length){location.assign("/api/access/open?service=client&role=client&return=/espace-client/croissance-enfant");return}const params=new URLSearchParams({service:service.key});if(access.length===1)params.set("role",access[0].role);location.assign(`/api/access/open?${params.toString()}`)}
  return <div className="grid gap-8">
    <section className="overflow-hidden rounded-[2rem] bg-forest text-white shadow-soft"><div className="grid gap-8 p-7 md:grid-cols-[1.3fr_.7fr] md:p-10"><div><p className="text-xs font-black uppercase tracking-[.22em] text-orange">{t("Mon espace NutVitaGlobalis","My NutVitaGlobalis space")}</p><h1 className="mt-4 text-4xl font-black text-white">{t("Bonjour","Hello")} {name}</h1><p className="mt-3 max-w-2xl leading-7 text-white/75">{t("Voici toutes les applications NutVitaGlobalis. Votre niveau d’accès est indiqué sur chaque carte.","Here are all NutVitaGlobalis applications. Your access level is shown on each card.")}</p></div><div className="rounded-3xl bg-white/10 p-6"><p className="text-sm text-white/70">{t("Vous souhaitez activer un service ?","Would you like to activate a service?")}</p><Link href="/services" className="mt-3 inline-flex items-center gap-2 font-black text-white">{t("Découvrir les solutions","Explore solutions")} <ArrowRightIcon className="h-4"/></Link></div></div></section>
    <section><h2 className="text-2xl font-black">{t("Applications et niveaux d’accès","Applications and access levels")}</h2><p className="mt-1 text-sm text-slate-500">{t("Une consultation active regroupe automatiquement tous les outils du suivi santé Premium.","An active consultation automatically includes every Premium health-monitoring tool.")}</p><div className="mt-5 grid gap-5 md:grid-cols-2">{SERVICES.filter(service=>(service.key!=="maximus"||choices.some(choice=>choice.service==="maximus"))&&!(service.key==="health"&&hasConsultation)).map(service=>{const access=choices.filter(c=>c.service===service.key);return <button key={service.key} type="button" onClick={()=>open(service,access)} className="group rounded-3xl border bg-white p-6 text-left shadow-soft transition hover:-translate-y-1 hover:border-leaf"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-forest"><service.icon className="h-6"/></span><span className={`rounded-full px-3 py-1 text-xs font-black ${access.length?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{access.length?t("Accessible","Accessible"):t("Non accessible","Not accessible")}</span></div><h3 className="mt-5 text-xl font-black text-forest">{t(service.title,service.titleEn)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{t(service.description,service.descriptionEn)}</p><div className="mt-4 flex flex-wrap gap-2">{access.length?access.map(c=><span key={c.role} className="rounded-full bg-mint px-3 py-1 text-xs font-black text-forest">{t("Accès","Access")}: {c.roleLabel}</span>):<span className="rounded-full bg-orange/10 px-3 py-1 text-xs font-black text-orange">{service.activation==="offer"?t("À activer","Activate"):t("Sur autorisation","Authorization required")}</span>}</div><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-leaf">{access.length?t("Ouvrir cet espace","Open this space"):service.activation==="offer"?t("Voir les offres","View offers"):t("Demander l’accès","Request access")} <ArrowRightIcon className="h-4 transition group-hover:translate-x-1"/></span></button>})}</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Utility href="/services" label={t("Acheter un service","Purchase a service")} icon={ShoppingBagIcon}/><Utility href="/espace-client/abonnement" label={t("Mes abonnements","My subscriptions")} icon={CreditCardIcon}/><Utility href="/espace-client/profil" label={t("Mon profil","My profile")} icon={UserCircleIcon}/><Utility href="/espace-client/securite" label={t("Mot de passe","Password")} icon={KeyIcon}/></section>
  </div>
}
function Utility({href,label,icon:Icon}:{href:string;label:string;icon:typeof HeartIcon}){return <Link href={href} className="flex items-center gap-3 rounded-2xl border bg-white p-5 font-black text-forest transition hover:border-leaf hover:bg-mint"><Icon className="h-6"/>{label}</Link>}
