"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { calculateMddw, mddwFoodItems } from "@/lib/dietary-diversity";

type Row=Record<string,any>;
export default function HealthDietaryDiversity({clientId,initial}:{clientId:string;initial:Row[]}){
  const [rows,setRows]=useState(initial),[message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fd=new FormData(form),foods=Object.fromEntries(mddwFoodItems.map(([key])=>[key,fd.get(`food_${key}`)==="on"])),result=calculateMddw(foods);const {data,error}=await createClient().from("health_dietary_diversity_assessments").insert({client_id:clientId,assessed_at:fd.get("assessed_at"),food_items:foods,group_scores:result.groups,diversity_score:result.score,mddw_met:result.met,notes:fd.get("notes")||null,created_by:clientId}).select().single();if(error)setMessage(error.message);else{setRows([data,...rows]);form.reset();setMessage(`Evaluation enregistree: ${result.score}/10 groupes, seuil ${result.met?"atteint":"non atteint"}.`)}}
  return <div className="grid gap-5"><form onSubmit={submit} className="grid gap-4 rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-black">Diversite alimentaire</h2><p className="mt-2 text-sm text-slate-500">Rappel des aliments consommes hier, adapte de la methode MDD-W. Le seuil est atteint a partir de 5 groupes sur 10.</p></div><input name="assessed_at" type="date" required defaultValue={new Date().toLocaleDateString("en-CA")} className="admin-input max-w-xs"/><div className="grid gap-2 md:grid-cols-2">{mddwFoodItems.map(([key,label])=><label key={key} className="flex gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" name={`food_${key}`} className="h-5 w-5"/>{label}</label>)}</div><textarea name="notes" className="admin-input" placeholder="Contexte du rappel ou observations"/><button className="btn-primary justify-self-start">Analyser et enregistrer</button></form>{message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}<div className="grid gap-3">{rows.map(row=><article key={row.id} className="rounded-xl border bg-white p-4"><b>{new Date(`${row.assessed_at}T12:00:00`).toLocaleDateString("fr-FR")}</b><p className="mt-1 text-sm">Score de diversite: {row.diversity_score}/10 - Seuil {row.mddw_met?"atteint":"non atteint"}</p></article>)}</div></div>
}
