"use client";
import {useEffect,useMemo,useState} from "react";
type Row=Record<string,any>;type Source="anthro"|"biology"|"food"|"wellness";type Point={date:Date;value:number};type Metric={key:string;label:string;unit:string;source:Source;date:string;color:string;cardio?:boolean;reference?:[number,number]};
const METRICS:Metric[]=[
 {key:"weight_kg",label:"Poids",unit:"kg",source:"anthro",date:"measured_at",color:"#087f5b"},{key:"height_cm",label:"Taille",unit:"cm",source:"anthro",date:"measured_at",color:"#0f766e"},{key:"bmi",label:"IMC",unit:"kg/m²",source:"anthro",date:"measured_at",color:"#f97316",reference:[18.5,24.9]},{key:"waist_cm",label:"Tour de taille",unit:"cm",source:"anthro",date:"measured_at",color:"#7c3aed"},{key:"body_fat_percent",label:"Masse grasse",unit:"%",source:"anthro",date:"measured_at",color:"#db2777"},
 {key:"glucose",label:"Glycémie",unit:"",source:"biology",date:"measured_at",color:"#0284c7"},{key:"hba1c",label:"HbA1c",unit:"%",source:"biology",date:"measured_at",color:"#7c3aed"},{key:"total_cholesterol",label:"Cholestérol total",unit:"",source:"biology",date:"measured_at",color:"#ea580c"},{key:"ldl",label:"LDL",unit:"",source:"biology",date:"measured_at",color:"#be123c"},{key:"hdl",label:"HDL",unit:"",source:"biology",date:"measured_at",color:"#059669"},{key:"triglycerides",label:"Triglycérides",unit:"",source:"biology",date:"measured_at",color:"#d97706"},
 {key:"systolic_pressure",label:"TA systolique",unit:"mmHg",source:"biology",date:"measured_at",color:"#dc2626",cardio:true,reference:[90,120]},{key:"diastolic_pressure",label:"TA diastolique",unit:"mmHg",source:"biology",date:"measured_at",color:"#2563eb",cardio:true,reference:[60,80]},{key:"pulse_bpm",label:"Pouls",unit:"bpm",source:"biology",date:"measured_at",color:"#16a34a",cardio:true},
 {key:"nutrition_score",label:"Score alimentation",unit:"%",source:"wellness",date:"assessment_date",color:"#ea580c"},{key:"physical_activity_score",label:"Score activité physique",unit:"%",source:"wellness",date:"assessment_date",color:"#0284c7"},{key:"lifestyle_score",label:"Score mode de vie",unit:"%",source:"wellness",date:"assessment_date",color:"#7c3aed"},
];
function pts(m:Metric,s:Record<Source,Row[]>){return s[m.source].map(r=>({date:new Date(r[m.date]||r.created_at),value:Number(r[m.key])})).filter(p=>Number.isFinite(p.value)&&p.value!==0&&Number.isFinite(+p.date)).sort((a,b)=>+a.date-+b.date)}
export default function HealthTrendsDashboardV2({anthropometry,biology,food,wellness=[],locale="fr"}:{anthropometry:Row[];biology:Row[];food:Row[];wellness?:Row[];locale?:"fr"|"en"}){
 const tx=(a:string,b:string)=>locale==="en"?b:a,sources=useMemo(()=>({anthro:anthropometry,biology,food,wellness}),[anthropometry,biology,food,wellness]);
 const available=useMemo(()=>METRICS.filter(m=>pts(m,sources).length>=2),[sources]);const [selected,setSelected]=useState<string[]>([]);
 useEffect(()=>setSelected(old=>old.length?old.filter(k=>available.some(m=>m.key===k)):available.map(m=>m.key)),[available]);
 const shown=available.filter(m=>selected.includes(m.key)),cardio=shown.filter(m=>m.cardio),others=shown.filter(m=>!m.cardio);
 if(!available.length)return <div className="rounded-3xl border bg-white p-12 text-center"><h2 className="text-xl font-black text-forest">{tx("Aucune tendance disponible","No trend available")}</h2><p className="mt-2 text-slate-500">{tx("Deux mesures datées au minimum sont nécessaires pour tracer une courbe.","At least two dated measurements are required to draw a curve.")}</p></div>;
 return <div className="grid gap-6"><section className="rounded-3xl border bg-white p-5 shadow-soft"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-forest">{tx("Variables affichées","Displayed variables")}</h2><p className="text-sm text-slate-500">{tx("Seules les variables ayant au moins deux mesures réelles sont proposées.","Only variables with at least two real measurements are available.")}</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setSelected(available.map(m=>m.key))}>{tx("Tout afficher","Show all")}</button><button className="btn-secondary" onClick={()=>setSelected([])}>{tx("Tout masquer","Hide all")}</button></div></div><div className="mt-4 flex flex-wrap gap-2">{available.map(m=><label key={m.key} className={`cursor-pointer rounded-full border px-4 py-2 text-sm font-bold ${selected.includes(m.key)?"border-forest bg-mint text-forest":"text-slate-500"}`}><input className="sr-only" type="checkbox" checked={selected.includes(m.key)} onChange={()=>setSelected(v=>v.includes(m.key)?v.filter(k=>k!==m.key):[...v,m.key])}/>{m.label}</label>)}</div></section>{cardio.length>0&&<Chart title={tx("Tension artérielle et pouls","Blood pressure and pulse")} metrics={cardio} sources={sources} locale={locale}/>}<div className="grid gap-6 xl:grid-cols-2">{others.map(m=><Chart key={m.key} title={m.label} metrics={[m]} sources={sources} locale={locale}/>)}</div></div>
}
function Chart({title,metrics,sources,locale}:{title:string;metrics:Metric[];sources:Record<Source,Row[]>;locale:"fr"|"en"}){
 const series=metrics.map(metric=>({metric,points:pts(metric,sources)}));const all=series.flatMap(s=>s.points),refs=metrics.flatMap(m=>m.reference||[]),values=[...all.map(p=>p.value),...refs],rawLo=Math.min(...values),rawHi=Math.max(...values),pad=Math.max((rawHi-rawLo)*.12,1),lo=Math.max(0,rawLo-pad),hi=rawHi+pad,span=hi-lo,dates=all.map(p=>+p.date),d0=Math.min(...dates),d1=Math.max(...dates),ds=d1-d0||1,w=860,h=370,l=70,r=28,t=32,b=62,x=(d:Date)=>l+(+d-d0)/ds*(w-l-r),y=(v:number)=>h-b-(v-lo)/span*(h-t-b);
 const unit=[...new Set(metrics.map(m=>m.unit).filter(Boolean))].join(" / ");
 return <section className="rounded-3xl border bg-white p-5 shadow-soft"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-forest">{title}</h2><p className="text-xs text-slate-500">{all.length} points · marqueurs sur chaque mesure</p></div><div className="flex flex-wrap gap-3">{series.map(s=><span key={s.metric.key} className="flex items-center gap-2 text-xs font-bold"><i className="h-3 w-3 rounded-full" style={{background:s.metric.color}}/>{s.metric.label} {s.metric.unit&&`(${s.metric.unit})`}</span>)}</div></div><div className="mt-4 overflow-x-auto"><svg viewBox={`0 0 ${w} ${h}`} className="w-full min-w-[650px]" role="img" aria-label={title}>
  {metrics.length===1&&metrics[0].reference&&<rect x={l} y={y(metrics[0].reference[1])} width={w-l-r} height={Math.max(0,y(metrics[0].reference[0])-y(metrics[0].reference[1]))} fill="#dff4ea" opacity=".75"><title>Plage de référence</title></rect>}
  {[0,.2,.4,.6,.8,1].map(v=>{const value=lo+span*v,py=y(value);return <g key={v}><line x1={l} y1={py} x2={w-r} y2={py} stroke="#d8dee7" strokeWidth="1"/><text x={l-10} y={py+4} textAnchor="end" fontSize="11" fill="#64748b">{value.toFixed(span<10?1:0)}</text></g>})}
  <line x1={l} y1={t} x2={l} y2={h-b} stroke="#475569"/><line x1={l} y1={h-b} x2={w-r} y2={h-b} stroke="#475569"/>
  {series.map(s=><g key={s.metric.key}><path d={s.points.map((p,i)=>`${i?"L":"M"}${x(p.date)},${y(p.value)}`).join(" ")} fill="none" stroke={s.metric.color} strokeWidth="3.5" strokeLinejoin="round"/>{s.points.map((p,i)=><circle key={i} cx={x(p.date)} cy={y(p.value)} r="5" fill="white" stroke={s.metric.color} strokeWidth="3"><title>{`${s.metric.label} · ${p.date.toLocaleDateString(locale==="en"?"en-GB":"fr-FR")} : ${p.value} ${s.metric.unit}`}</title></circle>)}</g>)}
  <text x={(l+w-r)/2} y={h-15} textAnchor="middle" fontSize="12" fontWeight="700" fill="#475569">{locale==="en"?"Measurement date":"Date de mesure"}</text>{unit&&<text transform={`translate(18 ${(t+h-b)/2}) rotate(-90)`} textAnchor="middle" fontSize="12" fontWeight="700" fill="#475569">{unit}</text>}<text x={l} y={h-b+22} fontSize="11" fill="#64748b">{new Date(d0).toLocaleDateString(locale==="en"?"en-GB":"fr-FR")}</text><text x={w-r} y={h-b+22} textAnchor="end" fontSize="11" fill="#64748b">{new Date(d1).toLocaleDateString(locale==="en"?"en-GB":"fr-FR")}</text>
 </svg></div>{metrics.length===1&&metrics[0].reference&&<p className="mt-2 text-xs text-slate-500"><span className="mr-2 inline-block h-3 w-5 rounded bg-[#dff4ea]"/>Plage de référence indicative configurée : {metrics[0].reference[0]}–{metrics[0].reference[1]} {metrics[0].unit}</p>}</section>
}
