"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row=Record<string,any>;

export default function PrescriptionResultsCenter({clientId,partnerId,consultations,initialResults,initialConsents}:{clientId:string;partnerId?:string|null;consultations:Row[];initialResults:Row[];initialConsents:Row[]}) {
  const [results,setResults]=useState(initialResults),[message,setMessage]=useState("");
  const [consents,setConsents]=useState(initialConsents);
  const consent=(scope:string)=>consents.find(item=>item.scope===scope)?.granted===true;

  async function toggleConsent(scope:string,granted:boolean){
    if(!partnerId){setMessage("Aucun nutritionniste soignant n'est encore affecte.");return}
    const payload={client_id:clientId,partner_id:partnerId,scope,granted,granted_at:granted?new Date().toISOString():null,revoked_at:granted?null:new Date().toISOString(),expires_at:null,consent_duration:"until_revoked",consent_version:"1.0",updated_at:new Date().toISOString()};
    const {data,error}=await createClient().from("professional_data_consents").upsert(payload,{onConflict:"client_id,partner_id,scope"}).select().single();
    if(error)setMessage(error.message);else{setConsents([...consents.filter(item=>item.scope!==scope),data]);setMessage(granted?"Consentement enregistre.":"Consentement retire.")}
  }

  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const form=event.currentTarget,fd=new FormData(form),file=fd.get("file") as File;
    let filePath:string|null=null;
    if(file?.size){filePath=`${clientId}/${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-")}`;const upload=await createClient().storage.from("laboratory-results").upload(filePath,file);if(upload.error){setMessage(upload.error.message);return}}
    const values=String(fd.get("result_values")||"").split("\n").map(line=>line.trim()).filter(Boolean).reduce((acc,line)=>{const [name,...rest]=line.split(":");acc[name.trim()]=rest.join(":").trim();return acc},{} as Record<string,string>);
    const payload={consultation_id:fd.get("consultation_id")||null,client_id:clientId,prescription_item:fd.get("prescription_item")||null,performed_at:fd.get("performed_at")||null,laboratory_name:fd.get("laboratory_name")||null,result_values:values,interpretation_notes:fd.get("notes")||null,file_path:filePath,shared_with_partner:fd.get("shared")==="on",created_by:clientId};
    const {data,error}=await createClient().from("consultation_lab_results").insert(payload).select().single();
    if(error)setMessage(error.message);else{setResults([data,...results]);form.reset();setMessage("Resultat de laboratoire enregistre.")}
  }
  async function open(bucket:string,path?:string){if(!path)return;const {data,error}=await createClient().storage.from(bucket).createSignedUrl(path,180);if(error)setMessage(error.message);else window.open(data.signedUrl,"_blank")}

  return <div className="grid gap-7">
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Consentement de partage</h2><p className="mt-2 text-sm leading-6 text-slate-600">Le consentement au dossier Suivi Sante Premium est donne une seule fois et reste valable pour toute la relation de suivi avec votre nutritionniste, sans date d'expiration. Vous pouvez toutefois le retirer a tout moment depuis cette page.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Consent checked={consent("premium_health_record")} label="J'autorise durablement mon nutritionniste a consulter tout mon dossier Suivi Sante Autonome Premium, jusqu'a mon retrait" onChange={value=>toggleConsent("premium_health_record",value)}/><Consent checked={consent("laboratory_results")} label="Partager mes resultats de laboratoire marques comme partageables" onChange={value=>toggleConsent("laboratory_results",value)}/><Consent checked={consent("care_collaboration")} label="Autoriser mon nutritionniste a inviter nominativement un collaborateur de soins" onChange={value=>toggleConsent("care_collaboration",value)}/></div></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Mes ordonnances d'examens</h2><div className="mt-4 grid gap-3">{consultations.filter(item=>item.prescription_pdf_path||item.prescription_items?.length).map(item=><article key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.reason||"Ordonnance d'examens"}</b><p className="text-sm text-slate-500">{new Date(item.finalized_at||item.scheduled_at).toLocaleDateString("fr-FR")}</p><p className="mt-2 text-sm">{(item.prescription_items||[]).join(", ")}</p></div>{item.prescription_pdf_path&&<button onClick={()=>open("document-vault",item.prescription_pdf_path)} className="btn-secondary px-4 py-2">Voir le PDF</button>}</div></article>)}{!consultations.some(item=>item.prescription_pdf_path||item.prescription_items?.length)&&<p className="text-slate-400">Aucune ordonnance.</p>}</div></section>
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><h2 className="text-xl font-black md:col-span-2">Renseigner un resultat de laboratoire</h2><label className="grid gap-2 text-sm font-bold">Ordonnance associee<select name="consultation_id" className="admin-input"><option value="">Aucune</option>{consultations.map(item=><option key={item.id} value={item.id}>{new Date(item.finalized_at||item.scheduled_at).toLocaleDateString("fr-FR")} - {item.reason||"Consultation"}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Examen<input name="prescription_item" required className="admin-input" placeholder="Ex. HbA1c"/></label><label className="grid gap-2 text-sm font-bold">Date de realisation<input name="performed_at" type="date" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Laboratoire<input name="laboratory_name" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Valeurs, une par ligne<textarea name="result_values" rows={4} className="admin-input" placeholder={"HbA1c : 6,8 %\nGlycemie : 1,10 g/L"}/></label><label className="grid gap-2 text-sm font-bold">Compte rendu PDF ou image<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Observations<textarea name="notes" className="admin-input"/></label><label className="flex items-center gap-3 rounded-xl bg-mint p-4 text-sm font-bold md:col-span-2"><input name="shared" type="checkbox" disabled={!consent("laboratory_results")}/>Autoriser mon nutritionniste a consulter ce resultat</label><button className="btn-primary justify-self-start md:col-span-2">Enregistrer le resultat</button></form>
    {message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Resultats enregistres</h2><div className="mt-4 grid gap-3">{results.map(item=><article key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.prescription_item||"Resultat"}</b><p className="text-sm text-slate-500">{item.performed_at||"Date non renseignee"} - {item.laboratory_name||"Laboratoire non renseigne"}</p><p className="mt-2 text-sm">{Object.entries(item.result_values||{}).map(([key,value])=>`${key}: ${value}`).join(" | ")}</p><p className="mt-1 text-xs text-slate-500">{item.shared_with_partner?"Partage avec le nutritionniste":"Prive"}</p></div>{item.file_path&&<button onClick={()=>open("laboratory-results",item.file_path)} className="btn-secondary px-4 py-2">Document</button>}</div></article>)}{!results.length&&<p className="text-slate-400">Aucun resultat enregistre.</p>}</div></section>
  </div>
}
function Consent({checked,label,onChange}:{checked:boolean;label:string;onChange:(value:boolean)=>void}){return <label className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-4 text-sm font-bold"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="h-5 w-5"/></label>}
