"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row=Record<string,any>;
type LabRow={id:string;name:string;date:string;value:string;unit:string;min:string;max:string;uncertainty:string};
const blank=(name=""):LabRow=>({id:crypto.randomUUID(),name,date:"",value:"",unit:"",min:"",max:"",uncertainty:""});
const num=(v:string)=>v!==""&&Number.isFinite(Number(v.replace(",",".")))?Number(v.replace(",",".")):null;

export default function PrescriptionResultsCenter({clientId,partnerId,consultations,initialResults,initialConsents,view="all"}:{clientId:string;partnerId?:string|null;consultations:Row[];initialResults:Row[];initialConsents:Row[];view?:"all"|"consents"|"prescriptions"|"results"}) {
  const [results,setResults]=useState(initialResults),[message,setMessage]=useState("");
  const [consents,setConsents]=useState(initialConsents);
  const [labRows,setLabRows]=useState<LabRow[]>([blank()]);
  const updateLab=(id:string,key:keyof LabRow,value:string)=>setLabRows(rows=>rows.map(row=>row.id===id?{...row,[key]:value}:row));
  const selectPrescription=(id:string)=>{const exams=consultations.find(item=>item.id===id)?.prescription_items||[];setLabRows(exams.length?exams.map((name:string)=>blank(name)):[blank()])};
  const consent=(scope:string)=>consents.find(item=>item.scope===scope)?.granted===true;

  async function toggleConsent(scope:string,granted:boolean){
    if(!partnerId){setMessage("Aucun nutritionniste soignant n'est encore affecte.");return}
    const payload={client_id:clientId,partner_id:partnerId,scope,granted,granted_at:granted?new Date().toISOString():null,revoked_at:granted?null:new Date().toISOString(),expires_at:null,consent_duration:"until_revoked",consent_version:"1.0",updated_at:new Date().toISOString()};
    const {data,error}=await createClient().from("professional_data_consents").upsert(payload,{onConflict:"client_id,partner_id,scope"}).select().single();
    if(error)setMessage(error.message);else{setConsents([...consents.filter(item=>item.scope!==scope),data]);setMessage(granted?"Consentement enregistre.":"Consentement retire.")}
  }

  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const form=event.currentTarget,fd=new FormData(form),file=fd.get("file") as File;
    let filePath:string|null=null;
    if(file?.size){filePath=`${clientId}/${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-")}`;const upload=await createClient().storage.from("laboratory-results").upload(filePath,file);if(upload.error){setMessage(upload.error.message);return}}
    const values=String(fd.get("result_values")||"").split("\n").map(line=>line.trim()).filter(Boolean).reduce((acc,line)=>{const [name,...rest]=line.split(":"),parts=rest.join(":").split("|").map(value=>value.trim()),numeric=(value?:string)=>value&&Number.isFinite(Number(value.replace(",",".")))?Number(value.replace(",",".")):null;if(parts.length>1)acc[name.trim()]={value:numeric(parts[0]),unit:parts[1]||"",normal_min:numeric(parts[2]),normal_max:numeric(parts[3]),uncertainty:numeric(parts[4])};else acc[name.trim()]=rest.join(":").trim();return acc},{} as Record<string,any>);
    const payload={consultation_id:fd.get("consultation_id")||null,client_id:clientId,prescription_item:fd.get("prescription_item")||null,performed_at:fd.get("performed_at")||null,laboratory_name:fd.get("laboratory_name")||null,result_values:values,interpretation_notes:fd.get("notes")||null,file_path:filePath,shared_with_partner:fd.get("shared")==="on",created_by:clientId};
    const {data,error}=await createClient().from("consultation_lab_results").insert(payload).select().single();
    if(error)setMessage(error.message);else{setResults([data,...results]);form.reset();setMessage("Resultat de laboratoire enregistre.")}
  }
  async function open(bucket:string,path?:string){if(!path)return;const {data,error}=await createClient().storage.from(bucket).createSignedUrl(path,180);if(error)setMessage(error.message);else window.open(data.signedUrl,"_blank")}

  return <div className="grid gap-7">
    {(view==="all"||view==="consents")&&<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Consentement de partage</h2><p className="mt-2 text-sm leading-6 text-slate-600">Le consentement au dossier Suivi Sante Premium est donne une seule fois et reste valable pour toute la relation de suivi avec votre nutritionniste, sans date d'expiration. Vous pouvez toutefois le retirer a tout moment depuis cette page.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Consent checked={consent("premium_health_record")} label="J'autorise durablement mon nutritionniste a consulter tout mon dossier Suivi Sante Autonome Premium, jusqu'a mon retrait" onChange={value=>toggleConsent("premium_health_record",value)}/><Consent checked={consent("laboratory_results")} label="Partager mes résultats de laboratoire marques comme partageables" onChange={value=>toggleConsent("laboratory_results",value)}/><Consent checked={consent("care_collaboration")} label="Autoriser mon nutritionniste a inviter nominativement un collaborateur de soins" onChange={value=>toggleConsent("care_collaboration",value)}/></div></section>}
    {(view==="all"||view==="prescriptions")&&<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Mes ordonnances d'examens</h2><div className="mt-4 grid gap-3">{consultations.filter(item=>item.prescription_pdf_path||item.prescription_items?.length).map(item=><article key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.reason||"Ordonnance d'examens"}</b><p className="text-sm text-slate-500">{new Date(item.finalized_at||item.scheduled_at).toLocaleDateString("fr-FR")}</p><p className="mt-2 text-sm">{(item.prescription_items||[]).join(", ")}</p></div>{item.prescription_pdf_path&&<button onClick={()=>open("document-vault",item.prescription_pdf_path)} className="btn-secondary px-4 py-2">Voir le PDF</button>}</div></article>)}{!consultations.some(item=>item.prescription_pdf_path||item.prescription_items?.length)&&<p className="text-slate-400">Aucune ordonnance.</p>}</div></section>}
    {(view==="all"||view==="results")&&<form onSubmit={submit} className="grid gap-5 rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Renseigner des résultats de laboratoire</h2><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Ordonnance associée<select name="consultation_id" onChange={e=>selectPrescription(e.target.value)} className="admin-input"><option value="">Aucune</option>{consultations.filter(x=>x.prescription_items?.length).map(item=><option key={item.id} value={item.id}>{item.reason||"Ordonnance"}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Laboratoire<input name="laboratory_name" className="admin-input"/></label></div><div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[980px] text-sm"><thead className="bg-mint text-left"><tr>{["Examen","Date de réalisation","Valeur","Unité","Min","Max","Incertitude",""] .map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{labRows.map(row=><tr key={row.id} className="border-t">{(["name","date","value","unit","min","max","uncertainty"] as (keyof LabRow)[]).map(key=><td key={key} className="p-2"><input type={key==="date"?"date":"text"} value={row[key]} required={key==="name"||key==="value"} onChange={e=>updateLab(row.id,key,e.target.value)} className="admin-input min-w-24"/></td>)}<td><button type="button" onClick={()=>setLabRows(rows=>rows.length>1?rows.filter(x=>x.id!==row.id):rows)} className="p-3 text-red-600">×</button></td></tr>)}</tbody></table></div><button type="button" onClick={()=>setLabRows(rows=>[...rows,blank()])} className="btn-secondary w-fit">+ Ajouter un examen</button><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Compte rendu<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Observations<textarea name="notes" className="admin-input"/></label></div><label className="flex items-center gap-3 rounded-xl bg-mint p-4 text-sm font-bold"><input name="shared" type="checkbox" disabled={!consent("laboratory_results")}/>Autoriser mon nutritionniste à consulter ces résultats</label><button className="btn-primary justify-self-start">Enregistrer les résultats</button></form>}
    {message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}
    {(view==="all"||view==="results")&&<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Résultats enregistres</h2><div className="mt-4 grid gap-3">{results.map(item=><article key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.prescription_item||"Resultat"}</b><p className="text-sm text-slate-500">{item.performed_at||"Date non renseignee"} - {item.laboratory_name||"Laboratoire non renseigne"}</p><p className="mt-2 text-sm">{Object.entries(item.result_values||{}).map(([key,value])=>`${key}: ${value&&typeof value==="object"?[(value as any).value,(value as any).unit].filter(Boolean).join(" "):String(value??"")}`).join(" | ")}</p><p className="mt-1 text-xs text-slate-500">{item.shared_with_partner?"Partage avec le nutritionniste":"Prive"}</p></div>{item.file_path&&<button onClick={()=>open("laboratory-results",item.file_path)} className="btn-secondary px-4 py-2">Document</button>}</div></article>)}{!results.length&&<p className="text-slate-400">Aucun résultat enregistre.</p>}</div></section>}
  </div>
}
function Consent({checked,label,onChange}:{checked:boolean;label:string;onChange:(value:boolean)=>void}){return <label className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-4 text-sm font-bold"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="h-5 w-5"/></label>}
