"use client";
import {useMemo,useState} from "react";
import {AppWindow,ArrowRight,BarChart3,BriefcaseBusiness,Crown,GraduationCap,HeartPulse,Info,Salad,Stethoscope,Users} from "lucide-react";
import type {ClientServiceCatalogSettings} from "@/data/client-service-catalog";
type Row=Record<string,any>;type Choice={service:string;role:string};
const icons:Record<string,typeof HeartPulse>={stethoscope:Stethoscope,chart:BarChart3,crown:Crown,child:HeartPulse,family:Users,academy:GraduationCap,apps:AppWindow,meal:Salad,briefcase:BriefcaseBusiness};
const tier=(value:string)=>["basic","standard"].includes(String(value).toLowerCase())?"standard":String(value).toLowerCase();
export default function ServiceCatalogV2({settings,plans,children,subscriptions=[],choices=[],english=false}:{settings:ClientServiceCatalogSettings;plans:Row[];children:Row[];subscriptions?:Row[];choices?:Choice[];english?:boolean}){
 const [selectedChild,setSelectedChild]=useState(children[0]?.id||"");const t=(fr:string,en:string)=>english?(en||fr):fr;
 const planFor=(card:ClientServiceCatalogSettings["cards"][number])=>plans.find(plan=>plan.service_type===card.service_type&&tier(plan.tier)===tier(card.tier));
 const active=useMemo(()=>subscriptions.filter(sub=>sub.status==="active"&&(!sub.expires_at||+new Date(sub.expires_at)>Date.now())),[subscriptions]);
 const choice=(service:string)=>choices.find(item=>item.service===service);
 function hasAccess(card:ClientServiceCatalogSettings["cards"][number]){if(["health_tracking","child_growth"].includes(card.service_type)){const plan=planFor(card);return Boolean(plan&&active.some(sub=>sub.plan_id===plan.id&&(card.service_type!=="child_growth"||!selectedChild||sub.child_id===selectedChild)))}if(card.service_type==="teleconsultation")return Boolean(choice("teleconsultation"));if(card.service_type==="academy")return Boolean(choice("academy"));return false}
 function open(card:ClientServiceCatalogSettings["cards"][number]){const granted=hasAccess(card);if(card.service_type==="teleconsultation"&&granted){location.href=`/api/access/open?service=teleconsultation&role=${choice("teleconsultation")!.role}`;return}if(card.service_type==="academy"&&granted){location.href=`/api/access/open?service=academy&role=${choice("academy")!.role}`;return}if(card.service_type==="health_tracking"&&granted){location.href="/api/access/open?service=health&role=client";return}if(card.service_type==="child_growth"&&granted){location.href="/api/access/open?service=child_growth&role=parent";return}const plan=planFor(card);if(plan){if(card.service_type==="child_growth"&&!selectedChild){location.href="/espace-client/croissance-enfant";return}const child=card.service_type==="child_growth"?`&child_id=${encodeURIComponent(selectedChild)}`:"";location.href=`/checkout?type=subscription&id=${encodeURIComponent(plan.id)}${child}`;return}location.href=card.destination}
 return <div className="grid gap-8">
  {children.length>0&&<div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4"><label className="font-black text-forest">{english?"Child concerned":"Enfant concerné"}</label><select className="admin-input max-w-xs" value={selectedChild} onChange={e=>setSelectedChild(e.target.value)}>{children.map(child=><option key={child.id} value={child.id}>{child.full_name||[child.first_name,child.last_name].filter(Boolean).join(" ")}</option>)}</select></div>}
  <div className="grid gap-5 [grid-template-columns:repeat(auto-fit,minmax(min(100%,430px),1fr))]">{settings.cards.filter(card=>card.active).map(card=>{const Icon=icons[card.icon]||HeartPulse,granted=hasAccess(card),premium=tier(card.tier)==="premium",blocked=tier(card.tier)==="standard"&&active.some(sub=>{const plan=plans.find(p=>p.id===sub.plan_id);return plan?.service_type===card.service_type&&tier(plan?.tier)==="premium"});return <article key={card.id} className="group grid min-h-[250px] overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl sm:grid-cols-[minmax(0,1fr)_38%]">
   <div className="flex min-w-0 flex-col p-6"><div className="flex items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-mint text-leaf"><Icon className="h-7 w-7"/></span><div><h2 className="break-words text-xl font-black leading-tight text-forest">{t(card.title,card.title_en)}</h2>{card.badge&&<span className={`mt-2 inline-flex rounded-full px-3 py-1 text-xs font-black ${premium?"bg-orange/15 text-orange":"bg-mint text-forest"}`}>{t(card.badge,card.badge_en)}</span>}</div></div><p className="mt-5 text-sm leading-6 text-slate-600">{t(card.description,card.description_en)}</p><div className="mt-auto flex flex-wrap gap-3 pt-5"><button onClick={()=>location.href=card.destination} className="rounded-full border border-leaf px-4 py-2 text-sm font-black text-forest">{t(card.secondary_label,card.secondary_label_en)}</button><button disabled={blocked} onClick={()=>open(card)} className={`rounded-full px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300 ${premium?"bg-orange":"bg-leaf"}`}>{blocked?(english?"Included in Premium":"Inclus dans Premium"):granted?(english?"Open service":"Ouvrir le service"):t(card.primary_label,card.primary_label_en)}<ArrowRight className="ml-2 inline h-4"/></button></div></div>
   <img src={card.image_url} alt="" className="hidden h-full min-h-[250px] w-full object-cover sm:block"/>
  </article>})}</div>
  <section className="grid items-center gap-6 rounded-3xl bg-gradient-to-r from-[#eaf6ef] to-white p-7 lg:grid-cols-[1.25fr_repeat(4,1fr)]"><div><h2 className="text-2xl font-black">{t(settings.footer_title,settings.footer_title_en)}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t(settings.footer_text,settings.footer_text_en)}</p></div>{[english?"Scientific expertise":"Expertise scientifique",english?"Security and privacy":"Sécurité et confidentialité",english?"Measurable impact":"Impact mesurable",english?"Responsive support":"Support réactif"].map((label,i)=><div key={label} className="flex items-center gap-3 border-l border-slate-200 pl-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-mint text-leaf">{i===0?<Info/>:i===1?<HeartPulse/>:i===2?<BarChart3/>:<Users/>}</span><b className="text-sm">{label}</b></div>)}</section>
 </div>
}