"use client";
import {useMemo,useState} from "react";
type Row=Record<string,any>;
type Choice={service:string;role:string};
const SUPPORT=[
  {key:"nutritrack",title:"Application de support à la prise en charge de la malnutrition aiguë (NutriTrack)"},
  {key:"survey",title:"Application de support aux enquêtes de sécurité alimentaire et nutrition"},
  {key:"project_management",title:"Application de support à la gestion des projets, programmes et portefeuilles"},
];
export default function ServiceCatalogV2({plans,packs,courses,children,subscriptions=[],choices=[],taxRate,initialFilter="all"}:{plans:Row[];packs:Row[];courses:Row[];children:Row[];subscriptions?:Row[];choices?:Choice[];taxRate:number;initialFilter?:string}){
 const [filter,setFilter]=useState(initialFilter),[selectedChild,setSelectedChild]=useState(children[0]?.id||"");
 const support=[...SUPPORT,...choices.some(c=>c.service==="maximus")?[{key:"maximus",title:"Maximus — gestion interne du cabinet"}]:[]];
 const services=useMemo(()=>[
  ...plans.map(plan=>({id:plan.id,kind:"subscription",group:plan.service_type,title:plan.name,premium:plan.tier==="premium",tier:plan.tier,features:plan.features||[],price:Number(plan.price_excluding_tax??plan.amount??0)})),
  ...packs.map(pack=>({id:pack.id,kind:"consultation",group:"packs",title:`Pack ${pack.name}`,premium:true,tier:"premium",price:Number(pack.price||0),features:["Bilan nutritionnel personnalisé","Plan d’action individualisé","Téléconsultations et messagerie"]})),
  ...courses.map(course=>({id:course.id,kind:"formation",group:"formations",title:course.title,premium:true,tier:"premium",price:Number(course.price||0),features:["Formation certifiante","Progression et évaluations","Certificat"]})),
 ],[plans,packs,courses]);
 const rows=filter==="all"?services:services.filter(item=>item.group===filter);
 const activeFor=(item:any)=>subscriptions.filter(sub=>sub.status==="active"&&(!sub.expires_at||+new Date(sub.expires_at)>Date.now())&&(item.group!=="child_growth"||sub.child_id===selectedChild));
 const planById=new Map(plans.map(p=>[p.id,p]));
 function state(item:any){const active=activeFor(item),current=active.find(s=>s.plan_id===item.id),same=active.filter(s=>planById.get(s.plan_id)?.service_type===item.group),premium=same.some(s=>planById.get(s.plan_id)?.tier==="premium"),basic=same.some(s=>planById.get(s.plan_id)?.tier==="basic");return{current,blocked:item.tier==="basic"&&premium,label:current?"Étendre le service":item.tier==="premium"&&basic?"Passer à Premium":"Acheter ce service"}}
 function checkout(item:any){const service=item.kind==="consultation"?"teleconsultation":item.kind==="formation"?"academy":null;const access=service?choices.find(c=>c.service===service):null;if(access){location.href=`/api/access/open?service=${service}&role=${access.role}`;return}if(item.group==="child_growth"&&!selectedChild){location.href="/api/access/open?service=client&role=client&return=/espace-client/croissance-enfant";return}const child=item.group==="child_growth"?`&child_id=${encodeURIComponent(selectedChild)}`:"";location.href=`/checkout?type=${item.kind}&id=${encodeURIComponent(item.id)}${child}`}
 function openSupport(key:string){const access=choices.find(c=>c.service===key);if(access)location.href=`/api/access/open?service=${key}&role=${access.role}`}
 return <div className="grid gap-8">
  <div className="flex flex-wrap gap-2">{[["all","Tous"],["health_tracking","Suivi santé"],["child_growth","Croissance enfant"],["packs","Consultations"],["formations","Formations"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===v?"bg-forest text-white":"bg-white text-forest"}`}>{l}</button>)}</div>
  <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map(item=>{const s=state(item);return <article key={`${item.kind}-${item.id}`} className={`rounded-3xl border p-6 ${s.blocked?"bg-slate-100 opacity-60":item.premium?"border-orange bg-white":"bg-white"}`}><p className="text-xs font-black uppercase text-leaf">{item.premium?"Premium":"Standard"}</p><h2 className="mt-2 text-2xl font-black">{item.title}</h2><p className="my-4 rounded-xl bg-mint p-3 text-sm font-bold text-forest">{Math.round((item.price||0)*(1+taxRate/100)).toLocaleString("fr-FR")} FCFA TTC</p><p className="mb-4 text-xs text-amber-700">Paiement pas encore disponible pour le moment.</p><ul className="my-5 grid gap-2 text-sm">{item.features.map((f:string)=><li key={f}>✓ {f}</li>)}</ul>{item.group==="child_growth"&&children.length>0&&<label className="mb-4 grid gap-2 text-sm font-bold">Enfant<select className="admin-input" value={selectedChild} onChange={e=>setSelectedChild(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.full_name||[c.first_name,c.last_name].filter(Boolean).join(" ")}</option>)}</select></label>}{item.group==="child_growth"&&!children.length&&<p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm">Commencez par créer le dossier de l’enfant.</p>}<button disabled={s.blocked} onClick={()=>checkout(item)} className="btn-primary w-full disabled:cursor-not-allowed disabled:bg-slate-300">{s.blocked?"Déjà inclus dans Premium":item.group==="child_growth"&&!children.length?"Créer un enfant":s.label}</button></article>})}</div>
  <section className="rounded-3xl border bg-white p-6"><p className="text-xs font-black uppercase text-orange">Service de restauration</p><h2 className="mt-2 text-2xl font-black">Menus sains et livraison</h2><p className="my-4 text-sm text-slate-500">Consultez les menus disponibles dans votre ville et transmettez votre commande pour devis.</p><button onClick={()=>location.href="/restauration"} className="btn-primary">Voir les menus et commander</button></section>
  <section><h2 className="text-2xl font-black">Applications de support</h2><p className="mt-2 text-slate-500">Ces solutions sont présentées dès maintenant. Leur activation commerciale sera ouverte prochainement.</p><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{support.map(item=>{const allowed=choices.some(c=>c.service===item.key);return <article key={item.key} className="rounded-3xl border bg-white p-6"><p className="text-xs font-black uppercase text-leaf">Application de support</p><h3 className="mt-2 text-xl font-black">{item.title}</h3><p className="my-5 text-sm text-slate-500">{allowed?"Votre compte dispose déjà d’un accès.":"L’achat et l’activation ne sont pas encore disponibles pour le moment."}</p><button disabled={!allowed} onClick={()=>openSupport(item.key)} className="btn-secondary w-full disabled:cursor-not-allowed disabled:opacity-50">{allowed?"Ouvrir l’application":"Bientôt disponible"}</button></article>})}</div></section>
 </div>
}
