"use client";
import {FormEvent,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import VideoRoom from "@/components/recruitment/VideoRoom";
type Row=Record<string,any>;
export default function CallManager({initial,currentUserId,conversations,clients=[],collaborators=[],canCreate=true}:{initial:Row[];currentUserId:string;conversations:Row[];clients?:Row[];collaborators?:Row[];canCreate?:boolean;adminMode?:boolean}){
 const [calls,setCalls]=useState(initial),[active,setActive]=useState<Row|null>(null),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[message,setMessage]=useState("");
 const contacts=useMemo<Row[]>(()=>[...clients.map((x:Row)=>({...x,role:"client"})),...collaborators.map((x:Row)=>({...x,role:"collaborateur"}))],[clients,collaborators]);
 const visible=useMemo(()=>calls.filter(x=>[x.call_code,x.title,x.call_type,x.provider,x.location_or_external_url].join(" ").toLowerCase().includes(query.toLowerCase())),[calls,query]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),clientIds=fd.getAll("client_ids").map(String).filter(Boolean),staffIds=fd.getAll("collaborator_ids").map(String).filter(Boolean),provider=String(fd.get("provider")||"jitsi"),location=String(fd.get("location_or_external_url")||"").trim(),room=`NutVita-${crypto.randomUUID().slice(0,8)}`;if(provider==="external"&&!location.startsWith("https://")){setMessage("Indiquez un lien HTTPS valide.");return}const payload={title:String(fd.get("title")),call_type:String(fd.get("call_type")||"consultation"),conversation_id:String(fd.get("conversation_id")||"")||null,scheduled_at:new Date(String(fd.get("scheduled_at"))).toISOString(),duration_minutes:Number(fd.get("duration_minutes")||45),provider,room_name:room,meeting_url:provider==="external"?location:null,location_or_external_url:location||null,status:"scheduled",created_by:currentUserId};const db=createClient(),{data,error}=await db.from("collaboration_calls").insert(payload).select().single();if(error){setMessage(error.message);return}const ids=Array.from(new Set([currentUserId,...clientIds,...staffIds]));if(ids.length)await db.from("collaboration_call_members").insert(ids.map(user_id=>({call_id:data.id,user_id,invited_by:currentUserId})));setCalls(x=>[{...data,collaboration_call_members:ids.map(user_id=>({user_id}))},...x]);setOpen(false);form.reset();setMessage("Réunion planifiée.")}
 return <div className="grid gap-5">{canCreate&&<div className="flex justify-end"><button onClick={()=>setOpen(true)} className="btn-primary">Planifier une réunion ou un appel</button></div>}{message&&<p className="rounded-xl bg-mint p-3 font-bold text-leaf">{message}</p>}<input value={query} onChange={e=>setQuery(e.target.value)} className="admin-input max-w-xl" placeholder="Filtrer par ID, titre, type ou mode…"/>
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID réunion","Titre","Type d’appel","Clients","Collaborateurs","Conversation","Mode","Lien externe ou lieu","Date","Durée","Action"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y">{visible.map(call=>{const members=(call.collaboration_call_members||[]).map((m:Row)=>contacts.find(c=>c.id===m.user_id)).filter(Boolean);return <tr key={call.id}><td className="p-4 font-black text-forest">{call.call_code||call.id.slice(0,10).toUpperCase()}</td><td className="p-4 font-bold">{call.title}</td><td className="p-4">{call.call_type||"consultation"}</td><td className="p-4">{members.filter((x:Row)=>x.role==="client").map((x:Row)=>x.full_name).join(", ")||"—"}</td><td className="p-4">{members.filter((x:Row)=>x.role!=="client").map((x:Row)=>x.full_name).join(", ")||"—"}</td><td className="p-4">{conversations.find(x=>x.id===call.conversation_id)?.title||"—"}</td><td className="p-4">{call.provider}</td><td className="max-w-[220px] p-4">{call.location_or_external_url||call.meeting_url||"Salle intégrée"}</td><td className="p-4">{new Date(call.scheduled_at).toLocaleString("fr-FR")}</td><td className="p-4">{call.duration_minutes} min</td><td className="p-4"><button onClick={()=>setActive(call)} className="btn-primary px-3 py-2">Ouvrir</button></td></tr>})}{!visible.length&&<tr><td colSpan={11} className="p-10 text-center text-slate-400">Aucune réunion planifiée.</td></tr>}</tbody></table></div>
  {open&&<div className="fixed inset-0 z-[140] overflow-y-auto bg-slate-950/65 p-4"><form onSubmit={create} className="mx-auto my-8 grid max-w-4xl gap-4 rounded-3xl bg-white p-7 md:grid-cols-2"><div className="flex justify-between md:col-span-2"><h2 className="text-2xl font-black">Planifier une réunion ou un appel</h2><button type="button" onClick={()=>setOpen(false)} className="text-3xl">×</button></div><label className="grid gap-2 text-sm font-bold">Titre<input name="title" required className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Type d’appel<select name="call_type" className="admin-input"><option value="consultation">Consultation</option><option value="follow_up">Suivi</option><option value="team">Réunion d’équipe</option><option value="other">Autre</option></select></label><label className="grid gap-2 text-sm font-bold">Clients<select name="client_ids" multiple className="admin-input min-h-28">{clients.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Collaborateurs<select name="collaborator_ids" multiple className="admin-input min-h-28">{collaborators.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Conversation associée<select name="conversation_id" className="admin-input"><option value="">Aucune</option>{conversations.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Mode<select name="provider" className="admin-input"><option value="jitsi">Visioconférence sécurisée</option><option value="external">Lien externe</option><option value="physical">Présentiel</option></select></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Lien externe ou lieu<input name="location_or_external_url" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Date<input name="scheduled_at" type="datetime-local" required className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">Durée (minutes)<input name="duration_minutes" type="number" min="5" defaultValue="45" className="admin-input"/></label><button className="btn-primary justify-self-end md:col-span-2">Planifier</button></form></div>}
  {active&&<div className="fixed inset-0 z-[150] overflow-y-auto bg-slate-950/80 p-4"><div className="mx-auto max-w-6xl"><div className="mb-3 flex justify-between text-white"><h2 className="text-xl font-black text-white">{active.title}</h2><button onClick={()=>setActive(null)}>Fermer</button></div><VideoRoom roomName={active.room_name} displayName="NutVitaGlobalis" provider={active.provider} meetingUrl={active.meeting_url}/></div></div>}
 </div>
}
