"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row=Record<string,any>;
export default function FosaRecordManager({module,organizationId,member,facilities,initial}:{module:{slug:string;title:string;description:string};organizationId:string;member:Row;facilities:Row[];initial:Row[]}){
  const [rows,setRows]=useState(initial),[message,setMessage]=useState("");
  const canCreate=["organization_admin","creator"].includes(member.role);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,body=Object.fromEntries(new FormData(form)),{data,error}=await createClient().from("fosa_records").insert({...body,module:module.slug,organization_id:organizationId,created_by:member.user_id,payload:{}}).select().single();if(error)setMessage(error.message);else{setRows([data,...rows]);form.reset();setMessage("Enregistrement cree en brouillon.");}}
  async function transition(row:Row,status:string){const changes:Row={status};if(status==="submitted")changes.submitted_at=new Date().toISOString();if(status==="verified"){changes.verified_at=new Date().toISOString();changes.verified_by=member.user_id;}if(status==="validated"){changes.validated_at=new Date().toISOString();changes.validated_by=member.user_id;}const {data,error}=await createClient().from("fosa_records").update(changes).eq("id",row.id).select().single();if(error)setMessage(error.message);else setRows(rows.map(item=>item.id===row.id?data:item));}
  return <div className="grid gap-7">{canCreate&&<form onSubmit={create} className="grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><h2 className="text-xl font-black md:col-span-2">Nouvel enregistrement</h2><label className="grid gap-2 text-sm font-bold">Formation sanitaire<select name="facility_id" required className="admin-input">{facilities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Reference<input name="reference" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Titre<input name="title" required className="admin-input"/></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Resume<textarea name="summary" rows={4} className="admin-input"/></label><button className="btn-primary justify-self-start md:col-span-2">Enregistrer le brouillon</button></form>}{message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}<div className="grid gap-3">{rows.map(row=><article key={row.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase text-leaf">{facilities.find(item=>item.id===row.facility_id)?.name||"FOSA"}</p><h2 className="mt-1 text-lg font-black">{row.title}</h2><p className="mt-2 text-sm text-slate-500">{row.summary||"Aucun resume."}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase">{row.status}</span></div><div className="mt-4 flex flex-wrap gap-2">{row.created_by===member.user_id&&row.status==="draft"&&<button onClick={()=>transition(row,"submitted")} className="btn-secondary px-4 py-2">Soumettre</button>}{["organization_admin","verifier"].includes(member.role)&&row.status==="submitted"&&<button onClick={()=>transition(row,"verified")} className="btn-primary px-4 py-2">Verifier</button>}{["organization_admin","validator"].includes(member.role)&&row.status==="verified"&&<button onClick={()=>transition(row,"validated")} className="btn-primary px-4 py-2">Valider</button>}</div></article>)}{!rows.length&&<p className="rounded-2xl bg-white p-8 text-center text-slate-400">Aucun enregistrement dans ce module.</p>}</div></div>;
}
