import Image from "next/image";
import Link from "next/link";
import { getCurrentLocale } from "@/lib/i18n-server";
import { localizedPath } from "@/lib/i18n";
import { getActiveMedicalSpecialists, medicalSpecialties } from "@/lib/medical-specialists";

export const metadata={title:"Trouver un spécialiste | NutVitaGlobalis"};
export default async function SpecialistsPage(){const locale=await getCurrentLocale(),en=locale==="en",specialists=await getActiveMedicalSpecialists();return <main className="bg-slate-50 py-12"><div className="container-site"><p className="text-sm text-slate-500">{en?"Home / Specialist medical consultations / Find a specialist":"Accueil / Consultations médicales spécialisées / Trouver un spécialiste"}</p><h1 className="mt-8 text-4xl font-black">{en?"Find a specialist":"Trouver un spécialiste"}</h1><p className="mt-2 text-slate-500">{en?"Choose the specialist who matches your needs and book online.":"Choisissez le spécialiste qui correspond à vos besoins et prenez rendez-vous en ligne."}</p>
<form className="mt-8 grid gap-4 rounded-3xl border bg-white p-6 shadow-sm md:grid-cols-3"><input name="q" placeholder={en?"Name, specialty, keyword...":"Nom, spécialité, mot-clé..."}/><select name="specialty"><option value="">{en?"All specialties":"Toutes les spécialités"}</option>{medicalSpecialties.map(s=><option key={s.fr}>{en?s.en:s.fr}</option>)}</select><select name="availability"><option>{en?"Next 24 hours":"Prochaines 24h"}</option><option>{en?"This week":"Cette semaine"}</option></select><select name="mode"><option>{en?"All modes":"Tous les modes"}</option><option>{en?"Video consultation":"Visioconférence"}</option><option>{en?"In office":"Cabinet"}</option></select><select name="language"><option>{en?"All languages":"Toutes les langues"}</option><option>Français</option><option>English</option></select><button className="btn-primary">{en?"Search":"Rechercher"}</button></form>
<div className="mt-6 flex gap-3 overflow-x-auto pb-2">{medicalSpecialties.map(s=><span key={s.fr} className="whitespace-nowrap rounded-2xl border bg-white px-5 py-4 text-sm font-bold">{en?s.en:s.fr}</span>)}</div><div className="mt-6 rounded-2xl bg-mint p-4 text-center font-bold text-forest">ⓘ {en?"Our specialists are qualified and legally licensed healthcare professionals.":"Nos spécialistes sont des professionnels de santé qualifiés et légalement habilités."}</div>
<h2 className="mt-10 text-xl font-black">{specialists.length} {en?"specialists available":"spécialistes disponibles"}</h2><div className="mt-5 grid gap-4">{specialists.length?specialists.map((s:any)=><article key={s.id} className="grid items-center gap-5 rounded-3xl border bg-white p-5 shadow-sm md:grid-cols-[100px_1fr_190px_180px]"><div className="relative h-24 w-24 overflow-hidden rounded-2xl bg-mint">{s.photo_url?<Image src={s.photo_url} alt={s.full_name} fill className="object-cover"/>:<span className="grid h-full place-items-center text-3xl font-black text-leaf">{s.sex==="female"?"♀":"♂"}</span>}</div><div><h3 className="text-xl font-black">Dr. {s.full_name}</h3><p className="mt-1 text-sm font-bold text-leaf">{s.specialty}</p><p className="mt-2 text-sm text-slate-500">{s.years_experience} {en?"years of experience":"ans d'expérience"} · {s.city}, {s.country}</p></div><div><small>{en?"Next available":"Prochaine disponibilité"}</small><b className="mt-1 block text-leaf">{s.next_availability?new Date(s.next_availability).toLocaleString(en?"en-GB":"fr-FR"):(en?"On request":"Sur demande")}</b></div><div className="grid gap-2"><Link className="btn-primary justify-center" href={localizedPath(locale,`/consultations-medicales/specialistes/${s.id}`)}>{en?"View profile":"Voir le profil"}</Link><Link className="btn-secondary justify-center" href={localizedPath(locale,`/connexion?next=/espace-client/consultations-medicales&specialist=${s.id}`)}>{en?"Book":"Prendre RDV"}</Link></div></article>):<div className="rounded-3xl border bg-white p-14 text-center text-slate-500">{en?"Approved specialists will appear here. Contact us so we can guide you.":"Les spécialistes validés apparaîtront ici. Contactez-nous pour être orienté."}</div>}</div></div></main>}
