"use client";
import { FormEvent, useState } from "react";
import { createStudioId } from "@/lib/instructor-storage";
import type { StudioCourse } from "@/types/instructor-studio";
export function StudioApplicationExerciseBuilder({course,onChange}:{course:StudioCourse;onChange:(patch:Partial<StudioCourse>)=>void}){
 const [title,setTitle]=useState(""),[instructions,setInstructions]=useState(""),[resourceUrl,setResourceUrl]=useState(""),[attempts,setAttempts]=useState("3"),exercises=course.applicationExercises??[];
 function add(e:FormEvent){e.preventDefault();if(!title.trim()||!instructions.trim())return;onChange({applicationExercises:[...exercises,{id:createStudioId("exercise"),courseSlug:course.slug,title:title.trim(),instructions:instructions.trim(),resourceUrl:resourceUrl.trim()||undefined,maxAttempts:attempts==="unlimited"?null:Math.max(1,Number(attempts)||1),createdAt:new Date().toISOString()}]});setTitle("");setInstructions("");setResourceUrl("");}
 return <section className="rounded-[24px] border border-green-100 bg-white p-6"><h2 className="text-2xl font-extrabold text-[#063D2E]">Exercices d&apos;application / Application assignments</h2><form onSubmit={add} className="mt-5 grid gap-3 md:grid-cols-2"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre" className="h-12 rounded-xl border px-3"/><input value={resourceUrl} onChange={e=>setResourceUrl(e.target.value)} placeholder="Lien du fichier ou consigne" className="h-12 rounded-xl border px-3"/><textarea required value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Instructions" rows={4} className="rounded-xl border p-3 md:col-span-2"/><select value={attempts} onChange={e=>setAttempts(e.target.value)} className="h-12 rounded-xl border px-3"><option value="1">1 tentative</option><option value="2">2 tentatives</option><option value="3">3 tentatives</option><option value="unlimited">Illimite / Unlimited</option></select><button className="rounded-full bg-[#0B5D3B] px-5 font-bold text-white">Ajouter</button></form><div className="mt-5 space-y-3">{exercises.map(x=><article key={x.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><b>{x.title}</b><p className="mt-1 text-sm text-slate-600">{x.instructions}</p><p className="mt-1 text-xs">Tentatives: {x.maxAttempts??"illimitees"}</p></div><button onClick={()=>onChange({applicationExercises:exercises.filter(e=>e.id!==x.id)})} className="text-red-600">Supprimer</button></div></article>)}</div></section>;
}
