import {indicatorRegistry,referenceById} from "./indicator-registry";
import type {AlertLevel,ClinicalMeaning,ConfidenceLevel,DataQuality,Direction,HealthReportModel,IndicatorAnalysis,IndicatorDefinition,ReportAlert,ReportLocale,ReportProfile,ReportRow,ReportType,Trend,ValidatedPoint,ValidationIssue} from "./types";
export const ENGINE_VERSION="health-report-engine-v2.1.0";
const n=(value:unknown)=>value===null||value===undefined||value===""?null:Number(value);
const round=(value:number,digits=2)=>Number(value.toFixed(digits));
export const formatIndicatorValue=(value:number|null,indicatorId:string,locale:ReportLocale="fr")=>{if(value===null)return locale==="fr"?"Non renseigné":"Not recorded";const digits=indicatorId.startsWith("questionnaire.")?1:indicatorId==="anthropometry.weight"||indicatorId==="anthropometry.bmi"?1:0;return new Intl.NumberFormat(locale==="fr"?"fr-FR":"en-GB",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)};
const validDate=(value:unknown)=>typeof value==="string"&&!Number.isNaN(+new Date(value));
export function resolveReportProfile(profile:ReportRow):ReportProfile{
 if(profile.pregnant===true||profile.pregnancy_status==="pregnant")return "pregnancy";
 const birth=validDate(profile.birth_date)?new Date(String(profile.birth_date)):null;
 if(!birth)return "general";
 const age=(Date.now()-+birth)/31557600000;
 return age<12?"child":age<18?"adolescent":"adult";
}
function rowsFor(def:IndicatorDefinition,data:Record<string,ReportRow[]>){return data[def.source]||[]}
function pointsFor(def:IndicatorDefinition,data:Record<string,ReportRow[]>,issues:ValidationIssue[]):ValidatedPoint[]{
 const seen=new Set<string>(),result:ValidatedPoint[]=[];
 for(const row of rowsFor(def,data)){
  const raw=n(row[def.field]); if(raw===null)continue;
  if(!Number.isFinite(raw)){issues.push({severity:"critical",code:"invalid_number",indicatorId:def.id,message:`${def.id}: valeur non numérique.`});continue}
  if(!validDate(row[def.dateField])){issues.push({severity:"critical",code:"invalid_date",indicatorId:def.id,message:`${def.id}: date invalide.`});continue}
  if(def.plausible&&(raw<def.plausible.min||raw>def.plausible.max)){issues.push({severity:"warning",code:"implausible_value",indicatorId:def.id,message:`${def.id}: valeur ${raw} hors plage de plausibilité.`});continue}
  const value=round(def.transform?def.transform(raw):raw,2),date=new Date(String(row[def.dateField])).toISOString();
  const key=`${date}|${value}`;if(seen.has(key)){issues.push({severity:"warning",code:"duplicate",indicatorId:def.id,message:`${def.id}: doublon ignoré.`});continue}seen.add(key);
  result.push({date,value,sourceId:typeof row.id==="string"?row.id:undefined});
 }
 return result.sort((a,b)=>+new Date(a.date)-+new Date(b.date));
}
function confidence(points:ValidatedPoint[]):ConfidenceLevel{
 if(points.length<2)return "insufficient";const days=(+new Date(points.at(-1)!.date)-+new Date(points[0].date))/86400000;
 if(points.length>=6&&days>=60)return "high";if(points.length>=4&&days>=28)return "moderate";return "low";
}
function direction(delta:number|null,tolerance:number):Direction{return delta===null?"initial":Math.abs(delta)<=tolerance?"stable":delta>0?"up":"down"}
function trend(points:ValidatedPoint[],dir:Direction):Trend{
 if(points.length===0)return "insufficient";if(points.length===1)return "initial";if(points.length===2)return "variation_only";
 const days=(+new Date(points.at(-1)!.date)-+new Date(points[0].date))/86400000;if(days<14)return "insufficient";
 const changes=points.slice(1).map((p,i)=>p.value-points[i].value),same=changes.filter(x=>x===0||Math.sign(x)===Math.sign(changes.reduce((a,b)=>a+b,0))).length/changes.length;
 if(same<.67)return "stable";return dir==="up"?"increasing":dir==="down"?"decreasing":"stable";
}
function meaning(def:IndicatorDefinition,dir:Direction,current:number|null,goals:ReportRow[]):ClinicalMeaning{
 if(current===null)return "insufficient_data";
 if(def.type==="questionnaire")return dir==="up"?"favorable":dir==="down"?"unfavorable":"neutral";
 if(def.id==="anthropometry.weight"){
  const goal=goals.find(g=>String(g.indicator_id||g.unit||"").toLowerCase().includes("weight")||String(g.label||"").toLowerCase().includes("poids"));
  if(!goal)return "contextual";const target=n(goal.target_value);if(target===null)return "contextual";
  return Math.abs(current-target)<Math.abs((n(goal.baseline_value)??current)-target)?"favorable":"contextual";
 }
 return "contextual";
}
function statusFor(def:IndicatorDefinition,current:number|null):AlertLevel|"normal"|"not_measured"{
 if(current===null)return "not_measured";
 if(def.id==="anthropometry.bmi")return current<18.5||current>=30?"watch":"normal";
 if(def.id==="questionnaire.nutrition"||def.id==="questionnaire.activity"||def.id==="questionnaire.lifestyle")return current<1.6?"watch":"normal";
 if(def.id==="cardiovascular.systolic")return current>=180?"critical":current>=140?"warning":"normal";
 if(def.id==="cardiovascular.diastolic")return current>=120?"critical":current>=90?"warning":"normal";
 return "normal";
}
const scoreLabel=(value:number,locale:ReportLocale)=>{const labels=locale==="fr"?["Très faible","Faible","Modéré","Bon","Excellent"]:["Very low","Low","Moderate","Good","Excellent"];return labels[Math.max(0,Math.min(4,Math.round(value)))]};
function wording(def:IndicatorDefinition,current:number|null,previous:number|null,baseline:number|null,dir:Direction,tr:Trend,status:IndicatorAnalysis["status"],locale:ReportLocale,count:number){
 const fr=locale==="fr",value=formatIndicatorValue(current,def.id,locale),unit=def.unit?` ${def.unit}`:"";
 if(current===null)return{interpretation:fr?"Donnée non disponible; aucune interprétation n’est produite.":"Data unavailable; no interpretation is produced.",action:fr?"Renseigner cette mesure uniquement si elle est prévue ou cliniquement pertinente.":"Record this measurement only when expected or clinically relevant."};
 const dPrev=previous===null?null:round(current-previous,def.type==="questionnaire"?1:1),dBase=baseline===null||count<2?null:round(current-baseline,def.type==="questionnaire"?1:1);
 const delta=(d:number|null)=>d===null?"—":`${d>0?"+":""}${formatIndicatorValue(d,def.id,locale)}${unit}`;
 if(def.type==="questionnaire"){
  const concept=def.id==="questionnaire.nutrition"?(fr?"Score nutritionnel NutVita fondé sur le questionnaire global.":"NutVita nutrition score based on the overall questionnaire."):def.id==="questionnaire.activity"?(fr?"Score global d’activité physique.":"Overall physical activity score."):(fr?"Score global des habitudes de vie.":"Overall lifestyle score.");
  const evolution=tr==="initial"?(fr?"Évaluation initiale; aucune tendance n’est encore établie.":"Initial assessment; no trend is established yet."):tr==="variation_only"?(fr?`Variation depuis la mesure précédente : ${delta(dPrev)}; deux mesures ne suffisent pas à établir une tendance.`:`Change since previous assessment: ${delta(dPrev)}; two assessments do not establish a trend.`):tr==="increasing"?(fr?`Amélioration longitudinale observée sur ${count} évaluations.`:`Longitudinal improvement observed across ${count} assessments.`):tr==="decreasing"?(fr?`Baisse longitudinale observée sur ${count} évaluations.`:`Longitudinal decrease observed across ${count} assessments.`):(fr?`Score globalement stable sur ${count} évaluations.`:`Score broadly stable across ${count} assessments.`);
  return{interpretation:`${scoreLabel(current,locale)} (${value}/4). ${concept} ${evolution}`,action:status==="watch"?(fr?"Choisir un axe d’amélioration réaliste pour le prochain cycle.":"Choose one realistic improvement area for the next cycle."):(fr?"Maintenir les acquis et réévaluer au prochain cycle.":"Maintain progress and reassess next cycle.")};
 }
 if(def.id==="anthropometry.weight")return{interpretation:count===1?(fr?`Le poids enregistré est de ${value}${unit}. Une mesure isolée ne permet pas d’établir une évolution.`:`Recorded weight is ${value}${unit}. A single measurement cannot establish a trend.`):(fr?`Le poids est ${tr==="stable"?"pratiquement stable":tr==="increasing"?"orienté à la hausse":tr==="decreasing"?"orienté à la baisse":"variable"} : ${delta(dBase)} depuis le début du suivi et ${delta(dPrev)} depuis la mesure précédente. ${count<3?"Cette variation ne constitue pas encore une tendance robuste.":"L’interprétation dépend de l’objectif pondéral convenu."}`:`Weight is ${tr==="stable"?"broadly stable":tr==="increasing"?"trending upward":tr==="decreasing"?"trending downward":"variable"}: ${delta(dBase)} since baseline and ${delta(dPrev)} since the previous measurement. ${count<3?"This change is not yet a robust trend.":"Interpretation depends on the agreed weight goal."}`),action:fr?"Poursuivre des mesures dans des conditions comparables selon l’objectif convenu.":"Continue measurements under comparable conditions according to the agreed goal."};
 if(def.id==="anthropometry.bmi")return{interpretation:fr?`L’IMC actuel est de ${value} kg/m²${count>1?` (${delta(dBase)} depuis le début du suivi)`:""}. Il s’agit d’un indicateur de dépistage à interpréter avec le tour de taille, la composition corporelle et le contexte clinique.`:`Current BMI is ${value} kg/m²${count>1?` (${delta(dBase)} since baseline)`:""}. This screening indicator should be interpreted with waist circumference, body composition and clinical context.`,action:fr?"Compléter l’interprétation par les mesures contextuelles pertinentes.":"Complete interpretation with relevant contextual measurements."};
 if(def.id==="cardiovascular.pulse")return{interpretation:fr?`La fréquence cardiaque est de ${value} bpm${dPrev!==null?`, soit ${delta(dPrev)} depuis la mesure précédente`:""}${dBase!==null?` et ${delta(dBase)} depuis la mesure initiale`:""}. ${count===1?"Une valeur isolée ne permet pas de conclure à une tendance.":tr==="stable"?"L’ensemble apparaît globalement stable.":"La dernière variation et l’évolution globale doivent être distinguées."}`:`Heart rate is ${value} bpm${dPrev!==null?`, ${delta(dPrev)} since the previous measurement`:""}${dBase!==null?` and ${delta(dBase)} since baseline`:""}. ${count===1?"A single value cannot establish a trend.":tr==="stable"?"Overall, values appear broadly stable.":"The latest change and overall evolution should be considered separately."}`,action:fr?"Interpréter selon les conditions de repos, l’effort récent et le contexte clinique.":"Interpret according to resting conditions, recent exertion and clinical context."};
 if(def.id.startsWith("cardiovascular."))return{interpretation:fr?`La dernière valeur enregistrée est ${value}${unit}. Elle est comparée à la référence configurée; une mesure isolée ne constitue pas un diagnostic.`:`The latest recorded value is ${value}${unit}. It is compared with the configured reference; a single measurement is not diagnostic.`,action:fr?"Confirmer toute valeur inhabituelle par des mesures standardisées et un avis professionnel.":"Confirm unusual values with standardized measurements and professional review."};
 if(def.type==="biology")return{interpretation:fr?`${def.label.fr} : ${value}${unit}. ${count===1?"Valeur biologique isolée; aucune tendance ni conclusion clinique ne peut être établie sans unité, contexte de prélèvement et référence adaptés.":`Évolution fondée sur ${count} mesures; interprétation conditionnée par l’unité, le type de test et les conditions de prélèvement.`}`:`${def.label.en}: ${value}${unit}. ${count===1?"Isolated biological value; no trend or clinical conclusion can be established without the unit, sampling context and relevant reference.":`Evolution based on ${count} measurements; interpretation depends on unit, test type and sampling conditions.`}`,action:fr?"Vérifier l’unité, le contexte, la date et la référence avant toute décision.":"Verify unit, context, date and reference before any decision."};
 return{interpretation:tr==="initial"?(fr?`Première mesure enregistrée : ${value}${unit}; aucune tendance ne peut être conclue.`:`First recorded measurement: ${value}${unit}; no trend can be concluded.`):(fr?`Valeur actuelle : ${value}${unit}; ${delta(dPrev)} depuis la mesure précédente et ${delta(dBase)} depuis le début du suivi.`:`Current value: ${value}${unit}; ${delta(dPrev)} since the previous measurement and ${delta(dBase)} since baseline.`),action:fr?"Poursuivre des mesures comparables et contextualisées.":"Continue comparable, contextualized measurements."};
}
function chartDomain(def:IndicatorDefinition,points:ValidatedPoint[]):[number,number]|undefined{
 if(def.recommendedDomain)return def.recommendedDomain;if(!points.length)return undefined;const values=points.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),minimum=def.minimumRange||1,span=Math.max(max-min,minimum),middle=(max+min)/2;return[round(middle-span*.6,2),round(middle+span*.6,2)];
}
export function validateReportData(data:Record<string,ReportRow[]>,profile:ReportProfile){const issues:ValidationIssue[]=[];for(const def of indicatorRegistry.filter(x=>x.profiles.includes(profile)||profile==="general"))pointsFor(def,data,issues);return issues}
export function buildHealthReportModel(input:{profile:ReportRow;anthropometry:ReportRow[];biology:ReportRow[];food:ReportRow[];lifestyle:ReportRow[];goals?:ReportRow[];locale?:ReportLocale;reportType?:ReportType;generatedAt?:string}):HealthReportModel{
 const locale=input.locale||"fr",reportType=input.reportType||"professional",profile=resolveReportProfile(input.profile),goals=input.goals||[],data={anthropometry:input.anthropometry,biology:input.biology,food:input.food,lifestyle:input.lifestyle},issues:ValidationIssue[]=[];
 const indicators:IndicatorAnalysis[]=indicatorRegistry.filter(def=>def.profiles.includes(profile)||profile==="general").map(def=>{
  const points=pointsFor(def,data,issues),current=points.at(-1)?.value??null,previous=points.at(-2)?.value??null,baseline=points[0]?.value??null,deltaPrevious=current!==null&&previous!==null?round(current-previous):null,deltaBaseline=current!==null&&baseline!==null&&points.length>1?round(current-baseline):null;
  const tolerance=def.type==="questionnaire"?.05:Math.max((def.minimumRange||1)*.01,.01),dir=direction(deltaPrevious,tolerance),tr:Trend=def.isLongitudinallyRelevant(profile)?trend(points,dir):"insufficient",clinicalMeaning=meaning(def,dir,current,goals),status=statusFor(def,current),reference=def.referenceId?referenceById.get(def.referenceId):undefined,words=wording(def,current,previous,baseline,dir,tr,status,locale,points.length),conf=confidence(points);
  const requiredRaw=input.profile.expected_health_data??input.profile.required_health_indicators;
  const required=Array.isArray(requiredRaw)?requiredRaw.map(String):[];
  const expectedData=required.includes(def.id)||required.includes(def.field)||goals.some(g=>String(g.indicator_id||"")===def.id);
  const latestSource=[...rowsFor(def,data)].filter(row=>n(row[def.field])!==null).sort((a,b)=>+new Date(String(a[def.dateField]))-+new Date(String(b[def.dateField]))).at(-1);
  const rawUnit=latestSource?.[`${def.field}_unit`]??latestSource?.measurement_unit??latestSource?.unit;
  const measuredUnit=typeof rawUnit==="string"&&rawUnit.trim()?rawUnit.trim():(def.unit||undefined);
  const rawContext=latestSource?.glucose_type??latestSource?.test_type??latestSource?.fasting_status??latestSource?.measurement_context;
  const measurementContext=typeof rawContext==="string"&&rawContext.trim()?rawContext.trim():undefined;
  const calculation=`current=${current??"N/A"}; previous=${previous??"N/A"}; baseline=${baseline??"N/A"}; deltaPrevious=${deltaPrevious??"N/A"}; deltaBaseline=${deltaBaseline??"N/A"}`;
  return{indicatorId:def.id,label:def.label[locale],type:def.type,unit:measuredUnit||"",contentType:def.contentType,points,currentValue:current,previousValue:previous,baselineValue:baseline,deltaPrevious,deltaBaseline,percentChangePrevious:deltaPrevious!==null&&previous?round(deltaPrevious/Math.abs(previous)*100,1):null,percentChangeBaseline:deltaBaseline!==null&&baseline?round(deltaBaseline/Math.abs(baseline)*100,1):null,direction:dir,clinicalMeaning,trend:tr,confidenceLevel:conf,status,referenceId:def.referenceId,referenceText:reference?.summary[locale],interpretation:words.interpretation,recommendedAction:words.action,missingData:current===null?[def.label[locale]]:[],expectedData,clinicallyRelevantMissingData:current===null&&expectedData,measurementContext,measuredUnit,chart:{enabled:def.isLongitudinallyRelevant(profile)&&points.length>=2,type:def.chartType,domain:chartDomain(def,points)},trace:{indicatorId:def.id,conclusion:words.interpretation,sourceValues:points.map(p=>p.value),dates:points.map(p=>p.date),currentValue:current,previousValue:previous,baselineValue:baseline,referenceId:def.referenceId,ruleId:def.interpretationRule,reason:`direction=${dir}; trend=${tr}; clinicalMeaning=${clinicalMeaning}`,calculation,confidenceLevel:conf}} satisfies IndicatorAnalysis;
 });
 const alerts:ReportAlert[]=indicators.filter(i=>["watch","warning","critical"].includes(i.status)).map(i=>({level:i.status as AlertLevel,indicatorId:i.indicatorId,value:i.currentValue,referenceId:i.referenceId,reason:i.interpretation,recommendedAction:i.recommendedAction,requiresProfessionalReview:i.status==="warning"||i.status==="critical"}));
 const usable=indicators.filter(i=>i.currentValue!==null),missing=indicators.filter(i=>i.currentValue===null),quality:DataQuality=issues.some(i=>i.severity==="critical")||usable.length<3?"limited":issues.length||missing.length>usable.length?"moderate":"good";
 const summaryEligible=(i:IndicatorAnalysis)=>!(profile==="adult"&&i.indicatorId==="anthropometry.height");
 const improvingItems=indicators.filter(i=>summaryEligible(i)&&i.clinicalMeaning==="favorable"&&(i.trend==="increasing"||i.trend==="decreasing")&&i.confidenceLevel!=="insufficient"),stableItems=indicators.filter(i=>summaryEligible(i)&&i.trend==="stable"&&i.currentValue!==null),attentionItems=alerts.map(a=>indicators.find(i=>i.indicatorId===a.indicatorId)).filter((i):i is IndicatorAnalysis=>Boolean(i&&summaryEligible(i))),missingItems=missing.filter(i=>i.clinicallyRelevantMissingData);
 const improving=improvingItems.map(i=>i.label).slice(0,3),stable=stableItems.map(i=>i.label).slice(0,3),attention=attentionItems.map(i=>i.label).slice(0,3),missingLabels=missingItems.map(i=>i.label).slice(0,3);
 const claims=[...improvingItems,...stableItems,...attentionItems].slice(0,9).map(i=>i.trace);
 const dates=Object.values(data).flat().flatMap(row=>[row.measured_at,row.assessment_date,row.entry_date]).filter(validDate).map(String).sort();
 const model:HealthReportModel={engineVersion:ENGINE_VERSION,reportType,locale,profile,generatedAt:input.generatedAt||new Date().toISOString(),period:{start:dates[0]?.slice(0,10)||new Date().toISOString().slice(0,10),end:dates.at(-1)?.slice(0,10)||new Date().toISOString().slice(0,10)},indicators,alerts,validationIssues:issues,dataQuality:quality,essentialSummary:{globalState:alerts.some(a=>a.level==="critical")?(locale==="fr"?"Attention requise":"Attention required"):alerts.length?(locale==="fr"?"À surveiller":"Requires monitoring"):improving.length?(locale==="fr"?"En amélioration":"Improving"):(locale==="fr"?"Globalement stable":"Globally stable"),improving,stable,attention,missing:missingLabels,priorities:[...attention,...missingLabels].slice(0,3),claims},traces:indicators.map(i=>i.trace),sourceSnapshot:{counts:{anthropometry:input.anthropometry.length,biology:input.biology.length,food:input.food.length,lifestyle:input.lifestyle.length},goals},previousGoals:goals.filter(g=>["achieved","partially_achieved","not_achieved","not_assessed","postponed"].includes(String(g.status))),nextGoals:goals.filter(g=>["active","todo","in_progress"].includes(String(g.status)))};
 return model;
}
export function validateFinalReport(model:HealthReportModel):ValidationIssue[]{const issues=[...model.validationIssues];if(/\[(watch|warning|critical|urgent|incomplete)\]/i.test(JSON.stringify(model)))issues.push({severity:"critical",code:"internal_code_visible",message:"Code interne visible dans le contenu final."});for(const item of model.indicators){if(!indicatorRegistry.some(def=>def.id===item.indicatorId))issues.push({severity:"critical",code:"unknown_indicator",indicatorId:item.indicatorId,message:"Indicateur absent du registre strict."});if(item.currentValue!==null&&!Number.isFinite(item.currentValue))issues.push({severity:"critical",code:"non_finite",indicatorId:item.indicatorId,message:"Valeur finale non finie."});if(/\[(watch|critical|urgent|incomplete)\]/i.test(item.interpretation))issues.push({severity:"critical",code:"internal_code_visible",indicatorId:item.indicatorId,message:"Code interne visible dans le contenu final."});if(!item.trace.sourceValues.length&&item.currentValue!==null)issues.push({severity:"critical",code:"missing_trace",indicatorId:item.indicatorId,message:"Interprétation sans source traçable."});}return issues}
export function assertFinalReport(model:HealthReportModel){const critical=validateFinalReport(model).filter(i=>i.severity==="critical");if(critical.length)throw new Error(`Rapport bloqué par la validation finale: ${critical.map(i=>i.code).join(", ")}`);return model}