import type {IndicatorDefinition,ReferenceDefinition,ReportProfile} from "./types";
const all:ReportProfile[]=["adult","adolescent","child","pregnancy","general"];
const adult:ReportProfile[]=["adult","pregnancy","general"];
export const reportReferences:ReferenceDefinition[]=[
 {id:"bmi-adult-screening-v1",organization:"NutVitaGlobalis",guideline:"Adult BMI screening categories",version:"1.0",year:2026,population:adult,indicatorId:"anthropometry.bmi",validFrom:"2026-01-01",summary:{fr:"Catégories de dépistage adulte; interprétation contextuelle requise.",en:"Adult screening categories; contextual interpretation required."}},
 {id:"wellness-score-v2",organization:"NutVitaGlobalis",guideline:"Wellness questionnaire scoring",version:"2.0",year:2026,population:all,indicatorId:"questionnaire.nutrition",validFrom:"2026-01-01",summary:{fr:"Score catégoriel NutVita de 0 à 4.",en:"NutVita categorical score from 0 to 4."}},
 {id:"blood-pressure-config-v1",organization:"NutVitaGlobalis",guideline:"Configured blood-pressure vigilance rules",version:"1.0",year:2026,population:adult,indicatorId:"cardiovascular.blood_pressure",validFrom:"2026-01-01",summary:{fr:"Seuils de vigilance configurés; une mesure isolée ne constitue pas un diagnostic.",en:"Configured vigilance thresholds; one measurement is not diagnostic."}},
];
const d=(value:IndicatorDefinition)=>value;
export const indicatorRegistry:IndicatorDefinition[]=[
 d({id:"anthropometry.weight",type:"anthropometry",source:"anthropometry",field:"weight_kg",label:{fr:"Poids",en:"Weight"},unit:"kg",dateField:"measured_at",contentType:"measured",profiles:all,interpretationRule:"weight_contextual",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:20,max:350},minimumRange:5}),
 d({id:"anthropometry.height",type:"anthropometry",source:"anthropometry",field:"height_cm",label:{fr:"Taille",en:"Height"},unit:"cm",dateField:"measured_at",contentType:"measured",profiles:all,interpretationRule:"height_context",chartType:"line",isLongitudinallyRelevant:p=>p==="child"||p==="adolescent",plausible:{min:40,max:230},minimumRange:10}),
 d({id:"anthropometry.bmi",type:"anthropometry",source:"anthropometry",field:"bmi",label:{fr:"IMC",en:"BMI"},unit:"kg/m²",dateField:"measured_at",contentType:"calculated",profiles:adult,referenceId:"bmi-adult-screening-v1",interpretationRule:"bmi_adult",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:10,max:80},recommendedDomain:[15,45],minimumRange:10}),
 d({id:"anthropometry.waist",type:"anthropometry",source:"anthropometry",field:"waist_cm",label:{fr:"Tour de taille",en:"Waist circumference"},unit:"cm",dateField:"measured_at",contentType:"measured",profiles:adult,interpretationRule:"waist_context",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:35,max:250},minimumRange:10}),
 d({id:"anthropometry.body_fat",type:"anthropometry",source:"anthropometry",field:"body_fat_percent",label:{fr:"Masse grasse",en:"Body fat"},unit:"%",dateField:"measured_at",contentType:"measured",profiles:adult,interpretationRule:"body_composition_context",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:2,max:75},recommendedDomain:[0,60],minimumRange:10}),
 d({id:"biology.glucose",type:"biology",source:"biology",field:"glucose",label:{fr:"Glycémie",en:"Blood glucose"},unit:"",dateField:"measured_at",contentType:"measured",profiles:all,interpretationRule:"glucose_unit_context",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:.2,max:600},minimumRange:1}),
 d({id:"biology.hba1c",type:"biology",source:"biology",field:"hba1c",label:{fr:"HbA1c",en:"HbA1c"},unit:"%",dateField:"measured_at",contentType:"measured",profiles:adult,interpretationRule:"hba1c_context",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:2,max:25},recommendedDomain:[3,15],minimumRange:2}),
 d({id:"cardiovascular.systolic",type:"cardiovascular",source:"biology",field:"systolic_pressure",label:{fr:"Pression systolique",en:"Systolic pressure"},unit:"mmHg",dateField:"measured_at",contentType:"measured",profiles:adult,referenceId:"blood-pressure-config-v1",interpretationRule:"blood_pressure_pair",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:60,max:250},recommendedDomain:[70,200],minimumRange:40}),
 d({id:"cardiovascular.diastolic",type:"cardiovascular",source:"biology",field:"diastolic_pressure",label:{fr:"Pression diastolique",en:"Diastolic pressure"},unit:"mmHg",dateField:"measured_at",contentType:"measured",profiles:adult,referenceId:"blood-pressure-config-v1",interpretationRule:"blood_pressure_pair",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:35,max:150},recommendedDomain:[40,130],minimumRange:30}),
 d({id:"cardiovascular.pulse",type:"cardiovascular",source:"biology",field:"pulse_bpm",label:{fr:"Fréquence cardiaque",en:"Heart rate"},unit:"bpm",dateField:"measured_at",contentType:"measured",profiles:adult,interpretationRule:"pulse_context",chartType:"line",isLongitudinallyRelevant:()=>true,plausible:{min:25,max:240},recommendedDomain:[40,180],minimumRange:30}),
 d({id:"questionnaire.nutrition",type:"questionnaire",source:"lifestyle",field:"nutrition_score",label:{fr:"Score nutritionnel NutVita",en:"NutVita nutrition score"},unit:"/4",dateField:"assessment_date",contentType:"calculated",profiles:all,referenceId:"wellness-score-v2",interpretationRule:"wellness_score",chartType:"categorical",isLongitudinallyRelevant:()=>true,plausible:{min:0,max:100},recommendedDomain:[0,4],transform:v=>v/25}),
 d({id:"questionnaire.activity",type:"questionnaire",source:"lifestyle",field:"physical_activity_score",label:{fr:"Activité physique",en:"Physical activity"},unit:"/4",dateField:"assessment_date",contentType:"calculated",profiles:all,referenceId:"wellness-score-v2",interpretationRule:"wellness_score",chartType:"categorical",isLongitudinallyRelevant:()=>true,plausible:{min:0,max:100},recommendedDomain:[0,4],transform:v=>v/25}),
 d({id:"questionnaire.lifestyle",type:"questionnaire",source:"lifestyle",field:"lifestyle_score",label:{fr:"Mode de vie",en:"Lifestyle"},unit:"/4",dateField:"assessment_date",contentType:"calculated",profiles:all,referenceId:"wellness-score-v2",interpretationRule:"wellness_score",chartType:"categorical",isLongitudinallyRelevant:()=>true,plausible:{min:0,max:100},recommendedDomain:[0,4],transform:v=>v/25}),
];
export const indicatorById=new Map(indicatorRegistry.map(item=>[item.id,item]));
export const referenceById=new Map(reportReferences.map(item=>[item.id,item]));