import Image from "next/image";
import Link from "next/link";
import { ChartBarIcon, ClockIcon } from "@heroicons/react/24/outline";
import ManagedPageHero from "@/components/ManagedPageHero";
import ManagedPageSections from "@/components/ManagedPageSections";
import { getCurrentLocale } from "@/lib/i18n-server";
import { getFormations } from "@/lib/public-content";
import { getSitePage } from "@/lib/site-pages";
import { createClient } from "@/lib/supabase/server";
export const metadata={title:"Formations certifiantes"};
export default async function Formations(){const[formations,page,locale]=await Promise.all([getFormations(),getSitePage("formations"),getCurrentLocale()]),english=locale==="en",supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();let enrolled=new Set<string>();if(user){const{data}=await supabase.from("formation_enrollments").select("formation_id").eq("client_id",user.id).eq("status","active");enrolled=new Set((data||[]).map((x:any)=>x.formation_id))}return <>{page&&<><ManagedPageHero initial={page}/><ManagedPageSections initial={page}/></>}<section className="section"><div className="container-site"><p className="mb-8 max-w-3xl text-lg leading-8 text-slate-600">{english?"This page contains only currently offered certification courses. Sign in once, purchase the course if needed, then enter Academy directly.":"Cette page contient uniquement les formations certifiantes actuellement offertes. Connectez-vous une seule fois, achetez la formation si nécessaire, puis accédez directement à Academy."}</p><div className="grid gap-7 md:grid-cols-2">{formations.map((formation:any)=>{const active=enrolled.has(formation.id),checkout=`/checkout?type=formation&id=${formation.id}`,href=active?"/api/access/open?service=academy&role=student":user?checkout:`/connexion?redirect=${encodeURIComponent(checkout)}`;return <article className="card group" key={formation.id||formation.title}><div className="relative h-64"><Image src={formation.image} alt={formation.title} fill className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-5 top-5 rounded-full bg-white px-4 py-2 text-xs font-bold text-leaf">{english?"Certificate included":"Certificat inclus"}</span></div><div className="p-7"><h2 className="text-2xl font-black">{formation.title}</h2>{formation.shortDescription&&<p className="mt-3 text-sm leading-6 text-slate-500">{formation.shortDescription}</p>}<div className="my-5 flex flex-wrap gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><ClockIcon className="h-5 text-orange"/>{formation.duration}</span><span className="flex items-center gap-2"><ChartBarIcon className="h-5 text-orange"/>{formation.level}</span></div><div className="flex flex-wrap items-center justify-between gap-4 border-t pt-5"><p className="font-black text-forest">{active?(english?"Access active":"Accès actif"):formation.price}</p><Link href={href} className="btn-primary">{active?(english?"Open the course":"Ouvrir la formation"):user?(english?"Get access":"Accéder à la formation"):(english?"Sign in and continue":"Se connecter et continuer")}</Link></div></div></article>})}</div></div></section></>}
