import Image from "next/image";
import Link from "next/link";
import { Activity, ArrowRight, Award, BarChart3, BookOpen, CheckCircle2, ClipboardCheck, Cloud, Code2, Database, GraduationCap, HeartPulse, Laptop, PlayCircle, ShieldCheck, Star, TrendingUp, UserPlus, Users, Wheat, type LucideIcon } from "lucide-react";
import type { ManagedSection } from "@/data/site-pages";
import { getCurrentLocale } from "@/lib/i18n-server";
import { getFormations } from "@/lib/public-content";
import { getSitePage } from "@/lib/site-pages";
import { createClient } from "@/lib/supabase/server";

export const metadata={title:"Formations certifiantes | NutVitaGlobalis Academy"};

const benefitIcons=[GraduationCap,Laptop,Users,Award] as const;
const statIcons=[Users,BookOpen,Cloud,Award] as const;
const domainIcons=[HeartPulse,Activity,TrendingUp,Wheat,ClipboardCheck,Laptop,BarChart3,Database,Code2,ShieldCheck] as const;
const reasonIcons=[BookOpen,TrendingUp,Users,Cloud,Award] as const;
const stepIcons=[UserPlus,BookOpen,PlayCircle,ClipboardCheck,Award] as const;

export default async function Formations(){
 const [formations,page,locale]=await Promise.all([getFormations(),getSitePage("formations"),getCurrentLocale()]);
 const english=locale==="en";
 const t=(fr:string,en:string)=>english?en:fr;
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 const enrolled=new Set<string>();
 if(user){const {data}=await supabase.from("formation_enrollments").select("formation_id").eq("client_id",user.id).eq("status","active");(data||[]).forEach((row:any)=>enrolled.add(row.formation_id));}
 const sections=page?.sections||[];
 const benefitFallbacks:ManagedSection[]=[{title:t("Formations certifiées","Certified courses")},{title:t("100 % en ligne et accessibles","100% online and accessible")},{title:t("Formateurs experts","Expert instructors")},{title:t("Attestation et certification","Certificates and certification")}];
 const statFallbacks:ManagedSection[]=[{title:"1 200+",text:t("Apprenants formés","Learners trained")},{title:"80+",text:t("Formations disponibles","Courses available")},{title:"25+",text:t("Pays touchés","Countries reached")},{title:"95%",text:t("Taux de satisfaction","Satisfaction rate")}];
 const domainFallbacks:ManagedSection[]=[
  {title:t("Nutrition clinique & diététique","Clinical nutrition & dietetics"),text:t("Prise en charge des patients, nutrition thérapeutique et pathologies.","Patient care, therapeutic nutrition and clinical conditions.")},
  {title:t("Nutrition maternelle & infantile","Maternal & child nutrition"),text:t("Grossesse, allaitement, diversification, croissance et développement.","Pregnancy, breastfeeding, complementary feeding, growth and development.")},
  {title:t("Santé publique & épidémiologie","Public health & epidemiology"),text:t("Épidémiologie, prévention, promotion de la santé et surveillance.","Epidemiology, prevention, health promotion and surveillance.")},
  {title:t("Sécurité alimentaire & nutrition","Food security & nutrition"),text:t("Systèmes alimentaires, résilience et analyse de la sécurité alimentaire.","Food systems, resilience and food security analysis.")},
  {title:t("Enquêtes & collecte de données","Surveys & data collection"),text:t("SMART, SENS, KAP, ODK, Kobo, gestion et analyse des données.","SMART, SENS, KAP, ODK, Kobo, data management and analysis.")},
  {title:t("Gestion de projets humanitaires","Humanitarian project management"),text:t("Cycle de projet, suivi-évaluation, risques et bailleurs.","Project cycle, monitoring and evaluation, risks and donors.")},
  {title:t("Analyse des données & statistiques","Data analysis & statistics"),text:t("Excel avancé, SPSS, R, Python, Power BI et interprétation.","Advanced Excel, SPSS, R, Python, Power BI and interpretation.")},
  {title:t("Intelligence artificielle","Artificial intelligence"),text:t("IA appliquée à la santé, assistants, analyse prédictive et responsabilité.","AI for health, assistants, predictive analysis and responsibility.")},
  {title:t("Logiciels & outils numériques","Software & digital tools"),text:t("SIG, Power BI, DHIS2, RedCap, Epi Info et plateformes digitales.","GIS, Power BI, DHIS2, RedCap, Epi Info and digital platforms.")},
  {title:t("Éthique, qualité & conformité","Ethics, quality & compliance"),text:t("Éthique en recherche, protection des données, qualité et normes.","Research ethics, data protection, quality and standards.")},
 ];
 const reasonFallbacks:ManagedSection[]=[{title:t("Contenus d’experts","Expert content"),text:t("Développés par des professionnels reconnus.","Developed by recognized professionals.")},{title:t("Approche pratique","Practical approach"),text:t("Études de cas, exercices et projets concrets.","Case studies, exercises and practical projects.")},{title:t("Flexibilité totale","Complete flexibility"),text:t("Apprenez à votre rythme, où que vous soyez.","Learn at your own pace, wherever you are.")},{title:t("Certification reconnue","Recognized certification"),text:t("Attestations valorisées sur le marché.","Certificates valued in the marketplace.")},{title:t("Communauté active","Active community"),text:t("Échangez, collaborez et progressez ensemble.","Exchange, collaborate and progress together.")}];
 const stepFallbacks:ManagedSection[]=[{title:t("Inscrivez-vous","Register"),text:t("Créez votre compte en quelques minutes.","Create your account in minutes.")},{title:t("Choisissez votre formation","Choose your course"),text:t("Parcourez et sélectionnez le programme adapté.","Browse and select the right programme.")},{title:t("Apprenez à votre rythme","Learn at your pace"),text:t("Accédez aux cours, ressources et activités pratiques.","Access courses, resources and practical activities.")},{title:t("Évaluez vos compétences","Assess your skills"),text:t("Réalisez les évaluations et exercices.","Complete assessments and assignments.")},{title:t("Obtenez votre certificat","Earn your certificate"),text:t("Recevez votre attestation et valorisez votre profil.","Receive your credential and strengthen your profile.")}];
 const benefits=benefitFallbacks.map((fallback,index)=>sections[index]||fallback);
 const stats=statFallbacks.map((fallback,index)=>sections[index+4]||fallback);
 const domains=domainFallbacks.map((fallback,index)=>sections[index+8]||fallback);
 const reasons=reasonFallbacks.map((fallback,index)=>sections[index+18]||fallback);
 const steps=stepFallbacks.map((fallback,index)=>sections[index+23]||fallback);
 const academy=sections[28]||{title:"NutVita Globalis Academy",text:t("Développez vos compétences, renforcez votre impact et faites évoluer votre carrière.","Build your skills, increase your impact and advance your career."),items:[t("Parcours flexibles","Flexible pathways"),t("Contenus à jour","Up-to-date content"),t("Apprentissage pratique","Practical learning"),t("Communauté active","Active community")]};
 const rating=sections[29]||{title:"4,8/5",text:t("Avis apprenants","Learner reviews")};
 const heroImage=(page as any)?.hero_image_url||"/images/academy-hero-v1.png";
 const ctaImage=(page as any)?.cta_image_url||"/images/academy-cta-v1.png";
 const primaryLabel=page?.cta_label||t("Explorer les formations","Explore courses");
 const primaryUrl=page?.cta_url||"#formations";
 const secondaryLabel=(page as any)?.secondary_cta_label||t("Voir comment ça fonctionne","See how it works");
 const secondaryUrl=(page as any)?.secondary_cta_url||"#fonctionnement";
 return <main className="overflow-hidden bg-[#fbfcfa] text-forest">
  <section className="relative min-h-[720px] overflow-hidden border-b bg-white"><img src={heroImage} alt={t("Apprenante NutVitaGlobalis Academy en formation en ligne","NutVitaGlobalis Academy learner studying online")} className="absolute inset-0 h-full w-full object-cover object-[72%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/95 to-white/5"/><div className="container-site relative grid min-h-[720px] items-center gap-10 py-16 lg:grid-cols-[1fr_.9fr]"><div><span className="inline-flex items-center rounded-full bg-white px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-leaf shadow-soft"><span className="mr-2 h-2 w-2 rounded-full bg-leaf"/>{page?.eyebrow||t("Se former","Learn")}</span><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.03] md:text-7xl">{page?.title||t("Des compétences qui transforment les pratiques","Skills that transform practice")}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{page?.description||t("Des parcours flexibles, concrets et conçus par des professionnels de la nutrition et de la santé publique.","Flexible, practical pathways designed by nutrition and public health professionals.")}</p><div className="mt-8 grid max-w-2xl grid-cols-2 gap-5 sm:grid-cols-4">{benefits.map((item,index)=>{const Icon=benefitIcons[index];return <div key={item.title} className="border-r border-slate-200 pr-3 last:border-0"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-leaf"><Icon className="h-6"/></span><p className="mt-3 text-sm font-black leading-5">{item.title}</p></div>})}</div><div className="mt-9 flex flex-wrap gap-4"><Link href={primaryUrl} className="btn-primary min-w-52">{primaryLabel}<ArrowRight className="ml-2 h-4"/></Link><Link href={secondaryUrl} className="btn-secondary min-w-56">{secondaryLabel}<PlayCircle className="ml-2 h-5"/></Link></div></div><div className="relative hidden min-h-[560px] lg:block"><div className="absolute right-0 top-6 w-72 rounded-3xl bg-forest p-7 text-white shadow-2xl"><BookOpen className="h-9 text-mint"/><h2 className="mt-3 text-2xl font-black text-white">{academy.title}</h2><p className="mt-4 text-sm leading-6 text-white/75">{academy.text}</p><div className="mt-5 grid gap-3 text-sm">{(academy.items||[]).map(item=><p key={item} className="flex gap-2"><CheckCircle2 className="h-5 shrink-0 text-emerald-300"/>{item}</p>)}</div></div><div className="absolute bottom-8 right-12 rounded-3xl bg-white p-6 shadow-2xl"><p className="text-3xl font-black">{rating.title}</p><div className="mt-2 flex text-amber-400">{[1,2,3,4,5].map(x=><Star key={x} className="h-5 fill-current"/>)}</div><p className="mt-2 text-xs text-slate-500">{rating.text}</p></div></div></div></section>

  <section className="relative z-10 -mt-8"><div className="container-site"><div className="grid gap-5 rounded-[2rem] border bg-white/95 p-7 shadow-xl backdrop-blur md:grid-cols-4">{stats.map((item,index)=>{const Icon=statIcons[index];return <div key={item.title} className="flex items-center justify-center gap-4 border-slate-200 md:border-r md:last:border-0"><Icon className="h-10 text-leaf"/><div><p className="text-3xl font-black text-leaf">{item.title}</p><p className="mt-1 text-sm font-bold">{item.text}</p></div></div>})}</div></div></section>

  <section className="section"><div className="container-site"><h2 className="text-center text-4xl font-black">{t("Explorez nos domaines de formation","Explore our training fields")}</h2><p className="mx-auto mt-3 max-w-2xl text-center text-slate-600">{t("Des formations spécialisées pour répondre aux défis d’aujourd’hui et de demain.","Specialized courses addressing today’s and tomorrow’s challenges.")}</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{domains.map((item,index)=>{const Icon=domainIcons[index];return <article key={item.title} className="rounded-3xl border bg-white p-6 text-center shadow-soft transition hover:-translate-y-1 hover:border-leaf"><Icon className="mx-auto h-10 text-leaf"/><h3 className="mt-5 text-lg font-black leading-6">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{item.text}</p></article>})}</div><div className="mt-8 text-center"><Link href="#formations" className="inline-flex items-center font-black text-leaf">{t("Voir toutes les formations","View all courses")}<ArrowRight className="ml-2 h-4"/></Link></div></div></section>

  <section id="formations" className="section scroll-mt-24 bg-[#f3f8f5]"><div className="container-site"><h2 className="text-4xl font-black">{t("Formations actuellement disponibles","Courses currently available")}</h2><p className="mt-3 max-w-3xl text-slate-600">{t("Connectez-vous une seule fois, achetez la formation si nécessaire, puis accédez directement à NutVitaGlobalis Academy.","Sign in once, purchase the course if needed, then open NutVitaGlobalis Academy directly.")}</p><div className="mt-9 grid gap-7 md:grid-cols-2">{formations.map((formation:any)=>{const active=enrolled.has(formation.id),checkout=`/checkout?type=formation&id=${formation.id}`,href=active?"/api/access/open?service=academy&role=student":user?checkout:`/connexion?redirect=${encodeURIComponent(checkout)}`;return <article className="group overflow-hidden rounded-[2rem] border bg-white shadow-soft" key={formation.id||formation.title}><div className="relative h-64 overflow-hidden"><Image src={formation.image} alt={formation.title} fill className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-5 top-5 rounded-full bg-white px-4 py-2 text-xs font-black text-leaf">{t("Certificat inclus","Certificate included")}</span></div><div className="p-7"><h3 className="text-2xl font-black">{formation.title}</h3>{formation.shortDescription&&<p className="mt-3 text-sm leading-6 text-slate-500">{formation.shortDescription}</p>}<div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-t pt-5"><div><p className="text-sm text-slate-500">{formation.duration} · {formation.level}</p><p className="mt-1 font-black">{active?t("Accès actif","Access active"):formation.price}</p></div><Link href={href} className="btn-primary">{active?t("Ouvrir la formation","Open course"):user?t("Accéder à la formation","Get course access"):t("Se connecter et continuer","Sign in and continue")}</Link></div></div></article>})}{!formations.length&&<p className="rounded-3xl border bg-white p-8 text-slate-500">{t("Les prochaines formations seront publiées ici.","Upcoming courses will be published here.")}</p>}</div></div></section>

  <section className="section bg-white"><div className="container-site"><div className="rounded-[2rem] border bg-gradient-to-r from-[#f3f8f5] to-white p-8"><h2 className="text-center text-3xl font-black">{t("Pourquoi se former avec NutVitaGlobalis Academy ?","Why learn with NutVitaGlobalis Academy?")}</h2><div className="mt-8 grid gap-6 md:grid-cols-5">{reasons.map((item,index)=>{const Icon=reasonIcons[index];return <div key={item.title} className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-mint text-leaf"><Icon className="h-6"/></span><div><h3 className="font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{item.text}</p></div></div>})}</div></div></div></section>

  <section id="fonctionnement" className="section scroll-mt-24"><div className="container-site"><h2 className="text-center text-4xl font-black">{t("Comment ça fonctionne ?","How does it work?")}</h2><div className="mt-12 grid gap-7 md:grid-cols-5">{steps.map((item,index)=>{const Icon=stepIcons[index];return <article key={item.title} className="relative text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full border-2 border-emerald-100 bg-white text-leaf shadow-soft"><Icon className="h-9"/></span><span className="absolute left-[calc(50%+3rem)] top-10 hidden h-px w-[calc(100%-6rem)] border-t border-dashed border-emerald-300 md:block"/><p className="mt-5 text-sm font-black">{index+1}. {item.title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{item.text}</p></article>})}</div></div></section>

  <section className="pb-16"><div className="container-site"><div className="relative min-h-[390px] overflow-hidden rounded-[2.25rem] bg-forest text-white shadow-xl"><img src={ctaImage} alt="NutVitaGlobalis Academy" className="absolute inset-0 h-full w-full object-cover object-left"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-forest/45 to-forest"/><div className="relative z-10 flex min-h-[390px] items-center px-7 py-12 md:ml-[38%] md:px-12"><div className="max-w-2xl rounded-3xl bg-forest/65 p-6 backdrop-blur-sm md:bg-transparent md:p-0 md:backdrop-blur-none"><h2 className="text-4xl font-black text-white">{t("Investissez dans vos compétences, amplifiez votre impact.","Invest in your skills, amplify your impact.")}</h2><p className="mt-4 text-white/75">{t("Rejoignez des professionnels qui transforment leurs pratiques et améliorent durablement des vies.","Join professionals who transform their practice and improve lives sustainably.")}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={primaryUrl} className="btn-primary">{t("Commencer maintenant","Start now")}<ArrowRight className="ml-2 h-4"/></Link><Link href="/contact" className="inline-flex items-center rounded-full border border-white px-6 py-3 font-black text-white">{t("Parler à un conseiller","Talk to an advisor")}</Link></div></div></div></div></div></section>
 </main>;
}
