export type ApplicationExercise = {
  id: string;
  courseSlug: string;
  moduleIds: string[];
  title: string;
  instructions: string;
  resourceUrl?: string;
  resourceName?: string;
  caseUrlFr?: string;
  caseNameFr?: string;
  caseTextFr?: string;
  caseUrlEn?: string;
  caseNameEn?: string;
  caseTextEn?: string;
  referenceAnswerUrlFr?: string;
  referenceAnswerNameFr?: string;
  referenceAnswerFr?: string;
  referenceAnswerUrlEn?: string;
  referenceAnswerNameEn?: string;
  referenceAnswerEn?: string;
  requiredBeforeProgress?: boolean;
  maxAttempts: number | null;
  createdAt: string;
};

export type ExerciseSubmission = {
  id: string;
  exerciseId: string;
  courseSlug: string;
  studentUserId: string;
  responseText: string;
  attachmentUrl?: string;
  attachmentName?: string;
  submittedAt: string;
  attemptNumber: number;
  scorePercent?: number;
  aiScorePercent?: number;
  aiFeedbackFr?: string;
  aiFeedbackEn?: string;
  aiStrengths?: string[];
  aiImprovements?: string[];
  aiModel?: string;
  aiGradedAt?: string;
  aiGradingError?: string;
  gradeSource?: "ai" | "instructor_override";
  instructorOriginalAiScore?: number;
  feedback?: string;
  gradedBy?: string;
  gradedAt?: string;
};
