"use client";
import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import RegionalMealPlanner from "./RegionalMealPlanner";
type Row=Record<string,any>;
export default function ClientMenuPlannerWorkspace({partnerId,clients,initial}:{partnerId:string;clients:Row[];initial:Row[]}){
 const [rows,setRows]=useState(initial),[open,setOpen]=useState(false),[clientId,setClientId]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[query,setQuery]=useState(""),[message,setMessage]=useState("");
 const filtered=useMemo(()=>rows.filter(x=>[x.menu_code,x.title,x.client_profiles?.full_name,x.status].join(" ").toLowerCase().includes(query.toLowerCase())),[rows,query]);
 async function save(plan:string){if(!clientId||!from||!to){setMessage("Sélectionnez le client et la période avant de construire le menu.");return}const {data,error}=await createClient().from("client_menu_plans").insert({partner_id:partnerId,client_id:clientId,period_start:from,period_end:to,menu_payload:{text:plan},status:"draft"}).select("*,client_profiles(full_name)").single();if(error)setMessage(error.message);else{setRows(x=>[data,...x]);setOpen(false);setMessage("Menu enregistré dans le dossier du client.")}}
 async function update(row:Row,status:string){const {error}=await createClient().from("client_menu_plans").update({status,updated_at:new Date().toISOString()}).eq("id",row.id);if(error)setMessage(error.message);else setRows(x=>x.map(v=>v.id===row.id?{...v,status}:v))}
 async function remove(row:Row){if(!confirm("Supprimer ce menu du dossier nutritionniste et de l’espace client ?"))return;const {error}=await createClient().from("client_menu_plans").delete().eq("id",row.id);if(error)setMessage(error.message);else setRows(x=>x.filter(v=>v.id!==row.id))}
 return <div className="grid gap-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Menus et équivalents régionaux</h1><p className="mt-2 text-slate-500">Chaque plan est rattaché à un client et synchronisé avec son espace.</p></div><button onClick={()=>setOpen(true)} className="btn-primary">Planifier un menu</button></div>{message&&<p className="rounded-xl bg-mint p-3 font-bold text-leaf">{message}</p>}<input value={query} onChange={e=>setQuery(e.target.value)} className="admin-input max-w-xl" placeholder="Filtrer par ID, client, titre ou statut…"/>
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID menu","Période","Client","Généré le","Statut","Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="p-4 font-black text-forest">{x.menu_code}</td><td className="p-4">{new Date(x.period_start).toLocaleDateString("fr-FR")} → {new Date(x.period_end).toLocaleDateString("fr-FR")}</td><td className="p-4 font-bold">{x.client_profiles?.full_name}</td><td className="p-4">{new Date(x.generated_at).toLocaleDateString("fr-FR")}</td><td className="p-4">{x.status}</td><td className="p-4"><div className="flex gap-2">{x.status!=="validated"&&<button onClick={()=>update(x,"validated")} className="btn-primary px-3 py-2">Valider</button>}<button onClick={()=>alert(x.menu_payload?.text||"Aucun détail")} className="btn-secondary px-3 py-2">Détails</button><button onClick={()=>{setClientId(x.client_id);setFrom(x.period_start);setTo(x.period_end);setOpen(true)}} className="btn-secondary px-3 py-2">Ajuster</button><button onClick={()=>remove(x)} className="rounded-xl bg-rose-50 px-3 py-2 font-bold text-rose-700">Supprimer</button></div></td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-400">Aucun menu enregistré.</td></tr>}</tbody></table></div>
  {open&&<div className="fixed inset-0 z-[140] overflow-y-auto bg-slate-950/65 p-3"><section className="mx-auto my-5 max-w-7xl rounded-3xl bg-white p-5"><div className="mb-5 flex justify-between"><div><h2 className="text-2xl font-black">Planifier un menu</h2><p className="text-sm text-slate-500">Le client et la période sont obligatoires.</p></div><button onClick={()=>setOpen(false)} className="text-3xl">×</button></div><div className="mb-5 grid gap-3 md:grid-cols-3"><select value={clientId} onChange={e=>setClientId(e.target.value)} className="admin-input"><option value="">Sélectionner le client</option>{clients.map(x=><option key={x.id} value={x.id}>{x.client_number} — {x.full_name}</option>)}</select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="admin-input"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="admin-input"/></div><RegionalMealPlanner onUsePlan={save}/></section></div>}
 </div>
}
