import Link from "next/link";
import { CalendarDays, ClipboardList, Clock3, FileText, MessageCircle, Users, Video } from "lucide-react";
type Row = Record<string, any>;
export default function ConsultationProfessionalOverview({ consultations, clients, english }: { consultations: Row[]; clients: Row[]; english: boolean }) {
  const t = (fr: string, en: string) => english ? en : fr;
  const now = Date.now();
  const upcoming = consultations.filter((item) => +new Date(item.scheduled_at) >= now && !["cancelled", "completed"].includes(item.status));
  const metrics = [[t("Patients actifs", "Active patients"), clients.length, Users], [t("Rendez-vous à venir", "Upcoming appointments"), upcoming.length, CalendarDays], [t("Consultations réalisées", "Completed consultations"), consultations.filter((item) => item.status === "completed").length, ClipboardList], [t("Dossiers à finaliser", "Records to complete"), consultations.filter((item) => ["in_progress", "draft"].includes(item.status)).length, FileText]] as const;
  return <div className="mb-7 grid gap-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon]) => <article key={label} className="rounded-3xl border bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-mint text-leaf"><Icon className="h-6 w-6" /></span><b className="mt-3 block text-3xl text-forest">{value}</b><span className="text-sm text-slate-500">{label}</span></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-forest">{t("Programme de la journée", "Today’s schedule")}</h2><Link href="/partenaire/consultations" className="text-xs font-black text-leaf">{t("Voir tout", "View all")} →</Link></div><div className="mt-4 grid gap-3">{upcoming.slice(0, 4).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><span><b className="block text-sm text-forest">{item.client_profiles?.full_name || "Patient"}</b><small className="text-slate-500">{new Date(item.scheduled_at).toLocaleString(english ? "en-GB" : "fr-FR")} · {item.reason || t("Consultation nutritionnelle", "Nutrition consultation")}</small></span><span className="rounded-full bg-mint px-3 py-1 text-xs font-black text-leaf">{item.status}</span></div>)}{!upcoming.length && <p className="py-6 text-center text-sm text-slate-400">{t("Aucun rendez-vous à venir.", "No upcoming appointment.")}</p>}</div></article><article className="rounded-3xl bg-gradient-to-br from-[#073f32] to-[#00533f] p-5 text-white shadow-xl"><h2 className="text-xl font-black">{t("Actions rapides", "Quick actions")}</h2><div className="mt-4 grid gap-2"><Link href="/partenaire/clients" className="flex items-center gap-3 rounded-xl bg-white/10 p-3 text-sm font-black"><Users className="h-5" />{t("Ouvrir un dossier patient", "Open patient record")}</Link><Link href="/partenaire/appels" className="flex items-center gap-3 rounded-xl bg-white/10 p-3 text-sm font-black"><Video className="h-5" />{t("Démarrer une téléconsultation", "Start teleconsultation")}</Link><Link href="/partenaire/messages" className="flex items-center gap-3 rounded-xl bg-white/10 p-3 text-sm font-black"><MessageCircle className="h-5" />{t("Messagerie sécurisée", "Secure messaging")}</Link><Link href="/partenaire/salle-attente" className="flex items-center gap-3 rounded-xl bg-white/10 p-3 text-sm font-black"><Clock3 className="h-5" />{t("Salle d’attente", "Waiting room")}</Link></div></article></section></div>;
}
