"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Row=Record<string,any>;
const txt={created:"Client cr\u00e9\u00e9. Son dossier est imm\u00e9diatement disponible.",create:"Cr\u00e9er un client",age:"\u00c2ge",goals:"Objectifs vis\u00e9s",details:"D\u00e9tails",transfer:"Transf\u00e9rer",phone:"T\u00e9l\u00e9phone",select:"S\u00e9lectionner",state:"\u00c9tat / r\u00e9gion",duration:"Dur\u00e9e d\u2019acc\u00e8s (mois)"};
const age=(birth?:string)=>birth?Math.max(0,new Date().getFullYear()-new Date(birth).getFullYear()):"\u2014";
export default function PartnerClientManager({initial,partnerId:_,collaborators,freeOnsiteCreation=false}:{initial:Row[];partnerId:string;collaborators:Row[];freeOnsiteCreation?:boolean}){
 const [rows,setRows]=useState(initial),[open,setOpen]=useState(false),[transfer,setTransfer]=useState<Row|null>(null),[query,setQuery]=useState(""),[sex,setSex]=useState("all"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 const filtered=useMemo(()=>rows.filter(r=>[r.client_number,r.full_name,r.complaints,r.objectives].join(" ").toLowerCase().includes(query.toLowerCase())&&(sex==="all"||r.sex===sex)),[rows,query,sex]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const form=e.currentTarget,res=await fetch("/api/partner/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))}),data=await res.json();if(res.ok){setRows(x=>[{...data.client,waiting_request:null},...x]);setOpen(false);form.reset();setMessage(txt.created)}else setMessage(data.message||"Creation impossible.");setLoading(false)}
 async function transferClient(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!transfer)return;const id=String(new FormData(e.currentTarget).get("partner_id")||""),{error}=await createClient().from("client_profiles").update({assigned_partner_id:id,partner_assignment_status:"active"}).eq("id",transfer.id);if(error)setMessage(error.message);else{setRows(x=>x.filter(r=>r.id!==transfer.id));setTransfer(null);setMessage("Client transf\u00e9r\u00e9 au collaborateur.")}}
 return <section className="grid gap-5">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Mes clients</h1><p className="mt-2 text-slate-500">Registre unique des clients cr&eacute;&eacute;s ou attribu&eacute;s.</p></div>{freeOnsiteCreation&&<button onClick={()=>setOpen(true)} className="btn-primary">+ {txt.create}</button>}</header>
  {!freeOnsiteCreation&&<p className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-900">La cr&eacute;ation de clients sur site est d&eacute;sormais centralis&eacute;e : demandez &agrave; la r&eacute;ception de cr&eacute;er l&apos;achat depuis la facturation Maximus.</p>}
  {message&&<p className="rounded-xl bg-mint p-3 text-sm font-bold text-leaf">{message}</p>}
  <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_220px]"><input value={query} onChange={e=>setQuery(e.target.value)} className="admin-input" placeholder={"Rechercher par ID, nom, plainte ou objectif\u2026"}/><select value={sex} onChange={e=>setSex(e.target.value)} className="admin-input"><option value="all">Tous les sexes</option><option value="female">Femme</option><option value="male">Homme</option><option value="other">Autre</option></select></div>
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID client","ID demande","Nom du client",txt.age,"Sexe","Plaintes",txt.goals,"Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(r=><tr key={r.id}><td className="p-4 font-black text-forest">{r.client_number||"En generation"}</td><td className="p-4">{r.waiting_request?.request_code||"Creation directe"}</td><td className="p-4 font-bold">{r.full_name}</td><td className="p-4">{age(r.birth_date)}</td><td className="p-4">{r.sex||"\u2014"}</td><td className="max-w-[220px] p-4">{r.complaints||r.waiting_request?.reason||"\u2014"}</td><td className="max-w-[220px] p-4">{r.objectives||"\u2014"}</td><td className="p-4"><div className="flex flex-wrap gap-2 font-bold"><Link href={`/partenaire/clients/${r.id}/suivi`} className="btn-secondary px-3 py-2">{txt.details}</Link><Link href={`/partenaire/consultations?client=${r.id}`} className="btn-secondary px-3 py-2">Consultations</Link><button onClick={()=>setTransfer(r)} className="btn-secondary px-3 py-2">{txt.transfer}</button><Link href={`/partenaire/messages?client=${r.id}`} className="btn-primary px-3 py-2">Message</Link></div></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-400">Aucun client ne correspond aux filtres.</td></tr>}</tbody></table></div>
  {open&&<div className="fixed inset-0 z-[130] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={create} className="mx-auto my-8 grid max-w-3xl gap-4 rounded-3xl bg-white p-7 md:grid-cols-2"><div className="flex justify-between md:col-span-2"><div><h2 className="text-2xl font-black">{txt.create}</h2><p className="text-sm text-slate-500">Le dossier complet sera cr&eacute;&eacute; automatiquement.</p></div><button type="button" onClick={()=>setOpen(false)} className="text-3xl">&times;</button></div>
   <Field label="Nom complet" name="full_name" required/><Field label="Nom utilisateur" name="username"/><Field label="Email" name="email" type="email"/><Field label={txt.phone} name="phone"/><Field label="Date de naissance" name="birth_date" type="date"/><label className="grid gap-2 text-sm font-bold">Sexe<select name="sex" className="admin-input"><option value="">{txt.select}</option><option value="female">Femme</option><option value="male">Homme</option><option value="other">Autre</option></select></label><Field label="Ville" name="city"/><Field label={txt.state} name="state_region"/><Field label="Pays" name="country"/><Field label={txt.duration} name="period_months" type="number" defaultValue="3"/><label className="grid gap-2 text-sm font-bold md:col-span-2">Plaintes<textarea name="complaints" className="admin-input"/></label><label className="grid gap-2 text-sm font-bold md:col-span-2">{txt.goals}<textarea name="objectives" className="admin-input"/></label><button disabled={loading} className="btn-primary justify-self-start md:col-span-2">{loading?"Creation...":txt.create+" et son dossier"}</button>
  </form></div>}
  {transfer&&<div className="fixed inset-0 z-[130] bg-slate-950/60 p-4"><form onSubmit={transferClient} className="mx-auto mt-24 grid max-w-lg gap-4 rounded-3xl bg-white p-7"><div className="flex justify-between"><h2 className="text-xl font-black">{txt.transfer} {transfer.full_name}</h2><button type="button" onClick={()=>setTransfer(null)} className="text-3xl">&times;</button></div><select name="partner_id" required className="admin-input"><option value="">Choisir un collaborateur</option>{collaborators.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><button className="btn-primary justify-self-end">Confirmer le transfert</button></form></div>}
 </section>
}
function Field({label,name,type="text",required=false,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="grid gap-2 text-sm font-bold">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} className="admin-input"/></label>}
