"use client";
import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Row=Record<string,any>;
const date=(v?:string)=>v?new Date(v).toLocaleDateString("fr-FR"):"—";
export default function PartnerWaitingRoom({initial,partnerId}:{initial:Row[];partnerId:string}){
 const [rows,setRows]=useState(initial),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[history,setHistory]=useState<Row[]|null>(null),[message,setMessage]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>{const p=r.client_profiles||{},hay=[r.request_code,p.full_name,p.city,p.state_region,p.country,r.reason,r.status].join(" ").toLowerCase();return hay.includes(query.toLowerCase())&&(status==="all"||r.status===status)}),[rows,query,status]);
 async function take(row:Row){if(row.selected_partner_id&&row.selected_partner_id!==partnerId){setMessage("Cette demande est déjà attribuée.");return}const {error}=await createClient().from("consultation_waiting_room").update({selected_partner_id:partnerId,status:"active",partner_endorsed_at:new Date().toISOString()}).eq("id",row.id);if(error)setMessage(error.message);else setRows(x=>x.map(v=>v.id===row.id?{...v,selected_partner_id:partnerId,status:"active",assigned_at:new Date().toISOString()}:v))}
 async function showHistory(row:Row){const {data,error}=await createClient().from("consultation_assignment_history").select("*").eq("request_id",row.id).order("created_at",{ascending:false});if(error)setMessage(error.message);else setHistory(data||[])}
 return <section className="grid gap-4">
  <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_240px]"><input value={query} onChange={e=>setQuery(e.target.value)} className="admin-input" placeholder="Rechercher un client, une ville, un motif…" /><select value={status} onChange={e=>setStatus(e.target.value)} className="admin-input"><option value="all">Tous les statuts</option><option value="waiting">En attente</option><option value="assigned_pending_partner">Attribué</option><option value="active">Pris en charge</option></select></div>
  {message&&<p className="rounded-xl bg-mint p-3 text-sm font-bold text-leaf">{message}</p>}
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1500px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID demande","Date","Client","Sexe","Ville","État / région","Pays","Motif / plaintes","Statut","Nutritionniste traitant","Date d’attribution","Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(r=>{const p=r.client_profiles||{},mine=r.selected_partner_id===partnerId;return <tr key={r.id}>
   <td className="p-4 font-black text-forest">{r.request_code||r.id.slice(0,10).toUpperCase()}</td><td className="p-4">{date(r.created_at)}</td><td className="p-4 font-bold">{p.full_name||"Client"}</td><td className="p-4">{p.sex||"—"}</td><td className="p-4">{p.city||"—"}</td><td className="p-4">{p.state_region||"—"}</td><td className="p-4">{p.country||"—"}</td><td className="max-w-[260px] p-4">{r.reason||p.complaints||"—"}</td><td className="p-4"><span className="rounded-full bg-mint px-3 py-1 text-xs font-black text-leaf">{r.status}</span></td><td className="p-4">{r.selected_partner?.full_name||(mine?"Vous":"Non attribué")}</td><td className="p-4">{date(r.assigned_at)}</td><td className="p-4"><div className="flex gap-2">{(!r.selected_partner_id||mine)&&r.status!=="active"&&<button onClick={()=>take(r)} className="btn-primary px-3 py-2">Prendre le client</button>}<button onClick={()=>showHistory(r)} className="btn-secondary px-3 py-2">Historique</button></div></td>
  </tr>})}{!filtered.length&&<tr><td colSpan={12} className="p-10 text-center text-slate-400">Aucune demande ne correspond aux filtres.</td></tr>}</tbody></table></div>
  {history&&<div className="fixed inset-0 z-[120] overflow-y-auto bg-slate-950/60 p-4"><section className="mx-auto my-12 max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Historique des attributions</h2><button onClick={()=>setHistory(null)} className="text-2xl">×</button></div><div className="mt-5 grid gap-3">{history.map(h=><div key={h.id} className="rounded-xl bg-slate-50 p-4"><b>{h.action}</b><p className="text-sm text-slate-500">{date(h.created_at)}</p></div>)}{!history.length&&<p>Aucun historique disponible.</p>}</div></section></div>}
 </section>
}
