"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import ConsultationManager from "./ConsultationManager";
type Row=Record<string,any>;
const day=(v:string)=>new Date(v).toLocaleDateString("fr-FR"),time=(v:string)=>new Date(v).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});
export default function PartnerConsultationWorkspace({initial,clients,partnerId,locale}:{initial:Row[];clients:Row[];partnerId:string;locale:"fr"|"en"}){
 const en=locale==="en",[open,setOpen]=useState(false),[query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const today=new Date().toDateString();
 const schedule=initial.filter(x=>x.scheduled_at&&new Date(x.scheduled_at).toDateString()===today&&x.status!=="completed");
 const completed=useMemo(()=>initial.filter(x=>{const dt=new Date(x.completed_at||x.scheduled_at);return x.status==="completed"&&(!from||dt>=new Date(from))&&(!to||dt<=new Date(to+"T23:59:59"))&&[x.consultation_code,x.client_profiles?.full_name,x.reason].join(" ").toLowerCase().includes(query.toLowerCase())}),[initial,query,from,to]);
 return <div className="grid gap-6">
  <div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]">
   <section className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">{en?"Today's schedule":"Programme de la journée"}</h2><p className="text-sm text-slate-500">{schedule.length} consultation(s)</p></div><button onClick={()=>setOpen(true)} className="btn-primary">+ {en?"Start a consultation":"Initier une consultation"}</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">ID client</th><th className="p-3">Client</th><th className="p-3">Heure</th><th className="p-3">Motif</th></tr></thead><tbody className="divide-y">{schedule.map(x=><tr key={x.id}><td className="p-3 font-black text-forest">{x.client_profiles?.client_number||"—"}</td><td className="p-3">{x.client_profiles?.full_name||"Client"}</td><td className="p-3">{time(x.scheduled_at)}</td><td className="p-3">{x.reason||"—"}</td></tr>)}{!schedule.length&&<tr><td colSpan={4} className="p-8 text-center text-slate-400">Aucune consultation planifiée aujourd’hui.</td></tr>}</tbody></table></div></section>
   <section className="rounded-3xl bg-forest p-6 text-white"><h2 className="text-xl font-black text-white">Actions rapides</h2><div className="mt-5 grid gap-3"><Link href="/partenaire/clients" className="rounded-xl bg-white/10 p-4 font-bold hover:bg-white/20">Ouvrir un dossier patient</Link><Link href="/partenaire/appels?action=planifier" className="rounded-xl bg-white/10 p-4 font-bold hover:bg-white/20">Planifier une réunion ou un appel</Link><Link href="/partenaire/planificateur-menus" className="rounded-xl bg-white/10 p-4 font-bold hover:bg-white/20">Planifier un menu régional</Link></div></section>
  </div>
  <section className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-black">Registre des consultations réalisées</h2><p className="text-sm text-slate-500">Fiches finalisées et documents imprimables.</p></div><div className="flex flex-wrap gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} className="admin-input max-w-[260px]" placeholder="ID, client, motif…"/><input value={from} onChange={e=>setFrom(e.target.value)} type="date" className="admin-input w-auto"/><input value={to} onChange={e=>setTo(e.target.value)} type="date" className="admin-input w-auto"/></div></div>
   <div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["ID consultation","ID client","Nom du client","Date","Motif","Prochain rendez-vous","Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody className="divide-y">{completed.map(x=><tr key={x.id}><td className="p-4 font-black text-forest">{x.consultation_code||"NVGCO—"}</td><td className="p-4">{x.client_profiles?.client_number||"—"}</td><td className="p-4 font-bold">{x.client_profiles?.full_name||"Client"}</td><td className="p-4">{day(x.completed_at||x.scheduled_at)}</td><td className="p-4">{x.reason||"—"}</td><td className="p-4">{x.next_appointment_at?day(x.next_appointment_at):"—"}</td><td className="p-4"><div className="flex flex-wrap gap-2"><Link href={`/partenaire/consultations/${x.id}`} className="btn-secondary px-3 py-2">Fiche / imprimer</Link><Link href={`/partenaire/clients/${x.client_id}/suivi`} className="btn-secondary px-3 py-2">Dossier client</Link><Link href={`/partenaire/planificateur-menus?client=${x.client_id}`} className="btn-secondary px-3 py-2">Menus</Link></div></td></tr>)}{!completed.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-400">Aucune consultation finalisée ne correspond aux filtres.</td></tr>}</tbody></table></div>
  </section>
  {open&&<div className="fixed inset-0 z-[140] overflow-y-auto bg-slate-950/65 p-3"><section className="mx-auto my-5 max-w-7xl rounded-3xl bg-white p-4 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-2xl font-black">Nouvelle consultation</h2><p className="text-sm text-slate-500">Complétez les neuf sections puis générez la fiche.</p></div><button onClick={()=>setOpen(false)} className="text-3xl">×</button></div><ConsultationManager initial={initial} clients={clients} partnerId={partnerId} locale={locale}/></section></div>}
 </div>
}
