"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Row=Record<string,any>;
export default function PartnerClientHealthRecord({client,partnerId,consented,careConsent,collaborators=[],initialShares=[],data}:{client:Row;partnerId?:string;consented:boolean;careConsent?:boolean;collaborators?:Row[];initialShares?:Row[];data:Record<string,Row[]>}){
 const [message,setMessage]=useState(""),[shares,setShares]=useState(initialShares),[collaboratorId,setCollaboratorId]=useState("");
 async function report(){const response=await fetch("/api/partner/client-health-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_id:client.id})}),result=await response.json();if(!response.ok)setMessage(result.message);else openDocument(result.file_path)}
 async function openDocument(path:string){const {data:link,error}=await createClient().storage.from("document-vault").createSignedUrl(path,180);if(error)setMessage(error.message);else window.open(link.signedUrl,"_blank")}
 async function openLab(path:string){const {data:link,error}=await createClient().storage.from("laboratory-results").createSignedUrl(path,180);if(error)setMessage(error.message);else window.open(link.signedUrl,"_blank")}
 async function share(){if(!collaboratorId||!partnerId)return;const {data:row,error}=await createClient().from("client_care_collaborators").upsert({client_id:client.id,partner_id:partnerId,collaborator_id:collaboratorId,active:true,revoked_at:null},{onConflict:"client_id,collaborator_id"}).select().single();if(error)setMessage(error.message);else{setShares([...shares.filter(item=>item.collaborator_id!==collaboratorId),row]);setMessage("Collaborateur ajoute a l'equipe de soins.")}}
 async function revoke(row:Row){const {error}=await createClient().from("client_care_collaborators").update({active:false,revoked_at:new Date().toISOString()}).eq("id",row.id);if(error)setMessage(error.message);else setShares(shares.map(item=>item.id===row.id?{...item,active:false}:item))}
 if(!consented)return <section className="rounded-2xl border bg-white p-8"><h2 className="text-xl font-black">Dossier Premium non partage</h2><p className="mt-3 text-slate-600">Le client doit donner son consentement depuis « Ordonnances et resultats ». Aucun parametre clinique n'est affiche avant cet accord.</p></section>;
 const sections=[["Anthropometrie",data.anthropometry],["Biologie",data.biology],["Alimentation",data.food],["Mode de vie",data.lifestyle],["Diversite alimentaire",data.dietary]] as const;
 return <div className="grid gap-6">{message&&<p className="rounded-xl bg-mint p-4">{message}</p>}<section className="rounded-2xl bg-forest p-6 text-white"><h2 className="text-2xl font-black text-white">{client.full_name}</h2><p className="mt-2 text-white/70">Dossier Premium partage avec consentement actif.</p><button onClick={report} className="btn-primary mt-5">Generer un rapport PDF pour le client</button></section>{careConsent&&<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Equipe de soins autorisee</h2><p className="mt-2 text-sm text-slate-500">Ajout nominatif uniquement, selon le consentement du client.</p><div className="mt-4 flex flex-wrap gap-3"><select value={collaboratorId} onChange={event=>setCollaboratorId(event.target.value)} className="admin-input max-w-md"><option value="">Choisir un collaborateur</option>{collaborators.map(item=><option key={item.id} value={item.id}>{item.full_name} - {item.job_title}</option>)}</select><button onClick={share} className="btn-secondary">Ajouter</button></div><div className="mt-4 grid gap-2">{shares.filter(item=>item.active).map(item=><div key={item.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{collaborators.find(c=>c.id===item.collaborator_id)?.full_name||item.collaborator_id}</span><button onClick={()=>revoke(item)} className="font-bold text-red-700">Retirer</button></div>)}</div></section>}{sections.map(([title,rows])=><section key={title} className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-3">{rows.slice(0,20).map(row=><pre key={row.id} className="overflow-x-auto rounded-xl bg-slate-50 p-3 text-xs">{JSON.stringify(row,null,2)}</pre>)}{!rows.length&&<p className="text-slate-400">Aucune donnee.</p>}</div></section>)}<section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Resultats de laboratoire partages</h2><div className="mt-4 grid gap-3">{data.lab.map(row=><article key={row.id} className="rounded-xl bg-slate-50 p-4"><b>{row.prescription_item||"Resultat"}</b><p className="text-sm">{Object.entries(row.result_values||{}).map(([key,value])=>`${key}: ${value}`).join(" | ")}</p>{row.file_path&&<button onClick={()=>openLab(row.file_path)} className="mt-3 text-sm font-bold text-leaf">Ouvrir le document</button>}</article>)}{!data.lab.length&&<p className="text-slate-400">Aucun resultat partage.</p>}</div></section></div>
}
