"use client";
import { useMemo, useState, type FormEvent } from "react";
import { XMarkIcon } from "@heroicons/react/24/outline";
import { createClient } from "@/lib/supabase/client";
import { nextSequence } from "@/lib/ppm/ids";
import { usePpmLocale } from "@/components/op-management/PpmLocaleContext";
import type { Activity, ActivityKind, ActivityStatus, Indicator, PPMResource, ResultChainNode, Site, WBSNode } from "@/lib/ppm/types";

export const activityStatusLabels: Record<ActivityStatus,{fr:string;en:string}>={not_started:{fr:"Non demarree",en:"Not started"},in_progress:{fr:"En cours",en:"In progress"},completed:{fr:"Terminee",en:"Completed"},delayed:{fr:"En retard",en:"Delayed"},blocked:{fr:"Bloquee",en:"Blocked"},cancelled:{fr:"Annulee",en:"Cancelled"}};
export const activityStatusTones: Record<ActivityStatus,string>={not_started:"bg-slate-100 text-slate-600",in_progress:"bg-sky-50 text-sky-800",completed:"bg-mint text-forest",delayed:"bg-amber-50 text-amber-800",blocked:"bg-red-50 text-red-700",cancelled:"bg-slate-200 text-slate-500"};
const kindLabels={activity:{fr:"Activite",en:"Activity"},sub_activity:{fr:"Sous-activite",en:"Sub-activity"},task:{fr:"Tache",en:"Task"}};
export type ActivityEditTarget=Activity|"new"|null;

export default function ActivityFormModal({projectId,target,onClose,onSaved,workPackages,outputs,indicators,activities,staff=[],sites=[]}:{projectId:string;target:ActivityEditTarget;onClose:()=>void;onSaved:(row:Activity,isNew:boolean)=>void;workPackages:WBSNode[];outputs:ResultChainNode[];indicators:Indicator[];activities:Activity[];staff?:PPMResource[];sites?:Site[];knownPeople?:unknown[]}){
 const {locale,en}=usePpmLocale(); const activity=target!=="new"?target:null; const isNew=target==="new";
 const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const [kind,setKind]=useState<ActivityKind>(activity?.kind||"activity"); const [workPackageId,setWorkPackageId]=useState(activity?.work_package_id||"");
 const [selectedOutputs,setSelectedOutputs]=useState<string[]>(activity?.output_ids?.length?activity.output_ids:(activity?.output_id?[activity.output_id]:[]));
 const [selectedIndicators,setSelectedIndicators]=useState<string[]>(activity?.indicator_ids?.length?activity.indicator_ids:(activity?.indicator_id?[activity.indicator_id]:[]));
 const [coResponsible,setCoResponsible]=useState<string[]>(activity?.co_responsible||[]); const [dependencies,setDependencies]=useState<string[]>(activity?.dependency_ids||[]);
 const availableOutputs=useMemo(()=>outputs.filter(o=>!workPackageId||!o.work_package_ids?.length||o.work_package_ids.includes(workPackageId)),[outputs,workPackageId]);
 const availableIndicators=useMemo(()=>indicators.filter(i=>selectedOutputs.includes(i.result_chain_id||"")),[indicators,selectedOutputs]);
 const requiredParentKind=kind==="sub_activity"?"activity":kind==="task"?"sub_activity":null;
 const parentOptions=activities.filter(a=>a.id!==activity?.id&&a.kind===requiredParentKind&&(!workPackageId||a.work_package_id===workPackageId));
 const dependencyOptions=activities.filter(a=>a.id!==activity?.id&&(!workPackageId||a.work_package_id===workPackageId));
 if(!target)return null;
 const toggle=(id:string,setter:React.Dispatch<React.SetStateAction<string[]>>)=>setter(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage(""); if(!selectedOutputs.length||!selectedIndicators.length){setSaving(false);setMessage(en?"Select an output and at least one of its indicators.":"Selectionnez un output et au moins un de ses indicateurs.");return} const f=new FormData(e.currentTarget); const responsibleId=String(f.get("responsible_id")||""); const responsible=staff.find(x=>x.id===responsibleId); const siteId=String(f.get("site_id")||""); const site=sites.find(x=>x.id===siteId); const payload={project_id:projectId,work_package_id:workPackageId||null,parent_id:String(f.get("parent_id")||"")||null,kind,title:String(f.get("title")||"").trim(),description:String(f.get("description")||"").trim()||null,output_id:selectedOutputs[0],output_ids:selectedOutputs,responsible_name:responsible?.name||null,responsible_email:responsible?.account_email||null,co_responsible:coResponsible,site_id:siteId||null,location:site?.site_name||null,target_population:String(f.get("target_population")||"").trim()||null,beneficiaries:f.get("beneficiaries")?Number(f.get("beneficiaries")):null,planned_start:String(f.get("planned_start")||"")||null,planned_end:String(f.get("planned_end")||"")||null,is_milestone:f.get("is_milestone")==="on",planned_budget:f.get("planned_budget")?Number(f.get("planned_budget")):null,status:activity?.status||"not_started",progress_percent:activity?.progress_percent||0,ev_method:activity?.ev_method||"percent_complete",milestone_weights:activity?.milestone_weights||[],indicator_id:selectedIndicators[0],indicator_ids:selectedIndicators,target_value:String(f.get("target_value")||"").trim()||null,deliverable:String(f.get("deliverable")||"").trim()||null,risk_note:String(f.get("risk_note")||"").trim()||null,comment:String(f.get("comment")||"").trim()||null,dependency_ids:dependencies,dependency_type:String(f.get("dependency_type")||"FS"),dependency_lag_days:Number(f.get("dependency_lag_days")||0)}; if(!payload.title){setSaving(false);setMessage(en?"Title is required.":"Le titre est obligatoire.");return} const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); let code=activity?.code||null; if(isNew){const seq=await nextSequence(supabase,projectId,"activity").catch(()=>null); if(seq){const prefix=kind==="activity"?"ACT":kind==="sub_activity"?"SACT":"TSK";code=`${prefix}-${String(seq).padStart(4,"0")}`}}; const result=isNew?await supabase.from("ppm_activities").insert({...payload,code,order_index:activities.length,created_by:user?.id}).select("*").single():await supabase.from("ppm_activities").update(payload).eq("id",activity!.id).select("*").single(); setSaving(false);if(result.error){setMessage(result.error.message);return}onSaved(result.data as Activity,isNew)}
 return <div className="ppm-modal-backdrop fixed inset-0 z-[150] overflow-y-auto p-4"><form onSubmit={submit} className="mx-auto my-10 max-w-4xl rounded-[30px] bg-white p-7 shadow-2xl"><div className="flex justify-between"><h2 className="text-2xl font-black text-forest">{isNew?(en?"New activity":"Nouvelle activite"):(en?"Edit activity":"Modifier l'activite")}</h2><button type="button" onClick={onClose}><XMarkIcon className="h-6"/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">
 <label className="grid gap-2 text-sm font-bold sm:col-span-2">{en?"Title":"Titre"}<input name="title" defaultValue={activity?.title||""} required className="admin-input"/></label>
 <label className="grid gap-2 text-sm font-bold">Type<select value={kind} onChange={e=>setKind(e.target.value as ActivityKind)} className="admin-input">{Object.entries(kindLabels).map(([v,l])=><option key={v} value={v}>{l[locale]}</option>)}</select></label>
 <label className="grid gap-2 text-sm font-bold">Work Package<select value={workPackageId} onChange={e=>{setWorkPackageId(e.target.value);setSelectedOutputs([]);setSelectedIndicators([])}} className="admin-input"><option value="">{en?"Select...":"Selectionner..."}</option>{workPackages.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 {requiredParentKind&&<label className="grid gap-2 text-sm font-bold sm:col-span-2">{kind==="task"?(en?"Parent sub-activity":"Sous-activite parente"):(en?"Parent activity":"Activite parente")}<select name="parent_id" defaultValue={activity?.parent_id||""} className="admin-input"><option value="">{en?"None":"Aucune"}</option>{parentOptions.map(x=><option key={x.id} value={x.id}>{x.code} - {x.title}</option>)}</select></label>}
 <label className="grid gap-2 text-sm font-bold sm:col-span-2">{en?"Linked outputs (filtered by Work Package)":"Outputs lies (filtres par Work Package)"}<select multiple value={selectedOutputs} onChange={e=>{const ids=Array.from(e.target.selectedOptions,o=>o.value);setSelectedOutputs(ids);setSelectedIndicators(cur=>cur.filter(id=>indicators.some(i=>i.id===id&&ids.includes(i.result_chain_id||""))))}} className="admin-input min-h-28">{availableOutputs.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 <label className="grid gap-2 text-sm font-bold">{en?"Responsible":"Responsable"}<select name="responsible_id" defaultValue={staff.find(x=>x.name===activity?.responsible_name)?.id||""} className="admin-input"><option value="">{en?"Select...":"Selectionner..."}</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}{x.role_title?` - ${x.role_title}`:""}</option>)}</select></label>
 <fieldset className="grid gap-2 rounded-xl border p-3"><legend className="px-1 text-sm font-bold">{en?"Co-responsibles":"Co-responsables"}</legend><div className="max-h-28 overflow-y-auto">{staff.map(x=><label key={x.id} className="flex gap-2 text-xs"><input type="checkbox" checked={coResponsible.includes(x.name)} onChange={()=>toggle(x.name,setCoResponsible)}/>{x.name}</label>)}</div></fieldset>
 <label className="grid gap-2 text-sm font-bold">{en?"Location / project site":"Localisation / site du projet"}<select name="site_id" defaultValue={activity?.site_id||""} className="admin-input"><option value="">{en?"Select...":"Selectionner..."}</option>{sites.map(x=><option key={x.id} value={x.id}>{x.site_name} - {[x.subdivision,x.division,x.region,x.country].filter(Boolean).join(", ")}</option>)}</select></label>
 <label className="grid gap-2 text-sm font-bold">{en?"Target population":"Population cible"}<input name="target_population" defaultValue={activity?.target_population||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">{en?"Beneficiaries":"Beneficiaires"}<input name="beneficiaries" type="number" min="0" defaultValue={activity?.beneficiaries??""} className="admin-input"/></label><label className="flex items-center gap-2 text-sm font-bold"><input name="is_milestone" type="checkbox" defaultChecked={activity?.is_milestone}/>{en?"Milestone":"Jalon"}</label>
 <label className="grid gap-2 text-sm font-bold">{en?"Planned start":"Debut prevu"}<input name="planned_start" type="date" defaultValue={activity?.planned_start||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">{en?"Planned end":"Fin prevue"}<input name="planned_end" type="date" defaultValue={activity?.planned_end||""} className="admin-input"/></label>
 <fieldset className="grid gap-3 rounded-xl border p-3 sm:col-span-2"><legend className="px-1 text-sm font-bold">{en?"Gantt dependencies":"Dependances Gantt"}</legend><div className="grid gap-1 sm:grid-cols-2">{dependencyOptions.map(x=><label key={x.id} className="flex gap-2 text-xs"><input type="checkbox" checked={dependencies.includes(x.id)} onChange={()=>toggle(x.id,setDependencies)}/>{x.code} - {x.title}</label>)}</div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">{en?"Relationship":"Relation"}<select name="dependency_type" defaultValue={activity?.dependency_type||"FS"} className="admin-input"><option value="FS">Finish-to-Start (FS)</option><option value="SS">Start-to-Start (SS)</option><option value="FF">Finish-to-Finish (FF)</option><option value="SF">Start-to-Finish (SF)</option></select></label><label className="grid gap-1 text-xs font-bold">{en?"Lag (days)":"Decalage (jours)"}<input name="dependency_lag_days" type="number" defaultValue={activity?.dependency_lag_days||0} className="admin-input"/></label></div></fieldset>
 <fieldset className="grid gap-2 rounded-xl border p-3 sm:col-span-2"><legend className="px-1 text-sm font-bold">{en?"Indicators linked to selected outputs":"Indicateurs des outputs selectionnes"}</legend><div className="grid gap-1 sm:grid-cols-2">{availableIndicators.map(x=><label key={x.id} className="flex gap-2 text-xs"><input type="checkbox" checked={selectedIndicators.includes(x.id)} onChange={()=>toggle(x.id,setSelectedIndicators)}/>{x.code?`${x.code} - `:""}{x.name}</label>)}</div></fieldset>
 <label className="grid gap-2 text-sm font-bold">{en?"Target":"Cible"}<input name="target_value" defaultValue={activity?.target_value||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold">{en?"Planned budget":"Budget prevu"}<input name="planned_budget" type="number" min="0" defaultValue={activity?.planned_budget??""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea name="description" defaultValue={activity?.description||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">{en?"Deliverable":"Livrable"}<input name="deliverable" defaultValue={activity?.deliverable||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">{en?"Risk":"Risque"}<input name="risk_note" defaultValue={activity?.risk_note||""} className="admin-input"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Commentaire<textarea name="comment" defaultValue={activity?.comment||""} className="admin-input"/></label>
 {message&&<p className="rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900 sm:col-span-2">{message}</p>}<div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={onClose} className="btn-secondary">{en?"Cancel":"Annuler"}</button><button disabled={saving} className="btn-primary">{saving?(en?"Saving...":"Enregistrement..."):(en?"Save":"Enregistrer")}</button></div></div></form></div>
}