"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {usePpmLocale} from "@/components/op-management/PpmLocaleContext";
import type {ChangeRequest,ScopeBaseline,ScopeBaselineStatus} from "@/lib/ppm/types";

const statusLabels:Record<ScopeBaselineStatus,{fr:string;en:string}>={draft:{fr:"Brouillon",en:"Draft"},review:{fr:"En revue",en:"Under review"},approved:{fr:"Approuvée",en:"Approved"},baseline:{fr:"Baseline verrouillée",en:"Locked baseline"}};
const statusTones:Record<ScopeBaselineStatus,string>={draft:"bg-slate-100 text-slate-600",review:"bg-amber-50 text-amber-800",approved:"bg-sky-50 text-sky-800",baseline:"bg-mint text-forest"};
const nextStep:Record<ScopeBaselineStatus,ScopeBaselineStatus|null>={draft:"review",review:"approved",approved:"baseline",baseline:null};

export default function ScopeBaselineManager({projectId,initial,changeRequests}:{projectId:string;initial:ScopeBaseline[];changeRequests:ChangeRequest[]}){
 const {locale,en}=usePpmLocale();const router=useRouter();const [versions,setVersions]=useState(initial),[saving,setSaving]=useState(false),[selecting,setSelecting]=useState(false),[selectedCr,setSelectedCr]=useState(""),[message,setMessage]=useState("");const latest=versions[0]||null;
 const availableChanges=useMemo(()=>changeRequests.filter(item=>item.status==="approved"&&item.request_code&&!item.baseline_id&&!versions.some(version=>version.change_request_id===item.id)),[changeRequests,versions]);
 async function createBaseline(changeRequestId?:string){if(latest?.status==="baseline"&&!changeRequestId){setSelecting(true);return}setSaving(true);setMessage("");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();const result=await supabase.from("ppm_scope_baselines").insert({project_id:projectId,version:(latest?.version||0)+1,status:"draft",change_request_id:changeRequestId||null,created_by:user?.id}).select("*").single();setSaving(false);if(result.error){setMessage(result.error.message);return}const baseline=result.data as ScopeBaseline;setVersions(current=>[baseline,...current]);setSelecting(false);if(changeRequestId)router.push(`/op-management/projets/${projectId}/cadrage/perimetre?changeRequest=${changeRequestId}&baseline=${baseline.id}&step=scope`)}
 async function advance(){if(!latest)return;const next=nextStep[latest.status];if(!next)return;setSaving(true);setMessage("");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();let result:any;if(next==="baseline")result=await supabase.rpc("ppm_lock_scope_baseline",{p_baseline_id:latest.id});else result=await supabase.from("ppm_scope_baselines").update({status:next,...(next==="approved"?{approved_by_name:user?.user_metadata?.full_name||user?.email,approved_at:new Date().toISOString()}: {})}).eq("id",latest.id).select("*").single();setSaving(false);if(result.error){setMessage(result.error.message);return}const updated=result.data as ScopeBaseline;await supabase.from("ppm_history").insert({entity_type:"project",entity_id:projectId,actor_id:user?.id,action:`Scope Baseline v${latest.version} — ${statusLabels[next].fr}`,from_status:latest.status,to_status:next});setVersions(current=>current.map(item=>item.id===latest.id?updated:item))}
 const elements=[{href:`/op-management/projets/${projectId}/cadrage/perimetre`,fr:"Périmètre du projet",en:"Project scope"},{href:`/op-management/projets/${projectId}/planification/wbs`,fr:"WBS",en:"WBS"},{href:`/op-management/projets/${projectId}/planification/wbs?view=dictionary`,fr:"Dictionnaire WBS",en:"WBS Dictionary"}];
 return <section className="grid gap-4 rounded-[28px] border border-emerald-100 bg-emerald-50/70 p-5 md:p-6">
  <div><h2 className="text-xl font-black text-forest">Scope Baseline</h2><p className="mt-1 text-sm text-slate-600">{en?"The baseline combines the Project Scope, WBS and WBS Dictionary. A locked baseline can only evolve through an approved Change Request.":"La baseline réunit le Périmètre du projet, le WBS et le Dictionnaire WBS. Une baseline verrouillée ne peut évoluer qu’au moyen d’une demande de changement approuvée."}</p></div>
  <div className="grid gap-3 sm:grid-cols-3">{elements.map(item=><Link key={item.href} href={item.href} className="rounded-2xl border border-emerald-200 bg-white p-4 font-bold text-forest shadow-sm transition hover:-translate-y-0.5 hover:border-leaf"><span className="block text-xs uppercase tracking-widest text-leaf">{en?"View":"Visualiser"}</span>{en?item.en:item.fr}</Link>)}</div>
  {!latest?<div className="rounded-2xl border bg-white p-8 text-center"><p className="text-slate-500">{en?"No baseline initiated.":"Aucune baseline initiée."}</p><button onClick={()=>createBaseline()} disabled={saving} className="btn-primary mt-4">{en?"Initiate Scope Baseline":"Initier la Scope Baseline"}</button></div>:<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-3"><b className="text-forest">Version {latest.version}</b><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusTones[latest.status]}`}>{statusLabels[latest.status][locale]}</span>{latest.change_request_id&&<span className="rounded-full bg-orange/10 px-3 py-1 text-xs font-bold text-orange">{changeRequests.find(item=>item.id===latest.change_request_id)?.request_code||"Change Request"}</span>}</div><div className="flex flex-wrap gap-2">{nextStep[latest.status]&&<button onClick={advance} disabled={saving} className="btn-primary px-4 py-2 text-sm">{en?"Move to":"Passer à"} « {statusLabels[nextStep[latest.status]!][locale]} »</button>}{latest.status==="baseline"&&<button onClick={()=>setSelecting(true)} disabled={saving||!availableChanges.length} title={!availableChanges.length?(en?"No approved unused Change Request":"Aucune demande approuvée disponible"):undefined} className="btn-secondary px-4 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-40">{en?"New version (via Change Request)":"Nouvelle version (via Change Request)"}</button>}</div></div>}
  {message&&<p className="rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">{message}</p>}
  {versions.length>1&&<p className="text-xs text-slate-500">{en?"History":"Historique"} : {versions.map(item=>`v${item.version} (${statusLabels[item.status][locale]})`).join(" · ")}</p>}
  {selecting&&<div className="fixed inset-0 z-[150] grid place-items-center overflow-y-auto bg-forest/90 p-4"><div className="w-full max-w-xl rounded-[30px] border border-white/20 bg-emerald-50 p-7 shadow-2xl"><h3 className="text-2xl font-black text-forest">{en?"Start a new baseline version":"Créer une nouvelle version de baseline"}</h3><p className="mt-2 text-sm text-slate-600">{en?"Select the approved Change Request that authorizes this version.":"Sélectionnez la demande de changement approuvée qui autorise cette version."}</p><label className="mt-5 grid gap-2 text-sm font-bold">{en?"Approved Change Request":"Demande approuvée"}<select value={selectedCr} onChange={event=>setSelectedCr(event.target.value)} className="admin-input"><option value="">{en?"Select...":"Sélectionner..."}</option>{availableChanges.map(item=><option key={item.id} value={item.id}>{item.request_code} — {item.title}</option>)}</select></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setSelecting(false)} className="btn-secondary">{en?"Cancel":"Annuler"}</button><button onClick={()=>createBaseline(selectedCr)} disabled={!selectedCr||saving} className="btn-primary disabled:opacity-40">{en?"Open Project Scope":"Ouvrir le Périmètre"}</button></div></div></div>}
 </section>
}