import {NextResponse} from "next/server";
import {z} from "zod";
import {getDegreeSession} from "@/lib/degree-programs/access";
import {createSupabaseServerClient} from "@/lib/supabase/server";
const programSchema=z.object({code:z.string().min(2).max(30),nameFr:z.string().min(2),nameEn:z.string().min(2),level:z.enum(["DUT","LICENCE_PRO","MASTER_PRO","OTHER"]),degreeType:z.string().min(2),durationYears:z.coerce.number().positive(),durationSemesters:z.coerce.number().int().positive(),totalCredits:z.coerce.number().positive(),language:z.enum(["FR","EN","FR_EN"]),departmentId:z.union([z.uuid(),z.literal("")]).optional(),coordinatorId:z.union([z.uuid(),z.literal("")]).optional(),effectiveFrom:z.string().min(10)});
const cloneSchema=z.object({programId:z.uuid(),effectiveFrom:z.string().min(10),reason:z.string().min(3)});
const decisionSchema=z.object({versionId:z.uuid(),action:z.enum(["SUBMIT","APPROVE","REJECT"]),reason:z.string().min(3)});
export async function POST(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!session.organizationId)return NextResponse.json({error:"Organization required"},{status:400});if(!session.isSuperAdmin&&!session.permissions.includes("curriculum.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=programSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload",details:parsed.error.flatten()},{status:400});const d=parsed.data;const supabase=await createSupabaseServerClient();const{data:program,error}=await supabase.from("academic_programs").insert({organization_id:session.organizationId,code:d.code,name_fr:d.nameFr,name_en:d.nameEn,level:d.level,degree_type:d.degreeType,duration_years:d.durationYears,duration_semesters:d.durationSemesters,total_credits:d.totalCredits,language:d.language,department_id:d.departmentId||null,coordinator_id:d.coordinatorId||null,created_by:session.userId,updated_by:session.userId}).select("id").single();if(error)return NextResponse.json({error:error.message},{status:400});const{error:versionError}=await supabase.from("academic_program_versions").insert({organization_id:session.organizationId,program_id:program.id,version_number:1,effective_from:d.effectiveFrom,total_credits:d.totalCredits,created_by:session.userId,updated_by:session.userId});if(versionError){await supabase.from("academic_programs").delete().eq("id",program.id);return NextResponse.json({error:versionError.message},{status:400})}return NextResponse.json({id:program.id},{status:201})}
export async function PATCH(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=decisionSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload"},{status:400});const canApprove=session.isSuperAdmin||session.permissions.includes("curriculum.approve");const canManage=session.isSuperAdmin||session.permissions.includes("curriculum.manage");if((parsed.data.action==="SUBMIT"&&!canManage)||(parsed.data.action!=="SUBMIT"&&!canApprove))return NextResponse.json({error:"Forbidden"},{status:403});const supabase=await createSupabaseServerClient();const rpc=parsed.data.action==="SUBMIT"?await supabase.rpc("academic_submit_program_version",{p_version_id:parsed.data.versionId,p_reason:parsed.data.reason}):await supabase.rpc("academic_decide_program_version",{p_version_id:parsed.data.versionId,p_approve:parsed.data.action==="APPROVE",p_reason:parsed.data.reason});if(rpc.error)return NextResponse.json({error:rpc.error.message},{status:400});return NextResponse.json({ok:true,data:rpc.data})}
export async function PUT(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!session.isSuperAdmin&&!session.permissions.includes("curriculum.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=cloneSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload"},{status:400});const supabase=await createSupabaseServerClient();const{data,error}=await supabase.rpc("academic_clone_program_version",{p_program_id:parsed.data.programId,p_effective_from:parsed.data.effectiveFrom,p_reason:parsed.data.reason});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,data})}