import Link from "next/link";
import { Activity, ArrowRight, Award, BarChart3, BookOpen, Building2, CheckCircle2, ClipboardCheck, Database, GraduationCap, HeartPulse, Hospital, Laptop, Microscope, ShieldCheck, Stethoscope, Users, type LucideIcon } from "lucide-react";
import type { ManagedSection } from "@/data/site-pages";

const statIcons=[Users,Building2,Activity,Stethoscope,Award,GraduationCap,Laptop,HeartPulse];
const serviceIcons=[Stethoscope,HeartPulse,Laptop,ClipboardCheck,Hospital,Users,GraduationCap,Microscope];
const methodIcons=[ClipboardCheck,Stethoscope,BookOpen,Users,Activity,BarChart3,ClipboardCheck,Award];
const domainIcons=[Hospital,Building2,Users,HeartPulse,Users,Activity,Stethoscope,HeartPulse,Microscope,Users,GraduationCap,Building2];
const achievementImages=["/images/consultation-format-clinic.png","/images/consultation-format-home.png","/images/consultation-format-online.png","/images/consultation-nutrition-hero.png"];
const teamImages=["/images/consultation-format-clinic.png","/images/consultation-format-online.png","/images/consultation-format-home.png","/images/consultation-nutrition-hero.png"];

export default function ClinicalNutritionInstitutional({sections,english}:{sections:ManagedSection[];english:boolean}){
 const t=(fr:string,en:string)=>english?en:fr;
 const fallbackStats=[["12 500+",t("Patients accompagnés","Patients supported")],["250+",t("Organisations partenaires","Partner organizations")],["25+",t("Pays couverts","Countries covered")],["80+",t("Nutritionnistes et experts","Dietitians and experts")],["95%",t("Satisfaction client","Client satisfaction")],["320+",t("Formations réalisées","Courses delivered")],["8 700+",t("Téléconsultations effectuées","Teleconsultations completed")],["24h",t("Temps moyen de réponse","Average response time")]];
 const fallbackServices=[t("Consultation nutritionnelle","Nutrition consultation"),t("Consultation diététique","Dietetic consultation"),t("Téléconsultation","Teleconsultation"),t("Plans alimentaires personnalisés","Personalized meal plans"),t("Nutrition clinique","Clinical nutrition"),t("Nutrition communautaire","Community nutrition"),t("Formation des professionnels","Professional training"),t("Recherche scientifique","Scientific research")];
 const domains=(sections[16]?.items?.length?sections[16].items:[t("Hôpitaux","Hospitals"),t("Ministères","Ministries"),t("ONG & associations","NGOs & associations"),t("Nutrition infantile","Child nutrition"),t("Femmes enceintes","Pregnant women"),t("Nutrition sportive","Sports nutrition"),t("Diabète","Diabetes"),t("Hypertension","Hypertension"),t("Cancer","Cancer"),t("Personnes âgées","Older adults"),t("Écoles & universités","Schools & universities"),t("Entreprises","Companies")]);
 const methodFallback=[t("Analyse des besoins","Needs analysis"),t("Diagnostic nutritionnel","Nutrition diagnosis"),t("Élaboration du plan","Plan development"),t("Consultation & intervention","Consultation & intervention"),t("Suivi personnalisé","Personalized follow-up"),t("Ajustements","Adjustments"),t("Rapport & recommandations","Report & recommendations"),t("Amélioration continue","Continuous improvement")];
 const individuals=sections[25]||{title:t("Pour les particuliers","For individuals"),text:t("Un accompagnement personnalisé pour chaque étape de votre vie.","Personalized support for every stage of life."),items:[t("Perte de poids","Weight loss"),t("Prise de poids","Weight gain"),t("Diabète","Diabetes"),t("Grossesse & allaitement","Pregnancy & breastfeeding"),t("Maladies chroniques","Chronic diseases"),t("Sportifs","Athletes")]};
 const organizations=sections[26]||{title:t("Pour les organisations","For organizations"),text:t("Nous concevons, mettons en œuvre et évaluons des interventions nutritionnelles et sanitaires à fort impact.","We design, implement and evaluate high-impact nutrition and health interventions."),items:[t("Conception de projets","Project design"),t("Études & enquêtes","Studies & surveys"),t("Collecte de données SMART","SMART data collection"),t("Renforcement des capacités","Capacity strengthening"),t("Évaluation & suivi","Evaluation & monitoring"),t("Recherche opérationnelle","Operational research"),t("Digitalisation & tableaux de bord","Digitalization & dashboards"),t("IA & analyse avancée","AI & advanced analytics")]};
 const achievements=[0,1,2,3].map((i)=>sections[27+i]||{title:[t("Projet Nutrition Maternelle","Maternal Nutrition Project"),t("Programme Alimentaire d’Urgence","Emergency Food Programme"),t("Unité de Nutrition Clinique","Clinical Nutrition Unit"),t("Enquête Nutritionnelle Nationale","National Nutrition Survey")][i],text:["Sénégal · OMS","Niger · PAM","Yaoundé · Ministère de la Santé","RDC · UNICEF"][i],image_url:achievementImages[i]});
 const testimonial=sections[31]||{title:t("Ce que nos partenaires disent","What our partners say"),text:t("NutVitaGlobalis a été un partenaire stratégique exceptionnel. Son expertise, sa rigueur et son engagement ont permis d’atteindre des résultats au-delà de nos attentes.","NutVitaGlobalis has been an exceptional strategic partner. Its expertise, rigor and commitment delivered results beyond our expectations."),items:["Dr. Awa Diallo",t("Nutritionniste spécialiste · UNICEF Sénégal","Specialist nutritionist · UNICEF Senegal")]};
 const technologies=sections[32]?.items?.length?sections[32].items:["NutriTrack","ODK","Kobo","Power BI","QGIS","R","Python","SPSS","Stata","OpenAI","Claude","Gemini"];
 const team=[0,1,2,3].map((i)=>sections[33+i]||{title:["Dr. Fatou Ndiaye","Dr. Moussa Koné","Dr. Aïssatou Traoré","Dr. David K." ][i],text:[t("Nutritionniste clinicienne","Clinical nutritionist"),t("Nutritionniste santé publique","Public health nutritionist"),t("Diététicienne nutrition pédiatrique","Pediatric dietitian"),t("Data scientist nutrition & IA","Nutrition & AI data scientist")][i],image_url:teamImages[i]});
 const resources=sections[37]?.items?.length?sections[37].items:[t("Guides pratiques","Practical guides"),t("Rapports & études","Reports & studies"),t("Articles scientifiques","Scientific articles"),t("Vidéos & webinaires","Videos & webinars")];
 const faqs=[0,1,2,3].map((i)=>sections[38+i]||{title:[t("Comment se déroule une consultation nutritionnelle ?","How does a nutrition consultation work?"),t("Proposez-vous des consultations à distance ?","Do you offer remote consultations?"),t("Quels documents faut-il fournir ?","Which documents should I provide?"),t("Travaillez-vous avec les organisations et projets ?","Do you work with organizations and projects?")][i],text:[t("La consultation comprend une évaluation, des objectifs convenus et des recommandations personnalisées.","The consultation includes an assessment, agreed goals and personalized recommendations."),t("Oui, avec des outils sécurisés selon votre formule et votre disponibilité.","Yes, using secure tools according to your plan and availability."),t("Vos bilans disponibles, traitements et informations utiles à votre objectif.","Available test results, treatments and information relevant to your goal."),t("Oui, de la conception à l’évaluation, au renforcement des capacités et à la digitalisation.","Yes, from design and evaluation to capacity strengthening and digitalization.")][i]});
 return <>
  <section className="relative z-10 -mt-8"><div className="container-site"><div className="grid gap-4 rounded-[2rem] border bg-white p-6 shadow-xl sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{fallbackStats.map(([value,label],i)=>{const item=sections[i],Icon=statIcons[i];return <div key={i} className="flex gap-3 border-slate-200 xl:border-r xl:last:border-0"><Icon className="h-7 shrink-0 text-leaf"/><div><p className="text-xl font-black">{item?.title||value}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{item?.text||label}</p></div></div>})}</div></div></section>
  <section className="section"><div className="container-site rounded-[2rem] bg-[#f5f7f5] p-7"><h2 className="text-center text-3xl font-black">{t("Des solutions adaptées à chaque besoin","Solutions tailored to every need")}</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{fallbackServices.map((label,i)=>{const item=sections[8+i],Icon=serviceIcons[i];return <article key={i} className="rounded-2xl bg-white p-5 text-center shadow-soft"><Icon className="mx-auto h-8 text-leaf"/><h3 className="mt-4 text-sm font-black leading-5">{item?.title||label}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{item?.text}</p></article>})}</div></div></section>
  <section className="pb-12"><div className="container-site rounded-[2rem] border bg-white p-7"><h2 className="text-center text-3xl font-black">{sections[16]?.title||t("Nos domaines d’intervention","Our fields of intervention")}</h2><div className="mt-7 grid gap-3 grid-cols-2 md:grid-cols-4 xl:grid-cols-12">{domains.map((label,i)=>{const Icon=domainIcons[i%domainIcons.length];return <div key={label} className="rounded-2xl bg-[#f7faf8] p-4 text-center"><Icon className="mx-auto h-7 text-leaf"/><p className="mt-3 text-xs font-black leading-4">{label}</p></div>})}</div></div></section>
  <section className="pb-12"><div className="container-site rounded-[2rem] bg-white p-8 shadow-soft"><h2 className="text-center text-3xl font-black">{t("Comment nous vous accompagnons","How we support you")}</h2><div className="mt-10 grid gap-6 md:grid-cols-4 xl:grid-cols-8">{methodFallback.map((title,i)=>{const item=sections[17+i],Icon=methodIcons[i];return <article key={i} className="relative text-center"><span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-leaf text-sm font-black text-white">{i+1}</span><Icon className="mx-auto mt-4 h-7 text-leaf"/><h3 className="mt-3 text-sm font-black">{item?.title||title}</h3><p className="mt-2 text-[11px] leading-4 text-slate-500">{item?.text}</p></article>})}</div></div></section>
  <section className="pb-12"><div className="container-site grid gap-6 lg:grid-cols-2">{[individuals,organizations].map((group,idx)=><article key={group.title} className="rounded-[2rem] border bg-white p-8 shadow-soft"><h2 className="text-3xl font-black">{group.title}</h2><p className="mt-3 text-slate-600">{group.text}</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(group.items||[]).map(x=><div key={x} className="flex items-center gap-2 rounded-xl bg-[#f4f8f5] p-3 text-sm font-black"><CheckCircle2 className="h-5 shrink-0 text-leaf"/>{x}</div>)}</div>{group.cta_url&&<Link href={group.cta_url} className="mt-6 inline-flex font-black text-leaf">{group.cta_label||t("Découvrir","Discover")}<ArrowRight className="ml-2 h-4"/></Link>}</article>)}</div></section>
  <section className="pb-12"><div className="container-site"><h2 className="text-3xl font-black">{t("Nos réalisations","Our achievements")}</h2><div className="mt-7 grid gap-6 lg:grid-cols-[3fr_1fr]"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{achievements.map((item,i)=><article key={i} className="overflow-hidden rounded-2xl border bg-white shadow-soft"><img src={item.image_url||achievementImages[i]} alt="" className="h-36 w-full object-cover"/><div className="p-5"><h3 className="font-black">{item.title}</h3><p className="mt-2 text-xs text-slate-500">{item.text}</p></div></article>)}</div><blockquote className="rounded-[2rem] bg-forest p-7 text-white"><h3 className="text-xl font-black text-white">{testimonial.title}</h3><p className="mt-5 text-sm leading-7 text-white/75">“{testimonial.text}”</p><div className="mt-6 text-sm">{(testimonial.items||[]).map(x=><p key={x}>{x}</p>)}</div></blockquote></div></div></section>
  <section className="pb-12"><div className="container-site grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-7"><h2 className="text-2xl font-black">{sections[32]?.title||t("Technologies & outils","Technologies & tools")}</h2><div className="mt-6 flex flex-wrap gap-3">{technologies.map(x=><span key={x} className="rounded-full bg-[#f0f7f3] px-4 py-2 text-sm font-black text-leaf">{x}</span>)}</div></article><article className="rounded-[2rem] border bg-white p-7"><h2 className="text-2xl font-black">{t("Notre équipe d’experts","Our expert team")}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{team.map((item,i)=><div key={i} className="text-center"><img src={item.image_url||teamImages[i]} alt="" className="mx-auto h-20 w-20 rounded-full object-cover"/><h3 className="mt-3 text-sm font-black">{item.title}</h3><p className="mt-1 text-[11px] leading-4 text-slate-500">{item.text}</p></div>)}</div></article></div></section>
  <section className="pb-16"><div className="container-site grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-7"><h2 className="text-2xl font-black">{sections[37]?.title||t("Ressources & publications","Resources & publications")}</h2><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{resources.map(x=><Link key={x} href="/ressources" className="rounded-xl bg-[#f4f8f5] p-4 text-center text-xs font-black"><BookOpen className="mx-auto mb-2 h-6 text-leaf"/>{x}</Link>)}</div></article><article className="rounded-[2rem] border bg-white p-7"><h2 className="text-2xl font-black">{t("Questions fréquentes","Frequently asked questions")}</h2><div className="mt-5 divide-y">{faqs.map((item,i)=><details key={i} className="group py-3"><summary className="cursor-pointer list-none font-black">{item.title}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p></details>)}</div></article></div></section>
 </>;
}