"use client";
import {FormEvent,useState} from "react";
import {PaperAirplaneIcon} from "@heroicons/react/24/outline";
import {usePathname} from "next/navigation";
import {normalizeLocale,stripLocale} from "@/lib/i18n";
export default function ContactForm(){
  const english=normalizeLocale(stripLocale(usePathname()).locale)==="en",tx=(fr:string,en:string)=>english?en:fr,[status,setStatus]=useState<{type:"idle"|"loading"|"success"|"error";message?:string}>({type:"idle"});
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setStatus({type:"loading"});try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))}),result=await response.json();if(!response.ok)throw new Error(result.message);form.reset();setStatus({type:"success",message:tx("Votre message a été déposé. Notre équipe le consultera depuis son espace administratif.","Your message has been submitted. Our team will review it from the administration area.")})}catch{setStatus({type:"error",message:tx("Une erreur est survenue. Veuillez réessayer.","Something went wrong. Please try again.")})}}
  const input="admin-input bg-slate-50 focus:bg-white";
  return <div className="rounded-[2rem] bg-forest p-5 shadow-2xl shadow-forest/20 md:p-8"><div className="mb-6 flex items-center gap-3 text-white"><span className="grid h-11 w-11 place-items-center rounded-full bg-orange"><PaperAirplaneIcon className="h-5"/></span><div><h2 className="text-2xl font-black text-white">{tx("Laissez-nous un message","Send us a message")}</h2><p className="mt-1 text-sm text-white/65">{tx("Notre équipe vous répondra dans les meilleurs délais.","Our team will get back to you as soon as possible.")}</p></div></div><form onSubmit={submit} className="grid gap-5 rounded-[1.6rem] bg-white p-6 md:p-9"><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">{tx("Nom (facultatif)","Name (optional)")}<input name="name" maxLength={100} className={input}/></label><label className="grid gap-2 text-sm font-bold">{tx("Email de réponse (facultatif)","Reply email (optional)")}<input name="email" type="email" className={input}/></label></div><label className="grid gap-2 text-sm font-bold">{tx("Téléphone / WhatsApp de réponse (facultatif)","Reply phone / WhatsApp (optional)")}<input name="phone" type="tel" maxLength={40} className={input}/></label><label className="grid gap-2 text-sm font-bold">{tx("Sujet","Subject")}<select name="subject" className={input}><option>{tx("Demande d’information","Information request")}</option><option>{tx("Formation","Course")}</option><option>{tx("Solution numérique","Digital solution")}</option><option>{tx("Partenariat","Partnership")}</option><option>Feedback</option></select></label><label className="grid gap-2 text-sm font-bold">Message<textarea name="message" required minLength={10} maxLength={5000} rows={7} className={`${input} resize-none`} placeholder={tx("Votre message...","Your message...")}/></label><p className="text-xs leading-5 text-slate-500">{tx("Vous pouvez envoyer un message anonymement. Ajoutez vos coordonnées uniquement si vous souhaitez recevoir une réponse.","You may submit anonymously. Add contact details only if you would like a reply.")}</p>{status.message&&<p role="status" className={`rounded-xl p-4 text-sm font-semibold ${status.type==="success"?"bg-mint text-forest":"bg-red-50 text-red-700"}`}>{status.message}</p>}<button disabled={status.type==="loading"} className="btn-primary justify-self-start"><PaperAirplaneIcon className="mr-2 h-5"/>{status.type==="loading"?tx("Envoi...","Submitting..."):tx("Envoyer le message","Submit message")}</button></form></div>;
}
