import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, CheckCircle2, Download, Globe2, Heart, Lightbulb, ShieldCheck, Sparkles, Users } from "lucide-react";
import type { ResearchSettings } from "@/lib/research-innovation";

type Expertise=ResearchSettings["expertises"][number];
const Icon=({index=0}:{index?:number})=>{const icons=[Sparkles,BarChart3,Users,ShieldCheck,Globe2,Heart,Lightbulb];const C=icons[index%icons.length];return <C className="h-6 w-6"/>};
export default function ExpertisePremiumDetail({item,data,english}:{item:Expertise;data:ResearchSettings;english:boolean}){
 const t=(fr:string,en:string)=>english?(en||fr):fr;
 const panel=english?item.hero_panel_items_en:item.hero_panel_items;
 return <main className="overflow-hidden bg-[#fbfcfa] text-forest">
  <section className="relative isolate min-h-[630px] overflow-hidden bg-forest text-white">
   <img src={item.image_url} alt={t(item.title,item.title_en)} className="absolute inset-0 h-full w-full object-cover object-center"/>
   <div className="absolute inset-0 bg-gradient-to-r from-[#003e31] via-[#003e31]/90 to-[#003e31]/20"/>
   <div className="container-site relative grid min-h-[630px] items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]">
    <div><Link href="/recherche-innovation#expertises" className="inline-flex items-center text-sm font-black text-white/80"><ArrowLeft className="mr-2 h-4"/>{english?"All expertise":"Toutes les expertises"}</Link><p className="mt-10 text-xs font-black uppercase tracking-[.2em] text-orange">NutVitaGlobalis Expertise</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-[1.04] text-white sm:text-5xl lg:text-6xl">{t(item.title,item.title_en)}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/80">{t(item.description||"",item.description_en||"")}</p>
     <div className="mt-8 grid max-w-3xl grid-cols-2 gap-4 sm:grid-cols-4">{item.hero_points.map((point,i)=><div key={point.title} className="flex items-start gap-2 text-sm font-bold"><span className="text-[#5fd486]"><Icon index={i}/></span>{t(point.title,point.title_en)}</div>)}</div>
     <div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="rounded-xl bg-[#159447] px-6 py-4 font-black text-white shadow-lg">{english?"Request a consultation":"Demander une consultation"}<ArrowRight className="ml-2 inline h-4"/></Link><Link href="/contact?objet=proposition-technique" className="rounded-xl bg-orange px-6 py-4 font-black text-white">{english?"Request a technical proposal":"Demander une proposition technique"}<ArrowRight className="ml-2 inline h-4"/></Link><Link href={item.brochure_url} className="rounded-xl border border-white/60 px-6 py-4 font-black text-white"><Download className="mr-2 inline h-4"/>{english?"Download brochure":"Télécharger la brochure"}</Link></div>
    </div>
    <aside className="self-end rounded-3xl bg-white p-7 text-forest shadow-2xl lg:mb-3 lg:ml-auto lg:max-w-md">{panel.map((line,i)=><div key={line} className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0"><CheckCircle2 className="h-5 w-5 shrink-0 text-leaf"/><span className="font-bold">{line}</span></div>)}</aside>
   </div>
  </section>
  <section className="container-site relative z-10 -mt-5"><div className="grid rounded-3xl border bg-white p-5 shadow-soft sm:grid-cols-2 lg:grid-cols-7">{item.detail_stats.map((stat,i)=><div key={`${stat.value}-${i}`} className="border-slate-100 p-4 text-center lg:border-r lg:last:border-0"><span className="mx-auto mb-2 block w-fit text-leaf"><Icon index={i}/></span><strong className="block text-3xl font-black">{stat.value}</strong><span className="text-xs font-bold text-slate-600">{t(stat.label,stat.label_en)}</span></div>)}</div></section>
  <section className="section"><div className="container-site"><h2 className="text-center text-4xl font-black">{english?"Solutions tailored to every need":"Des solutions adaptées à chaque besoin"}</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{item.detail_services.map((service,i)=><article key={service.title} className="rounded-3xl border bg-white p-6 shadow-soft"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-leaf"><Icon index={i}/></span><h3 className="mt-5 text-xl font-black">{t(service.title,service.title_en)}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{t(service.description||"Une solution rigoureuse, adaptée à votre contexte et à vos objectifs.",service.description_en||"A rigorous solution tailored to your context and objectives.")}</p></article>)}</div></div></section>
  <section className="section bg-[#f1f8f4]"><div className="container-site"><h2 className="text-center text-4xl font-black">{english?"Our proven approach":"Notre approche éprouvée"}</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{item.detail_steps.map((step,i)=><article key={step.title} className="relative rounded-2xl bg-white p-5 text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-forest font-black text-white">{i+1}</span><h3 className="mt-4 font-black">{t(step.title,step.title_en)}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{t(step.description||"",step.description_en||"")}</p></article>)}</div></div></section>
  {item.detail_tools.length>0&&<section className="section"><div className="container-site"><h2 className="text-center text-3xl font-black">{english?"Technologies and tools":"Technologies et outils"}</h2><div className="mt-7 flex flex-wrap justify-center gap-3">{item.detail_tools.map(tool=><span key={tool} className="rounded-2xl border bg-white px-5 py-4 font-black shadow-sm">{tool}</span>)}</div></div></section>}
  {item.detail_domains.length>0&&<section className="pb-16"><div className="container-site"><h2 className="text-center text-3xl font-black">{english?"Fields of intervention":"Domaines d’intervention"}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6">{(english?item.detail_domains_en:item.detail_domains).map((domain,i)=><div key={domain} className="rounded-2xl border bg-white p-5 text-center font-black"><span className="mx-auto mb-3 block w-fit text-leaf"><Icon index={i}/></span>{domain}</div>)}</div></div></section>}
  <section className="section bg-white"><div className="container-site"><h2 className="text-center text-4xl font-black">{english?"Recent achievements":"Nos réalisations récentes"}</h2><div className="mt-9 grid gap-6 lg:grid-cols-[1fr_1fr_1fr_.9fr]">{item.detail_projects.slice(0,3).map(project=><article key={project.title} className="overflow-hidden rounded-3xl border bg-white shadow-soft"><img src={project.image_url} alt="" className="h-44 w-full object-cover"/><div className="p-5"><h3 className="text-lg font-black">{t(project.title,project.title_en)}</h3><p className="mt-2 text-xs font-bold text-leaf">{project.client} · {project.country}</p><p className="mt-3 text-sm text-slate-600">{t(project.result,project.result_en)}</p></div></article>)}<aside className="rounded-3xl bg-mint p-7"><p className="text-5xl font-black text-leaf">“</p><p className="leading-7">{t(item.detail_testimonial.quote,item.detail_testimonial.quote_en)}</p><p className="mt-6 font-black">{item.detail_testimonial.name}</p><p className="text-sm text-slate-600">{t(item.detail_testimonial.role,item.detail_testimonial.role_en)} · {item.detail_testimonial.organization}</p></aside></div></div></section>
  <section className="section"><div className="container-site"><div className="relative overflow-hidden rounded-[2rem] bg-forest p-8 text-white shadow-xl lg:p-12"><img src={item.cta_image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-20"/><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><h2 className="max-w-3xl text-3xl font-black text-white lg:text-4xl">{t(item.final_title,item.final_title_en)}</h2><p className="mt-3 max-w-2xl text-white/75">{t(item.final_text,item.final_text_en)}</p></div><div className="flex flex-col gap-3"><Link href="/contact" className="rounded-xl bg-[#159447] px-6 py-4 text-center font-black text-white">{english?"Request a consultation":"Demander une consultation"}</Link><Link href="/contact?objet=proposition-technique" className="rounded-xl bg-orange px-6 py-4 text-center font-black text-white">{english?"Request a proposal":"Demander une proposition"}</Link></div></div></div></div></section>
 </main>
}
