import Link from "next/link";
import { ArrowRight, CheckCircle2, ChevronRight, ShieldCheck } from "lucide-react";
import type { nutritionPrograms } from "@/data/nutrition-programs";
import { programmeStandards } from "@/data/nutrition-programs";

type Program=(typeof nutritionPrograms)[number];
export default function NutritionProgramPage({program,en,managed}:{program:Program;en:boolean;managed?:any}){
 const sections=(managed?.sections||[]) as Array<{title?:string;text?:string;items?:string[]}>;
 const title=managed?.title||(en?program.titleEn:program.titleFr),tagline=managed?.eyebrow||(en?program.taglineEn:program.taglineFr),description=managed?.description||(en?program.descriptionEn:program.descriptionFr);
 const features=sections[0]?.items?.length?sections[0].items:(en?program.featuresEn:program.featuresFr),benefits=sections[1]?.items?.length?sections[1].items:(en?program.benefitsEn:program.benefitsFr),standards=sections[2]?.items?.length?sections[2].items:programmeStandards[en?"en":"fr"];
 const Icon=program.icon;
 return <main className="min-h-screen bg-white text-forest" style={{"--program":program.color,"--program-soft":program.soft} as React.CSSProperties}>
  <section className="container-site py-8 md:py-12"><nav className="flex items-center gap-2 text-xs font-bold text-slate-500"><Link href="/teleconseils">{en?"Specialized programmes":"Programmes spécialisés"}</Link><ChevronRight className="h-3"/><span className="text-forest">{title}</span></nav>
   <div className="mt-8 grid min-h-[570px] items-center gap-10 lg:grid-cols-[.9fr_1.1fr]">
    <article><span className="grid h-14 w-14 place-items-center rounded-full" style={{background:program.soft,color:program.color}}><Icon className="h-7 w-7"/></span><h1 className="mt-5 max-w-2xl text-4xl font-black leading-[1.08] md:text-6xl">{title}</h1><h2 className="mt-4 text-xl font-black" style={{color:program.color}}>{tagline}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{description}</p><div className="mt-7 grid gap-3">{features.map(item=><p key={item} className="flex items-center gap-3 font-semibold text-slate-700"><CheckCircle2 className="h-5 shrink-0" style={{color:program.color}}/>{item}</p>)}</div><div className="mt-9 flex flex-wrap gap-4"><Link href={`/rendez-vous?programme=${program.slug}`} className="inline-flex items-center rounded-full px-7 py-4 font-black text-white shadow-lg" style={{background:program.color}}>{managed?.cta_label||(en?"Start now":"Commencer maintenant")}<ArrowRight className="ml-2 h-4"/></Link><a href="#benefices" className="inline-flex items-center px-3 py-4 font-black">{managed?.secondary_cta_label||(en?"Learn more":"En savoir plus")}<ArrowRight className="ml-2 h-4"/></a></div></article>
    <ProgramDashboard program={program} en={en}/>
   </div>
   <div id="benefices" className="mt-8 grid gap-3 rounded-3xl border p-5 md:grid-cols-4" style={{background:program.soft}}>{benefits.map(item=><div key={item} className="flex items-center gap-3 px-3 py-3 text-sm font-black"><ShieldCheck className="h-6 shrink-0" style={{color:program.color}}/>{item}</div>)}</div>
   <div className="mt-6 grid gap-3 rounded-3xl bg-slate-50 p-5 md:grid-cols-4">{standards.map(item=><div key={item} className="flex items-center gap-3 px-3 py-3 text-sm font-bold text-slate-600"><CheckCircle2 className="h-5 shrink-0" style={{color:program.color}}/>{item}</div>)}</div>
  </section>
 </main>
}

function ProgramDashboard({program,en}:{program:Program;en:boolean}){const sports=program.key==="sport";return <div className="relative min-h-[510px] rounded-[2.2rem] p-4 md:p-8" style={{background:`linear-gradient(135deg,${program.soft},#fff)`}}>{sports&&program.image&&<img src={program.image} alt="" className="absolute inset-y-0 left-0 h-full w-[55%] object-cover object-left rounded-[2.2rem] opacity-95"/>}<div className={`relative grid h-full items-center gap-4 ${sports?"ml-auto w-[76%] grid-cols-[.42fr_.58fr]":"grid-cols-[.42fr_.58fr]"}`}><div className="rounded-[2.3rem] border-[7px] border-slate-900 bg-white p-5 shadow-2xl"><div className="mx-auto mb-4 h-5 w-24 rounded-full bg-slate-900"/><p className="text-xs font-black" style={{color:program.color}}>{en?"My follow-up":"Mon suivi"}</p><h3 className="mt-1 text-xl font-black">{program.key==="infant"?(en?"My child":"Mon enfant"):(en?"Dashboard":"Tableau de bord")}</h3><div className="mt-5 grid grid-cols-2 gap-2">{[en?"Current":"Actuel",en?"Goal":"Objectif",en?"Progress":"Progrès",en?"Status":"Statut"].map((x,i)=><div key={x} className="rounded-xl bg-slate-50 p-3"><small>{x}</small><b className="mt-1 block">{i===3?(en?"Good":"Bon"):["74.2 kg","67.0 kg","76%",""][i]}</b></div>)}</div><MiniChart color={program.color}/><div className="mt-5 grid gap-2">{[en?"Nutrition intake":"Apports nutritionnels",en?"Advice & reminders":"Conseils et rappels"].map(x=><div key={x} className="rounded-xl border p-3 text-xs font-bold">{x}<ArrowRight className="float-right h-3"/></div>)}</div></div><div className="rounded-3xl border bg-white p-6 shadow-xl"><p className="text-sm font-black">{en?"Monthly overview":"Vue mensuelle"}</p><div className="mt-5 grid grid-cols-3 gap-3">{["76%","+2.4","24.1"].map((x,i)=><div key={i} className="rounded-xl bg-slate-50 p-3"><small>{[en?"Score":"Score",en?"Change":"Évolution",en?"Indicator":"Indicateur"][i]}</small><b className="mt-2 block text-xl" style={{color:program.color}}>{x}</b></div>)}</div><h4 className="mt-6 font-black">{en?"Trend":"Évolution"}</h4><MiniChart color={program.color}/><div className="mt-5 grid gap-3">{[75,55,90,65].map((v,i)=><div key={i}><div className="mb-1 flex justify-between text-xs"><span>{[en?"Protein":"Protéines",en?"Iron":"Fer",en?"Hydration":"Hydratation",en?"Calcium":"Calcium"][i]}</span><b>{v}%</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full" style={{width:`${v}%`,background:program.color}}/></div></div>)}</div></div></div></div>}
function MiniChart({color}:{color:string}){return <svg viewBox="0 0 300 100" className="mt-5 h-24 w-full overflow-visible"><path d="M5 78 C45 70,55 84,90 60 S140 64,165 38 S215 55,295 18" fill="none" stroke={color} strokeWidth="4"/><path d="M5 90H295" stroke="#e2e8f0"/><path d="M5 60H295M5 30H295" stroke="#f1f5f9"/></svg>}
