import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { sendSystemEmail } from "@/lib/system-email";
import { cookies } from "next/headers";
import { hasLocalAdminMode, hasSupabaseConfig } from "@/lib/supabase/config";

const principalEmails=(process.env.ADMIN_ALERT_EMAILS||"pauln.zebaze@gmail.com,contact@nutvitaglobalis.com").split(",").map(value=>value.trim()).filter(Boolean);
const roles=["super_admin","content_admin","recruitment_admin","health_admin","finance_admin"];

export async function POST(request:Request){if(hasLocalAdminMode()&&!hasSupabaseConfig()){if((await cookies()).get('nutvita_local_admin')?.value!=='1')return NextResponse.json({message:'Session locale requise.'},{status:401});const body=await request.json();if(body.action==='reset_password')return NextResponse.json({message:'La reinitialisation email sera disponible apres connexion a Supabase.'},{status:400});return NextResponse.json({ok:true,user:{id:body.id||crypto.randomUUID(),email:body.email,full_name:body.full_name,role:body.role||'content_admin',active:body.active??true,created_at:new Date().toISOString()},local:true})}const session=await createClient(),{data:{user}}=await session.auth.getUser();if(!user)return NextResponse.json({message:"Non authentifie."},{status:401});const actorId=user.id;const {data:actor}=await session.from("admin_users").select("id,email,role").eq("id",actorId).eq("active",true).single();if(actor?.role!=="super_admin")return NextResponse.json({message:"Super-administrateur requis."},{status:403});const body=await request.json(),service=createAdminClient(),action=String(body.action||"create"),headers=request.headers,ip=(headers.get("x-forwarded-for")||"").split(",")[0]||null,userAgent=headers.get("user-agent");
  async function log(targetId:string|null,details:Record<string,unknown>={}){await service.from("admin_activity_logs").insert({admin_id:actorId,target_admin_id:targetId,action,resource_id:targetId,ip_address:ip,user_agent:userAgent,details})}
  async function alertPrincipals(templateId:string,variables:Record<string,string>,metadata:Record<string,unknown>){for(const email of principalEmails)await sendSystemEmail(service,templateId,email,{...variables,action_url:`${process.env.NEXT_PUBLIC_SITE_URL||""}/admin/utilisateurs-admin`},metadata)}
  if(action!=="create"){
    const {data:target}=await service.from("admin_users").select("*").eq("id",String(body.id)).maybeSingle();if(!target)return NextResponse.json({message:"Administrateur introuvable."},{status:404});
    if(action==="update"){if(!roles.includes(body.role))return NextResponse.json({message:"Role invalide."},{status:400});if(target.id===actorId&&body.active===false)return NextResponse.json({message:"Vous ne pouvez pas desactiver votre propre compte."},{status:400});const {error}=await service.from("admin_users").update({role:body.role,active:Boolean(body.active),permissions:Array.isArray(body.permissions)?body.permissions:[]}).eq("id",target.id);if(error)return NextResponse.json({message:error.message},{status:400});await log(target.id,{before:{role:target.role,active:target.active},after:{role:body.role,active:Boolean(body.active)}});return NextResponse.json({ok:true})}
    if(action==="remove"){if(target.id===actorId)return NextResponse.json({message:"Vous ne pouvez pas retirer votre propre acces."},{status:400});const {error}=await service.from("admin_users").delete().eq("id",target.id);if(error)return NextResponse.json({message:error.message},{status:400});await service.from("admin_activity_logs").insert({admin_id:actorId,action:"remove",resource_id:target.id,ip_address:ip,user_agent:userAgent,details:{email:target.email,role:target.role}});await alertPrincipals("admin_access_removed_alert",{admin_email:target.email,actor_email:actor.email},{target_email:target.email,actor_id:actorId});return NextResponse.json({ok:true})}
    if(action==="reset_password"){const redirectTo=`${process.env.NEXT_PUBLIC_SITE_URL||new URL(request.url).origin}/mot-de-passe-oublie`;const {error}=await service.auth.resetPasswordForEmail(target.email,{redirectTo});if(error)return NextResponse.json({message:error.message},{status:400});await log(target.id,{email:target.email});await sendSystemEmail(service,"admin_password_reset",target.email,{name:target.full_name||"Administrateur"},{target_admin_id:target.id});return NextResponse.json({ok:true})}
    return NextResponse.json({message:"Action inconnue."},{status:400});
  }
  if(body.password!==body.password_confirmation||String(body.password).length<8)return NextResponse.json({message:"Mot de passe invalide ou confirmation differente."},{status:400});if(!roles.includes(body.role))return NextResponse.json({message:"Role invalide."},{status:400});const metadata={full_name:body.full_name,whatsapp_phone:body.whatsapp_phone,country:body.country,country_code:body.country_code,state_region:body.state_region,city:body.city==="__other"?body.other_city:body.city,other_city:body.other_city,account_type:"admin",accepted_terms_at:new Date().toISOString(),accepted_privacy_at:new Date().toISOString()};const created=await service.auth.admin.createUser({email:body.email,password:body.password,email_confirm:true,user_metadata:metadata});if(created.error||!created.data.user)return NextResponse.json({message:created.error?.message||"Creation impossible."},{status:400});const {error}=await service.from("admin_users").insert({id:created.data.user.id,email:body.email,full_name:body.full_name,whatsapp_phone:body.whatsapp_phone,country:body.country,country_code:body.country_code,state_region:body.state_region,city:metadata.city,other_city:body.other_city,role:body.role,active:true,invited_by:actorId,accepted_terms_at:metadata.accepted_terms_at,accepted_privacy_at:metadata.accepted_privacy_at});if(error)return NextResponse.json({message:error.message},{status:400});await log(created.data.user.id,{email:body.email,role:body.role});await sendSystemEmail(service,"admin_invitation",body.email,{name:body.full_name},{admin_id:created.data.user.id});await alertPrincipals("admin_created_alert",{admin_email:body.email,role:body.role,actor_email:actor.email},{admin_id:created.data.user.id,actor_id:actorId});return NextResponse.json({ok:true,user:{id:created.data.user.id,email:body.email,full_name:body.full_name,role:body.role,active:true,created_at:new Date().toISOString()}})
}



