export type GrowthRow=Record<string,any>;
export type GrowthAlert={alert_type:string;severity:"info"|"warning"|"critical";title:string;message:string};
export type ParentAdvice={category:string;title:string;text:string};
export type ChildGrowthAnalysis={summary:string;positives:string[];attentionPoints:string[];practicalAdvice:string[];parentAdvice:ParentAdvice[];consultationRecommended:boolean;alerts:GrowthAlert[]};

const number=(value:any)=>value===null||value===undefined||value===""?null:Number(value);
const days=(a:any,b:any)=>(+new Date(b)-+new Date(a))/86400000;

export function analyzeChildGrowth(child:GrowthRow,source:GrowthRow[]):ChildGrowthAnalysis{
  const rows=[...source].sort((a,b)=>+new Date(a.measured_at)-+new Date(b.measured_at)),latest=rows.at(-1),previous=rows.at(-2);
  const alerts:GrowthAlert[]=[],positives:string[]=[],attentionPoints:string[]=[],practicalAdvice:string[]=[],parentAdvice:ParentAdvice[]=[];
  if(!latest)return{summary:"Aucune mesure n est encore disponible.",positives,attentionPoints:["Ajoutez une premiere mesure pour commencer le suivi."],practicalAdvice:["Mesurez le poids et la taille dans des conditions comparables."],parentAdvice:baseAdvice(child,0,[]),consultationRecommended:false,alerts:[{alert_type:"missing_data",severity:"info",title:"Donnees a completer",message:"Aucune mesure de croissance n est disponible."}]};
  const age=number(latest.age_months)??Math.max(0,days(child.birth_date,latest.measured_at)/30.4375),weight=number(latest.weight_kg),muac=number(latest.muac_cm);
  if(previous&&weight!==null&&number(previous.weight_kg)!==null){const change=weight-Number(previous.weight_kg),elapsed=days(previous.measured_at,latest.measured_at);if(change<-.05){alerts.push({alert_type:"weight_loss",severity:"critical",title:"Perte de poids",message:`Le poids a diminue de ${Math.abs(change).toFixed(2)} kg depuis la mesure precedente.`});attentionPoints.push("Une perte de poids a ete observee.")}else if(elapsed>=30&&Math.abs(change)<.1){alerts.push({alert_type:"weight_stagnation",severity:"warning",title:"Stagnation ponderale",message:"Le poids a peu evolue depuis au moins un mois."});attentionPoints.push("Le poids semble stagner.")}else if(change>0)positives.push("Le poids progresse depuis la mesure precedente.")}
  if(number(latest.height_for_age_z)!==null&&Number(latest.height_for_age_z)<-2){alerts.push({alert_type:"stunting_risk",severity:Number(latest.height_for_age_z)<-3?"critical":"warning",title:"Risque de retard de croissance",message:"La taille-pour-age est sous le seuil de vigilance OMS."});attentionPoints.push("La croissance lineaire necessite une verification professionnelle.")}
  if(latest.edema||number(latest.weight_for_height_z)!==null&&Number(latest.weight_for_height_z)<-2){alerts.push({alert_type:"acute_malnutrition_risk",severity:"critical",title:"Risque de malnutrition aigue",message:latest.edema?"Des oedemes nutritionnels ont ete signales.":"Le poids-pour-taille est sous le seuil de vigilance OMS."});attentionPoints.push("Un risque de malnutrition aigue doit etre evalue rapidement.")}
  if(age>=6&&age<=59&&muac!==null&&muac<12.5){alerts.push({alert_type:"low_muac",severity:muac<11.5?"critical":"warning",title:"PB / MUAC bas",message:`Le PB/MUAC mesure ${muac.toFixed(1)} cm.`});attentionPoints.push("Le perimetre brachial est bas pour la tranche d age.")}
  const recentIllness=rows.slice(-3).filter(row=>String(row.recent_illnesses||"").trim().length>2);if(recentIllness.length>=2){alerts.push({alert_type:"recurrent_illness",severity:"warning",title:"Maladies recentes repetees",message:"Des maladies ont ete renseignees dans plusieurs mesures recentes."});attentionPoints.push("Les maladies recentes peuvent affecter l appetit et la croissance.")}
  const stale=days(latest.measured_at,new Date());if(stale>60){alerts.push({alert_type:"missing_recent_data",severity:"info",title:"Mesure ancienne",message:`Aucune nouvelle mesure depuis ${Math.floor(stale)} jours.`});attentionPoints.push("Les donnees ne sont plus recentes.")}
  if(!alerts.some(a=>a.severity!=="info"))positives.push("Aucune tendance preoccupante n est detectee dans les donnees disponibles.");
  if(number(latest.weight_for_age_z)===null)practicalAdvice.push("Importez les references OMS officielles pour activer l interpretation complete des z-scores.");
  practicalAdvice.push("Poursuivez des mesures regulieres avec le meme materiel lorsque possible.");
  if(recentIllness.length)practicalAdvice.push("Pendant et apres une maladie, proposez souvent des aliments et liquides adaptes a l age.");
  parentAdvice.push(...baseAdvice(child,age,alerts));
  const critical=alerts.some(a=>a.severity==="critical"),summary=critical?`Les nouvelles donnees de ${child.full_name} comportent un signe qui doit etre verifie rapidement par un professionnel.`:alerts.some(a=>a.severity==="warning")?`La croissance de ${child.full_name} presente des points d attention. Une surveillance rapprochee est recommandee.`:`La croissance de ${child.full_name} evolue sans alerte majeure dans les donnees disponibles.`;
  return{summary,positives,attentionPoints,practicalAdvice,parentAdvice,consultationRecommended:critical||alerts.filter(a=>a.severity==="warning").length>=2,alerts};
}

function baseAdvice(child:GrowthRow,age:number,alerts:GrowthAlert[]):ParentAdvice[]{const items:ParentAdvice[]=[];if(child.currently_breastfed||age<6)items.push({category:"Allaitement",title:"Soutenir l allaitement",text:"Allaitez selon les besoins et demandez de l aide en cas de douleur, difficulte ou baisse des tetees."});if(age>=6&&age<24)items.push({category:"Alimentation complementaire",title:"Completer progressivement",text:"Proposez des aliments varies, riches en energie et nutriments, avec une texture adaptee a l age."});if(age>=6)items.push({category:"Diversification alimentaire",title:"Varier les groupes d aliments",text:"Associez chaque jour aliments de base, legumes ou fruits et sources de proteines disponibles."});items.push({category:"Hygiene alimentaire",title:"Prevenir les infections",text:"Lavez les mains, utilisez une eau sure et conservez les aliments a bonne temperature."});items.push({category:"Prevention de la malnutrition",title:"Suivre regulierement",text:"Surveillez l appetit, le poids et l activite de l enfant, surtout apres une maladie."});if(alerts.length)items.push({category:"Signes d alerte",title:"Observer l etat general",text:"Consultez si l enfant mange nettement moins, perd du poids, presente des oedemes, devient tres fatigue ou si son etat se degrade."});if(alerts.some(a=>a.severity==="critical"))items.push({category:"Quand consulter",title:"Avis professionnel rapide",text:"Une alerte importante a ete detectee. Faites evaluer l enfant rapidement par un professionnel de sante."});items.push({category:"Nutrition pendant la maladie",title:"Maintenir les apports",text:"Continuez l allaitement et proposez de petites quantites frequentes ainsi que des liquides adaptes."});items.push({category:"Nutrition apres maladie",title:"Favoriser le rattrapage",text:"Apres la maladie, ajoutez un repas ou une collation adaptee pendant une courte periode selon les conseils locaux."});return items;}
