export const PLATFORM_PRINCIPAL_EMAILS=["pauln.zebaze@gmail.com","contact@nutvitaglobalis.com"]as const;
export type PlatformServiceKey="client"|"academy"|"health"|"child_growth"|"teleconsultation"|"medical_consultation"|"survey"|"project_management"|"recruitment"|"nutritrack"|"maximus"|"catering"|"administration";
export type PlatformRole="client"|"candidate"|"student"|"nutritionist"|"specialist"|"instructor"|"staff"|"admin"|"super_admin";
export type PlatformService={key:PlatformServiceKey;title:string;titleEn?:string;description:string;roles:Array<{key:PlatformRole;label:string;href:string}>};
export const platformServices:PlatformService[]=[
{key:"client",title:"Espace client",titleEn:"Client space",description:"Achats, factures, profil et services actifs.",roles:[{key:"client",label:"Client",href:"/espace-client"}]},
{key:"academy",title:"NutVitaGlobalis Academy",description:"Formations, évaluations, classes et certificats.",roles:[{key:"student",label:"Apprenant",href:"/api/academy/sso?role=student"},{key:"instructor",label:"Formateur",href:"/api/academy/sso?role=instructor"},{key:"admin",label:"Administration Academy",href:"/api/academy/sso?role=admin"}]},
{key:"health",title:"Suivi santé personnalisé",titleEn:"Personalized health monitoring",description:"Dossier, tendances, analyses et rapports.",roles:[{key:"client",label:"Client",href:"/espace-client/dossier"},{key:"nutritionist",label:"Nutritionniste",href:"/partenaire/clients"},{key:"admin",label:"Administration santé",href:"/admin/sante"}]},
{key:"child_growth",title:"Croissance enfant",titleEn:"Child growth",description:"Mesures, courbes et analyses pédiatriques.",roles:[{key:"client",label:"Parent",href:"/espace-client/croissance-enfant"},{key:"nutritionist",label:"Nutritionniste",href:"/partenaire/clients"},{key:"admin",label:"Administration croissance",href:"/admin/croissance-enfant"}]},
{key:"teleconsultation",title:"Consultations diététiques et nutritionnelles",titleEn:"Dietetic and nutrition consultations",description:"Consultations, messages et appels vidéo.",roles:[{key:"client",label:"Client",href:"/espace-client/consultations"},{key:"nutritionist",label:"Nutritionniste",href:"/partenaire/consultations"},{key:"admin",label:"Administration consultations",href:"/admin/teleconseils"}]},
{key:"medical_consultation",title:"Consultations médicales spécialisées",titleEn:"Specialist medical consultations",description:"Consultations médicales coordonnées et sécurisées.",roles:[{key:"client",label:"Client",href:"/espace-client/consultations-medicales"},{key:"specialist",label:"Médecin spécialiste",href:"/medecin-specialiste"},{key:"admin",label:"Administration médicale",href:"/admin/medecins-specialistes"}]},
{key:"survey",title:"Enquêtes de sécurité alimentaire et nutrition (SANSurvey)",titleEn:"Food security and nutrition surveys (SANSurvey)",description:"Conception, collecte, analyse et rapports.",roles:[{key:"client",label:"Utilisateur",href:"/surveys"},{key:"admin",label:"Administration",href:"/surveys"}]},
{key:"project_management",title:"Gestion des projets, programmes et portefeuilles (ProManage)",titleEn:"Project, programme and portfolio management (ProManage)",description:"Pilotage des projets, programmes et portefeuilles.",roles:[{key:"client",label:"Utilisateur",href:"/op-management"},{key:"admin",label:"Administration",href:"/op-management"}]},
{key:"recruitment",title:"Mes candidatures",titleEn:"My applications",description:"Suivi de toutes vos candidatures.",roles:[{key:"candidate",label:"Candidat",href:"/candidatures"},{key:"admin",label:"Administration recrutement",href:"/admin/recrutement"}]},
{key:"nutritrack",title:"Prise en charge de la malnutrition aiguë (NutriTrack)",description:"Prise en charge et pilotage de la malnutrition.",roles:[{key:"client",label:"Utilisateur terrain",href:"/nutritrack"},{key:"admin",label:"Administration NutriTrack",href:"/super-admin/nutritrack"}]},
{key:"catering",title:"Service de restauration",titleEn:"Catering service",description:"Menus du jour, commandes et livraisons.",roles:[{key:"client",label:"Client",href:"/restauration/commander"},{key:"staff",label:"Commercial ou livreur",href:"/maximus/sales/customer-orders"},{key:"admin",label:"Administration restauration",href:"/maximus/sales/customer-orders"}]},
{key:"maximus",title:"Maximus",description:"Gestion interne du cabinet.",roles:[{key:"staff",label:"Membre du personnel",href:"/maximus"},{key:"admin",label:"Administration Maximus",href:"/maximus"}]},
{key:"administration",title:"Administration NutVitaGlobalis",description:"Configuration et contrôle transversal.",roles:[{key:"super_admin",label:"Super administrateur",href:"/admin"}]},];
export function isPrincipalEmail(email?:string|null){return PLATFORM_PRINCIPAL_EMAILS.includes(String(email||"").trim().toLowerCase()as(typeof PLATFORM_PRINCIPAL_EMAILS)[number])}export function findPlatformRole(service:string,role:string){return platformServices.find(x=>x.key===service)?.roles.find(x=>x.key===role)}
