"use client";

export type ImportedRecruitmentQuestion={prompt:string;options:string[];correctAnswers:string[];detectedType:"qcm"|"multi_qcm"|"open"};
const clean=(value:string)=>value.replace(/\u00a0/g," ").replace(/\s+/g," ").trim();
const tokens=(value:string)=>value.replace(/^[^:]*:/,"").split(/[|,;\/]/).map(clean).filter(Boolean);
function normalize(prompt:string,options:string[],answers:string[]):ImportedRecruitmentQuestion{const resolved=answers.map(answer=>{const letter=/^[A-Z]$/i.test(answer)?answer.toUpperCase().charCodeAt(0)-65:-1,n=Number(answer),index=letter>=0?letter:Number.isInteger(n)?(n>=1?n-1:n):options.findIndex(x=>clean(x).toLowerCase()===clean(answer).toLowerCase());return options[index]||answer}).filter(Boolean);return{prompt:clean(prompt),options:options.map(clean).filter(Boolean),correctAnswers:[...new Set(resolved)],detectedType:options.length<2?"open":resolved.length>1?"multi_qcm":"qcm"}}
function html(source:string){const doc=new DOMParser().parseFromString(source,"text/html");let blocks=[...doc.querySelectorAll<HTMLElement>("[data-question],.quiz-question,.question,fieldset")];if(!blocks.length)blocks=[...doc.querySelectorAll<HTMLElement>("article,section")].filter(x=>x.querySelectorAll("input,[data-option],li").length>=2);return blocks.map(block=>{const prompt=block.querySelector<HTMLElement>("[data-prompt],.question-text,.prompt,legend,h1,h2,h3,h4")?.textContent||"",inputs=[...block.querySelectorAll<HTMLInputElement>("input[type=radio],input[type=checkbox]")],els=inputs.length?inputs.map(x=>x.closest("label")||x.parentElement).filter(Boolean) as HTMLElement[]:[...block.querySelectorAll<HTMLElement>("[data-option],.option,li")],options=els.map(x=>clean(x.textContent||"").replace(/^\s*(?:[A-Z]|\d+)[).:\-]\s*/i,"")),answers:string[]=[];els.forEach((el,i)=>{const mark=`${el.getAttribute("data-correct")||""} ${el.className}`;if(inputs[i]?.checked||/\b(true|yes|correct|bonne?)\b/i.test(mark))answers.push(String(i+1))});const explicit=block.querySelector<HTMLElement>("[data-answer],.correct-answer,.answer,.reponse,.réponse")?.textContent||[...block.querySelectorAll<HTMLElement>("p,div")].map(x=>clean(x.textContent||"")).find(x=>/^(?:réponse|reponses|answer|correct)\s*:/i.test(x))||"";if(!answers.length&&explicit)answers.push(...tokens(explicit));return normalize(prompt,options,answers)}).filter(x=>x.prompt)}
function text(source:string){return source.replace(/\r/g,"\n").split(/\n\s*(?=(?:question\s*)?\d+\s*[).:\-])/i).map(block=>{const lines=block.split("\n").map(clean).filter(Boolean),opts=lines.filter(x=>/^(?:[A-Z]|\d+)[).:\-]\s+/.test(x)),answer=lines.find(x=>/^(?:réponse|reponses|answer|correct)\s*:/i.test(x))||"",prompt=lines.filter(x=>!opts.includes(x)&&x!==answer).join(" ").replace(/^\s*(?:question\s*)?\d+\s*[).:\-]\s*/i,"");return normalize(prompt,opts.map(x=>x.replace(/^\s*(?:[A-Z]|\d+)[).:\-]\s*/i,"")),tokens(answer))}).filter(x=>x.prompt)}
function csv(source:string){const rows:string[][]=[];let row:string[]=[],value="",quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(value.trim());value=""}else if(/[\r\n]/.test(c)&&!quoted){if(c==="\r"&&source[i+1]==="\n")i++;row.push(value.trim());if(row.some(Boolean))rows.push(row);row=[];value=""}else value+=c}row.push(value.trim());if(row.some(Boolean))rows.push(row);return rows}
export async function importRecruitmentQuestionFile(file:File){const source=await file.text(),name=file.name.toLowerCase();if(/\.html?$/.test(name))return html(source);if(name.endsWith(".json")){const parsed=JSON.parse(source),rows=Array.isArray(parsed)?parsed:parsed.questions||[];return rows.map((x:any)=>normalize(x.prompt||x.question||"",Array.isArray(x.options)?x.options:String(x.options||"").split("|"),Array.isArray(x.correctAnswers)?x.correctAnswers:Array.isArray(x.correct)?x.correct:String(x.correct_answer||x.answer||"").split(/[|,;]/)))}if(name.endsWith(".csv")){const [headers,...rows]=csv(source);return rows.map(row=>{const x=Object.fromEntries(headers.map((h,i)=>[h,row[i]||""])) as any;return normalize(x.prompt||x.question||"",String(x.options||"").split("|"),String(x.correct_answer||x.answer||"").split(/[|,;]/))})}return text(source)}
