import { createClient } from "@/lib/supabase/server";
import { hasSupabaseConfig } from "@/lib/supabase/config";
import { expertiseDetailDefaults, type ExpertiseDetailConfig } from "@/data/expertise-detail-defaults";
export type Bi={title:string;title_en:string;description?:string;description_en?:string};
export type ResearchSettings={
 id:number; hero_badge:string;hero_badge_en:string;hero_title:string;hero_title_en:string;hero_subtitle:string;hero_subtitle_en:string;hero_media_url:string;hero_media_type:"image"|"video";primary_cta_label:string;primary_cta_label_en:string;primary_cta_url:string;secondary_cta_label:string;secondary_cta_label_en:string;secondary_cta_url:string;
 stats:Array<{value:string;label:string;label_en:string;icon:string;order:number}>;
 expertises:Array<Bi&ExpertiseDetailConfig&{slug:string;icon:string;image_url:string;long_description:string;long_description_en:string;gallery:string[];parent:string;order:number;status:"published"|"draft";seo_title:string;seo_title_en:string;seo_description:string;seo_description_en:string;seo_keywords:string;services:Array<Bi&{media_url?:string;attachment_url?:string;video_url?:string}>;faq:Array<{question:string;question_en:string;answer:string;answer_en:string}>}>;
 service_groups:Array<Bi&{items:string[];items_en:string[]}>; reasons:Array<{label:string;label_en:string;icon:string}>; methodology:Array<{title:string;title_en:string;description:string;description_en:string;order:number}>; sectors:Array<{label:string;label_en:string;icon:string}>; technologies:Array<{name:string;description:string;description_en:string;logo_url:string;link:string;order:number}>;
 projects:Array<{slug:string;title:string;title_en:string;client:string;sector:string;sector_en:string;country:string;year:string;objectives:string;objectives_en:string;methodology:string;methodology_en:string;results:string;results_en:string;image_url:string;gallery:string[];testimonial:string;technologies:string[];status:"published"|"draft"}>;
 testimonials:Array<{name:string;role:string;role_en:string;organization:string;photo_url:string;rating:number;testimony:string;testimony_en:string;country:string;status:"published"|"draft"}>; faq:Array<{question:string;question_en:string;answer:string;answer_en:string}>;
 final_title:string;final_title_en:string;final_text:string;final_text_en:string;final_primary_label:string;final_primary_label_en:string;final_primary_url:string;final_secondary_label:string;final_secondary_label_en:string;final_secondary_url:string;
 seo_title:string;seo_title_en:string;seo_description:string;seo_description_en:string;og_image_url:string;twitter_card:string;schema_json_ld:Record<string,unknown>;
};
const ex=(slug:string,icon:string,title:string,title_en:string,description:string,description_en:string,image_url="/images/research-innovation/expertise-gis-v2.png")=>({slug,icon,title,title_en,description,description_en,image_url,long_description:description,long_description_en:description_en,gallery:[],parent:"",order:0,status:"published" as const,seo_title:title,seo_title_en:title_en,seo_description:description,seo_description_en:description_en,seo_keywords:"",services:[],faq:[],...expertiseDetailDefaults(slug,image_url)});
export const defaultResearchSettings:ResearchSettings={id:1,hero_badge:"EXPERTISE · INNOVATION · IMPACT",hero_badge_en:"EXPERTISE · INNOVATION · IMPACT",hero_title:"Une expertise mondiale au service de vos décisions",hero_title_en:"Global expertise serving your decisions",hero_subtitle:"De la recherche scientifique à l'intelligence artificielle, nous concevons des solutions innovantes qui transforment les données en décisions, les projets en impact et les connaissances en résultats mesurables.",hero_subtitle_en:"From scientific research to artificial intelligence, we design innovative solutions that turn data into decisions, projects into impact and knowledge into measurable results.",hero_media_url:"/images/research-innovation/expertise-public-health-v2.png",hero_media_type:"image",primary_cta_label:"Demander une consultation",primary_cta_label_en:"Request a consultation",primary_cta_url:"/contact",secondary_cta_label:"Explorer nos expertises",secondary_cta_label_en:"Explore our expertise",secondary_cta_url:"#expertises",
 stats:[{value:"50+",label:"Projets réalisés",label_en:"Projects delivered",icon:"briefcase",order:1},{value:"20+",label:"Pays accompagnés",label_en:"Countries supported",icon:"globe",order:2},{value:"10+",label:"Domaines d'expertise",label_en:"Fields of expertise",icon:"sparkles",order:3},{value:"1000+",label:"Professionnels formés",label_en:"Professionals trained",icon:"users",order:4},{value:"98 %",label:"Taux de satisfaction",label_en:"Satisfaction rate",icon:"chart",order:5}],
 expertises:[
  ex("nutrition-teleconsultation","heart","Nutrition clinique & téléconsultation","Clinical nutrition & teleconsultation","Interventions nutritionnelles fondées sur les preuves, consultations en présentiel ou à distance et continuité du suivi.","Evidence-based nutrition interventions, in-person or remote consultations and continuity of care.","/images/research-innovation/project-nutrition-survey.png"),
  ex("sante-publique-securite-alimentaire","leaf","Santé publique & sécurité alimentaire","Public health & food security","Politiques et programmes de santé, systèmes alimentaires, vulnérabilité et moyens d'existence analysés dans une même approche.","Health policies and programmes, food systems, vulnerability and livelihoods addressed through one integrated approach.","/images/research-innovation/expertise-public-health-v2.png"),
  ex("recherche-enquetes-donnees","microscope","Recherche scientifique, enquêtes & données","Scientific research, surveys & data","Protocoles, études, enquêtes SMART, collecte robuste, contrôle qualité et recherche opérationnelle.","Protocols, studies, SMART surveys, robust data collection, quality control and operational research.","/images/research-innovation/expertise-research-data-v2.png"),
  ex("ia-developpement-logiciels","brain","Intelligence artificielle & développement de logiciels","Artificial intelligence & software development","Modèles responsables et plateformes métier sécurisées pour accélérer l'analyse, la décision et les opérations.","Responsible models and secure business platforms that accelerate analysis, decisions and operations.","/images/research-innovation/expertise-ai-software-v2.png"),
  ex("sig-cartographie","map","SIG & cartographie","GIS & mapping","Analyse spatiale, cartographie décisionnelle, visualisation et suivi territorial.","Spatial analysis, decision mapping, visualization and territorial monitoring.","/images/research-innovation/expertise-gis-v2.png"),
  ex("monitoring-evaluation-impact","chart","Monitoring, Evaluation, Learning & Impact","Monitoring, Evaluation, Learning & Impact","Cadres de résultats, indicateurs, apprentissage, redevabilité et mesure rigoureuse de l'impact.","Results frameworks, indicators, learning, accountability and rigorous impact measurement.","/images/research-innovation/expertise-mel-v2.png"),
  ex("formation-renforcement-capacites","graduation","Formation & renforcement des capacités","Training & capacity strengthening","Parcours pratiques, coaching et transfert de compétences pour des résultats durables.","Practical learning pathways, coaching and skills transfer for sustainable results.","/images/research-innovation/expertise-training-v2.png"),
  ex("conseil-strategique","compass","Conseil stratégique & mise en œuvre","Strategic consulting & implementation","De la vision à l'exécution, avec des recommandations exploitables et un accompagnement des décideurs.","From vision to execution, with actionable recommendations and decision-maker support.","/images/research-innovation/expertise-strategic-advisory.png")
 ],
 service_groups:[{title:"Recherche scientifique",title_en:"Scientific research",description:"",description_en:"",items:["Protocoles","Revues systématiques","Publications","Recherche opérationnelle","Études qualitatives","Études quantitatives","Études mixtes"],items_en:["Protocols","Systematic reviews","Publications","Operational research","Qualitative studies","Quantitative studies","Mixed-method studies"]},{title:"Nutrition",title_en:"Nutrition",description:"",description_en:"",items:["Nutrition clinique","Nutrition communautaire","Nutrition maternelle","Nutrition infantile","Diabète","Obésité","Nutrition sportive"],items_en:["Clinical nutrition","Community nutrition","Maternal nutrition","Child nutrition","Diabetes","Obesity","Sports nutrition"]},{title:"Données et numérique",title_en:"Data and digital",description:"",description_en:"",items:["Enquêtes numériques","SIG et cartographie","Tableaux de bord","Intelligence artificielle","Développement logiciel"],items_en:["Digital surveys","GIS and mapping","Dashboards","Artificial intelligence","Software development"]}],
 reasons:["Approche basée sur les preuves|Evidence-based approach|check","Standards OMS / UNICEF / PAM|WHO / UNICEF / WFP standards|shield","Intelligence artificielle responsable|Responsible artificial intelligence|brain","Plateformes numériques sécurisées|Secure digital platforms|laptop","Experts internationaux|International experts|globe","Méthodes SMART|SMART methodologies|clipboard","Solutions personnalisées|Tailored solutions|sparkles","Accompagnement complet|End-to-end support|compass"].map(x=>{const[a,b,c]=x.split("|");return{label:a,label_en:b,icon:c}}),
 methodology:["Analyse|Analysis|Compréhension du contexte et des besoins|Understanding context and needs","Conception|Design|Méthodologie et plan d'action sur mesure|Tailored methodology and action plan","Collecte|Data collection|Données de qualité avec des outils numériques|Quality data using digital tools","Analyse|Analysis|Analyses avancées et intelligence artificielle|Advanced analytics and artificial intelligence","Recommandations|Recommendations|Résultats exploitables et décisions éclairées|Actionable findings and informed decisions","Mise en œuvre|Implementation|Appui technique et opérationnel|Technical and operational support","Suivi et impact|Monitoring and impact|Évaluation continue et amélioration|Continuous evaluation and improvement"].map((x,i)=>{const[a,b,c,d]=x.split("|");return{title:a,title_en:b,description:c,description_en:d,order:i+1}}),
 sectors:["Santé|Health|heart","Agriculture|Agriculture|leaf","Éducation|Education|graduation","Gouvernement|Government|building","Humanitaire|Humanitarian|globe","Entreprises|Business|briefcase","Banques|Banking|bank","ONG|NGOs|users","Universités|Universities|graduation"].map(x=>{const[a,b,c]=x.split("|");return{label:a,label_en:b,icon:c}}),
 technologies:["Next.js","React","Flutter","Supabase","Power BI","ODK","KoboToolbox","QGIS","R","Python","SPSS","Stata","TensorFlow","OpenAI","Claude","Gemini"].map((name,i)=>({name,description:"",description_en:"",logo_url:"",link:"",order:i+1})),
 projects:[{slug:"enquete-nutritionnelle",title:"Enquête nutritionnelle multisectorielle",title_en:"Multisector nutrition survey",client:"Organisation internationale",sector:"Nutrition",sector_en:"Nutrition",country:"Projet international",year:"2026",objectives:"Mesurer la situation nutritionnelle et éclairer la programmation.",objectives_en:"Measure the nutrition situation and inform programming.",methodology:"Enquête numérique, contrôle qualité et analyse statistique.",methodology_en:"Digital survey, quality control and statistical analysis.",results:"Données décisionnelles produites et équipes renforcées.",results_en:"Decision-ready data produced and teams strengthened.",image_url:"/images/research-innovation/project-nutrition-survey.png",gallery:[],testimonial:"",technologies:["ODK","R","Power BI"],status:"published"},{slug:"analyse-sig",title:"Analyse géospatiale et tableau de bord",title_en:"Geospatial analysis and dashboard",client:"Institution publique",sector:"Données",sector_en:"Data",country:"Projet international",year:"2026",objectives:"Transformer des données multisources en décisions territoriales.",objectives_en:"Turn multi-source data into territorial decisions.",methodology:"SIG, intégration de données et visualisation.",methodology_en:"GIS, data integration and visualization.",results:"Priorités géographiques clarifiées.",results_en:"Geographic priorities clarified.",image_url:"/images/research-innovation/expertise-gis-v2.png",gallery:[],testimonial:"",technologies:["QGIS","Python","Supabase"],status:"published"},{slug:"formation-experts",title:"Renforcement des capacités professionnelles",title_en:"Professional capacity strengthening",client:"Réseau de partenaires",sector:"Formation",sector_en:"Training",country:"Multi-pays",year:"2026",objectives:"Renforcer les compétences techniques et managériales.",objectives_en:"Strengthen technical and managerial skills.",methodology:"Ateliers pratiques, coaching et évaluation.",methodology_en:"Practical workshops, coaching and assessment.",results:"Compétences directement applicables consolidées.",results_en:"Immediately applicable skills strengthened.",image_url:"/images/research-innovation/expertise-training-v2.png",gallery:[],testimonial:"",technologies:["Academy","Power BI"],status:"published"}],
 testimonials:[{name:"Dr A. Mensah",role:"Directrice de programme",role_en:"Programme Director",organization:"Organisation internationale",photo_url:"",rating:5,testimony:"Une équipe rigoureuse, réactive et orientée résultats.",testimony_en:"A rigorous, responsive and results-oriented team.",country:"International",status:"published"},{name:"M. Jean-Paul K.",role:"Responsable suivi-évaluation",role_en:"Monitoring and Evaluation Lead",organization:"ONG",photo_url:"",rating:5,testimony:"Les analyses nous ont permis de prendre de meilleures décisions.",testimony_en:"The analyses enabled us to make better decisions.",country:"International",status:"published"}],
 faq:[{question:"Intervenez-vous dans plusieurs pays ?",question_en:"Do you work across countries?",answer:"Oui. Notre approche est mondiale et chaque intervention est adaptée au contexte local.",answer_en:"Yes. Our approach is global and every engagement is adapted to the local context."},{question:"Pouvez-vous accompagner tout le cycle d'un projet ?",question_en:"Can you support the full project cycle?",answer:"Oui, de l'analyse initiale à la mise en œuvre, au suivi-évaluation et à la capitalisation.",answer_en:"Yes, from initial analysis through implementation, monitoring, evaluation and learning."}],
 final_title:"Donnons vie à votre prochain projet.",final_title_en:"Let us bring your next project to life.",final_text:"Construisons ensemble une solution rigoureuse, innovante et mesurable.",final_text_en:"Together, let us build a rigorous, innovative and measurable solution.",final_primary_label:"Contacter un expert",final_primary_label_en:"Contact an expert",final_primary_url:"/contact",final_secondary_label:"Planifier une réunion",final_secondary_label_en:"Schedule a meeting",final_secondary_url:"/contact?objet=reunion",seo_title:"Recherche scientifique, innovation et conseil stratégique | NutVitaGlobalis",seo_title_en:"Scientific research, innovation and strategic consulting | NutVitaGlobalis",seo_description:"Recherche, données, IA, conseil, développement numérique, formation et mise en œuvre pour des organisations ambitieuses.",seo_description_en:"Research, data, AI, consulting, digital development, training and implementation for ambitious organizations.",og_image_url:"/images/research-innovation/expertise-public-health-v2.png",twitter_card:"summary_large_image",schema_json_ld:{"@context":"https://schema.org","@type":"ProfessionalService","name":"NutVitaGlobalis Research, Innovation & Strategic Consulting"}};
export function normalizeResearchSettings(input?:Partial<ResearchSettings>|null):ResearchSettings{const merged={...defaultResearchSettings,...(input||{})} as ResearchSettings;const legacySlugs=new Set(["nutrition-clinique","sante-publique","securite-alimentaire","recherche-scientifique","intelligence-artificielle","developpement-logiciels","enquetes-smart","sig-cartographie","monitoring-evaluation","formation-professionnelle","teleconsultation","conseil-strategique"]);if(merged.expertises.length>8&&merged.expertises.every(item=>legacySlugs.has(item.slug)))merged.expertises=defaultResearchSettings.expertises;merged.expertises=merged.expertises.map(item=>{const d=expertiseDetailDefaults(item.slug,item.image_url);const value={...d,...item};for(const key of ["hero_points","hero_panel_items","hero_panel_items_en","detail_stats","detail_services","detail_steps","detail_tools","detail_projects","detail_domains","detail_domains_en"] as const)if(!value[key]?.length)(value as any)[key]=d[key];return value});return merged;}
export async function getResearchSettings():Promise<ResearchSettings>{if(!hasSupabaseConfig())return defaultResearchSettings;const{data}=await(await createClient()).from("research_innovation_settings").select("*").eq("id",1).maybeSingle();return normalizeResearchSettings(data as Partial<ResearchSettings>|null)}
