import Link from "next/link";
import { Activity, ArrowRight, BadgeCheck, BarChart3, Bell, BrainCircuit, Check, ClipboardList, Clock3, Database, Droplets, EyeOff, FileClock, Gauge, HeartPulse, LineChart, LockKeyhole, Scale, ShieldCheck, Smartphone, Sparkles, TrendingUp, UserRound } from "lucide-react";
import HealthOfferCards from "@/components/HealthOfferCards";
import MedicalDisclaimer from "@/components/MedicalDisclaimer";
import { getClientEntitlements } from "@/lib/client";
import { getCurrentLocale } from "@/lib/i18n-server";
import { createClient } from "@/lib/supabase/server";

export const metadata={title:"Suivi santé autonome | NutVitaGlobalis"};

export default async function HealthTracking(){
 const locale=await getCurrentLocale();
 const english=locale==="en";
 const t=(fr:string,en:string)=>english?en:fr;
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 const access=user?await getClientEntitlements(supabase,user.id):null;
 const {data:plans}=await supabase.from("subscription_plans").select("*").eq("active",true).in("service_type",["health_tracking","child_growth"]).order("service_type").order("tier");
 const fallback=[
  {id:"health-standard",name:"Suivi santé autonome Standard",name_en:"Standard Autonomous Health Monitoring",price_excluding_tax:10000,currency:"XOF",service_type:"health_tracking",tier:"basic",features:[]},
  {id:"health-premium",name:"Suivi santé autonome Premium",name_en:"Premium Autonomous Health Monitoring",price_excluding_tax:20000,currency:"XOF",service_type:"health_tracking",tier:"premium",features:[]},
  {id:"child-standard",name:"Suivi de la croissance de l’enfant Standard",name_en:"Standard Child Growth Monitoring",price_excluding_tax:10000,currency:"XOF",service_type:"child_growth",tier:"basic",features:[]},
  {id:"child-premium",name:"Suivi de la croissance de l’enfant Premium",name_en:"Premium Child Growth Monitoring",price_excluding_tax:20000,currency:"XOF",service_type:"child_growth",tier:"premium",features:[]}
 ];
 const openHref=access?.health?"/api/access/open?service=health&role=client":"#offres";
 const benefits=[[LockKeyhole,t("Données sécurisées et confidentielles","Secure and confidential data")],[Sparkles,t("Analyses fiables et IA prudente","Reliable analysis and careful AI")],[TrendingUp,t("Suivi personnalisé au quotidien","Personalized daily monitoring")],[HeartPulse,t("Recommandations adaptées","Tailored recommendations")]] as const;
 const features=[
  {icon:BarChart3,title:t("Vos tendances","Your trends"),text:t("Suivez l’évolution de vos indicateurs : poids, IMC, glycémie, cholestérol, tension artérielle, activité physique, sommeil et mode de vie.","Track your indicators over time: weight, BMI, blood glucose, cholesterol, blood pressure, physical activity, sleep and lifestyle."),visual:<MiniTrend english={english}/>},
  {icon:BrainCircuit,title:t("Analyse IA prudente","Careful AI analysis"),text:t("L’analyse tient compte de vos mesures, unités, plages de référence et réponses complètes aux questionnaires pour produire des recommandations contextualisées.","Analysis considers your measurements, units, reference ranges and complete questionnaire responses to provide contextualized recommendations."),visual:<div className="grid gap-2 text-xs">{[t("Détection des tendances","Trend detection"),t("Alertes précoces","Early alerts"),t("Comparaison aux normes","Reference comparison"),t("Recommandations ciblées","Targeted recommendations")].map(x=><span key={x} className="flex items-center gap-2 rounded-xl bg-white p-3 shadow-sm"><Check className="h-4 text-leaf"/>{x}</span>)}</div>},
  {icon:FileClock,title:t("Historique privé","Private history"),text:t("Retrouvez toutes vos mesures, questionnaires et rapports dans un espace sécurisé, modifiable uniquement selon vos droits d’accès.","Find all your measurements, questionnaires and reports in a secure space, editable only according to your access rights."),visual:<MiniTable english={english}/>},
  {icon:UserRound,title:t("Croissance de l’enfant","Child growth"),text:t("Chaque enfant dispose d’un dossier strictement cloisonné avec mesures, courbes OMS et analyses propres à son suivi.","Each child has a strictly isolated record with measurements, WHO charts and monitoring-specific analysis."),visual:<GrowthChart/>}
 ];
 const steps=[[UserRound,t("Créez votre compte","Create your account"),t("Inscription rapide et sécurisée.","Fast, secure registration.")],[ClipboardList,t("Enregistrez vos données","Record your data"),t("Manuellement ou via vos outils compatibles.","Manually or through compatible tools.")],[LineChart,t("Visualisez vos tendances","View your trends"),t("Des graphiques clairs pour suivre vos progrès.","Clear charts to monitor progress.")],[Sparkles,t("Recevez des analyses","Receive analysis"),t("Conseils personnalisés et IA prudente.","Personalized guidance and careful AI.")],[Activity,t("Agissez et progressez","Act and progress"),t("Appliquez les recommandations adaptées.","Apply tailored recommendations.")]] as const;
 return <main className="overflow-hidden bg-[#fbfcfa] text-forest"><MedicalDisclaimer/>
  <section className="relative border-b bg-gradient-to-br from-white via-[#f7fbf8] to-[#fff4ed] py-16 lg:py-24"><div className="container-site grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><span className="inline-flex items-center rounded-full bg-mint px-4 py-2 text-xs font-black uppercase tracking-[.17em] text-leaf"><HeartPulse className="mr-2 h-4"/>{t("Suivi santé personnalisé","Personalized health monitoring")}</span><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.04] md:text-7xl">{t("Comprendre vos indicateurs de santé, jour après jour","Understand your health indicators, day after day")}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{t("Enregistrez vos données, visualisez vos tendances et bénéficiez d’analyses fiables et personnalisées pour mieux prendre soin de vous et atteindre vos objectifs santé.","Record your data, visualize trends and receive reliable, personalized analysis to care for your health and reach your goals.")}</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{benefits.map(([Icon,label])=><p key={label} className="flex items-center gap-3 text-sm font-bold"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-mint text-leaf"><Icon className="h-5"/></span>{label}</p>)}</div></div><DashboardMock english={english}/></div></section>

  <section className="py-8"><div className="container-site"><div className="flex flex-wrap items-center justify-between gap-5 rounded-[1.5rem] bg-forest px-7 py-6 text-white shadow-xl md:px-12"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange">{t("Accès personnalisé","Personalized access")}</p><h2 className="mt-2 text-2xl font-black text-white">{t("Choisissez le suivi adapté à vos besoins","Choose the monitoring that fits your needs")}</h2></div><Link href={openHref} className="inline-flex items-center rounded-xl bg-white px-6 py-4 font-black text-forest">{access?.health?t("Ouvrir mon suivi personnalisé","Open my personalized monitoring"):t("Découvrir les formules","Explore plans")}<ArrowRight className="ml-2 h-4"/></Link></div></div></section>

  <section className="section pt-8"><div className="container-site grid gap-6 md:grid-cols-2">{features.map(({icon:Icon,title,text,visual})=><article key={title} className="grid items-center gap-7 rounded-[2rem] border bg-white p-7 shadow-soft lg:grid-cols-[1fr_.85fr]"><div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mint text-leaf"><Icon className="h-6"/></span><h2 className="mt-5 text-2xl font-black">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></div><div className="rounded-2xl bg-slate-50 p-4">{visual}</div></article>)}</div></section>

  <section id="offres" className="section scroll-mt-24 bg-[#f4f8f5]"><div className="container-site"><p className="text-center text-xs font-black uppercase tracking-[.18em] text-leaf">NutVitaGlobalis</p><h2 className="mt-3 text-center text-4xl font-black">{t("Services de suivi santé autonome disponibles","Available autonomous health monitoring services")}</h2><HealthOfferCards plans={(plans?.length?plans:fallback) as any[]} english={english} userConnected={Boolean(user)} access={access}/></div></section>

  <section className="section bg-white"><div className="container-site"><h2 className="text-center text-4xl font-black">{t("Comment ça fonctionne ?","How does it work?")}</h2><div className="mt-12 grid gap-6 md:grid-cols-5">{steps.map(([Icon,title,text],index)=><article key={title} className="relative text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full border-2 border-mint bg-white text-leaf shadow-soft"><Icon className="h-6"/></span><span className="absolute left-[calc(50%+2rem)] top-7 hidden h-px w-[calc(100%-4rem)] bg-emerald-200 md:block last:hidden"/><p className="mt-5 text-xs font-black text-orange">{index+1}</p><h3 className="mt-1 font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div><div className="mt-12 grid gap-4 rounded-[1.75rem] border bg-[#f7fbf8] p-6 md:grid-cols-4">{[[ShieldCheck,t("Confidentialité garantie","Privacy guaranteed"),t("Données chiffrées et protégées.","Encrypted, protected data.")],[Database,t("Données sécurisées","Secure data"),t("Hébergement conforme et fiable.","Reliable, compliant hosting.")],[EyeOff,t("Sans partage non autorisé","No unauthorized sharing"),t("Votre consentement reste central.","Your consent remains central.")],[BadgeCheck,t("Conforme et fiable","Compliant and reliable"),t("Référentiels reconnus et prudence médicale.","Recognized references and medical caution.")]].map(([Icon,title,text]:any)=><div key={title} className="flex gap-3"><Icon className="h-7 shrink-0 text-leaf"/><div><h3 className="font-black">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>)}</div></div></section>

  <section className="pb-16"><div className="container-site"><div className="relative min-h-[430px] overflow-hidden rounded-[2.25rem] bg-forest text-white shadow-xl"><img src="/images/health-monitoring-cta-v1.png" alt={t("Utilisatrice du suivi santé autonome NutVitaGlobalis","NutVitaGlobalis autonomous health monitoring user")} className="absolute inset-0 h-full w-full object-cover object-[28%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-forest/35 to-forest md:via-forest/55"/><div className="relative z-10 flex min-h-[430px] items-center px-7 py-12 md:ml-[38%] md:px-12 lg:ml-[42%]"><div className="max-w-2xl rounded-[1.75rem] bg-forest/65 p-6 backdrop-blur-sm md:bg-transparent md:p-0 md:backdrop-blur-none"><h2 className="text-4xl font-black text-white">{t("Prenez le contrôle de votre santé dès aujourd’hui","Take control of your health today")}</h2><p className="mt-4 max-w-2xl text-white/80">{t("Un suivi régulier, des analyses prudentes et des conseils personnalisés pour une vie plus saine et plus épanouie.","Regular monitoring, careful analysis and personalized guidance for a healthier, more fulfilling life.")}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={openHref} className="btn-primary">{t("Ouvrir mon suivi","Open my monitoring")}<ArrowRight className="ml-2 h-4"/></Link><Link href="/contact" className="inline-flex items-center rounded-full border border-white bg-forest/25 px-6 py-3 font-black text-white">{t("Parler à un nutritionniste","Talk to a dietitian")}</Link></div></div></div></div><div className="mt-6 grid gap-4 text-xs font-bold text-slate-600 sm:grid-cols-2 lg:grid-cols-4">{[[UserRound,t("Supervisé par des professionnels qualifiés","Supervised by qualified professionals")],[ClipboardList,t("Basé sur des preuves scientifiques","Evidence-based")],[Clock3,t("Disponible 24h/24 et 7j/7","Available 24/7")],[Smartphone,t("Accessible sur tous vos appareils","Accessible on all devices")]].map(([Icon,label]:any)=><p key={label} className="flex items-center justify-center gap-2"><Icon className="h-5 text-leaf"/>{label}</p>)}</div></div></section> </main>;
}

function DashboardMock({english}:{english:boolean}){const t=(fr:string,en:string)=>english?en:fr;return <div className="overflow-hidden rounded-[2rem] border bg-white shadow-2xl"><div className="grid min-h-[480px] sm:grid-cols-[110px_1fr]"><aside className="hidden bg-forest p-5 text-white sm:block"><HeartPulse className="h-8 text-orange"/><div className="mt-10 grid gap-4 text-[10px] font-bold"><span className="rounded-lg bg-white/15 p-2">{t("Tableau","Dashboard")}</span><span className="p-2 text-white/55">{t("Données","Data")}</span><span className="p-2 text-white/55">{t("Rapports","Reports")}</span></div></aside><div className="p-5 md:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{t("Tableau de bord","Dashboard")}</h2><div className="flex gap-2"><Bell className="h-5 text-slate-400"/><span className="h-6 w-6 rounded-full bg-orange"/></div></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Scale,t("Poids","Weight"),"72,4 kg"],[Gauge,"IMC / BMI","24,6"],[Activity,t("Tension artérielle","Blood pressure"),"120/80"],[Droplets,t("Glycémie à jeun","Fasting glucose"),"0,92 g/L"]].map(([Icon,label,value]:any)=><div key={label} className="rounded-xl border p-3"><Icon className="h-4 text-leaf"/><p className="mt-2 text-[10px] text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p><p className="mt-1 text-[9px] font-bold text-emerald-600">{t("Normal","Normal")}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_150px]"><div className="rounded-xl border p-4"><p className="text-xs font-black">{t("Évolution du poids","Weight trend")}</p><svg viewBox="0 0 400 180" className="mt-4 h-44 w-full"><g stroke="#e2e8f0" strokeWidth="1">{[30,70,110,150].map(y=><line key={y} x1="20" y1={y} x2="385" y2={y}/>)}</g><polyline points="25,145 80,118 135,132 190,92 245,72 300,78 370,42" fill="none" stroke="#168651" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{[[25,145],[80,118],[135,132],[190,92],[245,72],[300,78],[370,42]].map(([x,y])=><circle key={`${x}-${y}`} cx={x} cy={y} r="5" fill="#168651"/>)}</svg></div><div className="grid place-items-center rounded-xl border p-4 text-center"><p className="text-xs font-black">{t("Score santé global","Global health score")}</p><div className="mt-5 grid h-24 w-24 place-items-center rounded-full border-[12px] border-emerald-100 border-t-leaf text-2xl font-black">84</div><p className="mt-4 text-xs font-bold text-emerald-600">{t("Bonne progression","Good progress")}</p></div></div></div></div></div>}
function MiniTrend({english}:{english:boolean}){return <div><svg viewBox="0 0 300 120" className="h-28 w-full"><g stroke="#e2e8f0">{[25,55,85].map(y=><line key={y} x1="5" y1={y} x2="295" y2={y}/>)}</g><polyline points="8,92 55,70 95,76 145,45 190,50 245,28 292,20" fill="none" stroke="#168651" strokeWidth="4"/>{[[8,92],[55,70],[95,76],[145,45],[190,50],[245,28],[292,20]].map(([x,y])=><circle key={x} cx={x} cy={y} r="4" fill="#168651"/>)}</svg><div className="grid grid-cols-2 gap-2 text-xs"><span><b>72,4 kg</b><br/><small>{english?"Current weight":"Poids actuel"}</small></span><span><b className="text-emerald-600">−1,2 kg</b><br/><small>{english?"30-day change":"Variation sur 30 jours"}</small></span></div></div>}
function MiniTable({english}:{english:boolean}){return <div className="overflow-hidden rounded-xl border bg-white text-[10px]"><div className="grid grid-cols-3 bg-slate-100 p-2 font-black"><span>{english?"Date":"Date"}</span><span>{english?"Indicator":"Indicateur"}</span><span>{english?"Value":"Valeur"}</span></div>{[["12/05/2026",english?"Weight":"Poids","72,4 kg"],["05/05/2026","IMC / BMI","24,6"],["26/04/2026",english?"Blood pressure":"Tension","120/80"]].map(row=><div key={row[0]} className="grid grid-cols-3 border-t p-2">{row.map(v=><span key={v}>{v}</span>)}</div>)}</div>}
function GrowthChart(){return <svg viewBox="0 0 300 150" className="h-36 w-full"><path d="M10 125 Q80 70 145 58 T290 28 L290 58 Q210 68 145 82 T10 145Z" fill="#dcfce7"/><path d="M10 132 Q80 82 145 70 T290 42" fill="none" stroke="#168651" strokeWidth="3"/><path d="M10 145 Q80 105 145 94 T290 75" fill="none" stroke="#60a5fa" strokeWidth="2"/><g stroke="#e2e8f0">{[30,70,110,145].map(y=><line key={y} x1="10" y1={y} x2="290" y2={y}/>)}</g></svg>}
