import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, CheckCircleIcon, HeartIcon, ShieldCheckIcon, UserGroupIcon } from "@heroicons/react/24/outline";
import { getCurrentLocale } from "@/lib/i18n-server";
import { localizedPath } from "@/lib/i18n";
import { getMedicalSettings, medicalCopy, medicalSpecialties } from "@/lib/medical-specialists";

export const metadata={title:"Consultations médicales spécialisées | NutVitaGlobalis"};
export default async function MedicalConsultationsPage(){
 const locale=await getCurrentLocale(); const en=locale==="en"; const stored=await getMedicalSettings(); const c={...medicalCopy[locale],...((en?stored?.content_en:stored?.content_fr)||{})};
 const steps=en?["Specialist consultation","Assessment & tests","Personalized care plan","Nutrition support","Follow-up & reassessment"]:["Consultation médicale","Bilan & examens","Plan de prise en charge","Accompagnement nutritionnel","Suivi & réévaluation"];
 return <main className="bg-[#fbfdfc]">
  <section className="container-site grid min-h-[610px] items-center gap-12 py-12 lg:grid-cols-[1.05fr_.95fr]">
   <div><span className="inline-flex rounded-full bg-mint px-4 py-2 text-xs font-black tracking-widest text-leaf">{c.badge}</span><h1 className="mt-6 max-w-2xl text-5xl font-black leading-[1.02] md:text-7xl">{String(c.title).split(" ").slice(0,1)} <span className="text-orange">{String(c.title).split(" ").slice(1).join(" ")}</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{c.lead}</p>
   <div className="mt-7 grid gap-3 text-sm font-bold text-slate-700 sm:grid-cols-2">{(en?["Secure online consultations","Qualified and verified professionals","Personalized care","Coordination with nutritionists"]:["Consultations en ligne sécurisées","Professionnels qualifiés et vérifiés","Prise en charge personnalisée","Suivi et coordination avec nos nutritionnistes"]).map(x=><span key={x} className="flex gap-2"><CheckCircleIcon className="h-5 text-leaf"/>{x}</span>)}</div>
   <div className="mt-8 flex flex-wrap gap-4"><Link className="btn-primary" href={localizedPath(locale,"/consultations-medicales/specialistes")}>{c.find}<ArrowRightIcon className="h-5"/></Link><a href="#parcours" className="btn-secondary">{c.how}</a></div></div>
   <div className="relative min-h-[500px] overflow-hidden rounded-[38px]"><Image src="/images/medical-specialist-hero-v1.png" alt="Consultation médicale spécialisée NutVitaGlobalis" fill priority className="object-cover"/><div className="absolute bottom-6 right-6 max-w-xs rounded-3xl bg-white p-5 shadow-xl"><ShieldCheckIcon className="h-10 text-leaf"/><b className="mt-2 block">{en?"Secure and confidential platform":"Plateforme sécurisée et confidentielle"}</b></div></div>
  </section>
  <section className="section pt-5"><div className="container-site"><h2 className="text-center text-3xl font-black">{c.specialtiesTitle}</h2><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-5">{medicalSpecialties.map((s,i)=><article key={s.fr} className={`rounded-3xl border p-6 text-center ${["bg-mint","bg-orange/5","bg-violet-50","bg-amber-50","bg-blue-50"][i]}`}><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white text-leaf"><HeartIcon className="h-7"/></span><h3 className="mt-4 font-black">{en?s.en:s.fr}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{en?s.textEn:s.textFr}</p></article>)}</div></div></section>
  <section id="parcours" className="section"><div className="container-site rounded-[36px] border bg-white p-8 shadow-sm"><h2 className="text-center text-3xl font-black">{c.journeyTitle}</h2><p className="mt-2 text-center text-slate-500">{en?"Medical and nutrition professionals work together for complete care.":"Nos médecins et nutritionnistes travaillent ensemble pour une prise en charge complète."}</p><div className="mt-10 grid gap-6 md:grid-cols-5">{steps.map((step,i)=><div className="relative text-center" key={step}><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-mint font-black text-leaf">{i+1}</span><b className="mt-4 block">{step}</b></div>)}</div></div></section>
  <section className="container-site mb-20 flex flex-col items-center justify-between gap-6 rounded-[36px] bg-mint p-10 md:flex-row"><div className="flex items-center gap-5"><span className="grid h-20 w-20 place-items-center rounded-full bg-white text-leaf"><UserGroupIcon className="h-10"/></span><div><h2 className="text-2xl font-black">{c.legal}</h2><p className="mt-2 text-slate-600">{en?"Every consultation is delivered by a verified, qualified professional.":"Toutes nos consultations sont réalisées par des professionnels qualifiés et vérifiés."}</p></div></div><Link href={localizedPath(locale,"/consultations-medicales/specialistes")} className="btn-primary">{c.find}</Link></section>
 </main>
}
