"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row=Record<string,any>;
function names(fullName:string){const parts=String(fullName||"").trim().split(/\s+/);return{first:parts[0]||"—",last:parts.slice(1).join(" ")||"—"}}

export default function ChildGrowthAlertManager({initial,userId}:{initial:Row[];userId:string}){
  const [rows,setRows]=useState(initial),[severity,setSeverity]=useState(""),[state,setState]=useState(""),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState<Row|null>(null),[comment,setComment]=useState("");
  const filtered=useMemo(()=>rows.filter(row=>{const child=row.children||{},text=`${row.id} ${child.full_name||""} ${row.title||""} ${row.message||""} ${child.client_profiles?.full_name||""}`.toLowerCase();return(!severity||row.severity===severity)&&(!state||(state==="verified"?Boolean(row.acknowledged_at):!row.acknowledged_at))&&(!query||text.includes(query.toLowerCase()))}),[rows,severity,state,query]);
  async function update(row:Row,changes:Record<string,unknown>){const {error}=await createClient().from("child_growth_alerts").update(changes).eq("id",row.id);if(error)setMessage(error.message);else setRows(items=>items.map(item=>item.id===row.id?{...item,...changes}:item))}
  async function review(row:Row){await update(row,{acknowledged_at:row.acknowledged_at?null:new Date().toISOString(),reviewed_by:row.acknowledged_at?null:userId})}
  async function saveComment(){if(!editing)return;await update(editing,{professional_comment:comment,commented_at:new Date().toISOString(),reviewed_by:userId});setEditing(null);setComment("")}
  return <div className="space-y-5">
    {message&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{message}</p>}
    <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ID, enfant, parent ou alerte…" className="admin-input"/><select value={severity} onChange={event=>setSeverity(event.target.value)} className="admin-input"><option value="">Toutes les sévérités</option><option value="critical">Critique</option><option value="warning">Vigilance</option><option value="info">Information</option></select><select value={state} onChange={event=>setState(event.target.value)} className="admin-input"><option value="">Tous les états</option><option value="open">À vérifier</option><option value="verified">Vérifiée</option></select></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">ID enfant</th><th className="p-4">Prénom</th><th className="p-4">Nom</th><th className="p-4">Parent</th><th className="p-4">Alerte</th><th className="p-4">Niveau</th><th className="p-4">État</th><th className="p-4">Date</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(row=>{const child=row.children||{},parsed=names(child.full_name);return <tr key={row.id} className="align-top hover:bg-slate-50/70"><td className="p-4 font-mono text-xs font-bold">{child.child_number||String(row.child_id||row.id).slice(0,12)}</td><td className="p-4 font-bold">{parsed.first}</td><td className="p-4">{parsed.last}</td><td className="p-4">{child.client_profiles?.full_name||"—"}</td><td className="max-w-md p-4"><b>{row.title}</b><p className="mt-1 text-xs text-slate-500">{row.message}</p>{row.professional_comment&&<p className="mt-2 rounded-lg bg-mint p-2 text-xs"><b>Commentaire :</b> {row.professional_comment}</p>}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${row.severity==="critical"?"bg-red-50 text-red-700":row.severity==="warning"?"bg-orange/10 text-orange":"bg-sky-50 text-sky-700"}`}>{row.severity==="critical"?"Critique":row.severity==="warning"?"Vigilance":"Information"}</span></td><td className="p-4">{row.acknowledged_at?"Vérifiée":"À vérifier"}</td><td className="whitespace-nowrap p-4">{new Date(row.created_at).toLocaleDateString("fr-FR")}</td><td className="p-4"><div className="flex flex-wrap gap-2"><button onClick={()=>{setEditing(row);setComment(row.professional_comment||"")}} className="btn-secondary px-3 py-2 text-xs">Commenter</button><button onClick={()=>review(row)} className={`px-3 py-2 text-xs ${row.acknowledged_at?"btn-secondary":"btn-primary"}`}>{row.acknowledged_at?"Rouvrir":"Marquer vérifiée"}</button></div></td></tr>})}</tbody></table></div>{!filtered.length&&<p className="p-10 text-center text-slate-500">Aucune alerte ne correspond aux filtres.</p>}</section>
    {editing&&<div className="fixed inset-0 z-[90] grid place-items-center bg-forest/70 p-4"><div className="w-full max-w-xl rounded-[28px] bg-forest p-5 shadow-2xl"><div className="rounded-2xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-orange">Suivi professionnel</p><h2 className="mt-2 text-2xl font-black">Commenter l’alerte</h2></div><button onClick={()=>setEditing(null)} className="text-2xl">×</button></div><label className="mt-6 block text-sm font-bold">Commentaire<textarea rows={6} value={comment} onChange={event=>setComment(event.target.value)} className="admin-input mt-2 resize-y" placeholder="Saisissez votre observation professionnelle…"/></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setEditing(null)} className="btn-secondary">Annuler</button><button onClick={saveComment} className="btn-primary">Enregistrer</button></div></div></div></div>}
  </div>
}
