"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Message = { id:string; name?:string|null; email?:string|null; phone?:string|null; subject:string; message:string; status:string; admin_note?:string|null; created_at:string };
export default function ExternalMessagesManager({ initial }: { initial: Message[] }) {
  const [items,setItems]=useState(initial),[busy,setBusy]=useState<string>();
  async function update(id:string,status:string,admin_note:string){setBusy(id);const{error}=await createClient().from("external_messages").update({status,admin_note}).eq("id",id);if(!error)setItems(current=>current.map(item=>item.id===id?{...item,status,admin_note}:item));setBusy(undefined);}
  return <div className="grid gap-5">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-mint px-3 py-1 text-xs font-black uppercase text-forest">{item.status}</span><h2 className="mt-3 text-xl font-black text-forest">{item.subject}</h2><p className="mt-1 text-sm text-slate-500">{item.name||"Expediteur anonyme"} · {new Date(item.created_at).toLocaleString("fr-FR")}</p></div><div className="text-sm"><p>{item.email&&<a className="font-bold text-leaf" href={`mailto:${item.email}`}>{item.email}</a>}</p><p>{item.phone&&<a className="font-bold text-leaf" href={`tel:${item.phone}`}>{item.phone}</a>}</p></div></div><p className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-5 leading-7">{item.message}</p><div className="mt-5 grid gap-3 md:grid-cols-[1fr_180px_auto]"><input id={`note-${item.id}`} defaultValue={item.admin_note||""} className="admin-input" placeholder="Note interne ou suivi effectue"/><select id={`status-${item.id}`} defaultValue={item.status} className="admin-input"><option value="new">Nouveau</option><option value="read">Lu</option><option value="replied">Repondu</option><option value="archived">Archive</option></select><button disabled={busy===item.id} onClick={()=>{const note=(document.getElementById(`note-${item.id}`) as HTMLInputElement).value,status=(document.getElementById(`status-${item.id}`) as HTMLSelectElement).value;void update(item.id,status,note)}} className="btn-primary">Enregistrer</button></div></article>)}{!items.length&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">Aucun message externe.</div>}</div>;
}
