"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { HealthRecordPageSettings } from "@/data/health-record-page";

export default function HealthRecordPageEditor({initial}:{initial:HealthRecordPageSettings}) {
  const [data,setData]=useState(initial); const [message,setMessage]=useState("");
  const set=(key:keyof HealthRecordPageSettings,value:any)=>setData({...data,[key]:value});
  async function save(){setMessage("Enregistrement…");const{error}=await createClient().from("health_record_page_settings").upsert({...data,id:1,updated_at:new Date().toISOString()});setMessage(error?error.message:"Page de suivi santé enregistrée.")}
  async function upload(file?:File){if(!file)return;const client=createClient(),path=`health-record/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,"-")}`;const result=await client.storage.from("research-assets").upload(path,file);if(result.error){setMessage(result.error.message);return}set("guide_image_url",client.storage.from("research-assets").getPublicUrl(path).data.publicUrl)}
  return <div className="grid gap-6"><section className="grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><Field label="Titre FR" value={data.page_title} set={v=>set("page_title",v)}/><Field label="Title EN" value={data.page_title_en} set={v=>set("page_title_en",v)}/><Area label="Introduction FR" value={data.page_intro} set={v=>set("page_intro",v)}/><Area label="Introduction EN" value={data.page_intro_en} set={v=>set("page_intro_en",v)}/><Field label="Encadré conseil FR" value={data.guide_title} set={v=>set("guide_title",v)}/><Field label="Guide card EN" value={data.guide_title_en} set={v=>set("guide_title_en",v)}/><Area label="Conseil FR" value={data.guide_text} set={v=>set("guide_text",v)}/><Area label="Advice EN" value={data.guide_text_en} set={v=>set("guide_text_en",v)}/><label className="grid gap-2 text-sm font-bold md:col-span-2">Illustration<input className="admin-input" value={data.guide_image_url} onChange={e=>set("guide_image_url",e.target.value)}/><input className="admin-input" type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/></label></section><section className="grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><Field label="Objectif FR" value={data.objective_title} set={v=>set("objective_title",v)}/><Field label="Goal EN" value={data.objective_title_en} set={v=>set("objective_title_en",v)}/><Field label="Conseils FR" value={data.advice_title} set={v=>set("advice_title",v)}/><Field label="Advice EN" value={data.advice_title_en} set={v=>set("advice_title_en",v)}/><label className="grid gap-2 text-sm font-bold md:col-span-2">Conseils bilingues (JSON)<textarea rows={14} className="admin-input font-mono text-xs" value={JSON.stringify(data.advice,null,2)} onChange={e=>{try{set("advice",JSON.parse(e.target.value));setMessage("")}catch{setMessage("JSON invalide")}}}/></label></section><div className="sticky bottom-4 flex items-center justify-between rounded-2xl border bg-white p-4 shadow-xl"><b className="text-leaf">{message||"Les mesures patient restent dynamiques et séparées de ce contenu éditorial."}</b><button onClick={save} className="btn-primary">Enregistrer</button></div></div>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="grid gap-2 text-sm font-bold">{label}<input className="admin-input" value={value||""} onChange={e=>set(e.target.value)}/></label>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="grid gap-2 text-sm font-bold">{label}<textarea rows={4} className="admin-input" value={value||""} onChange={e=>set(e.target.value)}/></label>}
