"use client";

import {FormEvent,useMemo,useState} from "react";
type Row=Record<string,any>;
type Props={applications:Row[];interviews:Row[];specialists:Row[];accounts:Row[];payments:Row[];settings:Row};

export default function MedicalSpecialistAdmin(props:Props){
  const[tab,setTab]=useState<"applications"|"interviews"|"settings">("applications"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[modal,setModal]=useState(false),[selected,setSelected]=useState<Row|null>(null),[busy,setBusy]=useState(false);
  const filtered=useMemo(()=>props.applications.filter(a=>(status==="all"||a.status===status)&&`${a.full_name} ${a.email} ${a.specialty} ${a.application_code}`.toLowerCase().includes(query.toLowerCase())),[props.applications,query,status]);
  async function action(type:string,payload:Row){setBusy(true);const response=await fetch("/api/admin/medical-specialists",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:type,...payload})});setBusy(false);const result=await response.json();if(!response.ok)return alert(result.message||"Erreur");location.reload()}
  return <div><div className="grid gap-3 md:grid-cols-3"><Tab active={tab==="applications"} onClick={()=>setTab("applications")} label="Dossiers en attente"/><Tab active={tab==="interviews"} onClick={()=>setTab("interviews")} label="Entretiens d’embauche"/><Tab active={tab==="settings"} onClick={()=>setTab("settings")} label="Paramètres & contenus FR/EN"/></div>
  {tab==="applications"&&<section className="admin-card mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2>Dossiers de médecins spécialistes</h2><p className="text-sm text-slate-500">Registre filtrable, documents contrôlables et décision traçable.</p></div><div className="flex flex-wrap gap-2"><input className="admin-input w-72" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Candidat, spécialité, ID…"/><select className="admin-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option>{[...new Set(props.applications.map(a=>a.status))].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="mt-5 overflow-x-auto"><table className="admin-table min-w-[1450px]"><thead><tr>{["ID candidature","Date","Candidat","Spécialité","Localisation","N° ordre","Documents","Statut","Décision"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td>{a.application_code}</td><td>{new Date(a.applied_at||a.created_at).toLocaleDateString("fr-FR")}</td><td><b>{a.full_name}</b><small className="block text-slate-500">{a.email}</small></td><td>{a.specialty}</td><td>{[a.city,a.state_region,a.country].filter(Boolean).join(", ")}</td><td>{a.medical_license_number||"—"}</td><td><div className="max-h-24 overflow-y-auto">{(a.documents||[]).map((d:Row)=><a className="block text-leaf underline" key={d.path} href={`/api/admin/medical-specialists/document?path=${encodeURIComponent(d.path)}`} target="_blank">{d.name}</a>)}{!a.documents?.length&&"—"}</div></td><td><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-forest">{a.status}</span></td><td><select disabled={busy} className="admin-input min-w-52" defaultValue="" onChange={e=>{const decision=e.target.value;if(!decision)return;if(decision==="interview"){setSelected(a);setModal(true)}else action("application_status",{id:a.id,status:decision})}}><option value="">Choisir…</option><option value="interview">Inviter à l’entretien</option><option value="additional_documents">Demander un complément</option><option value="rejected">Décliner</option></select></td></tr>)}{!filtered.length&&<tr><td colSpan={9} className="py-12 text-center text-slate-400">Aucun dossier ne correspond aux filtres.</td></tr>}</tbody></table></div></section>}
  {tab==="interviews"&&<section className="admin-card mt-6"><div className="flex flex-wrap justify-between gap-3"><div><h2>Entretiens et décisions</h2><p className="text-sm text-slate-500">Seuls les candidats invités sont proposés dans le planificateur.</p></div><button className="btn-primary" onClick={()=>{setSelected(null);setModal(true)}}>Planifier un entretien</button></div><div className="mt-5 overflow-x-auto"><table className="admin-table min-w-[1200px]"><thead><tr>{["ID entretien","Date","Candidat","Salle","Invités externes","Statut","Recommandé","Décision finale"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{props.interviews.map(i=><tr key={i.id}><td>{i.interview_code}</td><td>{new Date(i.scheduled_at).toLocaleString("fr-FR")}</td><td>{i.medical_specialist_applications?.full_name}</td><td><a className="font-bold text-leaf underline" href={i.meeting_url} target="_blank">Ouvrir</a><button className="ml-2 text-xs" onClick={()=>navigator.clipboard.writeText(i.meeting_url)}>Copier</button></td><td>{i.external_guest_emails?.join(", ")||"—"}</td><td>{i.status}</td><td>{i.recommended==null?"—":i.recommended?"Oui":"Non"}</td><td><select className="admin-input min-w-44" value={i.final_decision||""} onChange={e=>e.target.value&&action("interview_decision",{id:i.id,decision:e.target.value})}><option value="">Décider…</option><option value="recruit">Recruter</option><option value="reject">Rejeter</option><option value="inconclusive">Non concluant</option></select></td></tr>)}{!props.interviews.length&&<tr><td colSpan={8} className="py-12 text-center text-slate-400">Aucun entretien planifié.</td></tr>}</tbody></table></div></section>}
  {tab==="settings"&&<section className="mt-6 rounded-[30px] bg-forest p-5"><form className="grid gap-5 rounded-3xl bg-white p-7" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await action("settings",{practitioner_share_percent:Number(f.get("share")),content_fr:String(f.get("content_fr")),content_en:String(f.get("content_en"))})}}><div><h2>Paramètres et contenus bilingues</h2><p className="text-sm text-slate-500">Les finances et comptes partenaires sont désormais centralisés dans Maximus.</p></div><label className="grid gap-2 font-bold">Part du médecin (%)<input className="admin-input" name="share" type="number" min="0" max="100" step="0.01" defaultValue={props.settings?.practitioner_share_percent||48}/></label><div className="grid gap-4 lg:grid-cols-2"><label className="grid gap-2 font-bold">Contenu public FR (JSON)<textarea className="admin-input min-h-72" name="content_fr" defaultValue={JSON.stringify(props.settings?.page?.content_fr||{},null,2)}/></label><label className="grid gap-2 font-bold">Public content EN (JSON)<textarea className="admin-input min-h-72" name="content_en" defaultValue={JSON.stringify(props.settings?.page?.content_en||{},null,2)}/></label></div><button className="btn-primary justify-self-end">Enregistrer</button></form></section>}
  {modal&&<InterviewModal applications={props.applications} selected={selected} close={()=>setModal(false)} submit={action}/>}</div>
}
function Tab({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-2xl border p-4 text-left text-sm font-black ${active?"bg-forest text-white":"bg-white"}`}>{label}</button>}
function InterviewModal({applications,selected,close,submit}:any){async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await submit("interview",{application_id:f.get("application_id"),scheduled_at:f.get("scheduled_at"),duration_minutes:f.get("duration_minutes"),external_guest_emails:f.get("external_guest_emails")})}const candidates=applications.filter((a:Row)=>["interview_invited","interview_scheduled","pending"].includes(a.status)||a.id===selected?.id);return <div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-black/55 p-4"><div className="w-full max-w-2xl rounded-[32px] bg-forest p-5"><form onSubmit={send} className="rounded-3xl bg-white p-7"><div className="flex justify-between"><div><h2>Planifier un entretien</h2><p className="text-sm text-slate-500">Salle sécurisée et invitations externes par email.</p></div><button type="button" onClick={close} className="text-3xl">×</button></div><div className="mt-6 grid gap-4"><label className="grid gap-2 font-bold">Candidat<select className="admin-input" name="application_id" defaultValue={selected?.id||""} required><option value="">Sélectionner…</option>{candidates.map((a:Row)=><option value={a.id} key={a.id}>{a.full_name} — {a.application_code}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-bold">Date et heure<input className="admin-input" name="scheduled_at" type="datetime-local" required/></label><label className="grid gap-2 font-bold">Durée (minutes)<input className="admin-input" name="duration_minutes" type="number" defaultValue="45" min="15"/></label></div><label className="grid gap-2 font-bold">Invités externes<textarea className="admin-input min-h-28" name="external_guest_emails" placeholder="adresses email séparées par des virgules"/></label><button className="btn-primary justify-self-end">Planifier et inviter</button></div></form></div></div>}
