"use client";

import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {applicationStatuses,documentFields,type ApplicationStatus} from "@/lib/recruitment-data";

type Row=Record<string,any>;
const decisions:[ApplicationStatus,string][]=[["incomplete","Marquer incomplet"],["invited_to_test","Inviter au test écrit"],["invited_to_interview","Inviter à l’entretien"],["rejected","Rejeter"],["integrated","Intégrer au réseau"]];

export default function RecruitmentManager({initial}:{initial:Row[];questions?:Row[]}){
  const [rows,setRows]=useState(initial),[selected,setSelected]=useState<Row|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[message,setMessage]=useState(""),[history,setHistory]=useState<Row[]>([]);
  const supabase=useMemo(()=>createClient(),[]);
  const filtered=useMemo(()=>rows.filter(row=>[row.full_name,row.email,row.specialization,row.city,row.country,row.status].join(" ").toLowerCase().includes(query.toLowerCase())&&(!status||row.status===status)),[rows,query,status]);
  function patch(id:string,values:Row){setRows(current=>current.map(row=>row.id===id?{...row,...values}:row));if(selected?.id===id)setSelected(current=>current?{...current,...values}:current)}
  async function open(row:Row){setSelected(row);const{data}=await supabase.from("recruitment_history").select("*").eq("application_id",row.id).order("created_at",{ascending:false});setHistory(data||[])}
  async function save(row:Row,nextStatus?:ApplicationStatus,notify=false){
    const statusValue=nextStatus||row.status as ApplicationStatus;
    setMessage("Enregistrement…");
    const response=await fetch("/api/recruitment/admin-action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,status:statusValue,notify,note:row.candidate_visible_message||"",internal_comments:row.internal_comment||row.internal_comments||"",administrative_score:row.internal_evaluation_percent??row.administrative_score??null,internal_evaluation_percent:row.internal_evaluation_percent??null,internal_comment:row.internal_comment||"",candidate_visible_message:row.candidate_visible_message||"",last_admin_decision:statusValue})});
    const result=await response.json();if(!response.ok){setMessage(result.message||"Enregistrement impossible.");return}
    patch(row.id,{status:statusValue,last_admin_decision:statusValue,last_admin_decision_at:new Date().toISOString()});setMessage(notify?"Décision enregistrée et candidat notifié.":"Évaluation interne enregistrée.");
  }
  async function openDocument(path:string){const{data,error}=await supabase.storage.from("recruitment-documents").createSignedUrl(path,300);if(error)setMessage(error.message);else window.open(data.signedUrl,"_blank","noopener,noreferrer")}
  return <div className="grid gap-5">
    <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_260px_auto]"><input className="admin-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Candidat, email, poste, pays…"/><select className="admin-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{Object.entries(applicationStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button onClick={()=>exportCsv(filtered)} className="btn-secondary">Exporter CSV</button></div>
    {message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1500px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Candidat</th><th className="p-4">Poste / spécialité</th><th className="p-4">Date</th><th className="p-4">Statut</th><th className="p-4">Vue</th><th className="p-4">Évaluation interne</th><th className="p-4">Décision</th><th className="p-4">Commentaire interne</th><th className="p-4">Message candidat</th><th className="p-4">Enregistrer</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="border-t align-top"><td className="p-4"><b className="text-forest">{row.full_name||"Sans nom"}</b><p className="text-xs text-slate-500">{row.email}</p></td><td className="p-4">{row.specialization||row.professional_title||"Candidature spontanée"}</td><td className="p-4">{date(row.created_at)}</td><td className="p-4"><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-forest">{applicationStatuses[row.status as ApplicationStatus]||row.status}</span></td><td className="p-4"><button onClick={()=>open(row)} className="btn-secondary px-3 py-2">Voir</button></td><td className="p-4"><div className="flex items-center gap-2"><input className="admin-input w-24" type="number" min="0" max="100" value={row.internal_evaluation_percent??row.administrative_score??""} onChange={e=>patch(row.id,{internal_evaluation_percent:e.target.value===""?null:Number(e.target.value)})}/><span>%</span></div></td><td className="p-4"><select className="admin-input min-w-48" value={row.last_admin_decision||""} onChange={e=>{const next=e.target.value as ApplicationStatus;patch(row.id,{last_admin_decision:next});if(next)save({...row,last_admin_decision:next},next,true)}}><option value="">Choisir…</option>{decisions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td className="p-4"><textarea rows={3} className="admin-input min-w-64" value={row.internal_comment||row.internal_comments||""} onChange={e=>patch(row.id,{internal_comment:e.target.value})}/></td><td className="p-4"><textarea rows={3} className="admin-input min-w-64" value={row.candidate_visible_message||""} onChange={e=>patch(row.id,{candidate_visible_message:e.target.value})} placeholder="Visible dans l’espace candidat"/></td><td className="p-4"><button onClick={()=>save(row,undefined,false)} className="btn-primary px-4 py-2">Enregistrer</button></td></tr>)}{!filtered.length&&<tr><td colSpan={10} className="p-10 text-center text-slate-400">Aucune candidature correspondant aux filtres.</td></tr>}</tbody></table></div>
    {selected&&<CandidateModal row={selected} history={history} close={()=>setSelected(null)} openDocument={openDocument}/>}
  </div>;
}

function CandidateModal({row,history,close,openDocument}:{row:Row;history:Row[];close:()=>void;openDocument:(path:string)=>void}){
  const docs=(row.documents&&typeof row.documents==="object"?row.documents:{}) as Record<string,Array<{name:string;path:string}>>;
  return <div className="fixed inset-0 z-[130] overflow-y-auto bg-slate-950/65 p-4"><div className="mx-auto my-6 max-w-5xl rounded-[2rem] bg-forest p-4 shadow-2xl"><div className="rounded-[1.5rem] bg-white p-6 md:p-8"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-orange">Dossier candidat</p><h2 className="mt-2 text-3xl font-black text-forest">{row.full_name}</h2><p className="text-slate-500">{row.email} · {row.specialization||row.professional_title}</p></div><button onClick={close} className="text-3xl">×</button></div><div className="mt-7 grid gap-5 md:grid-cols-2"><Card title="Informations" items={[["Téléphone",row.whatsapp_phone||row.phone],["Pays",row.country],["Région",row.state_region],["Ville",row.city],["Diplôme",row.highest_degree],["Expérience",`${row.years_experience||0} ans`],["Disponibilité",row.weekly_availability],["Statut",applicationStatuses[row.status as ApplicationStatus]||row.status]]}/><section className="rounded-2xl bg-slate-50 p-5"><h3 className="text-xl font-black">Documents</h3><div className="mt-4 grid gap-3">{documentFields.map(([key,label])=><div key={key}><b className="text-sm">{label}</b>{(docs[key]||[]).map(file=><button key={file.path} onClick={()=>openDocument(file.path)} className="ml-3 text-sm font-bold text-leaf">{file.name}</button>)}</div>)}</div></section><Card title="Évaluation et décision" items={[["Note administrative",`${row.internal_evaluation_percent??row.administrative_score??"—"}%`],["Décision",row.last_admin_decision||"—"],["Commentaire interne",row.internal_comment||row.internal_comments||"—"],["Message candidat",row.candidate_visible_message||"—"]]}/><section className="rounded-2xl bg-slate-50 p-5"><h3 className="text-xl font-black">Historique complet</h3><div className="mt-4 grid gap-2">{history.map(item=><div key={item.id} className="rounded-xl bg-white p-3 text-sm"><b>{item.action}</b><span className="ml-2 text-xs text-slate-400">{new Date(item.created_at).toLocaleString("fr-FR")}</span>{item.note&&<p>{item.note}</p>}</div>)}{!history.length&&<p className="text-sm text-slate-400">Aucun événement.</p>}</div></section></div></div></div></div>;
}
function Card({title,items}:{title:string;items:Array<[string,unknown]>}){return <section className="rounded-2xl bg-slate-50 p-5"><h3 className="text-xl font-black">{title}</h3><dl className="mt-4 grid gap-3">{items.map(([key,value])=><div key={key}><dt className="text-xs font-bold uppercase text-slate-400">{key}</dt><dd className="whitespace-pre-wrap">{String(value||"—")}</dd></div>)}</dl></section>}
function date(value:unknown){return value?new Date(String(value)).toLocaleDateString("fr-FR"):"—"}
function exportCsv(rows:Row[]){const esc=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`;const csv=["Nom,Email,Spécialité,Statut,Évaluation,Date",...rows.map(row=>[row.full_name,row.email,row.specialization,row.status,row.internal_evaluation_percent,row.created_at].map(esc).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download="candidatures-nutritionnistes.csv";link.click();URL.revokeObjectURL(url)}
