"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Row=Record<string,any>;
type Settings={id:number;title:string;instructions:string;available_from:string|null;available_until:string|null;duration_minutes:number;camera_required:boolean;active:boolean};
const types=[["qcm","Réponse unique"],["multi_qcm","Réponses multiples"],["open","Question ouverte"],["case_study","Cas pratique"],["file_upload","Fichier à remettre"]];

export default function TestConfigManager({initialSettings,initialQuestions,candidates,jobOffers,initialExams}:{initialSettings:Settings|null;initialQuestions:Row[];candidates:Row[];jobOffers:Row[];initialExams:Row[]}){
  const [settings,setSettings]=useState<Settings>(initialSettings||{id:1,title:"Test écrit NutVitaGlobalis",instructions:"Lisez attentivement chaque question.",available_from:null,available_until:null,duration_minutes:60,camera_required:false,active:true}),[questions,setQuestions]=useState(initialQuestions),[exams,setExams]=useState(initialExams),[showGenerate,setShowGenerate]=useState(false),[showQuestion,setShowQuestion]=useState(false),[message,setMessage]=useState(""),[assignments,setAssignments]=useState<Record<string,string>>({}),[review,setReview]=useState<Row|null>(null);
  const [request,setRequest]=useState<Row>({job_offer_id:"",title:"",qcm_count:5,multi_qcm_count:0,case_study_count:1,open_count:0,file_upload_count:0}),[draft,setDraft]=useState<Row>({category:"",job_offer_id:"",question_type:"qcm",prompt:"",options:"",correct_answer:"",points:10,active:true});
  const supabase=useMemo(()=>createClient(),[]);
  const waiting=candidates.filter(row=>["submitted","under_review","preselected","invited_to_test","test_completed"].includes(row.status));
  const corrections=candidates.flatMap(candidate=>(candidate.recruitment_test_attempts||[]).filter((attempt:Row)=>["submitted","expired","graded"].includes(attempt.status)).map((attempt:Row)=>({...attempt,candidate})));
  const offer=(id:string)=>jobOffers.find(row=>row.id===id)?.title||"Candidature spontanée";
  async function generate(){
    if(!request.job_offer_id){setMessage("Sélectionnez le poste ou la catégorie de l’épreuve.");return}
    const{data,error}=await supabase.rpc("generate_recruitment_exam",{p_job_offer_id:request.job_offer_id,p_title:request.title||`${offer(request.job_offer_id)} – ${new Date().toLocaleDateString("fr-FR")}`,p_qcm_count:Number(request.qcm_count),p_multi_qcm_count:Number(request.multi_qcm_count),p_case_study_count:Number(request.case_study_count),p_open_count:Number(request.open_count),p_file_upload_count:Number(request.file_upload_count)});
    if(error){setMessage(error.message);return}
    const{data:exam,error:updateError}=await supabase.from("recruitment_generated_exams").update({duration_minutes:Number(settings.duration_minutes),available_from:settings.available_from||null,available_until:settings.available_until||null,camera_required:settings.camera_required,invited_only:true}).eq("id",data).select("*").single();
    if(updateError){setMessage(updateError.message);return}setExams([exam,...exams.map(row=>row.job_offer_id===exam.job_offer_id?{...row,active:false}:row)]);setShowGenerate(false);setMessage("Épreuve générée et enregistrée dans le registre.");
  }
  async function addQuestion(){
    if(!draft.prompt.trim()){setMessage("Saisissez l’énoncé.");return}
    const options=String(draft.options||"").split("\n").map(value=>value.trim()).filter(Boolean);const{data,error}=await supabase.from("recruitment_test_questions").insert({...draft,job_offer_id:draft.job_offer_id||null,options:options.length?options:null,points:Number(draft.points)}).select("*").single();
    if(error){setMessage(error.message);return}setQuestions([...questions,data]);setShowQuestion(false);setMessage("Question ajoutée à la banque.");
  }
  async function send(candidate:Row){const examId=assignments[candidate.id];if(!examId){setMessage("Sélectionnez une épreuve pour ce candidat.");return}const response=await fetch("/api/recruitment/send-test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignments:[{id:candidate.id,exam_id:examId}]})});const result=await response.json();setMessage(response.ok?"Épreuve envoyée au candidat.":result.message)}
  async function saveCorrection(){if(!review)return;const response=await fetch("/api/recruitment/admin-action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:review.application_id,status:"test_completed",notify:false,manual_score:Number(review.manual_score||0),reviewer_comments:review.reviewer_comments||""})});const result=await response.json();if(!response.ok){setMessage(result.message);return}setReview(null);setMessage("Correction enregistrée.")}
  async function decide(attempt:Row,status:string){const response=await fetch("/api/recruitment/admin-action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:attempt.application_id,status,notify:true,note:attempt.reviewer_comments||""})});const result=await response.json();setMessage(response.ok?"Décision enregistrée et candidat notifié.":result.message)}
  return <div className="grid gap-7">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl font-black">Tests écrits</h2><p className="text-slate-500">Générez, attribuez, surveillez et corrigez les épreuves des nutritionnistes.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/recrutement/banque-questions" className="btn-secondary">Banque de questions</Link><button onClick={()=>setShowQuestion(true)} className="btn-secondary">Ajouter une question</button><button onClick={()=>setShowGenerate(true)} className="btn-primary">+ Générer l’épreuve</button></div></div>
    {message&&<p className="rounded-xl bg-mint p-4 font-bold text-forest">{message}</p>}
    <Registry title="Registre des épreuves"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50"><tr><Th>ID épreuve</Th><Th>Date de création</Th><Th>Titre du test</Th><Th>Durée</Th><Th>Ouverture</Th><Th>Fermeture</Th><Th>Caméra</Th><Th>Actif pour invités</Th><Th>Questions</Th></tr></thead><tbody>{exams.map(row=><tr key={row.id} className="border-t"><Td>{String(row.id).slice(0,10).toUpperCase()}</Td><Td>{date(row.created_at)}</Td><Td><b>{row.title}</b><p className="text-xs text-slate-400">{offer(row.job_offer_id)}</p></Td><Td>{row.duration_minutes||settings.duration_minutes} min</Td><Td>{dateTime(row.available_from)}</Td><Td>{dateTime(row.available_until)}</Td><Td>{row.camera_required?"Oui":"Non"}</Td><Td>{row.active?"Oui":"Non"}</Td><Td>{(row.question_ids||[]).length}</Td></tr>)}{!exams.length&&<Empty span={9}/>}</tbody></table></Registry>
    <Registry title="Invitation des candidats au test"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50"><tr><Th>Candidat</Th><Th>Poste</Th><Th>Statut</Th><Th>Épreuve à attribuer</Th><Th>Action</Th></tr></thead><tbody>{waiting.map(row=><tr key={row.id} className="border-t"><Td><b>{row.full_name||row.email}</b><p className="text-xs text-slate-400">{row.email}</p></Td><Td>{row.specialization||"Candidature spontanée"}</Td><Td>{row.status}</Td><Td><select className="admin-input min-w-72" value={assignments[row.id]||row.assigned_exam_id||""} onChange={e=>setAssignments({...assignments,[row.id]:e.target.value})}><option value="">Sélectionner une épreuve</option>{exams.filter(exam=>exam.active).map(exam=><option key={exam.id} value={exam.id}>{exam.title}</option>)}</select></Td><Td><button onClick={()=>send(row)} className="btn-primary px-4 py-2">Envoyer</button></Td></tr>)}{!waiting.length&&<Empty span={5}/>}</tbody></table></Registry>
    <Registry title="Tests écrits à corriger"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50"><tr><Th>Candidat</Th><Th>Soumission</Th><Th>Score automatique</Th><Th>Score final</Th><Th>Commentaires</Th><Th>Correction</Th><Th>Décision</Th></tr></thead><tbody>{corrections.map(attempt=><tr key={attempt.id} className="border-t"><Td><b>{attempt.candidate.full_name}</b></Td><Td>{dateTime(attempt.submitted_at)}</Td><Td>{Number(attempt.automatic_score||0)}%</Td><Td>{mean(attempt)}%</Td><Td>{attempt.reviewer_comments||"—"}</Td><Td><button onClick={()=>setReview(attempt)} className="btn-secondary px-3 py-2">Corriger l’épreuve</button></Td><Td><select className="admin-input" defaultValue="" onChange={e=>e.target.value&&decide(attempt,e.target.value)}><option value="">Choisir…</option><option value="invited_to_interview">Inviter à l’entretien</option><option value="rejected">Rejeter</option></select></Td></tr>)}{!corrections.length&&<Empty span={7}/>}</tbody></table></Registry>
    {showGenerate&&<Modal title="Générer une épreuve" close={()=>setShowGenerate(false)}><div className="grid gap-4 md:grid-cols-2"><Field label="Titre du test"><input className="admin-input" value={request.title} onChange={e=>setRequest({...request,title:e.target.value})}/></Field><Field label="Poste"><select className="admin-input" value={request.job_offer_id} onChange={e=>setRequest({...request,job_offer_id:e.target.value})}><option value="">Sélectionner</option>{jobOffers.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></Field><Field label="Durée (minutes)"><input className="admin-input" type="number" value={settings.duration_minutes} onChange={e=>setSettings({...settings,duration_minutes:Number(e.target.value)})}/></Field><Field label="Ouverture"><input className="admin-input" type="datetime-local" onChange={e=>setSettings({...settings,available_from:iso(e.target.value)})}/></Field><Field label="Fermeture"><input className="admin-input" type="datetime-local" onChange={e=>setSettings({...settings,available_until:iso(e.target.value)})}/></Field><Field label="QCU"><input className="admin-input" type="number" value={request.qcm_count} onChange={e=>setRequest({...request,qcm_count:Number(e.target.value)})}/></Field><Field label="QCM multiples"><input className="admin-input" type="number" value={request.multi_qcm_count} onChange={e=>setRequest({...request,multi_qcm_count:Number(e.target.value)})}/></Field><Field label="Cas pratiques"><input className="admin-input" type="number" value={request.case_study_count} onChange={e=>setRequest({...request,case_study_count:Number(e.target.value)})}/></Field><Field label="Questions ouvertes"><input className="admin-input" type="number" value={request.open_count} onChange={e=>setRequest({...request,open_count:Number(e.target.value)})}/></Field><Field label="Fichiers à remettre"><input className="admin-input" type="number" value={request.file_upload_count} onChange={e=>setRequest({...request,file_upload_count:Number(e.target.value)})}/></Field><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-4 font-bold"><input type="checkbox" checked={settings.camera_required} onChange={e=>setSettings({...settings,camera_required:e.target.checked})}/>Activer la caméra</label></div><button onClick={generate} className="btn-primary mt-5">Générer et enregistrer</button></Modal>}
    {showQuestion&&<Modal title="Ajouter une question" close={()=>setShowQuestion(false)}><div className="grid gap-4 md:grid-cols-2"><Field label="Catégorie"><input className="admin-input" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></Field><Field label="Poste"><select className="admin-input" value={draft.job_offer_id} onChange={e=>setDraft({...draft,job_offer_id:e.target.value})}><option value="">Générique</option>{jobOffers.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></Field><Field label="Type"><select className="admin-input" value={draft.question_type} onChange={e=>setDraft({...draft,question_type:e.target.value})}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Points"><input className="admin-input" type="number" value={draft.points} onChange={e=>setDraft({...draft,points:Number(e.target.value)})}/></Field><Field label="Énoncé"><textarea className="admin-input min-h-28" value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})}/></Field><Field label="Options, une par ligne"><textarea className="admin-input min-h-28" value={draft.options} onChange={e=>setDraft({...draft,options:e.target.value})}/></Field><Field label="Bonne réponse"><input className="admin-input" value={draft.correct_answer} onChange={e=>setDraft({...draft,correct_answer:e.target.value})}/></Field></div><button onClick={addQuestion} className="btn-primary mt-5">Ajouter à la banque</button></Modal>}
    {review&&<Modal title={`Correction – ${review.candidate.full_name}`} close={()=>setReview(null)}><p className="rounded-xl bg-slate-50 p-4">Score automatique : <b>{Number(review.automatic_score||0)}%</b></p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Note du correcteur (%)"><input className="admin-input" type="number" min="0" max="100" value={review.manual_score??""} onChange={e=>setReview({...review,manual_score:e.target.value})}/></Field><Field label="Commentaire visible au candidat"><textarea className="admin-input" value={review.reviewer_comments||""} onChange={e=>setReview({...review,reviewer_comments:e.target.value})}/></Field></div><button onClick={saveCorrection} className="btn-primary mt-5">Enregistrer la correction</button></Modal>}
  </div>;
}

function Registry({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white"><h3 className="p-5 text-xl font-black text-forest">{title}</h3><div className="overflow-x-auto">{children}</div></section>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[140] overflow-y-auto bg-slate-950/65 p-4"><div className="mx-auto my-6 max-w-4xl rounded-[2rem] bg-forest p-4"><div className="rounded-[1.5rem] bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black text-forest">{title}</h2><button onClick={close} className="text-3xl">×</button></div><div className="mt-5">{children}</div></div></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-bold">{label}{children}</label>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4">{children}</th>}function Td({children}:{children:React.ReactNode}){return <td className="p-4">{children}</td>}function Empty({span}:{span:number}){return <tr><td colSpan={span} className="p-10 text-center text-slate-400">Aucune donnée.</td></tr>}
function date(value:any){return value?new Date(value).toLocaleDateString("fr-FR"):"—"}function dateTime(value:any){return value?new Date(value).toLocaleString("fr-FR"):"—"}function iso(value:string){return value?new Date(value).toISOString():null}function mean(attempt:Row){const values=[attempt.automatic_score,attempt.manual_score].filter(value=>value!==null&&value!==undefined).map(Number);return values.length?(values.reduce((sum,value)=>sum+value,0)/values.length).toFixed(1):"0"}
