"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row = Record<string, any>;
const labels: Record<string,string>={pending:"En attente",assigned_pending_partner:"Attribution à confirmer",assigned:"Attribuée",accepted:"Prise en charge",declined:"Refusée"};

function score(request:Row,partner:Row){let value=Number(partner.internal_quality_score||50);const text=`${request.reason||""} ${request.client_profiles?.complaints||""}`.toLowerCase();for(const specialty of partner.specialties||[])if(text.includes(String(specialty).toLowerCase()))value+=15;if(request.client_profiles?.country&&partner.country===request.client_profiles.country)value+=10;if(partner.status!=="active")value-=100;return value}

export default function WaitingRoomManager({initial,partners,adminId}:{initial:Row[];partners:Row[];adminId:string}){
  const [rows,setRows]=useState(initial),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[country,setCountry]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[current,setCurrent]=useState<Row|null>(null),[partnerId,setPartnerId]=useState(""),[history,setHistory]=useState<Row|null>(null);
  const active=useMemo(()=>partners.filter(item=>item.status==="active"),[partners]);
  const countries=useMemo(()=>Array.from(new Set(rows.map(item=>item.client_profiles?.country).filter(Boolean))).sort(),[rows]);
  const filtered=useMemo(()=>rows.filter(row=>{const profile=row.client_profiles||{},text=`${row.id} ${profile.full_name||""} ${profile.city||""} ${profile.state_region||""} ${profile.country||""} ${row.reason||""} ${profile.complaints||""}`.toLowerCase(),date=String(row.created_at||"").slice(0,10);return(!query||text.includes(query.toLowerCase()))&&(!status||row.status===status)&&(!country||profile.country===country)&&(!from||date>=from)&&(!to||date<=to)}),[rows,query,status,country,from,to]);
  function open(row:Row){const ranked=[...active].sort((a,b)=>score(row,b)-score(row,a));setPartnerId(row.selected_partner_id||ranked[0]?.id||"");setCurrent(row)}
  async function assign(){if(!current||!partnerId)return;const supabase=createClient(),now=new Date().toISOString(),previous=current.selected_partner_id||null;setMessage("");const {error}=await supabase.from("consultation_waiting_room").update({selected_partner_id:partnerId,selected_by_admin:adminId,admin_validated_at:now,status:"assigned_pending_partner"}).eq("id",current.id);if(error)return setMessage(error.message);await supabase.from("client_profiles").update({assigned_partner_id:partnerId,partner_assignment_status:"assigned_pending_partner"}).eq("id",current.client_id);setRows(items=>items.map(item=>item.id===current.id?{...item,selected_partner_id:partnerId,selected_by_admin:adminId,admin_validated_at:now,status:"assigned_pending_partner"}:item));setCurrent(null);setMessage(previous?"Client réattribué avec succès.":"Client attribué avec succès.")}
  return <div className="space-y-5">
    {message&&<p className={`rounded-2xl p-4 font-bold ${message.includes("succès")?"bg-mint text-leaf":"bg-red-50 text-red-700"}`}>{message}</p>}
    <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ID, client, plainte, lieu…" className="admin-input"/><select value={status} onChange={event=>setStatus(event.target.value)} className="admin-input"><option value="">Tous les statuts</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={country} onChange={event=>setCountry(event.target.value)} className="admin-input"><option value="">Tous les pays</option>{countries.map(value=><option key={String(value)}>{String(value)}</option>)}</select><input type="date" value={from} onChange={event=>setFrom(event.target.value)} className="admin-input"/><input type="date" value={to} onChange={event=>setTo(event.target.value)} className="admin-input"/></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">ID demande</th><th className="p-4">Date</th><th className="p-4">Client</th><th className="p-4">Sexe</th><th className="p-4">Ville</th><th className="p-4">Région/État</th><th className="p-4">Pays</th><th className="p-4">Motif / plaintes</th><th className="p-4">Statut</th><th className="p-4">Nutritionniste</th><th className="p-4">Date d’attribution</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(row=>{const profile=row.client_profiles||{},partner=partners.find(item=>item.id===row.selected_partner_id);return <tr key={row.id} className="align-top hover:bg-slate-50/70"><td className="p-4 font-mono text-xs font-bold">{row.request_number||String(row.id).slice(0,12)}</td><td className="whitespace-nowrap p-4">{row.created_at?new Date(row.created_at).toLocaleDateString("fr-FR"):"—"}</td><td className="p-4"><b>{profile.full_name||"Client"}</b><br/><span className="text-xs text-slate-500">{profile.email||""}</span></td><td className="p-4">{profile.sex||"—"}</td><td className="p-4">{profile.city||row.city||"—"}</td><td className="p-4">{profile.state_region||"—"}</td><td className="p-4">{profile.country||row.country||"—"}</td><td className="max-w-xs p-4">{profile.complaints||row.reason||"Consultation"}</td><td className="p-4"><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-forest">{labels[row.status]||row.status}</span></td><td className="p-4">{partner?.full_name||"Non attribué"}</td><td className="whitespace-nowrap p-4">{row.admin_validated_at?new Date(row.admin_validated_at).toLocaleString("fr-FR"):"—"}</td><td className="p-4"><div className="flex gap-2"><button onClick={()=>open(row)} className="btn-primary px-3 py-2 text-xs">{row.selected_partner_id?"Réattribuer":"Attribuer"}</button><button onClick={()=>setHistory(row)} className="btn-secondary px-3 py-2 text-xs">Historique</button></div></td></tr>})}</tbody></table></div>{!filtered.length&&<p className="p-10 text-center text-slate-500">Aucune demande ne correspond aux filtres.</p>}</section>
    {current&&<div className="fixed inset-0 z-[90] grid place-items-center bg-forest/70 p-4"><div className="w-full max-w-xl rounded-[28px] bg-forest p-5 shadow-2xl"><div className="rounded-2xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-orange">Attribution du client</p><h2 className="mt-2 text-2xl font-black">{current.client_profiles?.full_name}</h2></div><button onClick={()=>setCurrent(null)} className="text-2xl">×</button></div><label className="mt-6 block text-sm font-bold">Nutritionniste traitant<select value={partnerId} onChange={event=>setPartnerId(event.target.value)} className="admin-input mt-2"><option value="">Sélectionner…</option>{[...active].sort((a,b)=>score(current,b)-score(current,a)).map(item=><option value={item.id} key={item.id}>{item.full_name} — score {score(current,item)}</option>)}</select></label><div className="mt-7 flex justify-end gap-3"><button onClick={()=>setCurrent(null)} className="btn-secondary">Annuler</button><button onClick={assign} disabled={!partnerId} className="btn-primary disabled:opacity-50">Confirmer</button></div></div></div></div>}
    {history&&<div className="fixed inset-0 z-[90] grid place-items-center bg-forest/70 p-4"><div className="w-full max-w-lg rounded-[28px] bg-white p-7 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">Historique des attributions</h2><button onClick={()=>setHistory(null)} className="text-2xl">×</button></div><div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm"><p><b>Client :</b> {history.client_profiles?.full_name}</p><p className="mt-2"><b>Attribution actuelle :</b> {partners.find(item=>item.id===history.selected_partner_id)?.full_name||"Aucune"}</p><p className="mt-2"><b>Date :</b> {history.admin_validated_at?new Date(history.admin_validated_at).toLocaleString("fr-FR"):"—"}</p><p className="mt-3 text-xs text-slate-500">Le détail est conservé dans le registre sécurisé des attributions.</p></div></div></div>}
  </div>
}
