"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useRouter} from "next/navigation";

type Question={id:string;category:string;type:'qcm'|'open'|'case_study';prompt:string;options?:string[];points:number};
type TestData={attempt_id:string;expires_at:string;status:string;answers:Record<string,string>;questions:Question[]};

export default function WrittenTest({eligible,completed,candidateId,candidateName}:{eligible:boolean;completed:boolean;candidateId:string;candidateName:string}){
  const [test,setTest]=useState<TestData|null>(null),[seconds,setSeconds]=useState(0),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[identity,setIdentity]=useState(false),[photo,setPhoto]=useState<Blob|null>(null),[camera,setCamera]=useState(false),[switches,setSwitches]=useState(0);
  const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),router=useRouter();
  const log=useCallback(async(type:string,details:Record<string,unknown>={})=>{if(test)await createClient().rpc('log_test_event',{p_attempt_id:test.attempt_id,p_event_type:type,p_details:details})},[test]);

  async function enableCamera(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});if(video.current)video.current.srcObject=stream.current;setCamera(true)}catch{setMessage('Impossible d’accéder à la caméra. Autorisez-la dans votre navigateur pour confirmer votre identité.')}}
  function capture(){if(!video.current)return;const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth||640;canvas.height=video.current.videoHeight||480;canvas.getContext('2d')?.drawImage(video.current,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob){setPhoto(blob);setMessage('Photo capturée. Vous pouvez maintenant commencer le test.')}},'image/jpeg',0.82);stream.current?.getTracks().forEach(track=>track.stop());setCamera(false)}
  async function start(){if(!identity||!photo){setMessage('Confirmez votre identité et prenez une photo avant de commencer.');return}setLoading(true);const previousAttempt=sessionStorage.getItem('nutvita-test-attempt');const path=`${candidateId}/test-identity/${crypto.randomUUID()}.jpg`;const supabase=createClient();const uploaded=await supabase.storage.from('recruitment-documents').upload(path,photo,{contentType:'image/jpeg'});if(uploaded.error){setMessage(uploaded.error.message);setLoading(false);return}const {data,error}=await supabase.rpc('start_recruitment_test');if(error){setMessage(error.message);setLoading(false);return}const current=data as TestData;setTest(current);await supabase.rpc('confirm_test_identity',{p_photo_path:path});await supabase.rpc('log_test_event',{p_attempt_id:current.attempt_id,p_event_type:previousAttempt===current.attempt_id?'reconnected':'started',p_details:{identity_name:candidateName}});sessionStorage.setItem('nutvita-test-attempt',current.attempt_id);setLoading(false)}
  useEffect(()=>()=>stream.current?.getTracks().forEach(track=>track.stop()),[]);
  useEffect(()=>{if(!test)return;const tick=()=>{const left=Math.max(0,Math.floor((new Date(test.expires_at).getTime()-Date.now())/1000));setSeconds(left);if(left===0)submit(true)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[test]);
  useEffect(()=>{if(!test)return;const visibility=()=>{if(document.hidden){setSwitches(value=>{const next=value+1;log('tab_hidden',{count:next});return next})}else log('tab_visible')};const offline=()=>log('connection_lost');const online=()=>log('reconnected');document.addEventListener('visibilitychange',visibility);window.addEventListener('offline',offline);window.addEventListener('online',online);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('offline',offline);window.removeEventListener('online',online)}},[test,log]);
  function answer(id:string,value:string){if(!test)return;const next={...test,answers:{...test.answers,[id]:value}};setTest(next);if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(async()=>{const {error}=await createClient().rpc('save_recruitment_test_answers',{p_answers:next.answers});setMessage(error?error.message:'Réponses sauvegardées automatiquement.')},700)}
  async function submit(expired=false){if(!test)return;if(!expired&&seconds>0&&!confirm('Terminer et soumettre définitivement le test ?'))return;await log('submission_requested',{expired});const {data,error}=await createClient().rpc('submit_recruitment_test');if(error){setMessage(error.message);return}await fetch('/api/recruitment/test-complete',{method:'POST'});sessionStorage.removeItem('nutvita-test-attempt');setMessage(`Test terminé. Score QCM automatique : ${data}.`);setTest(null);router.refresh()}
  if(completed)return <Panel title="Test écrit terminé" text="Votre tentative et son journal ont été enregistrés. Les événements de surveillance sont examinés uniquement par un humain."/>;
  if(!eligible)return <Panel title="Test non disponible" text="Le test sera accessible uniquement après une invitation officielle dans votre espace candidat."/>;
  if(!test)return <div className="rounded-2xl border bg-white p-8"><h2 className="text-2xl font-black">Confirmation d’identité</h2><p className="mt-3 leading-7 text-slate-500">Avant le test, confirmez votre identité et prenez une photo. Elle sera stockée de manière privée pour la vérification du dossier.</p><label className="mt-5 flex gap-3 rounded-xl bg-mint p-4"><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)} className="h-5 w-5"/><span>Je confirme être <b>{candidateName||'le candidat associé à ce compte'}</b> et j’accepte cette vérification raisonnable.</span></label><div className="mt-5">{camera?<><video ref={video} autoPlay playsInline muted className="max-h-80 w-full rounded-2xl bg-slate-900 object-cover"/><button onClick={capture} className="btn-primary mt-3">Capturer la photo</button></>:photo?<div className="rounded-xl bg-mint p-4 font-bold text-forest">Photo capturée avec succès.</div>:<button onClick={enableCamera} className="btn-secondary">Activer la caméra</button>}</div><p className="mt-5 text-sm text-slate-500">Durée : 60 minutes. Une seule tentative. Les changements d’onglet et reconnexions sont journalisés sans blocage automatique.</p>{message&&<p className="mt-4 text-sm font-semibold text-orange">{message}</p>}<button onClick={start} disabled={loading||!identity||!photo} className="btn-primary mt-6 disabled:opacity-50">{loading?'Préparation…':'Commencer le test'}</button></div>;
  return <div><div className="sticky top-3 z-20 mb-6 flex items-center justify-between rounded-2xl bg-forest p-5 text-white shadow-xl"><div><b>Test en cours</b><p className="text-xs text-white/60">Sauvegarde automatique · Sorties détectées : {switches}</p></div><div className="text-2xl font-black text-orange">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</div></div>{switches>=3&&<p className="mb-5 rounded-xl bg-orange/10 p-4 text-sm font-bold text-orange">Plusieurs sorties de page ont été détectées. Elles seront simplement examinées par l’équipe, sans blocage automatique.</p>}<div className="grid gap-5">{test.questions.map((q,i)=><section key={q.id} className="rounded-2xl border bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-leaf">{q.category} · {q.points} point(s)</p><h2 className="mt-3 text-lg font-black">{i+1}. {q.prompt}</h2>{q.type==='qcm'?<div className="mt-5 grid gap-3">{q.options?.map(option=><label key={option} className="flex cursor-pointer gap-3 rounded-xl border p-4"><input type="radio" name={q.id} checked={test.answers[q.id]===option} onChange={()=>answer(q.id,option)}/>{option}</label>)}</div>:<textarea rows={q.type==='case_study'?9:5} className="admin-input mt-5" value={test.answers[q.id]||''} onChange={e=>answer(q.id,e.target.value)} placeholder="Votre réponse…"/>}</section>)}</div>{message&&<p className="my-4 text-sm font-semibold text-leaf">{message}</p>}<button onClick={()=>submit(false)} className="btn-primary mt-6">Terminer le test</button></div>;
}
function Panel({title,text}:{title:string;text:string}){return <div className="rounded-2xl border bg-white p-8"><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 text-slate-500">{text}</p></div>}
