import "server-only";
import {cache} from "react";
import {redirect} from "next/navigation";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import type{AcademicPermission,AcademicRole,DegreeSession}from"@/types/degree-programs";

const commonManagement=["registry.export","curriculum.read","application.read","student.read","registration.read","enrollment.read","teaching.read","attendance.read","assessment.read","grade.read","result.read","internship.read","thesis.read","practicum.read","reporting.read"];
const fullAcademic=["academic.manage","reference.manage","roles.manage","audit.read","registry.export","curriculum.read","curriculum.manage","curriculum.approve","application.read","application.manage","application.decide","student.read","student.manage","registration.read","registration.manage","registration.validate","registration.finance","enrollment.read","enrollment.manage","teaching.read","teaching.manage","attendance.read","attendance.manage","assessment.read","assessment.manage","grade.read","grade.enter","grade.moderate","grade.approve","grade.publish","grade.correct","result.read","result.calculate","result.validate","internship.read","internship.manage","internship.validate","thesis.read","thesis.manage","thesis.validate","practicum.read","reporting.read","reporting.export","academic.finance.read","academic.finance.manage","competency.read","competency.manage"];
const rolePermissions:Partial<Record<AcademicRole,string[]>>={
 STUDENT:["student.self.read","application.self.manage","registration.self.read","learning.self","grade.self.read","assessment.self.read","result.self.read","practicum.self.read","dashboard.self.read","official_documents.self.read","finance.self.read","competency.self.read","portfolio.self.manage"],
 INSTRUCTOR:["teaching.assigned.manage","curriculum.read","teaching.read","teaching.content","attendance.manage","assessment.read","assessment.manage","grade.read","grade.enter","result.read","result.calculate","dashboard.instructor.read"],
 COURSE_COORDINATOR:["course.manage","curriculum.read","teaching.read","teaching.manage","attendance.read","assessment.read","assessment.manage","grade.read","grade.enter","grade.moderate","result.read","result.calculate","dashboard.instructor.read"],
 UNIT_COORDINATOR:["unit.manage","curriculum.read","assessment.read","grade.read","grade.moderate","result.read","result.calculate","dashboard.instructor.read"],
 PROGRAM_COORDINATOR:["program.manage",...commonManagement,"curriculum.manage","enrollment.manage","teaching.manage","attendance.manage","assessment.manage","grade.enter","grade.moderate","grade.approve","result.read","result.calculate","result.validate","internship.read","internship.manage","internship.validate","thesis.read","thesis.manage","thesis.validate","practicum.read","reporting.read","reporting.export"],
 ACADEMIC_SECRETARY:["admission.manage",...commonManagement,"application.manage","registration.manage","registration.validate","registration.finance","enrollment.manage","teaching.manage"],
 ACADEMIC_ADMIN:fullAcademic,
 INTERNSHIP_SUPERVISOR:["internship.assigned.manage","internship.read","internship.manage","practicum.read"],
 THESIS_SUPERVISOR:["thesis.assigned.manage","thesis.read","thesis.manage","practicum.read"],
 JURY_MEMBER:["jury.assigned.read"],
 JURY_CHAIR:["jury.assigned.decide"],
 FINANCE_OFFICER:["finance.manage","registry.export","registration.read","registration.finance","academic.finance.read","academic.finance.manage"],
 SUPER_ADMIN:fullAcademic
};
export const getDegreeSession=cache(async():Promise<DegreeSession|null>=>{const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:profile}=await supabase.from("profiles").select("full_name,email,role").eq("id",user.id).maybeSingle();const isSuperAdmin=profile?.role==="super_admin";const{data:assignments}=await supabase.from("academic_role_assignments").select("organization_id,role").eq("user_id",user.id).eq("active",true);const roles=Array.from(new Set((assignments||[]).map(row=>row.role as AcademicRole)));if(isSuperAdmin&&!roles.includes("SUPER_ADMIN"))roles.push("SUPER_ADMIN");if(!roles.length)return null;let organizationId=(assignments||[])[0]?.organization_id||null;let organizationName:string|null=null;if(!organizationId&&isSuperAdmin){const{data:ownedOrganization}=await supabase.from("organizations").select("id,name").order("created_at").limit(1).maybeSingle();organizationId=ownedOrganization?.id||null;organizationName=ownedOrganization?.name||null}if(organizationId&&!organizationName){const{data:organization}=await supabase.from("organizations").select("name").eq("id",organizationId).maybeSingle();organizationName=organization?.name||null}const permissions=Array.from(new Set(roles.flatMap(role=>rolePermissions[role]||[])));return{userId:user.id,fullName:profile?.full_name||user.user_metadata?.full_name||user.email||"User",email:profile?.email||user.email||"",platformRole:profile?.role||"student",organizationId,organizationName,roles,permissions,isSuperAdmin}});
export async function requireDegreeSession(permission?:AcademicPermission){const session=await getDegreeSession();if(!session)redirect("/dashboard");if(permission&&!session.permissions.includes(permission)&&!session.isSuperAdmin)redirect("/degree-programs?denied=1");return session}