import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";

async function identity(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();
 if(!user)return {error:NextResponse.json({message:"Authentification requise."},{status:401})};
 const [{data:admin},{data:access}]=await Promise.all([supabase.from("admin_users").select("role,active,full_name").eq("id",user.id).eq("active",true).maybeSingle(),supabase.from("maximus_user_access").select("*").eq("user_id",user.id).eq("active",true).maybeSingle()]);
 const isAdmin=admin?.role==="super_admin";if(!isAdmin&&!access)return {error:NextResponse.json({message:"Compte Maximus requis."},{status:403})};
 const units=Array.isArray(access?.units)&&access.units.length?access.units:[access?.unit].filter(Boolean);
 return {user,access,isAdmin,isFinance:units.includes("finance"),name:admin?.full_name||access?.full_name||user.email||"Staff"};
}
export async function GET(){const ctx=await identity();if("error" in ctx)return ctx.error;const admin=createAdminClient();let query=admin.from("maximus_internal_transfers").select("*,source:maximus_financial_accounts!maximus_internal_transfers_source_account_id_fkey(*),destination:maximus_financial_accounts!maximus_internal_transfers_destination_account_id_fkey(*)").order("created_at",{ascending:false});if(!ctx.isAdmin&&!ctx.isFinance)query=query.eq("initiated_by",ctx.user.id);const [{data,error},{data:accounts}]=await Promise.all([query,admin.from("maximus_financial_accounts").select("*").eq("active",true).order("channel").order("name")]);if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({items:data||[],accounts:accounts||[],permissions:{isAdmin:ctx.isAdmin,isFinance:ctx.isFinance}})}
export async function POST(request:Request){const ctx=await identity();if("error" in ctx)return ctx.error;const body=await request.json(),admin=createAdminClient();const source=String(body.source_account_id||""),destination=String(body.destination_account_id||""),amount=Number(body.amount||0),proof=String(body.proof_reference||"").trim(),reason=String(body.reason||"").trim();if(!source||!destination||source===destination||amount<=0||!proof||!reason)return NextResponse.json({message:"Comptes, montant, motif et preuve sont obligatoires."},{status:400});const {data:accounts}=await admin.from("maximus_financial_accounts").select("id,currency,active").in("id",[source,destination]);if(accounts?.length!==2||accounts.some(a=>!a.active)||accounts[0].currency!==accounts[1].currency)return NextResponse.json({message:"Selectionnez deux comptes actifs dans la meme devise."},{status:400});const {data,error}=await admin.from("maximus_internal_transfers").insert({source_account_id:source,destination_account_id:destination,amount,currency:accounts[0].currency,reason,proof_reference:proof,proof_url:String(body.proof_url||"")||null,initiated_by:ctx.user.id,initiated_by_name:ctx.name,initiator_is_finance:ctx.isFinance||ctx.isAdmin,transfer_date:body.transfer_date||new Date().toISOString().slice(0,10)}).select("*").single();if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({item:data},{status:201})}
export async function PATCH(request:Request){const ctx=await identity();if("error" in ctx)return ctx.error;const body=await request.json(),admin=createAdminClient();const {data:transfer}=await admin.from("maximus_internal_transfers").select("*").eq("id",String(body.id)).eq("status","pending").maybeSingle();if(!transfer)return NextResponse.json({message:"Transfert indisponible."},{status:404});if(transfer.initiated_by===ctx.user.id&&!ctx.isAdmin)return NextResponse.json({message:"Seul un administrateur peut confirmer son propre transfert."},{status:403});if(transfer.initiator_is_finance&&!ctx.isAdmin)return NextResponse.json({message:"Un transfert initie par la finance doit etre confirme par un administrateur."},{status:403});if(!transfer.initiator_is_finance&&!ctx.isAdmin&&!ctx.isFinance)return NextResponse.json({message:"Confirmation reservee a la finance ou a un administrateur."},{status:403});if(body.action==="reject"){const {data,error}=await admin.from("maximus_internal_transfers").update({status:"rejected",reviewed_by:ctx.user.id,review_note:String(body.note||""),reviewed_at:new Date().toISOString()}).eq("id",transfer.id).select("*").single();if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({item:data})}const {data,error}=await admin.rpc("confirm_maximus_internal_transfer",{p_transfer_id:transfer.id,p_actor:ctx.user.id,p_note:String(body.note||"")});if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({item:data})}
