import {NextResponse} from "next/server";
import {z} from "zod";
import {getDegreeSession} from "@/lib/degree-programs/access";
import {createSupabaseServerClient} from "@/lib/supabase/server";
const createSchema=z.object({candidateUserId:z.uuid(),programId:z.uuid(),programVersionId:z.union([z.uuid(),z.literal("")]).optional(),academicYearId:z.uuid(),campusId:z.union([z.uuid(),z.literal("")]).optional(),comments:z.string().optional()});
const transitionSchema=z.object({applicationId:z.uuid(),status:z.enum(["SUBMITTED","UNDER_REVIEW","INCOMPLETE","ELIGIBLE","ADMITTED","REJECTED","WAITLISTED","WITHDRAWN"]),comment:z.string().min(3)});
const studentSchema=z.object({applicationId:z.uuid(),reason:z.string().min(3)});
export async function POST(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!session.organizationId)return NextResponse.json({error:"Organization required"},{status:400});const parsed=createSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload",details:parsed.error.flatten()},{status:400});if(parsed.data.candidateUserId!==session.userId&&!session.isSuperAdmin&&!session.permissions.includes("application.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const d=parsed.data;const supabase=await createSupabaseServerClient();const{data,error}=await supabase.from("academic_applications").insert({organization_id:session.organizationId,candidate_user_id:d.candidateUserId,program_id:d.programId,program_version_id:d.programVersionId||null,academic_year_id:d.academicYearId,campus_id:d.campusId||null,application_number:"",comments:d.comments||null,created_by:session.userId,updated_by:session.userId}).select("id,application_number").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data,{status:201})}
export async function PATCH(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=transitionSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload"},{status:400});const supabase=await createSupabaseServerClient();const{data,error}=await supabase.rpc("academic_transition_application",{p_application_id:parsed.data.applicationId,p_status:parsed.data.status,p_comment:parsed.data.comment});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,data})}
export async function PUT(request:Request){const session=await getDegreeSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!session.isSuperAdmin&&!session.permissions.includes("student.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=studentSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid payload"},{status:400});const supabase=await createSupabaseServerClient();const{data,error}=await supabase.rpc("academic_materialize_student",{p_application_id:parsed.data.applicationId,p_reason:parsed.data.reason});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,data})}