'use client';

import { FormEvent, useEffect, useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

type Call = { id: string; reference: string; title: string; category: string; service_area?: string; requirements: string; terms_of_reference: string; closing_at?: string };

export default function VendorCallsPage() {
  const [items, setItems] = useState<Call[]>([]);
  const [selected, setSelected] = useState<Call | null>(null);
  const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/vendor-calls').then(response => response.json()).then(payload => setItems(payload.items || [])); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch('/api/vendor-calls', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, call_id: selected.id }) }); const payload = await response.json(); setMessage(response.ok ? 'Votre candidature fournisseur a ete transmise.' : payload.message); if (response.ok) setSelected(null); }
  return <><Header /><main className="mx-auto min-h-[70vh] max-w-7xl px-5 py-12"><p className="text-xs font-black uppercase tracking-widest text-orange">Partenariats</p><h1 className="mt-2 text-4xl font-black text-forest">Appels fournisseurs</h1><p className="mt-3 max-w-3xl text-slate-600">Consultez les opportunites ouvertes et soumettez la candidature de votre structure.</p>{message && <p className="mt-6 rounded-md bg-mint p-4 font-semibold text-forest">{message}</p>}<div className="mt-8 grid gap-5">{items.map(item => <article key={item.id} className="rounded-lg border bg-white p-6"><p className="text-xs font-bold text-leaf">{item.reference} · {item.category}</p><h2 className="mt-2 text-2xl font-black">{item.title}</h2><p className="mt-2 text-sm text-slate-500">{item.service_area}</p><p className="mt-5 whitespace-pre-wrap text-sm leading-7">{item.requirements}</p><button onClick={() => setSelected(item)} className="mt-5 rounded-md bg-[#24945f] px-5 py-3 font-bold text-white">Soumettre une candidature</button></article>)}{!items.length && <p className="rounded-lg border bg-white p-10 text-center text-slate-500">Aucun appel fournisseur ouvert.</p>}</div></main><Footer />{selected && <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={submit} className="mx-auto my-6 grid max-w-3xl gap-4 rounded-lg bg-white p-6"><h2 className="text-2xl font-black">{selected.title}</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Entreprise"><input name="company_name" className="admin-input" required /></Field><Field label="Numero d enregistrement"><input name="registration_number" className="admin-input" /></Field><Field label="Personne de contact"><input name="contact_name" className="admin-input" required /></Field><Field label="Email"><input name="email" type="email" className="admin-input" required /></Field><Field label="Telephone"><input name="phone" className="admin-input" required /></Field><Field label="Pays"><input name="country" className="admin-input" required /></Field><Field label="Region"><input name="region" className="admin-input" /></Field><Field label="Ville"><input name="city" className="admin-input" /></Field></div><Field label="Adresse"><input name="address" className="admin-input" /></Field><Field label="Experience et capacites"><textarea name="experience_summary" className="admin-input min-h-32" required /></Field><div className="flex justify-end gap-3"><button type="button" onClick={() => setSelected(null)} className="rounded-md border px-4 py-2 font-bold">Annuler</button><button className="rounded-md bg-[#24945f] px-5 py-3 font-bold text-white">Soumettre</button></div></form></div>}</>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold">{label}{children}</label>; }
