import {describe,expect,it} from "vitest";
import {buildHealthReportModel,validateFinalReport} from "../engine";
const profile={birth_date:"1985-01-01",preferred_language:"fr"};
const row=(date:string,values:Record<string,unknown>)=>({id:date,measured_at:`${date}T12:00:00Z`,...values});
const build=(overrides:Record<string,any>={})=>buildHealthReportModel({profile,anthropometry:[],biology:[],food:[],lifestyle:[],locale:"fr",...overrides});
const indicator=(model:ReturnType<typeof buildHealthReportModel>,id:string)=>model.indicators.find(item=>item.indicatorId===id)!;
describe("health report engine v2",()=>{
 it("keeps strict height and waist mappings",()=>{const model=build({anthropometry:[row("2026-01-01",{height_cm:180,waist_cm:95}),row("2026-02-01",{height_cm:180,waist_cm:92})]});expect(indicator(model,"anthropometry.height").currentValue).toBe(180);expect(indicator(model,"anthropometry.waist").currentValue).toBe(92);expect(indicator(model,"anthropometry.height").chart.enabled).toBe(false)});
 it("uses kg, cm and kg/m² with a calculated BMI",()=>{const model=build({anthropometry:[row("2026-01-01",{weight_kg:81,height_cm:180,bmi:25})]});expect(indicator(model,"anthropometry.weight").unit).toBe("kg");expect(indicator(model,"anthropometry.height").unit).toBe("cm");expect(indicator(model,"anthropometry.bmi").unit).toBe("kg/m²");expect(indicator(model,"anthropometry.bmi").contentType).toBe("calculated")});
 it("normalizes wellness domains to a fixed 0-4 scale",()=>{const model=build({lifestyle:[{id:"l1",assessment_date:"2026-01-01",nutrition_score:75,physical_activity_score:50,lifestyle_score:100}]});expect(indicator(model,"questionnaire.nutrition").currentValue).toBe(3);expect(indicator(model,"questionnaire.activity").currentValue).toBe(2);expect(indicator(model,"questionnaire.lifestyle").currentValue).toBe(4);expect(indicator(model,"questionnaire.activity").chart.domain).toEqual([0,4])});
 it("distinguishes initial, variation and longitudinal trend",()=>{expect(indicator(build({anthropometry:[row("2026-01-01",{weight_kg:80})]}),"anthropometry.weight").trend).toBe("initial");expect(indicator(build({anthropometry:[row("2026-01-01",{weight_kg:80}),row("2026-02-01",{weight_kg:79})]}),"anthropometry.weight").trend).toBe("variation_only");expect(indicator(build({anthropometry:[row("2026-01-01",{weight_kg:80}),row("2026-02-01",{weight_kg:79}),row("2026-03-01",{weight_kg:78})]}),"anthropometry.weight").trend).toBe("decreasing")});
 it("never treats missing data as normal",()=>{const item=indicator(build(),"anthropometry.waist");expect(item.status).toBe("not_measured");expect(item.currentValue).toBeNull();expect(item.interpretation).toContain("Donnée non disponible")});
 it("does not call weight loss favorable without a goal context",()=>{const model=build({anthropometry:[row("2026-01-01",{weight_kg:80}),row("2026-02-01",{weight_kg:78})]});expect(indicator(model,"anthropometry.weight").direction).toBe("down");expect(indicator(model,"anthropometry.weight").clinicalMeaning).toBe("contextual")});
 it("rejects implausible adult BMI instead of interpreting it",()=>{const model=build({anthropometry:[row("2026-01-01",{bmi:333024})]});expect(indicator(model,"anthropometry.bmi").currentValue).toBeNull();expect(model.validationIssues.some(issue=>issue.code==="implausible_value")).toBe(true)});
 it("does not infer a blood-pressure trend from one measure",()=>{const model=build({biology:[row("2026-01-01",{systolic_pressure:116,diastolic_pressure:79})]});expect(indicator(model,"cardiovascular.systolic").trend).toBe("initial");expect(indicator(model,"cardiovascular.diastolic").trend).toBe("initial")});
 it("blocks internal alert codes from final content",()=>{const model=build();model.indicators[0].interpretation="[watch] internal";expect(validateFinalReport(model).some(issue=>issue.code==="internal_code_visible"&&issue.severity==="critical")).toBe(true)});
 it("renders English labels from the same engine",()=>{const model=buildHealthReportModel({profile,anthropometry:[row("2026-01-01",{weight_kg:80})],biology:[],food:[],lifestyle:[],locale:"en"});expect(indicator(model,"anthropometry.weight").label).toBe("Weight")});
});