import { Award, Ban, CheckCircle2, Search } from "lucide-react";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getPublicEnvironment, isSupabaseConfigured } from "@/lib/env";
import { LocalizedText } from "@/components/i18n/LocalizedText";
import { DynamicCertificate } from "@/components/certificates/DynamicCertificate";
import type { ReactNode } from "react";
type VerificationRecord={certificate_number:string;status:string;recipient_name:string;course_title:string;course_code:string;final_score:number;issued_at:string;revoked_at:string|null};
export async function PublicCertificateVerification({certificateId}:{certificateId:string}){
 if(!isSupabaseConfigured())return <StatusCard icon={<Search size={42}/>} titleFr="Registre public non configure" titleEn="Public registry not configured" message="Configurez Supabase et appliquez les migrations Academy 006 et 009."/>;
 const supabase=await createSupabaseServerClient();const{data,error}=await supabase.rpc("verify_certificate",{public_certificate_number:certificateId});const record=(data as VerificationRecord[]|null)?.[0]??null;const valid=record?.status==="valid"&&!record.revoked_at;
 if(!valid)return <StatusCard icon={record?<Ban size={42}/>:<Search size={42}/>} titleFr={record?"Certificat non valide":"Certificat introuvable"} titleEn={record?"Invalid certificate":"Certificate not found"} message={error?"Le registre de verification est indisponible.":`Aucun certificat valide ne correspond au numero ${certificateId}.`}/>;
 const base=getPublicEnvironment().siteUrl.replace(/\/$/,"");const verificationUrl=`${base}/certificates/verify/${record.certificate_number}`;
 return <main className="min-h-screen bg-[#F8FAFC] px-4 py-10"><section className="mx-auto mb-7 max-w-5xl rounded-2xl bg-green-100 p-5 text-center text-green-800"><CheckCircle2 className="mx-auto" size={34}/><h1 className="mt-2 text-2xl font-extrabold">Certificat authentique</h1><p>Verification effectuee directement dans le registre public NutVitaGlobalis Academy.</p></section><DynamicCertificate data={{recipientName:record.recipient_name,courseName:record.course_title,courseSubtitle:`Score final : ${Number(record.final_score)}%`,certificateId:record.certificate_number,completionDate:new Date(record.issued_at).toLocaleDateString("fr-FR",{day:"2-digit",month:"long",year:"numeric"}),directorName:"Direction academique NutVitaGlobalis",verificationUrl}}/></main>;
}
function StatusCard({icon,titleFr,titleEn,message}:{icon:ReactNode;titleFr:string;titleEn:string;message:string}){return <main className="min-h-screen bg-[#F8FAFC] px-6 py-16"><section className="mx-auto max-w-2xl rounded-[30px] border bg-white p-8 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-amber-100 text-amber-700">{icon}</div><LocalizedText as="h1" className="mt-5 text-3xl font-extrabold text-[#063D2E]" fr={titleFr} en={titleEn}/><p className="mt-4 text-slate-600">{message}</p><div className="mt-8 flex justify-center gap-2 border-t pt-6 text-sm text-slate-500"><Award size={18}/>Registre public NutVitaGlobalis Academy</div></section></main>}