import Link from "next/link";
import { ArrowRight, CalendarDays, Check, ClipboardCheck, HeartPulse, House, Laptop, MessageCircle, Scale, ShieldCheck, Sparkles, Stethoscope, Target, UserRound, Video } from "lucide-react";
import MedicalDisclaimer from "@/components/MedicalDisclaimer";
import ClinicalNutritionInstitutional from "@/components/ClinicalNutritionInstitutional";
import { getClientEntitlements } from "@/lib/client";
import { getCurrentLocale } from "@/lib/i18n-server";
import { getTeleconseils } from "@/lib/public-content";
import { getSitePage } from "@/lib/site-pages";
import { createClient } from "@/lib/supabase/server";

export const metadata={title:"Consultations diététiques et nutritionnelles | NutVitaGlobalis"};

type StoredProgram={id?:string;name?:string;description?:string};
const programmeDefinitions=[
 {key:"pregnancy",match:["femme enceinte","grossesse","pregnan"],icon:HeartPulse,fr:"Nutrition/alimentation pendant la grossesse",en:"Nutrition and healthy eating during pregnancy",descriptionFr:"Un accompagnement nutritionnel adapté à chaque étape de la grossesse.",descriptionEn:"Nutrition support tailored to every stage of pregnancy.",tone:"bg-rose-50 text-rose-600"},
 {key:"infant",match:["infant","enfant","child"],icon:UserRound,fr:"Nutrition infantile",en:"Infant nutrition",descriptionFr:"Des repères personnalisés pour soutenir la croissance et l'alimentation de l'enfant.",descriptionEn:"Personalized guidance to support child growth and nutrition.",tone:"bg-sky-50 text-sky-600"},
 {key:"metabolic",match:["diab","hypertension","metabol"],icon:Stethoscope,fr:"Diabète, Hypertension, Dyslipidémie / Syndrome métabolique",en:"Diabetes, Hypertension, Dyslipidemia / Metabolic Syndrome",descriptionFr:"Une stratégie alimentaire coordonnée avec votre situation clinique et vos traitements.",descriptionEn:"A nutrition strategy coordinated with your clinical situation and treatment.",tone:"bg-emerald-50 text-emerald-700"},
 {key:"weight",match:["poids","weight"],icon:Scale,fr:"Gestion du poids",en:"Weight management",descriptionFr:"Un parcours réaliste et progressif pour retrouver un équilibre durable.",descriptionEn:"A realistic, progressive pathway towards lasting balance.",tone:"bg-amber-50 text-amber-600"},
 {key:"sport",match:["sport","performance"],icon:Target,fr:"Nutrition sportive",en:"Sports nutrition",descriptionFr:"Optimisez vos performances, votre récupération et votre composition corporelle.",descriptionEn:"Optimize performance, recovery and body composition.",tone:"bg-violet-50 text-violet-600"},
] as const;

export default async function Teleconseils(){
 const[loaded,locale,page]=await Promise.all([getTeleconseils(),getCurrentLocale(),getSitePage("teleconseils")]);
 const en=locale==="en",t=(fr:string,english:string)=>en?english:fr;
 const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();
 const hasAccess=user?(await getClientEntitlements(supabase,user.id)).teleconsultation:false;
 const stored=(loaded||[]) as StoredProgram[];
 const programmes=programmeDefinitions.map(def=>{const source=stored.find(row=>def.match.some(term=>String(row.name||"").toLowerCase().includes(term)));return{...def,id:source?.id};});
 const bookingHref=hasAccess
  ? "/api/access/open?service=teleconsultation&role=client"
  : user
    ? "/nutritionnistes"
    : `/connexion?redirect=${encodeURIComponent("/nutritionnistes")}`; const consultationTypes=[
  [Stethoscope,t("Consultation nutritionnelle","Nutrition consultation"),t("Bilan nutritionnel et recommandations personnalisées","Nutrition assessment and personalized recommendations")],
  [ClipboardCheck,t("Consultation diététique","Dietetic consultation"),t("Plan alimentaire adapté à vos besoins et préférences","Meal plan tailored to your needs and preferences")],
  [CalendarDays,t("Consultation de suivi","Follow-up consultation"),t("Suivi des progrès et ajustement du plan","Progress monitoring and plan adjustments")],
  [Video,t("Téléconsultation","Teleconsultation"),t("Échange sécurisé en ligne avec un professionnel","Secure online session with a professional")],
  [House,t("Consultation à domicile","Home consultation"),t("Disponible dans certaines zones","Available in selected areas")],
 ] as const;
 const needs=en?["Weight loss or gain","Child, maternal and breastfeeding nutrition","Diabetes, hypertension, dyslipidemia / metabolic syndrome","Malnutrition and clinical nutrition","Sport and performance","Kidney disease, cancer or other needs"]:["Perte ou prise de poids","Nutrition infantile, grossesse et allaitement","Diabète, hypertension, dyslipidémie / syndrome métabolique","Malnutrition et nutrition clinique","Sport et performance","Maladie rénale, cancer ou autres besoins"];
 const steps=en?[["Book your consultation","Choose online or in person and the time that suits you."],["Assessment and evaluation","We review your needs, habits and health objectives."],["Personalized nutrition plan","You receive a realistic plan tailored to your daily life."],["Follow-up and adjustments","We monitor progress and adapt recommendations."]]:[["Réservez votre consultation","Choisissez le format et le créneau qui vous conviennent."],["Échange et évaluation","Nous analysons vos besoins, vos habitudes et vos objectifs."],["Plan nutritionnel personnalisé","Vous recevez un plan réaliste, clair et adapté à votre quotidien."],["Suivi et ajustements","Nous suivons vos progrès et adaptons les recommandations."]];
 return <main className="overflow-hidden bg-[#fbfcfa] text-forest"><MedicalDisclaimer/>
  <section className="relative isolate min-h-[680px] overflow-hidden border-b bg-forest"><img src={page?.hero_image_url||"/images/clinical-nutrition-hero-v1.png"} alt={t("Nutritionniste NutVitaGlobalis en consultation","NutVitaGlobalis dietitian during a consultation")} className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-forest/95 via-forest/55 to-transparent"/><div className="container-site relative flex min-h-[650px] items-center py-20"><div className="max-w-2xl"><span className="inline-flex items-center rounded-full bg-white/90 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-leaf shadow-soft"><HeartPulse className="mr-2 h-4"/>{page?.eyebrow||t("NutVitaGlobalis expertise","NutVitaGlobalis expertise")}</span><h1 className="mt-6 whitespace-pre-line text-5xl font-black leading-[1.02] text-white md:text-7xl">{page?.title||t("Nutrition clinique & téléconsultation","Clinical nutrition & teleconsultation")}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/80">{page?.description||t("Accompagner les patients, les établissements de santé et les organisations grâce à des interventions nutritionnelles fondées sur les preuves.","Supporting patients, health facilities and organizations through evidence-based nutrition interventions.")}</p><div className="mt-6 grid gap-3 text-sm font-bold text-white sm:grid-cols-2">{[t("En ligne ou en présentiel","Online or in person"),t("Suivi personnalisé","Personalized follow-up"),t("Approche fondée sur les preuves","Evidence-based approach"),t("Confidentialité et écoute","Privacy and attentive care")].map(item=><span key={item} className="flex items-center gap-2"><Check className="h-5 text-leaf"/>{item}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={bookingHref} className="btn-primary">{hasAccess?t("Accéder à mes consultations","Open my consultations"):t("Consulter un nutritionniste/Diététicien","Consult a nutritionist/Dietitian")}<ArrowRight className="ml-2 h-4"/></Link><Link href={page?.secondary_cta_url||"/contact"} className="btn-secondary">{page?.secondary_cta_label||t("Demander une proposition","Request a proposal")}<MessageCircle className="ml-2 h-4"/></Link></div></div></div></section>

  <ClinicalNutritionInstitutional sections={page?.sections||[]} english={en}/>

  <section className="relative z-10 pb-16"><div className="container-site grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-7 shadow-xl md:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-leaf">{t("Choisissez votre type de consultation","Choose your consultation type")}</p><div className="mt-5 grid gap-2">{consultationTypes.map(([Icon,title,text])=><div key={title} className="group flex items-center gap-4 rounded-2xl border p-4 transition hover:border-leaf hover:bg-mint"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-mint text-leaf"><Icon className="h-5"/></span><div className="flex-1"><h2 className="font-black">{title}</h2><p className="mt-1 text-xs text-slate-500">{text}</p></div><ArrowRight className="h-4 text-leaf transition group-hover:translate-x-1"/></div>)}</div><Link href={bookingHref} className="mt-6 inline-flex items-center font-black text-leaf">{t("Accéder à mes consultations","Open consultations")}<ArrowRight className="ml-2 h-4"/></Link></article><article className="rounded-[2rem] bg-forest p-7 text-white shadow-xl md:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-orange">{t("Une orientation fondée sur vos besoins","Guidance based on your needs")}</p><h2 className="mt-3 text-3xl font-black text-white">{t("Votre objectif définit le bon parcours","Your goal shapes the right pathway")}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{needs.map(item=><div key={item} className="flex min-h-20 items-center gap-3 rounded-2xl border border-white/10 bg-white/10 p-4 text-sm font-bold"><Sparkles className="h-5 shrink-0 text-orange"/>{item}</div>)}</div><div className="mt-6 flex items-center justify-between rounded-2xl bg-white p-5 text-forest"><div><p className="font-black">{t("Un besoin spécifique ?","A specific need?")}</p><p className="mt-1 text-xs text-slate-500">{t("Notre équipe vous aide à choisir.","Our team helps you choose.")}</p></div><Link href="/contact" className="font-black text-leaf">{t("Nous contacter","Contact us")}</Link></div></article></div></section>

  <section className="section bg-white"><div className="container-site"><p className="text-xs font-black uppercase tracking-[.18em] text-leaf">{t("Programmes spécialisés","Specialized programmes")}</p><div><h2 className="mt-3 max-w-3xl text-4xl font-black md:text-5xl">{t("Nos principaux programmes d'accompagnement","Our main support programmes")}</h2></div><div className="mt-9 grid items-start gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{programmes.map(program=>{const Icon=program.icon;return <article key={program.key} className="group grid min-h-[350px] grid-rows-[auto_auto_1fr_auto] overflow-hidden rounded-3xl border bg-white p-6 shadow-soft transition hover:-translate-y-1 hover:shadow-xl"><span className={`grid h-14 w-14 place-items-center rounded-full ${program.tone}`}><Icon className="h-7"/></span><h3 className="mt-5 break-words text-[1.08rem] font-black leading-6 hyphens-auto">{en?program.en:program.fr}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{en?program.descriptionEn:program.descriptionFr}</p><Link href={`/programmes-nutritionnels/${({pregnancy:"grossesse",infant:"nutrition-infantile",metabolic:"cardiometabolique",weight:"gestion-poids",sport:"nutrition-sportive"} as Record<string,string>)[program.key]}`} className="mt-6 inline-flex items-center font-black text-leaf">{t("Découvrir","Discover")}<ArrowRight className="ml-2 h-4 transition group-hover:translate-x-1"/></Link></article>})}</div></div></section>

  <section className="section bg-[#eef7f2]"><div className="container-site"><h2 className="text-center text-4xl font-black">{t("Un accompagnement simple et efficace en 4 étapes","Simple, effective support in 4 steps")}</h2><div className="relative mt-10 grid gap-5 md:grid-cols-4">{steps.map(([title,text],index)=><article key={title} className="relative rounded-3xl border bg-white p-6 text-center shadow-soft"><span className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-leaf font-black text-white">{index+1}</span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div></section>

  <section className="section"><div className="container-site grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-[2rem] border bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-leaf">{t("Pourquoi nous choisir","Why choose us")}</p><h2 className="mt-3 text-3xl font-black">{t("Une expertise attentive et rigoureuse","Attentive, rigorous expertise")}</h2><div className="mt-6 grid gap-4">{[t("Approche scientifique et personnalisée","Scientific and personalized approach"),t("Nutritionnistes expérimentés et certifiés","Experienced, qualified dietitians"),t("Plans alimentaires réalistes et culturellement adaptés","Realistic, culturally appropriate meal plans"),t("Suivi régulier et motivation continue","Regular follow-up and continued motivation"),t("Confidentialité et écoute garanties","Privacy and attentive listening")].map(item=><p key={item} className="flex gap-3 text-sm font-bold"><ShieldCheck className="h-5 shrink-0 text-leaf"/>{item}</p>)}</div></article><article className="rounded-[2rem] bg-forest p-8 text-white shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-orange">{t("Formats disponibles","Available formats")}</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["/images/consultation-format-online.png",t("En ligne","Online"),t("WhatsApp, Zoom ou visioconférence sécurisée","WhatsApp, Zoom or secure video")],["/images/consultation-format-clinic.png",t("En cabinet","In clinic"),t("Dans nos centres NutVitaGlobalis","At our NutVitaGlobalis centres")],["/images/consultation-format-home.png",t("À domicile","At home"),t("Disponible dans certaines zones","Available in selected areas")]].map(([image,title,text])=><div key={title} className="overflow-hidden rounded-2xl bg-white/10"><img src={image} alt={title} className="h-36 w-full object-cover"/><div className="p-5"><h3 className="font-black text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-white/65">{text}</p></div></div>)}</div></article></div></section>

  <section className="pb-16"><div className="container-site"><div className="relative overflow-hidden rounded-[2.5rem] bg-forest px-8 py-12 text-white md:px-14"><div className="relative z-10 max-w-3xl"><p className="text-xs font-black uppercase tracking-[.18em] text-orange">NutVitaGlobalis</p><h2 className="mt-4 text-4xl font-black text-white md:text-5xl">{t("Prêt(e) à améliorer votre santé ?","Ready to improve your health?")}</h2><p className="mt-4 max-w-2xl text-white/70">{t("Notre équipe vous accompagne à chaque étape avec une approche professionnelle, humaine et personnalisée.","Our team supports you at every step with a professional, human and personalized approach.")}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={bookingHref} className="btn-primary">{t("Prendre rendez-vous","Book an appointment")}</Link><Link href="/contact" className="inline-flex items-center rounded-full border border-white px-6 py-3 font-black text-white">{t("Discuter avec nous","Talk to us")}<MessageCircle className="ml-2 h-4"/></Link></div></div><div className="absolute -bottom-28 -right-20 h-80 w-80 rounded-full bg-orange/20 blur-3xl"/></div></div></section>
 </main>
}
