import ClientShell from "@/components/client/ClientShell";
import {requireTeleconsultationAccess} from "@/lib/client";
export default async function Page(){
 const {supabase,user}=await requireTeleconsultationAccess();
 const [{data:consultations},{data:menus},{data:meetings}]=await Promise.all([
  supabase.from("partner_consultations").select("id,consultation_code,reason,status,scheduled_at,completed_at").eq("client_id",user.id).order("scheduled_at",{ascending:false}),
  supabase.from("client_menu_plans").select("id,menu_code,title,status,period_start,period_end,generated_at").eq("client_id",user.id).eq("status","validated").order("generated_at",{ascending:false}),
  supabase.from("collaboration_call_members").select("call_id,collaboration_calls(id,call_code,title,status,scheduled_at,duration_minutes)").eq("user_id",user.id)
 ]);
 const rows=[...(consultations||[]).map((x:any)=>({id:x.id,date:x.completed_at||x.scheduled_at,type:"Consultation",reference:x.consultation_code,title:x.reason||"Consultation",status:x.status,href:`/espace-client/dossier?consultation=${x.id}`})),...(menus||[]).map((x:any)=>({id:x.id,date:x.generated_at,type:"Menu",reference:x.menu_code,title:x.title,status:x.status,href:`/espace-client/menus?id=${x.id}`})),...(meetings||[]).map((x:any)=>({id:x.call_id,date:x.collaboration_calls?.scheduled_at,type:"Réunion",reference:x.collaboration_calls?.call_code,title:x.collaboration_calls?.title,status:x.collaboration_calls?.status,href:"/espace-client/appels"}))].sort((a,b)=>new Date(b.date||0).getTime()-new Date(a.date||0).getTime());
 return <ClientShell email={user.email||""}><div className="mb-7"><h1 className="text-3xl font-black">Historique complet de mon accompagnement</h1><p className="mt-2 text-slate-500">Consultations, menus et réunions consignés dans votre dossier.</p></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Date</th><th className="p-4">Type</th><th className="p-4">Référence</th><th className="p-4">Détail</th><th className="p-4">Statut</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{rows.map(x=><tr key={x.type+x.id}><td className="p-4">{x.date?new Date(x.date).toLocaleString("fr-FR"):"—"}</td><td className="p-4 font-bold">{x.type}</td><td className="p-4 font-black text-forest">{x.reference||"—"}</td><td className="p-4">{x.title}</td><td className="p-4">{x.status}</td><td className="p-4"><a href={x.href} className="btn-secondary px-3 py-2">Voir les détails</a></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-400">Aucune activité enregistrée.</td></tr>}</tbody></table></div></ClientShell>
}
