"use client";
import { useEffect, useState } from "react";
import { Building2, CheckCircle2, MapPin, Truck, Utensils } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Mode="menus"|"locations"|"orders";
const statusLabels:Record<string,string>={awaiting_review:"Salle d’attente",quoted:"Devis envoyé",customer_confirmed:"Confirmée par le client",awaiting_delivery:"À livrer",out_for_delivery:"En livraison",delivered:"Livrée"};
export default function CateringManagement({mode}:{mode:Mode}){
  const [items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(){const response=await fetch(`/api/maximus/catering?resource=${mode}`,{cache:"no-store"});const json=await response.json();setItems(json.items||[]);if(!response.ok)setMessage(json.message)}
  useEffect(()=>{void load()},[mode]);
  async function create(form:FormData){setBusy(true);let imageUrl=String(form.get("image_url")||"")||null;const imageFile=form.get("image_file");if(mode==="menus"&&imageFile instanceof File&&imageFile.size>0){const extension=imageFile.name.split(".").pop()||"jpg",name=`${crypto.randomUUID()}.${extension}`;const client=createClient(),{error}=await client.storage.from("catering-menu-images").upload(name,imageFile,{upsert:false});if(error){setBusy(false);setMessage(error.message);return}imageUrl=client.storage.from("catering-menu-images").getPublicUrl(name).data.publicUrl}const data=mode==="menus"?{name_fr:form.get("name_fr"),name_en:form.get("name_en"),description_fr:form.get("description_fr"),description_en:form.get("description_en"),image_url:imageUrl,available_date:form.get("available_date"),city:form.get("city"),base_price:Number(form.get("base_price")||0)||null,currency:"XAF",published:form.get("published")==="on"}:{kind:form.get("kind"),name_fr:form.get("name_fr"),name_en:form.get("name_en"),city:form.get("city"),address:form.get("address"),contact_name:form.get("contact_name"),phone:form.get("phone"),active:true};const response=await fetch("/api/maximus/catering",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resource:mode,data})});const json=await response.json();setBusy(false);setMessage(response.ok?"Enregistrement effectué.":json.message);if(response.ok)void load()}
  async function action(id:string,actionName:string,extra:Record<string,unknown>={}){setBusy(true);const response=await fetch("/api/maximus/catering",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({resource:"orders",id,action:actionName,...extra})});const json=await response.json();setBusy(false);setMessage(response.ok?"Étape enregistrée.":json.message);if(response.ok)void load()}
  if(mode==="orders")return <div className="grid gap-6"><Header icon={Truck} title="Commandes de restauration" text="De la salle d’attente jusqu’à la recette remise à la finance."/><div className="grid gap-4">{items.map(order=><article key={order.id} className="rounded-xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black text-orange-600">{order.order_number}</p><h3 className="text-xl font-black">{order.contact_name} · {order.city}</h3><p className="mt-1 text-sm text-slate-500">{order.contact_phone} · {order.delivery_address}</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-800">{statusLabels[order.status]||order.status}</span></div><p className="mt-4 text-sm">{order.catering_order_items?.map((item:any)=>`${item.quantity} × ${item.menu_name}`).join(" · ")}</p>
      {order.status==="awaiting_review"&&<Quote order={order} busy={busy} onSubmit={action}/>}
      {order.status==="awaiting_delivery"&&<button disabled={busy} onClick={()=>action(order.id,"dispatch")} className="mt-5 rounded-lg bg-[#123d32] px-4 py-2 font-black text-white">Affecter et lancer la livraison</button>}
      {order.status==="out_for_delivery"&&<button disabled={busy} onClick={()=>action(order.id,"deliver",{delivery_note:"Livraison confirmée par le personnel"})} className="mt-5 rounded-lg bg-[#ef7f3b] px-4 py-2 font-black text-white">Marquer livrée</button>}
      {order.status==="delivered"&&<p className="mt-5 rounded-lg bg-amber-50 p-3 text-sm font-bold text-amber-900">Ticket de versement transmis à la Finance.</p>}
      {order.total_amount!=null&&<p className="mt-4 text-xl font-black">{Number(order.total_amount).toLocaleString("fr-FR")} {order.currency}</p>}
    </article>)}</div>{message&&<p className="rounded-lg bg-emerald-50 p-4 font-bold">{message}</p>}</div>;
  return <div className="grid gap-6"><Header icon={mode==="menus"?Utensils:Building2} title={mode==="menus"?"Publication des menus":"Sites de restauration"} text={mode==="menus"?"Publiez les plats visibles sur le site, en français et en anglais.":"Gérez les cuisines centrales, points de vente et hôpitaux partenaires."}/><form action={create} className="grid gap-4 rounded-xl border bg-white p-6 md:grid-cols-2"><input className="input" name="name_fr" required placeholder="Nom français"/><input className="input" name="name_en" placeholder="English name"/>{mode==="menus"?<><textarea className="input" name="description_fr" placeholder="Commentaire français"/><textarea className="input" name="description_en" placeholder="English description"/><input className="input" name="image_file" type="file" accept="image/jpeg,image/png,image/webp"/><input className="input" name="image_url" placeholder="Ou URL de la photo"/><input className="input" name="available_date" required type="date"/><input className="input" name="city" required placeholder="Ville"/><input className="input" name="base_price" type="number" min="0" placeholder="Prix indicatif"/><label className="flex items-center gap-2 font-bold"><input name="published" type="checkbox"/>Publier immédiatement</label></>:<><select className="input" name="kind"><option value="central_kitchen">Cuisine centrale</option><option value="sale_point">Point de vente</option><option value="partner_hospital">Hôpital partenaire</option></select><input className="input" name="city" required placeholder="Ville"/><input className="input" name="address" placeholder="Adresse"/><input className="input" name="contact_name" placeholder="Point focal"/><input className="input" name="phone" placeholder="Téléphone du point focal"/></>}<button disabled={busy} className="rounded-lg bg-[#123d32] px-5 py-3 font-black text-white md:col-span-2">Enregistrer</button></form>
    <div className="grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-xl border bg-white p-5"><h3 className="text-lg font-black">{item.name_fr}</h3><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><MapPin className="h-4"/>{item.city}</p><p className="mt-2 text-sm">{mode==="menus"?`${item.available_date} · ${item.published?"Publié":"Brouillon"}`:`${item.kind} · ${item.phone||"Sans téléphone"}`}</p></article>)}</div>{message&&<p className="rounded-lg bg-emerald-50 p-4 font-bold">{message}</p>}</div>
}
function Header({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <section><span className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-6"/></span><h2 className="mt-4 text-3xl font-black">{title}</h2><p className="mt-2 text-slate-500">{text}</p></section>}
function Quote({order,busy,onSubmit}:{order:any;busy:boolean;onSubmit:(id:string,action:string,extra:Record<string,unknown>)=>void}){const [prices,setPrices]=useState<Record<string,number>>({});return <div className="mt-5 grid gap-3 rounded-lg bg-slate-50 p-4">{order.catering_order_items?.map((item:any)=><label key={item.id} className="flex items-center justify-between gap-3 text-sm font-bold">{item.quantity} × {item.menu_name}<input className="input w-36" type="number" min="0" placeholder="Prix unitaire" onChange={e=>setPrices(p=>({...p,[item.id]:Number(e.target.value)}))}/></label>)}<button disabled={busy} onClick={()=>onSubmit(order.id,"quote",{item_prices:prices,delivery_fee:0,additional_fee:0,quote_note:"Tarif calculé selon le lieu de livraison et les exigences de la commande."})} className="mt-2 rounded-lg bg-[#ef7f3b] px-4 py-2 font-black text-white"><CheckCircle2 className="mr-2 inline h-4"/>Valider le coût et envoyer au client</button></div>}
