"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Row=Record<string,any>;
type Mode="online-payments"|"organization-accounts"|"partner-accounts"|"partner-payments"|"partner-registry";
const emptyAccount={account_type:"bank",account_holder:"",holder_type:"company",bank_name:"",bank_country:"",bank_address:"",account_number:"",iban:"",swift_bic:"",routing_code:"",mobile_operator:"",mobile_number:"",currency:"XAF",partner_vendor_id:"",active:true};
const emptyPayment={partner_vendor_id:"",payment_account_id:"",period_start:"",period_end:"",source_type:"online_services",source_reference:"",gross_revenue:0,amount_due:0,amount_paid:0,currency:"XAF",status:"pending",payment_date:"",finance_comment:""};

async function request(resource:string,body?:unknown){const response=await fetch(`/api/maximus/online-finance${body?"":`?resource=${resource}`}`,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,...body as object})}:{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.message||"Opération impossible.");return data}

export default function OnlineServiceFinance({mode}:{mode:Mode}){
  const [items,setItems]=useState<Row[]>([]),[vendors,setVendors]=useState<Row[]>([]),[accounts,setAccounts]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[type,setType]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[modal,setModal]=useState(false),[account,setAccount]=useState<Row>(emptyAccount),[payment,setPayment]=useState<Row>(emptyPayment),[commenting,setCommenting]=useState<Row|null>(null),[comment,setComment]=useState("");
  const fileRef=useRef<HTMLInputElement>(null),uploadTarget=useRef<Row|null>(null);
  const resource=mode;
  useEffect(()=>{(async()=>{setLoading(true);setError("");try{const result=await request(resource);setItems(result.items||[]);if(mode==="partner-payments"||mode==="partner-accounts"){const [vendorResult,accountResult]=await Promise.all([request("partner-registry"),request("partner-accounts")]);setVendors(vendorResult.items||[]);setAccounts(accountResult.items||[])}}catch(value){setError(value instanceof Error?value.message:"Chargement impossible.")}finally{setLoading(false)}})()},[resource,mode]);
  const filtered=useMemo(()=>items.filter(row=>{const text=JSON.stringify(row).toLowerCase(),date=String(row.payment_date||row.created_at||"").slice(0,10),rowType=row.partner_type||row.account_type||row.purchase_type||"",rowStatus=row.status||String(row.active);return(!query||text.includes(query.toLowerCase()))&&(!status||rowStatus===status)&&(!type||rowType===type)&&(!from||date>=from)&&(!to||date<=to)}),[items,query,status,type,from,to]);
  async function saveAccount(event:FormEvent){event.preventDefault();try{const result=await request(resource,{data:{...account,partner_vendor_id:mode==="partner-accounts"?account.partner_vendor_id:null}});setItems(current=>[result.item,...current]);setAccount(emptyAccount);setModal(false)}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible.")}}
  async function savePayment(event:FormEvent){event.preventDefault();try{const result=await request("partner-payments",{data:{...payment,gross_revenue:Number(payment.gross_revenue),amount_due:Number(payment.amount_due),amount_paid:Number(payment.amount_paid),payment_account_id:payment.payment_account_id||null,payment_date:payment.payment_date||null}});setItems(current=>[result.item,...current]);setPayment(emptyPayment);setModal(false)}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible.")}}
  async function addComment(){if(!commenting||!comment.trim())return;try{const result=await request("partner-payments",{action:"comment",id:commenting.id,comment});setItems(current=>current.map(row=>row.id===commenting.id?{...row,partner_payment_comments:[...(row.partner_payment_comments||[]),result.item]}:row));setComment("");setCommenting(null)}catch(value){setError(value instanceof Error?value.message:"Commentaire impossible.")}}
  async function upload(file:File){const row=uploadTarget.current;if(!row)return;const form=new FormData();form.append("resource",mode==="partner-payments"?"partner-payments":resource);form.append("id",row.id);form.append("file",file);const response=await fetch("/api/maximus/online-finance",{method:"POST",body:form});const data=await response.json();if(!response.ok)return setError(data.message||"Téléversement impossible.");setItems(current=>current.map(item=>item.id===row.id?{...item,...data.item}:item))}
  async function openDocument(path:string){const {data,error}=await createClient().storage.from("document-vault").createSignedUrl(path,180);if(error)setError(error.message);else window.open(data.signedUrl,"_blank","noopener,noreferrer")}
  const isAccounts=mode==="organization-accounts"||mode==="partner-accounts";
  const title=mode==="online-payments"?"Paiements en ligne":mode==="organization-accounts"?"Comptes de paiement manuel":mode==="partner-accounts"?"Comptes partenaires":mode==="partner-payments"?"Suivi des paiements aux prestataires":"Registre des partenaires";
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-black text-[#123d32]">{title}</h2><p className="mt-2 text-slate-500">Suivi Finance pour les services en ligne, centralisé dans Maximus.</p></div>{isAccounts&&<button onClick={()=>setModal(true)} className="rounded-md bg-[#209b68] px-5 py-3 font-bold text-white">+ Ajouter un compte</button>}{mode==="partner-payments"&&<button onClick={()=>setModal(true)} className="rounded-md bg-[#209b68] px-5 py-3 font-bold text-white">+ Initier un paiement</button>}</header>
    {error&&<p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
    <section className="rounded-md border bg-white p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input value={query} onChange={event=>setQuery(event.target.value)} className="admin-input" placeholder="Rechercher…"/><select value={type} onChange={event=>setType(event.target.value)} className="admin-input"><option value="">Tous les types</option>{mode==="partner-registry"?<><option value="nutritionist">Nutritionniste</option><option value="medical_specialist">Médecin</option><option value="promoter">Promoteur</option><option value="supplier">Fournisseur</option><option value="other">Autre</option></>:<><option value="bank">Bancaire</option><option value="mobile_money">Mobile Money</option><option value="consultation">Consultation</option><option value="subscription">Abonnement</option><option value="formation">Formation</option></>}</select><select value={status} onChange={event=>setStatus(event.target.value)} className="admin-input"><option value="">Tous les statuts</option>{["active","inactive","pending","approved","paid","succeeded","failed"].map(value=><option key={value}>{value}</option>)}</select><input type="date" value={from} onChange={event=>setFrom(event.target.value)} className="admin-input"/><input type="date" value={to} onChange={event=>setTo(event.target.value)} className="admin-input"/></div></section>
    <section className="overflow-hidden rounded-md border bg-white">{loading?<p className="p-12 text-center text-slate-500">Chargement…</p>:<div className="overflow-x-auto">
      {mode==="online-payments"&&<table className="w-full min-w-[1250px] text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-4">Date</th><th className="p-4">Client</th><th className="p-4">Service</th><th className="p-4">HT</th><th className="p-4">Taxes</th><th className="p-4">TTC</th><th className="p-4">Moyen</th><th className="p-4">Référence</th><th className="p-4">Statut</th><th className="p-4">Facture</th></tr></thead><tbody className="divide-y">{filtered.map(row=><tr key={row.id}><td className="p-4">{new Date(row.created_at).toLocaleDateString("fr-FR")}</td><td className="p-4"><b>{row.client_profiles?.full_name||"Client"}</b><br/><small>{row.client_profiles?.email}</small></td><td className="p-4">{row.product_name||row.purchase_type}</td><td className="p-4">{Number(row.price_excluding_tax||0).toLocaleString("fr-FR")}</td><td className="p-4">{Number(row.tax_amount||0).toLocaleString("fr-FR")}</td><td className="p-4 font-bold">{Number(row.total_including_tax||row.amount||0).toLocaleString("fr-FR")} {row.currency}</td><td className="p-4">{row.provider}</td><td className="p-4 font-mono text-xs">{row.checkout_reference}</td><td className="p-4">{row.status}</td><td className="p-4">{row.invoices?.file_path?<button onClick={()=>openDocument(row.invoices.file_path)} className="font-bold text-[#168353]">Consulter</button>:row.invoice_id?<Link href={`/espace-client/factures/${row.invoice_id}`} className="font-bold text-[#168353]">Consulter</Link>:"—"}</td></tr>)}</tbody></table>}
      {isAccounts&&<table className="w-full min-w-[1450px] text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-4">Partenaire</th><th className="p-4">Type de compte</th><th className="p-4">Titulaire</th><th className="p-4">Banque / opérateur</th><th className="p-4">Compte / téléphone</th><th className="p-4">IBAN</th><th className="p-4">SWIFT / Routing</th><th className="p-4">Pays</th><th className="p-4">Devise</th><th className="p-4">Pièces jointes</th><th className="p-4">Statut</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{filtered.map(row=><tr key={row.id}><td className="p-4">{row.partner_vendor_registry?.full_name||"NutVitaGlobalis"}</td><td className="p-4">{row.account_type}</td><td className="p-4"><b>{row.account_holder}</b><br/><small>{row.holder_type}</small></td><td className="p-4">{row.bank_name||row.mobile_operator||"—"}</td><td className="p-4">{row.account_number||row.mobile_number||"—"}</td><td className="p-4">{row.iban||"—"}</td><td className="p-4">{row.swift_bic||row.routing_code||"—"}</td><td className="p-4">{row.bank_country||"—"}</td><td className="p-4">{row.currency}</td><td className="p-4">{(row.attachments||[]).map((file:Row)=><button key={file.path} onClick={()=>openDocument(file.path)} className="block text-[#168353]">{file.name}</button>)}</td><td className="p-4">{row.active?"Actif":"Inactif"}</td><td className="p-4"><button onClick={()=>{uploadTarget.current=row;fileRef.current?.click()}} className="font-bold text-[#168353]">Joindre un document</button></td></tr>)}</tbody></table>}
      {mode==="partner-registry"&&<table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-4">N° vendor</th><th className="p-4">Type</th><th className="p-4">Nom</th><th className="p-4">Email</th><th className="p-4">Téléphone</th><th className="p-4">Localisation</th><th className="p-4">Recruté le</th><th className="p-4">Statut</th></tr></thead><tbody className="divide-y">{filtered.map(row=><tr key={row.id}><td className="p-4 font-mono font-bold">{row.vendor_number}</td><td className="p-4">{row.partner_type}</td><td className="p-4 font-bold">{row.full_name}</td><td className="p-4">{row.email||"—"}</td><td className="p-4">{row.phone||"—"}</td><td className="p-4">{[row.city,row.state_region,row.country].filter(Boolean).join(", ")||"—"}</td><td className="p-4">{new Date(row.recruited_at).toLocaleDateString("fr-FR")}</td><td className="p-4">{row.status}</td></tr>)}</tbody></table>}
      {mode==="partner-payments"&&<table className="w-full min-w-[1500px] text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-4">Référence</th><th className="p-4">Période</th><th className="p-4">N° vendor</th><th className="p-4">Prestataire</th><th className="p-4">Type</th><th className="p-4">Revenu généré</th><th className="p-4">À payer</th><th className="p-4">Payé</th><th className="p-4">Reliquat</th><th className="p-4">Statut</th><th className="p-4">Preuves</th><th className="p-4">Commentaires</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(row=>{const vendor=row.partner_vendor_registry||{};return <tr key={row.id}><td className="p-4 font-mono text-xs font-bold">{row.payment_reference}</td><td className="p-4">{row.period_start||"—"} → {row.period_end||"—"}</td><td className="p-4 font-mono">{vendor.vendor_number}</td><td className="p-4 font-bold">{vendor.full_name}</td><td className="p-4">{vendor.partner_type}</td><td className="p-4">{Number(row.gross_revenue).toLocaleString("fr-FR")}</td><td className="p-4">{Number(row.amount_due).toLocaleString("fr-FR")}</td><td className="p-4">{Number(row.amount_paid).toLocaleString("fr-FR")}</td><td className="p-4 font-bold">{Math.max(0,Number(row.amount_due)-Number(row.amount_paid)).toLocaleString("fr-FR")} {row.currency}</td><td className="p-4">{row.status}</td><td className="p-4">{(row.proofs||[]).map((file:Row)=><button key={file.path} onClick={()=>openDocument(file.path)} className="block text-[#168353]">{file.name}</button>)}</td><td className="max-w-xs p-4"><p>{row.finance_comment||"—"}</p>{(row.partner_payment_comments||[]).map((entry:Row)=><p key={entry.id} className="mt-1 text-xs text-slate-500">• {entry.comment}</p>)}</td><td className="p-4"><div className="grid gap-2"><button onClick={()=>{uploadTarget.current=row;fileRef.current?.click()}} className="font-bold text-[#168353]">Ajouter une preuve</button><button onClick={()=>setCommenting(row)} className="font-bold text-[#ef7f3b]">Commenter</button></div></td></tr>})}</tbody></table>}
    </div>}{!loading&&!filtered.length&&<p className="p-10 text-center text-slate-500">Aucune donnée ne correspond aux filtres.</p>}</section>
    <input ref={fileRef} type="file" className="hidden" onChange={event=>{const file=event.target.files?.[0];if(file)upload(file);event.currentTarget.value=""}}/>
    {modal&&<div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-[#123d32]/80 p-4"><form onSubmit={isAccounts?saveAccount:savePayment} className="my-8 w-full max-w-4xl rounded-[30px] bg-[#123d32] p-5 shadow-2xl"><div className="rounded-2xl bg-white p-6 md:p-8"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#ef7f3b]">Suivi Finance en ligne</p><h3 className="mt-2 text-2xl font-black">{isAccounts?"Ajouter un compte":"Initier un paiement"}</h3></div><button type="button" onClick={()=>setModal(false)} className="text-2xl">×</button></div>{isAccounts?<AccountFields value={account} setValue={setAccount} partners={vendors} partner={mode==="partner-accounts"}/>:<PaymentFields value={payment} setValue={setPayment} vendors={vendors} accounts={accounts}/>}<div className="mt-7 flex justify-end gap-3"><button type="button" onClick={()=>setModal(false)} className="btn-secondary">Annuler</button><button className="btn-primary">Enregistrer</button></div></div></form></div>}
    {commenting&&<div className="fixed inset-0 z-[100] grid place-items-center bg-[#123d32]/80 p-4"><div className="w-full max-w-xl rounded-[28px] bg-[#123d32] p-5"><div className="rounded-2xl bg-white p-6"><h3 className="text-xl font-black">Ajouter un commentaire</h3><textarea rows={5} className="admin-input mt-4" value={comment} onChange={event=>setComment(event.target.value)}/><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setCommenting(null)} className="btn-secondary">Annuler</button><button onClick={addComment} className="btn-primary">Publier</button></div></div></div></div>}
  </div>
}

function AccountFields({value,setValue,partners,partner}:{value:Row;setValue:(value:Row)=>void;partners:Row[];partner:boolean}){const set=(key:string,next:unknown)=>setValue({...value,[key]:next});return <div className="mt-6 grid gap-4 md:grid-cols-2">{partner&&<label className="grid gap-2 text-sm font-bold md:col-span-2">Partenaire<select required className="admin-input" value={value.partner_vendor_id} onChange={event=>set("partner_vendor_id",event.target.value)}><option value="">Sélectionner…</option>{partners.map(row=><option value={row.id} key={row.id}>{row.vendor_number} — {row.full_name}</option>)}</select></label>}<label className="grid gap-2 text-sm font-bold">Type de compte<select className="admin-input" value={value.account_type} onChange={event=>set("account_type",event.target.value)}><option value="bank">Compte bancaire</option><option value="mobile_money">Mobile Money</option><option value="petty_cash">Petite caisse</option><option value="other">Autre</option></select></label><label className="grid gap-2 text-sm font-bold">Type de titulaire<select className="admin-input" value={value.holder_type} onChange={event=>set("holder_type",event.target.value)}><option value="company">Entreprise</option><option value="individual">Personne physique</option></select></label><Field label="Titulaire du compte" value={value.account_holder} onChange={next=>set("account_holder",next)} required/><Field label="Devise" value={value.currency} onChange={next=>set("currency",next)} required/>{value.account_type==="bank"?<><Field label="Nom de la banque" value={value.bank_name} onChange={next=>set("bank_name",next)}/><Field label="Pays de la banque" value={value.bank_country} onChange={next=>set("bank_country",next)}/><Field label="Adresse de la banque" value={value.bank_address} onChange={next=>set("bank_address",next)}/><Field label="Numéro de compte" value={value.account_number} onChange={next=>set("account_number",next)}/><Field label="IBAN" value={value.iban} onChange={next=>set("iban",next)}/><Field label="SWIFT / BIC" value={value.swift_bic} onChange={next=>set("swift_bic",next)}/><Field label="Routing number / code banque" value={value.routing_code} onChange={next=>set("routing_code",next)}/></>:value.account_type==="mobile_money"?<><Field label="Opérateur" value={value.mobile_operator} onChange={next=>set("mobile_operator",next)}/><Field label="Numéro Mobile Money" value={value.mobile_number} onChange={next=>set("mobile_number",next)}/></>:null}</div>}
function PaymentFields({value,setValue,vendors,accounts}:{value:Row;setValue:(value:Row)=>void;vendors:Row[];accounts:Row[]}){const set=(key:string,next:unknown)=>setValue({...value,[key]:next});return <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold md:col-span-2">Prestataire / partenaire<select required className="admin-input" value={value.partner_vendor_id} onChange={event=>set("partner_vendor_id",event.target.value)}><option value="">Sélectionner…</option>{vendors.map(row=><option key={row.id} value={row.id}>{row.vendor_number} — {row.full_name} ({row.partner_type})</option>)}</select></label><Field type="date" label="Début de période" value={value.period_start} onChange={next=>set("period_start",next)}/><Field type="date" label="Fin de période" value={value.period_end} onChange={next=>set("period_end",next)}/><Field type="number" label="Revenu généré" value={value.gross_revenue} onChange={next=>set("gross_revenue",next)}/><Field type="number" label="Montant à payer" value={value.amount_due} onChange={next=>set("amount_due",next)} required/><Field type="number" label="Montant payé" value={value.amount_paid} onChange={next=>set("amount_paid",next)}/><Field label="Devise" value={value.currency} onChange={next=>set("currency",next)}/><label className="grid gap-2 text-sm font-bold">Compte destinataire<select className="admin-input" value={value.payment_account_id} onChange={event=>set("payment_account_id",event.target.value)}><option value="">Non précisé</option>{accounts.filter(row=>!value.partner_vendor_id||row.partner_vendor_id===value.partner_vendor_id).map(row=><option key={row.id} value={row.id}>{row.account_holder} — {row.account_number||row.mobile_number}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Statut<select className="admin-input" value={value.status} onChange={event=>set("status",event.target.value)}><option value="pending">En attente</option><option value="approved">Approuvé</option><option value="paid">Payé</option><option value="cancelled">Annulé</option></select></label><Field type="date" label="Date de paiement" value={value.payment_date} onChange={next=>set("payment_date",next)}/><Field label="Référence source" value={value.source_reference} onChange={next=>set("source_reference",next)}/><label className="grid gap-2 text-sm font-bold md:col-span-2">Commentaire finance<textarea className="admin-input" rows={4} value={value.finance_comment} onChange={event=>set("finance_comment",event.target.value)}/></label></div>}
function Field({label,value,onChange,type="text",required=false}:{label:string;value:any;onChange:(value:any)=>void;type?:string;required?:boolean}){return <label className="grid gap-2 text-sm font-bold">{label}<input required={required} type={type} className="admin-input" value={value??""} onChange={event=>onChange(event.target.value)}/></label>}
