"use client";
import { useEffect, useState } from "react";
import { Landmark, Smartphone, WalletCards } from "lucide-react";

type Mode="accounts"|"settlements";
const labels:Record<string,string>={bank:"Banque",mobile_money:"Mobile money",petty_cash:"Petite caisse"};
export default function TreasuryManagement({mode}:{mode:Mode}){
  const [accounts,setAccounts]=useState<any[]>([]),[tickets,setTickets]=useState<any[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  async function load(){const [a,t]=await Promise.all([fetch("/api/maximus/treasury?resource=accounts").then(r=>r.json()),mode==="settlements"?fetch("/api/maximus/treasury?resource=tickets").then(r=>r.json()):Promise.resolve({items:[]})]);setAccounts(a.items||[]);setTickets(t.items||[])}
  useEffect(()=>{void load()},[mode]);
  async function createAccount(form:FormData){setBusy("account");const response=await fetch("/api/maximus/treasury",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resource:"accounts",data:{channel:form.get("channel"),name:form.get("name"),institution:form.get("institution"),account_number:form.get("account_number"),currency:form.get("currency")||"XAF",opening_balance:Number(form.get("opening_balance")||0),active:true}})});const json=await response.json();setBusy("");setMessage(response.ok?"Compte enregistré.":json.message);if(response.ok)void load()}
  async function settle(form:FormData){const id=String(form.get("id"));setBusy(id);const response=await fetch("/api/maximus/treasury",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resource:"settle",id,financial_account_id:form.get("financial_account_id"),payment_reference:form.get("payment_reference"),note:form.get("note")})});const json=await response.json();setBusy("");setMessage(response.ok?"Versement confirmé et recette enregistrée.":json.message);if(response.ok)void load()}
  if(mode==="accounts")return <div className="grid gap-6"><Header title="Comptes de versement" text="Configurez les banques, comptes Mobile Money et petites caisses utilisables dans les recettes et dépenses."/><form action={createAccount} className="grid gap-4 rounded-xl border bg-white p-6 md:grid-cols-2"><select name="channel" className="admin-input" required><option value="bank">Banque</option><option value="mobile_money">Mobile money</option><option value="petty_cash">Petite caisse</option></select><input name="name" className="admin-input" required placeholder="Nom du compte"/><input name="institution" className="admin-input" placeholder="Banque ou opérateur"/><input name="account_number" className="admin-input" placeholder="Numéro ou identifiant du compte"/><input name="opening_balance" className="admin-input" type="number" defaultValue="0" placeholder="Solde initial"/><input name="currency" className="admin-input" defaultValue="XAF"/><button disabled={busy==="account"} className="rounded-lg bg-[#123d32] px-5 py-3 font-black text-white md:col-span-2">Enregistrer le compte</button></form><AccountGrid accounts={accounts}/>{message&&<p className="rounded-lg bg-emerald-50 p-4 font-bold">{message}</p>}</div>;
  const pending=tickets.filter(t=>t.status==="pending"),received=tickets.filter(t=>t.status==="received");
  return <div className="grid gap-6"><Header title="Versements en attente" text="Seuls la finance et les administrateurs peuvent confirmer un versement et choisir son compte de destination."/><div className="grid gap-4">{pending.map(ticket=><form key={ticket.id} action={settle} className="grid gap-4 rounded-xl border border-amber-200 bg-white p-6 md:grid-cols-2"><input type="hidden" name="id" value={ticket.id}/><div className="md:col-span-2"><p className="text-xs font-black text-orange-700">{ticket.ticket_number}</p><h3 className="text-xl font-black">{ticket.payer_name}</h3><p className="text-sm text-slate-500">{ticket.source_type==="catering_delivery"?"Livraison restauration":"Clôture du point de vente"} · {ticket.sale_point||"Sans point de vente"}</p><p className="mt-3 text-2xl font-black">{Number(ticket.amount).toLocaleString("fr-FR")} {ticket.currency}</p></div><select name="financial_account_id" required className="admin-input"><option value="">Choisir le compte de versement</option>{accounts.filter(a=>a.active).map(account=><option key={account.id} value={account.id}>{labels[account.channel]} — {account.name}{account.account_number?` (${account.account_number})`:""}</option>)}</select><input name="payment_reference" className="admin-input" placeholder="Référence banque / Mobile Money / caisse"/><textarea name="note" className="admin-input md:col-span-2" placeholder="Note de réception"/><button disabled={busy===ticket.id} className="rounded-lg bg-[#24945f] px-5 py-3 font-black text-white md:col-span-2">Confirmer la réception du versement</button></form>)}{!pending.length&&<p className="rounded-xl border border-dashed bg-white p-8 text-center text-slate-500">Aucun versement en attente.</p>}</div><section><h3 className="text-xl font-black">Versements reçus</h3><div className="mt-4 grid gap-3">{received.map(ticket=><article key={ticket.id} className="flex flex-wrap justify-between gap-4 rounded-xl border bg-white p-5"><div><b>{ticket.ticket_number} · {ticket.payer_name}</b><p className="text-sm text-slate-500">{ticket.payment_reference||"Sans référence"}</p></div><b>{Number(ticket.amount).toLocaleString("fr-FR")} {ticket.currency}</b></article>)}</div></section>{message&&<p className="rounded-lg bg-emerald-50 p-4 font-bold">{message}</p>}</div>
}
function Header({title,text}:{title:string;text:string}){return <section><h2 className="text-3xl font-black">{title}</h2><p className="mt-2 text-slate-500">{text}</p></section>}
function AccountGrid({accounts}:{accounts:any[]}){const icons={bank:Landmark,mobile_money:Smartphone,petty_cash:WalletCards};return <div className="grid gap-4 md:grid-cols-3">{accounts.map(account=>{const Icon=icons[account.channel as keyof typeof icons]||WalletCards;return <article key={account.id} className="rounded-xl border bg-white p-5"><Icon className="h-7 text-emerald-700"/><p className="mt-4 text-xs font-black uppercase text-slate-500">{labels[account.channel]}</p><h3 className="text-lg font-black">{account.name}</h3><p className="mt-2 text-sm">{account.institution||""} {account.account_number||""}</p></article>})}</div>}
