import{NextResponse}from"next/server";import{z}from"zod";import{getDegreeSession}from"@/lib/degree-programs/access";import{createSupabaseServerClient}from"@/lib/supabase/server";
const schema=z.discriminatedUnion("kind",[
 z.object({kind:z.literal("JURY"),programId:z.string().uuid(),academicYearId:z.string().uuid().optional(),semesterId:z.string().uuid().optional(),juryType:z.enum(["SEMESTER","YEAR","GRADUATION","DEFENSE"]),meetingDate:z.string().min(1),location:z.string().optional(),chairUserId:z.string().uuid(),quorum:z.coerce.number().int().min(1),notesFr:z.string().optional(),notesEn:z.string().optional()}),
 z.object({kind:z.literal("MEMBER"),juryId:z.string().uuid(),userId:z.string().uuid(),role:z.enum(["CHAIR","SECRETARY","MEMBER","RAPPORTEUR","EXTERNAL_EXAMINER"])}),
 z.object({kind:z.literal("DECISION"),juryId:z.string().uuid(),studentId:z.string().uuid(),decisionType:z.enum(["SEMESTER","YEAR","PROGRESSION","GRADUATION","DEFENSE"]),decisionValue:z.string().min(2),reasonFr:z.string().min(3),reasonEn:z.string().min(3),eligibilityCheckId:z.string().uuid().optional()})
]);
export async function POST(req:Request){const s=await getDegreeSession();if(!s?.organizationId)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});if(!s.isSuperAdmin&&!s.permissions.includes("jury.manage"))return NextResponse.json({error:"jury.manage required"},{status:403});const db=await createSupabaseServerClient(),x=parsed.data;let q;
if(x.kind==="JURY")q=db.from("academic_juries").insert({organization_id:s.organizationId,jury_number:null,jury_type:x.juryType,program_id:x.programId,academic_year_id:x.academicYearId||null,semester_id:x.semesterId||null,meeting_date:x.meetingDate,location_or_link:x.location||null,chair_user_id:x.chairUserId,quorum_required:x.quorum,notes_fr:x.notesFr||null,notes_en:x.notesEn||null,created_by:s.userId}).select().single();
else if(x.kind==="MEMBER")q=db.from("academic_jury_members").insert({organization_id:s.organizationId,jury_id:x.juryId,user_id:x.userId,member_role:x.role}).select().single();
else q=db.from("academic_jury_decisions").insert({organization_id:s.organizationId,decision_number:null,jury_id:x.juryId,student_id:x.studentId,decision_type:x.decisionType,decision_value:x.decisionValue,reason_fr:x.reasonFr,reason_en:x.reasonEn,eligibility_check_id:x.eligibilityCheckId||null,proposed_by:s.userId}).select().single();
const{data,error}=await q;if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({data},{status:201})}